### ISSUE TITLE
Display menu bugging out

### ISSUE THREAD

**Issue by Ikxi1** [OpenTabletDriver/OpenTabletDriver#1008]
## Description
Hello,
I just downloaded this driver and it seems the display menu is kinda bugged.
I think it is because I'm using 1 of my monitors in portrait mode (seen in screenshot).
I don't know how to position the window like this, so that I only have my middle screen in the field.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 (latest update just yesterday)
| Software Version | 0.5.3.1
| Tablet           | Wacom CTL-490
![grafik](https://user-images.githubusercontent.com/69396495/115141532-2b9b9d80-a03d-11eb-8605-aff8a60f46e9.png)

**Comment by AbstractQbit** [comment]
Right click on display area editor > Set to display > Choose the one you need

**Comment by Ikxi1** [comment]
> 
> 
> Right click on display area editor > Set to display > Choose the one you need

.....yea, I just found out
I didn't really expect that you can actually do that.
Found out accidentally. (maybe include in the start guide)


Thank you!!
