### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by KurisuDesuru** [OpenTabletDriver/OpenTabletDriver#1011]
# Support Request
tablet: gaomon s56k
cursor is not moving
at first he even is not detected then i change gaomon s56k config
tablet detected, but cursor is not moving
os: archlinux

## What I've already tried
fixed ArgumentOutOfRangeException: Value [0-15]

## Diagnostic Information
[diagnostics.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6331816/diagnostics.json.txt)

**Comment by Mrcubix** [comment]
provided you followed every steps from the wiki, and checking the console everytime for more errors, it should be working on latest master https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ

**Comment by KurisuDesuru** [comment]
i try use all faq
![image](https://user-images.githubusercontent.com/82760122/115155000-77266980-a086-11eb-8329-eb9f5bf2115e.png)
tablet debugger works, but cursor not moving ((((

**Comment by KurisuDesuru** [comment]
i get only this warning
![image](https://user-images.githubusercontent.com/82760122/115155222-95d93000-a087-11eb-9b61-4669f195b4eb.png)

**Comment by KurisuDesuru** [comment]
bruh, the problem was solved by installing lib32-libevdev

**Comment by InfinityGhost** [comment]
Odd that it was looking for a 32 bit libevdev, but if it works its w/e lol
