### ISSUE TITLE
add a "mouse mode" option?

### ISSUE THREAD

**Issue by Pentamity** [OpenTabletDriver/OpenTabletDriver#1021]
## Description

Like in most other tablet drivers, could you add a mouse mode option? I wanted to swap from Hawku Drivers until I realised that there was no mouse mode option in this driver.

**Comment by X9VoiD** [comment]
Change output mode to "Relative Mode" or use [VMultiMode](https://github.com/X9VoiD/VoiDPlugins/wiki/VMultiMode) if you're planning on using OTD on Valorant and other games with anti cheat mechanisms.
