### ISSUE TITLE
Add binds to switch between profiles

### ISSUE THREAD

**Issue by Beatsz** [OpenTabletDriver/OpenTabletDriver#1022]
I was wondering if there is a way to switch between my **WindowsInk profile (for drawing)** and **Absolute mode (for playing osu!)** using **keybinds** without the hassle of going through the setting and loading the profile every single time. (YES i know what i'm asking is pretty stupid but meh)

**Comment by InfinityGhost** [comment]
Basically a duplicate of #400, its planned for v0.6

**Comment by Beatsz** [comment]
> Basically a duplicate of #400, its planned for v0.6

oh cool
