### ISSUE TITLE
Express Buttons not working on Huion H640P

### ISSUE THREAD

**Issue by athdesk** [OpenTabletDriver/OpenTabletDriver#1033]
## Description
Express Buttons not working on Huion H640P. Also when pushing on one of them, the cursor skips on the upper-left corner of the screen.
I think this is a configuration issue and I might be able to fix it, given some time; if it's ok, I can make a pull request that fixes this.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Linux 5.11.15
| Software Version | OTD 0.5.3.1
| Tablet           | Huion H640P

**Comment by InfinityGhost** [comment]
This is most certainly a configuration issue, likely the lack of any advanced parser for the tablet. As of 3b9690dbc2491a7300d112a8ad824a169a24afbe its using the `TabletReportParser` which is designed for only basic tablets.

This tablet likely requires the `UCLogicReportParser` instead, like many other Huion tablets do.

**Comment by athdesk** [comment]
I just tried adding an entry in the AuxilaryDeviceIdentifiers field (using the same VID/PID used in the DigitizerIdentifiers entry), handled by UCLogicReportParser, and the buttons now work correctly.
I'll just play around with the debugger to try and fix the cursor skipping when pushing any of them, i'll update this issue as progress is made

**Comment by X9VoiD** [comment]
Don't add a new AuxiliaryIdentifier unless it's of a different input/output length

**Comment by InfinityGhost** [comment]
Ideally we'd replace the existing digitizer identifier, thats the intended use case for the UCLogicReportParser.

**Comment by athdesk** [comment]
Thanks, I'll try and do it this way

**Comment by athdesk** [comment]
Using UCLogicReportParser directly in the DigitizerIdentifier works for the express buttons, and limiting the active report range fixes the cursor jumping around.

This is fixed in PR #1034 , I think this issue can be closed
