### ISSUE TITLE
CTH480 cursor teleporting like crossmap jumps

### ISSUE THREAD

**Issue by naenaebabyy** [OpenTabletDriver/OpenTabletDriver#1045]
## Description

The cursor jumps to the topleft corner of my screen like im doing crossmap jumps on absolute mode
## System Information:

| Name             | Value |
| ? |? |
| Operating System |
Windows 10
| Software Version |
0.4.1
| Tablet         CTH480|

**Comment by X9VoiD** [comment]
Use the latest version of OTD.

**Comment by naenaebabyy** [comment]
> Use the latest version of OTD.

I AM WTF

**Comment by X9VoiD** [comment]
The latest version is [0.5.3.1](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.1), not 0.4.1.

**Comment by naenaebabyy** [comment]
> The latest version is [0.5.3.1](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.1), not 0.4.1.

![image](https://user-images.githubusercontent.com/78448715/115966528-e2a88500-a525-11eb-8782-60fd1405b1ad.png)

**Comment by naenaebabyy** [comment]
> > The latest version is [0.5.3.1](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.1), not 0.4.1.
> 
> ![image](https://user-images.githubusercontent.com/78448715/115966528-e2a88500-a525-11eb-8782-60fd1405b1ad.png)

im retarded

**Comment by X9VoiD** [comment]
Just to be clear, when does it jump to the top left corner?

**Comment by naenaebabyy** [comment]
> Just to be clear, when does it jump to the top left corner?

When it was detected that i was putting the pen near the tablet

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, then upload the file here in zipped format

**Comment by naenaebabyy** [comment]
Im on the new version now lemme test

**Comment by naenaebabyy** [comment]
Fixed old version was problem
