### ISSUE TITLE
cth 480 not detected

### ISSUE THREAD

**Issue by naenaebabyy** [OpenTabletDriver/OpenTabletDriver#1047]
## System Information:

| Name             | Value |
idk what your meant to put here
| Operating System |
win 10
| Software Version |
latest
| Tablet           |
cth480

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload file here in zipped format.

**Comment by naenaebabyy** [comment]
here it is
[cth480.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6370202/cth480.zip)

**Comment by X9VoiD** [comment]
`"The configuration directory 'C:\\Users\\billy\\Desktop\\Configurations' does not exist."`.

Reinstall your OTD properly. If this is from a zip file then you should have extracted everything to a folder of it's own, instead of in `Desktop`. Also, update your plugins.

**Comment by naenaebabyy** [comment]
oh
