### ISSUE TITLE
Cursor vibrates up and down in absolute mode

### ISSUE THREAD

**Issue by Doksha** [OpenTabletDriver/OpenTabletDriver#1048]
## Description

When I start the software the cursor vibrates up and down when the pen is near the surface, it seems to be affected by the area, and is a small enough vibration that it is still somewhat playable (not teleporting to the corner, just a few pixels up and down).
I saw that there was a similar issue 4 hours ago, but updating to the latest software does not seem to fix the issue, switching to relative mode has similar issues, but instead of actively moving the cursor, it simply causes the cursor to bug around when the pen moves
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | 0.5.3.1
| Tablet           | Veikk A15

**Comment by X9VoiD** [comment]
Is there any other driver running in the background? And does the vibration look like a cursor ghosting (two cursors)?

**Comment by Doksha** [comment]
> Is there any other driver running in the background? And does the vibration look like a cursor ghosting (two cursors)?

I made sure (okay the weather made sure) that there were no other running drivers, I also uninstalled previous drivers so there should be no issues there, and yes, the cursor is ghosting.

**Comment by Doksha** [comment]
Fixed the issue, needed to search for two other tablet drivers that were installed, they had weird names so it took a while to find, but that did fix it.
