### ISSUE TITLE
Binding handler isn't inside the output pipeline.

### ISSUE THREAD

**Issue by adryzz** [OpenTabletDriver/OpenTabletDriver#1049]
## Description
With the new change to `IPositionedPipelineElement<T>`, plugins have now access to the `IDeviceReport`s, and can change their type, maybe creating a new type of report that inherits from both `ITabletReport` and `IEraserReport`, essentially adding eraser to tablets that don't support it.

This works with pressure, hover distance and tilt, but not with buttons, pen tip and eraser (essentially anything that is handled by the binding handler)

**Comment by InfinityGhost** [comment]
I think wrapping reports in other types isn't a good way about doing that. However, the binding handler *should* be at the end of the pipeline so this is still a worthy change.

**Comment by InfinityGhost** [comment]
Resolved in #1098
