### ISSUE TITLE
Compatibility with windows ink

### ISSUE THREAD

**Issue by Doksha** [OpenTabletDriver/OpenTabletDriver#1055]
## Description

I really dont like having to uninstall this and install the veikk drivers every time I want to draw, then uninstall those drivers and install these drivers every time I play osu! (this process usually takes 3-5 minutes to play osu, and another 10 minutes for drawing since I have to reconfigure the hotkeys since veikk doesnt create a save file) I would really like a windows ink option.

**Comment by X9VoiD** [comment]
https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk
