### ISSUE TITLE
When I open OpenTabletDriver through Windows Search Bar my tablet doesn't get detected and then it says "No tablet detected"

### ISSUE THREAD

**Issue by DXNAST** [OpenTabletDriver/OpenTabletDriver#1056]
## Description

When I open OpenTabletDriver through Windows Search Bar, it does open, but it doesn't detect my tablet and it says, "No tablet detected"

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System - Windows 10 (Version: 20H2) |
| Software Version - v0.5.3.1 |
| Tablet - GAOMON S620 |
![Screenshot_27](https://user-images.githubusercontent.com/73253085/116008453-e9fa8c00-a614-11eb-94b5-01d7949bd361.jpg)

**Comment by Mrcubix** [comment]
Windows issue, unrelated to OTD, using the installer could serve a workaround, but is basically deprecated
