### ISSUE TITLE
Add support for VEIKK VK640

### ISSUE THREAD

**Issue by TLRS69** [OpenTabletDriver/OpenTabletDriver#1066]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | VEIKK
| Product Name    | VEIKK VK640
| Width           | 152.4mm
| Height          | 101.6mm
| Pressure Levels | 8192
| LPI             | 5080

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload the file in zipped format

**Comment by TLRS69** [comment]
> OTD -> Help -> Export Diagnostics, upload the file in zipped format

**Comment by TLRS69** [comment]
[VEIKK VK640.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6391725/VEIKK.VK640.zip)

**Comment by X9VoiD** [comment]
Wait until #1063 gets merged

**Comment by InfinityGhost** [comment]
Bump, this is ready for a PR

**Comment by TLRS69** [comment]
How?

**Comment by InfinityGhost** [comment]
Download a [development build](https://github.com/OpenTabletDriver/OpenTabletDriver/actions?query=event%3Apush+is%3Acompleted) of OpenTabletDriver and put the file in this zip in the `Configurations` folder.

[VK640.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6418978/VK640.zip)

LMK if this works, there's still more work to be done even if it does work.

**Comment by TLRS69** [comment]
It doesn't work

**Comment by TLRS69** [comment]
It detected it at first but once i put my pen on the tablet it doesn't detect it anymore

**Comment by rigellroy** [comment]
Sorry for reviving this, but any update on the situation? Thinking of buying another tablet but don't know whether to get the S640 or VK640.

**Comment by InfinityGhost** [comment]
> Sorry for reviving this, but any update on the situation? Thinking of buying another tablet but don't know whether to get the S640 or VK640.

No progress, adding new configurations is something that can take quite a bit of trial and error. The VEIKK S640 is a known working tablet if you're still searching for a tablet that OpenTabletDriver supports.

**Comment by InfinityGhost** [comment]
Pushed to the backlog until we have a solution for the aux button quirk.

**Comment by Garbodow** [comment]
Hey, I was just wondering if there has been any progress on the support on VK640? Had mine for a while now and there really aren't any decent tablet drivers out there that support this model. :(

**Comment by Mrcubix** [comment]
An advice for you: Read.
