### ISSUE TITLE
Configurable amount of auxiliaries button in tablet configuration

### ISSUE THREAD

**Issue by Akeeru** [OpenTabletDriver/OpenTabletDriver#1069]
Can you add this feature (in title)?
I had to create a patch to use all the buttons from the Huion H1060P tablet.

I am sending the patch I used as a text file with the extension "txt"
[patch](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6391946/huion.patch.txt)

++ Additionally
And to use the Tilt function, I had to change its configuration. Can you change its default configuration?

**Comment by X9VoiD** [comment]
The button count is already being worked on on #1063, and open a PR for the tilt function.

**Comment by gonX** [comment]
`Specifications.AuxiliaryButtons.ButtonCount` is now a config option since #1063. Closing as resolved.
