### ISSUE TITLE
In area editor, area can stick to cursor

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1073]
## Description

Holding left click to drag the area then right clicking before letting go of left click will make the area stick to the cursor when leaving the menu.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | win10
| Software Version | 0.5.3.1

**Comment by gonX** [comment]
Also happens on Arch Linux and can confirm it still happens on master (53a7dcfd60a)
