### ISSUE TITLE
Plugins fail to load on Manjaro.

### ISSUE THREAD

**Issue by nekkan** [OpenTabletDriver/OpenTabletDriver#1091]
## Description
Every plugin I try to install results in a warning message in the console.
![image](https://user-images.githubusercontent.com/45243386/117394689-f6140280-aecc-11eb-8f36-367673418964.png)

## System Information:

| Name             | Value |
| ---------------- | ----- | 
| Operating System | Manjaro 21.0.4
| Software Version | v0.5.3.1-r188.gf2ec9fd4
| Tablet           | Gaomon S620

**Comment by InfinityGhost** [comment]
We have changed a large majority of the plugin library, breaking basically all v0.5.3 plugins. The PKGBUILD can be modified to directly fetch the v0.5.3.1 release so you won't be building on latest master, if needed.

**Comment by nekkan** [comment]
How can I modify the PKGBUILD?

**Comment by nekkan** [comment]
How can I modify the PKGBUILD?
