### ISSUE TITLE
CTL-671 cursor position acts weirdly when you are far to the left or to the right of physical active area

### ISSUE THREAD

**Issue by Kert** [OpenTabletDriver/OpenTabletDriver#1092]
It does not happen when you are below or above physical active area

OTD v0.5.3.1 (with fixed config from https://github.com/OpenTabletDriver/OpenTabletDriver/commit/2e2dafd216af4803d1f20285c539fbbeb56b46f2)

**Comment by InfinityGhost** [comment]
> It does not happen when you are below or above physical active area
> 
> OTD v0.5.3.1 (with fixed config from [2e2dafd](https://github.com/OpenTabletDriver/OpenTabletDriver/commit/2e2dafd216af4803d1f20285c539fbbeb56b46f2))

Because this was already fixed in that commit, this is resolved.
