### ISSUE TITLE
Bug: XP PEN G430S When hovering over the tablet it gets undetected?

### ISSUE THREAD

**Issue by rudyon** [OpenTabletDriver/OpenTabletDriver#1094]
## Description
The tablet is detected after plugging it in. However when I go to use the tablet. As soon as my pen hovers over. The driver stops detecting it.

I created this as a support request at first. Please edit the labels.
## System Information
| Name             | Value |
| ---------------- | ----- |
| Operating System | Arch Linux |
| Software Version | v0.5.3.1-r188.gf92ec9fd4 |
| Tablet           | XP Star G430S |

## Diagnostic Information
I have looked through the diagnostics myself the issue seems to be a NullReferenceException in [DeviceReader.cs at line 92](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/f2ec9fd42a73ce540489bf44759d8c6848570d3a/OpenTabletDriver/Devices/DeviceReader.cs#L92).
~~I have forked the repository and will look into it myself later.~~ After trying to understand C# for around 2 hours. I gave up trying to fix it myself. Sorry.
- [Privatebin](https://privatebin.net/?9007a439753b7e7e#694Be98XbMJ53GfGRdReNpFgvvDvzXU3xz8wZc4KPFiq)
- [paste.gg](https://paste.gg/p/anonymous/3f8c8a5a42c84a1e9d181c26de315510)

**Comment by Jummit** [comment]
I'm having a simillar issue with a Wacom tablet.
```json
[NullReferenceException:Error]	Object reference not set to an instance of an object.
   at OpenTabletDriver.Desktop.DesktopDriver.HandleReport(IDeviceReport report) in /home/jummit/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/DesktopDriver.cs:line 10
   at OpenTabletDriver.Devices.DeviceReader`1.Main() in /home/jummit/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver/Devices/DeviceReader.cs:line 99
```

**Comment by Faithy3** [comment]
Just encountered this issue. Arch Linux kernel 5.12.5-arch1-1, software version v0.5.3.1-r192.g03d1d05e. The tablet's a CTH-680

**Comment by ixhbinphoenix** [comment]
Have the same issue. Manjaro kernel 5.10.41-1-MANJARO OpenTabletDriver v0.5.3.1-r221.g96516285. Tablet is a Wacom CTL-472

**Comment by InfinityGhost** [comment]
Odds are this is out of date plugins, can't reproduce in any scenario.

**Comment by InfinityGhost** [comment]
Stale support request, assuming resolved.
