### ISSUE TITLE
"To run this application, you must install .NET"

### ISSUE THREAD

**Issue by xalgenyt** [OpenTabletDriver/OpenTabletDriver#1099]
![unknown](https://user-images.githubusercontent.com/24656975/118238847-c43d0600-b4a1-11eb-9a56-6dbf79f7f16a.png)
## Description

As said in the title, to install the driver it asks me to install .NET. I have already installed it, and it still ask me to download the .NET. Is this a bug or am I doing something wrong?

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |     win10
| Software Version |   0.5.3.1
| Tablet           |       Veikk s640

**Comment by X9VoiD** [comment]
Install .NET 5 **x64** runtime.
