### ISSUE TITLE
Add Lock to display

### ISSUE THREAD

**Issue by Naozumi520** [OpenTabletDriver/OpenTabletDriver#1100]
## Description
So I have got a second monitor, but after that my tablet area was weird, so I have found that I need to use the "Set to display" option, but after that my tablet still able to control the second monitor and the aspect ratio of the tablet area is wrong.
Would be nice if there could be an option to just use the single screen then we don't need to edit the current area.

![image](https://user-images.githubusercontent.com/52615455/118249176-b5714600-b4d7-11eb-83e3-da80f453254e.png)

**Comment by X9VoiD** [comment]
Tablet Area Editor -> Right Click -> Ignore input outside area

**Comment by X9VoiD** [comment]
For the S640 measurements open up a new issue.

Open up Tablet -> Tablet Debugger and post there the highest values you can get for Position

**Comment by Naozumi520** [comment]
Hmmmm Idk why but yeah I have choose Ignore input outside area, but I can still move the cursor to the other screen.
