### ISSUE TITLE
Add support for GAOMON S630

### ISSUE THREAD

**Issue by xSage420** [OpenTabletDriver/OpenTabletDriver#1101]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | GAOMON
| Product Name    | GAOMON S630
| Width           | 152.4mm
| Height          | 129.2mm
| Pressure Levels | 8192
| LPI             | 5080

**Comment by shugen002** [comment]
|Name | Value|
------ | ----
hardware button | 4

GM001_T203 ? (base on official driver unpack)

**Comment by Mrcubix** [comment]
@xSage420 join the [discord server](https://discord.gg/P3GYdUS), WinUSB support has been added and we need some info in order to make this tablet compatible
