### ISSUE TITLE
Support Request: How do I get smoothing. 

### ISSUE THREAD

**Issue by CodeKidGames** [OpenTabletDriver/OpenTabletDriver#1103]
Where do I get tablet smoothing. Most people say to get this due to the fact that its tablet smoothing filter didn't die.
I have already tried finding it but idk what one it is.

**Comment by X9VoiD** [comment]
OTD -> Plugin -> Plugin Manager -> Pick whatever filter/interpolator you want. Choose hawku or devocub if you're already familiar with those.
