### ISSUE TITLE
Not detecting my tablet (Huion H640P)

### ISSUE THREAD

**Issue by drpure** [OpenTabletDriver/OpenTabletDriver#1105]
## Description

Hi, i just recently switched form using hawku to opentabletdriver because someone told me that this driver gives lower latency. sorry for bothering you guys
## System Information:

| Name             | Value |
| ---------------- | ----- |
|Operating System | Windows 10
|Software Version | 0.5.3.1
| Tablet        |Huion 640P

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, then upload the diagnostics as a zipped file. Will close the issue for now until further information is provided.

**Comment by drpure** [comment]
[H640P.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6571785/H640P.zip)

**Comment by drpure** [comment]
when I look at console, it says "tablet found", but on the top of the application it says "no tablet detected"

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/120235996-8ab71980-c25b-11eb-9a8c-4a87066c8e34.png)
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0

**Comment by drpure** [comment]
still doesn't work

**Comment by Mrcubix** [comment]
export diag again

**Comment by drpure** [comment]
[H640P (5).zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6573170/H640P.5.zip)

**Comment by Mrcubix** [comment]
the previously linked cleanup script wasn't launched or it didn't work for a reason or another, run it as admin just to make sure and it should work

**Comment by drpure** [comment]
it worked, ty!
