### ISSUE TITLE
draw area not working correctly

### ISSUE THREAD

**Issue by Rvvni** [OpenTabletDriver/OpenTabletDriver#1114]
# Support Request
 tablet cursor gets stuck when outside of draw area and draw area is very innaccurate
 
![image](https://user-images.githubusercontent.com/84618782/119220483-af382680-bae2-11eb-80e1-f91062ed7233.png)

## What I've already tried
 i've tried switching to OpenTabletDriver but it still doesn't work

**Comment by X9VoiD** [comment]
Tablet cursor will of course stick to the edge of the screen when you're outside the assigned tablet area. This is true for every tablet driver you'll see out there unless you want your cursor to physically be outside the monitor via some sort of futuristic holographic thing.

And we can't do anything with this information sorry, please follow the template and upload diagnostic information if you want to be helped. Will re-open issue once you've given enough info.
