### ISSUE TITLE
Backslash "\" is overwriting Leftbracket "["

### ISSUE THREAD

**Issue by OnARiverMadeOfEyes** [OpenTabletDriver/OpenTabletDriver#1115]
## Description
Also both the Keybind GUI and Daemon have no indication of this.

\ ] \ ] \ ]
When it should be:
[ ] [ ] [ ]
## System Information:
| Name             | Value |
| ---------------- | ----- |
| Windows 10 |
| v0.5.3.1 |
| Wacom CTL-4100 |

**Comment by X9VoiD** [comment]
Closing in favor of #2350
