### ISSUE TITLE
Exception on Win shutdown

### ISSUE THREAD

**Issue by C0D3-M4513R** [OpenTabletDriver/OpenTabletDriver#1120]
## Description

I was shutting down my pc, when this appeared:
![image](https://user-images.githubusercontent.com/28912031/119341303-e4d04180-bc93-11eb-9142-f132e81ae523.png)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win 10, version 21H1, build 19043.985
| Software Version | v.0.5.3.1
| Tablet           | MTE-450

EDIT: Power menu (sleep,shutdown, reboot) was not appearing. Might be a Reboot and fixed problem?

**Comment by X9VoiD** [comment]
Please provide a stack trace or log, we can't do anything with just the screenshot. Will close for now until further information is provided.

**Comment by InfinityGhost** [comment]
This appears to either be a .NET bug or a WPF bug.

**Comment by C0D3-M4513R** [comment]
> Please provide a stack trace or log, we can't do anything with just the screenshot. Will close for now until further information is provided.

Where are the logs? Do I need to restart the app, to get to the logs? How do I take a stacktrace? The Window is still open btw.

**Comment by Mrcubix** [comment]
One way you can get the stacktrace is by checking the event viewer > windows log > application for .NET Runtime errors related to OTD, from there, copy paste the content of that stacktrace contained in the text box in the middle.
![image](https://user-images.githubusercontent.com/39861216/119352795-6929c100-bca2-11eb-8ef1-668dc2867c16.png)

**Comment by C0D3-M4513R** [comment]
I do not have a stacktrace available. I am finding some errors, that were one to many months before, from other apps though.
I am writing this off as a freak accident, and will just not worry about it.
Some Computer wierdness, that probably occurred because of my leniency, to not reboot my computer, when installing/updating stuff?
Don't worry about this!
