### ISSUE TITLE
Add support for UGEE HK 1060pro

### ISSUE THREAD

**Issue by YvanDroid** [OpenTabletDriver/OpenTabletDriver#1122]
# Tablet Information

| Name            | Value |
| ----------------- | ----- |
| Manufacturer    |UGEE
| Product Name   |HK 1060pro
| Width                |10 inches
| Height               |6 inches
| Pressure Levels  |2048
| LPI                     |5080

## Diagnostic Information

[Diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6540667/Diagnostic.zip)

**Comment by jamesbt365** [comment]
This tablet has been supported since
