### ISSUE TITLE
Instances where plugins folder needs to be created will cause tablet input to throw NullReferenceException

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1123]
## Description

Any instance of the daemon that needs to create the plugins folder will throw the following upon receiving any normal tablet input (aux doesn't always have the issue):
```
[NullReferenceException:Error]	Object reference not set to an instance of an object.
   at OpenTabletDriver.Desktop.DesktopDriver.HandleReport(IDeviceReport report)
   at OpenTabletDriver.Devices.DeviceReader`1.Main()
```
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | win10
| Software Version |  *all commits after around 4/15/2021* -> 03d1d05

**Comment by InfinityGhost** [comment]
This has been resolved in a miscellaneous PR afaik.
