### ISSUE TITLE
Plugins should not have access to reports filtered out by parsers

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1124]
## Description

Currently it is possible for plugins to access reports that are filtered out on the parser side. Reports filtered out by configs are not sent through plugins and config side filtering works as it should. But having parser filtering ignored by plugins can lead to messed up output from plugins that track reports over time. 

For example: [Tablet Debounce](https://github.com/Kuuuube/Tablet_Debounce) ends up sending wrong pressure values over valid reports because it records bad pressure values from invalid reports that are filtered parser side.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Software Version | 03d1d05

**Comment by InfinityGhost** [comment]
Is this issue still valid with pipeline elements?

**Comment by Kuuuube** [comment]
This issue only came up because of pipeline. I believe it is still an issue but the parser changes may have made it not matter anymore. I don't have a good way to test it currently though.

**Comment by InfinityGhost** [comment]
Looks like the only fix to this would to basically implement a "disposed" property of sorts to determine if a report should be ignored. 
Not sure on a good fix for this.

**Comment by gonX** [comment]
This sounds more like a parser issue that should be handled on a case by case basis.

**Comment by Kuuuube** [comment]
This doesn't matter anymore.

**Comment by jamesbt365** [comment]
Reopening because this infact does still occur:
https://www.youtube.com/watch?v=6J27M_cGxsc

**Comment by InfinityGhost** [comment]
What would be a good way to go about fixing this other than what I suggested before? I'm not too fond of a disposed property and would rather use idle or out of range sort of interface if possible.

**Comment by gonX** [comment]
I think this should be solved in the relevant parser if possible

**Comment by vedattt** [comment]
https://github.com/X9VoiD/VoiDPlugins/issues/27

**Comment by gonX** [comment]
Setting to high priority because a lot of plugin users seem to be hitting this occasionally

**Comment by X9VoiD** [comment]
This is not an issue of the pipeline but rather the implementation of the output mode. Since it's already fixed I'll close this.
