### ISSUE TITLE
Support Request: Wacom tablet not working properly since windows ink update

### ISSUE THREAD

**Issue by ryad600** [OpenTabletDriver/OpenTabletDriver#1125]
# Support Request
I dont know how to fix this problem since windows doesn't give you asetting to turn of the windows ink.
It doesnt apply my changes, filters and its in 20Hz or smth.

I tried searching in the windows settings but i didn't find anything to turn it of,
searched thru r/Wacom and didn't find anything like it maybe im just blind.

Can't find any Diagnostics in the folder only JSON files idk seems likegit hub doest support it.
idk what im doing i just need help thx.

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
