### ISSUE TITLE
Document -m/--minimized command line flag.

### ISSUE THREAD

**Issue by DynamicDonkey** [OpenTabletDriver/OpenTabletDriver#1129]
## Description
Cloned the code to attempt to implement autostarting the application in the system tray on Windows, only to find out the option is already there. Thanks for that! However, it would be awesome to see this documented rather than having to find it out manually by searching the source code. 

https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.UX/App.cs#L21

**Comment by InfinityGhost** [comment]
Thanks for the issue! I've added documentation for command line arguments for both the UI and the Daemon now.

https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/General-FAQ/b892933f2c4daa405d7aa6e91f7009304a9fd92f
