### ISSUE TITLE
Windows ink tablet buttons not working

### ISSUE THREAD

**Issue by Vishnu-Siddharth** [OpenTabletDriver/OpenTabletDriver#1135]
I am using a Huion H640p. I got this tablet for osu! and drawing mainly. I tried to download windows ink plugin to have pressure sensitivity, but when I enable the windows ink absolute mode, my tablet/pen buttons stop working. No matter what I do, even the left click is not working. Please help

**Comment by AbstractQbit** [comment]
Have you bound windows ink keys as described in the tutorial? https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk

**Comment by X9VoiD** [comment]
Will close issue, if you are still experiencing the issue after following the instructions above then open an issue on [VoiDPlugins](https://github.com/X9VoiD/VoiDPlugins) repo.
