### ISSUE TITLE
Support Request: OpenTabletDriver not detecting GaomonS620 in MacOS

### ISSUE THREAD

**Issue by Mora502** [OpenTabletDriver/OpenTabletDriver#1138]
# Support Request
 I dont know much about programming and im kind of a noob in this sort of things, i downloaded the drivers, installed everything that was required but when i plug my Gaomon S620 to my computer it says that no tablet was found.

**Comment by narlock** [comment]
See here to make sure you installed OpenTabletDriver properly: https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Installation-Guide#macos-experimental

It could be the version of macOS you're running that could be causing an issue.

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
