### ISSUE TITLE
deleted "VEIKK" file and cannot use tablet area

### ISSUE THREAD

**Issue by rat12314** [OpenTabletDriver/OpenTabletDriver#1140]
## Description

I accidently deleted everything in the "VEIKK" file. Now opentabletdriver is no longer detecting my tablet and I cannot use my tablet area.
## System Information:

| Name             | Value |
| Rat12314 | ----- |
| Operating System  | windows 10
| Software Version | 
| Tablet           | Veikk S640

**Comment by rat12314** [comment]
when i do anything, my cursor goes to the top left of my screen

**Comment by jjhhgg100123** [comment]
Download the portable version and pull the Veikk files out of the configurations directory. Insert them back wherever you deleted them.

**Comment by Mrcubix** [comment]
this issue shouldn't be a thing, just redownload OTD

**Comment by InfinityGhost** [comment]
User error is not a problem of OpenTabletDriver.

**Comment by rat12314** [comment]
when i try to download OTD it doesnt download

**Comment by Mrcubix** [comment]
https://www.youtube.com/watch?v=aFejLY4vKeY
