### ISSUE TITLE
Huion H430P doesn't work.

### ISSUE THREAD

**Issue by rinfumi** [OpenTabletDriver/OpenTabletDriver#1141]
## Description
No input is done when i move my pen. 

## System Information:
| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | V0.5.3.1
| Tablet           | Huion H430P

**Comment by Mrcubix** [comment]
Fill the template, no support will be provided until filled (see the template that you should had used instead of deleting it below)

```
## Description
<!-- Describe the issue below -->

## System Information:
<!-- Please fill out this information -->
| Name             | Value |
| ---------------- | ----- |
| Operating System |
| Software Version |
| Tablet           |
```

**Comment by rinfumi** [comment]
> 
> ## Description
> 
> No input is done when i move my pen.
> ## System Information:
> Name 	Value
> Operating System 	Windows 10
> Software Version 	V0.5.3.1
> Tablet 	Huion H430P


re:
nevermind it fixed itself
