### ISSUE TITLE
Add support for Gaomon M10K 2018

### ISSUE THREAD

**Issue by FloriaProduction** [OpenTabletDriver/OpenTabletDriver#1144]
Gaomon
Gaomon M10K 2018
360
240
8192
5080

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6598891/diagnostics.txt)

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/120812265-1e833100-c54d-11eb-847f-7a26c61d626e.png)
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0
then use this instead
https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/897942452

**Comment by InfinityGhost** [comment]
It is already supported.
