### ISSUE TITLE
Tablet Area doesn't reach the whole screen

### ISSUE THREAD

**Issue by mine2fs** [OpenTabletDriver/OpenTabletDriver#1151]
I got following Issue, when i set a Tablet Area in the Program the Cursor only goes to about the half of the Screen and like 3 cm above the task bar. I know it's an Issue with my windows because i tried the Hawku Drivers and even the Wacom Drivers. When i use the full area of the Tablet it works perfectly. Does anyone have a clue what's going on? 

Btw. i have a Wacom CTL-480 and i also tried it with my XP-Pen G640

**Comment by Mrcubix** [comment]
if you use the latest version & uninstall the manufacturer driver, everything should work normally, tho, every issue require a diagnostic file, like specified in the template you just removed, so i'll need you to provide one.

in the UX : help > export diagnostic > zip it > upload it

**Comment by mine2fs** [comment]
Thx for the quick response.
Yeah, here ya go.
[diagnostic file.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6611218/diagnostic.file.zip)

**Comment by Ferco124** [comment]
I have the same problem too
I have a CTL-4100 
[disgnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6611390/disgnostic.zip)

**Comment by gonX** [comment]
Closing as a stale issue. If anyone else has the same issue, please open a new support request report. It is likely caused by old drivers conflicting.
