### ISSUE TITLE
Start with windows

### ISSUE THREAD

**Issue by LemonJuicer** [OpenTabletDriver/OpenTabletDriver#1157]
Add an option to open on windows startup.

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/121437486-b7b5ab80-c982-11eb-843d-0ea03b9cae41.png)

**Comment by X9VoiD** [comment]
There's no plans of doing this for now since OTD is a cross-platform driver and there is no clear way to perform auto-launch on all supported platforms
