### ISSUE TITLE
Support Request: Plugins can't be loaded on Manjaro

### ISSUE THREAD

**Issue by chezbananas** [OpenTabletDriver/OpenTabletDriver#1159]
# Support Request
When installing plugins through the built-in manager on Manjaro KDE 21.0.6, I receive this message: "Plugin '(name), version 1.0.0.0' can't be loaded and is likely out of date." This message appears for all plugins, and persists after uninstalling/reinstalling them and restarting the computer. The rest of the driver works fine.

## What I've already tried
Tried uninstalling/reinstalling the plugins, driver, and Manjaro entirely to no avail. Issue existed on Manjaro KDE 21.0.4 as well.

## Diagnostic Information
[pastebin](https://pastebin.com/QiLxELiT)

**Comment by adryzz** [comment]
You are running a development build.
Either compile and install plugins manually or go to the latest tagged release by editing your PKGBUILD
