### ISSUE TITLE
cursor flickers when changing tablet surface area. (Ubuntu)

### ISSUE THREAD

**Issue by YoNoSoyVictor** [OpenTabletDriver/OpenTabletDriver#1160]
Changing tablet area makes cursor flick between two places.

Ubuntu 20.04.2 LTS
OTD version 0.5.3.1 
Wacom ctl-472

Here is a video of the problem, as you can see at the beginning I use the tablet with the default settings perfectly (proving that it is not the tablet's fault), and once I change and apply settings, the cursor starts going crazy. 
[https://youtu.be/0Re-Mj-5jRY](url)

Edit: In the recording it does look a little bit like the cursor is not being tracked properly at the beginning, That is because I recorded the video in low FPS. In real life it looks much smoother and you still can tell there is a clear difference between using default and custom settings in the video.

**Comment by adryzz** [comment]
you have multiple drivers running. blacklist wacom

**Comment by X9VoiD** [comment]
Read [FAQ](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ).
