### ISSUE TITLE
XP-Pen Deco 1 v2 not detected in OpenTablet but registers input

### ISSUE THREAD

**Issue by jobs-git** [OpenTabletDriver/OpenTabletDriver#1162]
## Description

First of all, thank you for this software. My tablet can now register inputs! I forced remove the vendor driver `vmulti.sys` cause it is causing BSOD.

W/ OpenTabletDriver, I am now able to get inputs! But within the software it says its not detected, so I could not change the table area
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win. 10 v 19042.985
| Software Version | OpenTable v0.1.0-rc1
| Tablet           | XP-Pen Deco 1 v2

**Comment by Mrcubix** [comment]
you one step away from filling the template, the most important piece of information we need to start here: the diagnostic file

![image](https://user-images.githubusercontent.com/39861216/121602171-33792c00-ca47-11eb-9423-b20c0b8422fd.png)
zip it or .txt it

**Comment by jobs-git** [comment]
Closing: outdated version
