### ISSUE TITLE
Start when OS starts

### ISSUE THREAD

**Issue by jobs-git** [OpenTabletDriver/OpenTabletDriver#1163]
As the title. 

Typically, start right during login screen so users can use the tablet right away.

**Comment by Mrcubix** [comment]
this won't be added in the UI until we find a way to only show it on a specific platform. in the meanwhile, enjoy this method everyone is using.
![image](https://user-images.githubusercontent.com/39861216/121608544-81dff800-ca52-11eb-867f-b9564dfc8002.png)
