### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Exaltz** [OpenTabletDriver/OpenTabletDriver#1167]
## Description
I've been trying to download it after uninstalling and when I run the installer and click install it starts then it closes and when I open it again it just does the same thing.

## System Information:
| Operating System | Windows 10
| Software Version | 21H1 I think
| Tablet           | XP-Pen Star G640S

**Comment by X9VoiD** [comment]
Installer/Updater will be deprecated in the near future (it'll be integrated into OTD). If you're having problems with it just use portable instead. Closing as a `wont fix` issue.

**Comment by Exaltz** [comment]
What is "portable?"

**Comment by Exaltz** [comment]
> Installer/Updater will be deprecated in the near future (it'll be integrated into OTD). If you're having problems with it just use portable instead. Closing as a `wont fix` issue.

What is "portable?"

**Comment by AbstractQbit** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/releases
