### ISSUE TITLE
Support Request: Device in use Exception

### ISSUE THREAD

**Issue by boxcat0043** [OpenTabletDriver/OpenTabletDriver#1169]
Device is currently in use by another kernel module

Ubuntu
21.04
Gaomon M10K

**Comment by X9VoiD** [comment]
That exception literally have a link to the fix.

**Comment by boxcat0043** [comment]
Yes it says to reboot but even after the reboot it doesn't detect it

**Comment by AbstractQbit** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#argumentoutofrangeexception-value-0-15
