### ISSUE TITLE
Failure finding non-existent express keys (Wacom CTL-472)

### ISSUE THREAD

**Issue by Tudi20** [OpenTabletDriver/OpenTabletDriver#1170]
## Description
For Wacom CTL-472, this error is given when the tablet itself has no express keys.

```
[Detect:Info]	Searching for tablet 'Wacom CTL-472'
[Device:Warning]	Failed to set tablet feature: 02-02
[Detect:Info]	Found tablet 'Wacom CTL-472'
[Detect:Warning]	Failed to find auxiliary device, express keys may be unavailable.
```

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10; 20H2; 19042.1052
| Software Version | 0.5.3.2
| Tablet           | Wacom CTL-472

**Comment by adryzz** [comment]
The warnings are not device-specific. It is expected behaviour to show the warning even on devices without express keys.

**Comment by Tudi20** [comment]
Reporting that you have a perfectly working tablet without express keys, or a not-perfectly working tablet with express keys that can't be used are two different things.
Unless I'm misunderstanding the error message, and you're saying that due to the software's capabilities or misconfiguration on my system express keys couldn't be used, regardless of what tablet I would be using.

**Comment by Mrcubix** [comment]
the message mean what it mean, in your case, you tablet doesn't have express key, which is why this message show up.

**Comment by Tudi20** [comment]
In that case the warning should show as info or be silenced. (Especially since osu!lazer likes to show every warning in OTD as a critical error.)

**Comment by Mrcubix** [comment]
Re-opening for tracking purposes since ghost mentioned the possibility of removal of aux device identifier on tablet that doesn't have aux buttons

**Comment by Mayla99654** [comment]
Here the same thing happens, and the cursor is static, the tablet stops responding to inputs after this message appears.

**Comment by jamesbt365** [comment]
correlation != causation. Open your own issue.
