### ISSUE TITLE
Not starting on Apple Silicon mac

### ISSUE THREAD

**Issue by Knallli** [OpenTabletDriver/OpenTabletDriver#1174]
## Description
Program won't start, no window, no error message, no sign of life when starting

## System Information:
| ---------------- | ----- |
| MacOS BigSur and Monterey |
| 11.3.2/12.0 Beta |

I think osu!lazer has some sort of opentabletdriver implemented aswell right? It works flawlessly there

The only sign of live shows in launchd.log:
[launchd.log](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6642056/launchd.log)

**Comment by InfinityGhost** [comment]
We do not have an ARM build of OpenTabletDriver, which is why it doesn't start. I will look into building for macOS ARM in future releases.

**Comment by Knallli** [comment]
I wonder why it won't run on rosetta2 though? or is that specific to just arm macs

**Comment by InfinityGhost** [comment]
Might have to do with .NET 5 itself, make sure that's installed at least. I personally don't own an ARM mac so I only can speculate.

**Comment by Knallli** [comment]
Okay I had the dotnet 6 preview installed. When uninstalling this and just having the dotnet 5 sdk it works

**Comment by InfinityGhost** [comment]
Appears resolved then, closing.

**Comment by sheerun** [comment]
Aren't then plans to make it work with dotnet 6 on macos? :)

**Comment by jamesbt365** [comment]
#1441

**Comment by RoyiAvital** [comment]
> We do not have an ARM build of OpenTabletDriver, which is why it doesn't start. I will look into building for macOS ARM in future releases.

It would be great to have Apple M CPU support (Apple ARM / Apple Silicone).
