### ISSUE TITLE
Does not lock to unusable area

### ISSUE THREAD

**Issue by nkkicole** [OpenTabletDriver/OpenTabletDriver#1178]
## Description

I set my display area to my monitor (display 2) but the cursor does not lock to display 2, instead, it keeps going back and forth blinking between display1 and display2. So when I open osu, the cursor looks like it is having a siezure. 
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | 20H2
| Tablet           | xp pen g640

**Comment by Mrcubix** [comment]
uninstall your other tablet driver
