### ISSUE TITLE
Support Request: can't install the installer

### ISSUE THREAD

**Issue by fouzo53** [OpenTabletDriver/OpenTabletDriver#1180]
# Support Request

## What I've already tried

i have no clue why its cant install even the portable, i haved install .net 5.0

**Comment by X9VoiD** [comment]
Install .NET 5.0, and installer installs OTD, it doesn't install itself, so no, installer will not install itself.

**Comment by fouzo53** [comment]
which OTD i have download? office deployment tool?

**Comment by fouzo53** [comment]
which OTD i have download? Oracle Traffic Director?

**Comment by fouzo53** [comment]
i haved download .net, but the OTD installer just wont pop up

**Comment by X9VoiD** [comment]
.NET 5.0 is not OTD itself, it's a runtime required by OTD to properly run. OTD portable can be found in [Releases](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.2). ([direct link](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.5.3.2/OpenTabletDriver.win-x64.zip))

Installer/Updater is deprecated and is not the recommended way anymore to setup OTD.

**Comment by fouzo53** [comment]
i mean... OTD don't open when i have clicked
