### ISSUE TITLE
Support Request: OpenTabletDriver installer not detecting .NET framework

### ISSUE THREAD

**Issue by cluckl3s** [OpenTabletDriver/OpenTabletDriver#1182]
Installed framework 5.0 and all, but when I try to install using the OTB installer, I get "To run this application, you must install .NET. The framework 'Microsoft.WindowsDesktop.App', versoion '5.0.0' was not found." Please, help.

**Comment by InfinityGhost** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Installation-Guide#windows

> 1. Install [**.NET 5 Desktop Runtime x64**](https://dotnet.microsoft.com/download/dotnet/5.0), other versions will not work.

You didn't install the right version.
