### ISSUE TITLE
Support Request: Tablet settings not applying (wacom CTL-472

### ISSUE THREAD

**Issue by CodeKidGames** [OpenTabletDriver/OpenTabletDriver#1187]
# Support Request
the driver won't apply the settings I set. and sometimes the tablet dosen't even work.

## What I've already tried
e

**Comment by Mrcubix** [comment]
![E](https://i.imgur.com/u3EUGZu.png)

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
