### ISSUE TITLE
Support Request: Tablet Area doesn't reach the whole screen

### ISSUE THREAD

**Issue by lex1k1337** [OpenTabletDriver/OpenTabletDriver#1188]
I have two monitors and after the latest update of windows my mapping was broken. In Hawku Drivers, when i set only one monitor it's mapped only half of this one. After this case i tried to use OTD and in OTD i have another issue. I can't choose the first monitor area. I tried to drag area to the left, but it's have invisible barrier. Any one know how to fix it?
[xp-pen g430.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6654397/xp-pen.g430.zip)
![image](https://user-images.githubusercontent.com/54908019/122027442-8efb3f00-cde4-11eb-9f2e-55b219315cf6.png)

**Comment by AbstractQbit** [comment]
Right click display area > set to display > select the needed display.

**Comment by lex1k1337** [comment]
I can't click on need display because after i hover on set to display and drag a cursor the menu is disappearing

**Comment by lex1k1337** [comment]
Ok, with the TAB i do it. Thx for help

**Comment by X9VoiD** [comment]
This is already fixed on latest master, the next major release will contain the fix.
