### ISSUE TITLE
driver not working right in terms of mouse buttons and and when saving the driver delete the tablet and then i have to ctrl d to redetct it and no issues in the console

### ISSUE THREAD

**Issue by XXX6000USER** [OpenTabletDriver/OpenTabletDriver#1193]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |
| Software Version |
| Tablet           |

**Comment by jjhhgg100123** [comment]
Fill in the issue template please.

**Comment by SnowLire** [comment]
Fix the entire issue please.

**Comment by X9VoiD** [comment]
Will close for now until the issue template is filled in correctly.
