### ISSUE TITLE
Support Request: tablet wont work at all in the debugger i see the cursor move but i cant get my cursor to move on desktop

### ISSUE THREAD

**Issue by ahdorable** [OpenTabletDriver/OpenTabletDriver#1198]
# Support Request
i would like to able to use my tablet again it wont do anything after ive reinstalled the software and tried all of the fixes ive seen on the windows faq

**Comment by vsimochi** [comment]
also happening to me too

**Comment by SnowLire** [comment]
Fill out the support issue template correctly first, then we can continue.

**Comment by Lorphex** [comment]
Happening to me after updating to v0.5.3.3
I've tried switching nubs, restarting OTD, restarting my PC, etc.
Here's my diagnostic:
[OTDissue1207.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6834571/OTDissue1207.zip)

**Comment by Mrcubix** [comment]
Open your own issue

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
