### ISSUE TITLE
Support Request: no tablet detected

### ISSUE THREAD

**Issue by iIIlustrator** [OpenTabletDriver/OpenTabletDriver#1200]
I use VEIKK S640.
Please help !!!
This is diagnostic :
[VEIKK S640.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6679912/VEIKK.S640.zip)

**Comment by X9VoiD** [comment]
This is already fixed in OTD master. Wait for next release for the fix.

**Comment by iIIlustrator** [comment]
> This is already fixed in OTD master branch. Wait for next release for the fix.

thank you very much
