### ISSUE TITLE
Support Request: Failed to set tablet feature: 02-02

### ISSUE THREAD

**Issue by Inspraa** [OpenTabletDriver/OpenTabletDriver#1202]
# Support Request
Hello! A few hours ago, my OTD stopped working all of a sudden and i've been trying to find how to fix it ever since. It shows this error:
![image](https://user-images.githubusercontent.com/80841939/122639047-5e771600-d100-11eb-820f-3bf7e1a9cecb.png)

## What I've already tried
Uninstalling & Reinstalling OTD, Restarting the PC

## Diagnostic Information
[Diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6680479/Diagnostic.txt)

**Comment by AbstractQbit** [comment]
Try uninstalling the Wacom driver. If it's not installed then install it and uninstall again.

**Comment by Inspraa** [comment]
That fixed it, thank you!
