### ISSUE TITLE
Support Request: Wacom CTL-4100 pen movement not detected

### ISSUE THREAD

**Issue by Lorphex** [OpenTabletDriver/OpenTabletDriver#1207]
# Support Request
Moving the pen does not move the cursor on screen. I can only tap to click. I have no plugins installed. 
This started about a week ago.

## What I've already tried
Switch USB ports. 
Restarting OTD. 
Restarting my PC.
Switching stylus nubs.

**Comment by Mrcubix** [comment]
Do you see that one program on your desktop called "Wacom", head to programs and feature and uninstall that _**thing**_ from your PC.

**Comment by Lorphex** [comment]
I don't have the default Wacom drivers / program installed

**Comment by Mrcubix** [comment]
Then fill the template and provide a diagnostic file : Help > export diagnostic...

**Comment by Lorphex** [comment]
The only files when I do that are .JSON and that type isn't supported by github attachments

**Comment by Mrcubix** [comment]
just zip it or .txt it?

**Comment by Lorphex** [comment]
Ran the updater and it seems to work now. Updater shows I'm on 0.5.3.2, but in OTD itself it shows I'm in 0.5.3.1 still.
Had the same issue as #1198

**Comment by Mrcubix** [comment]
that person never filled the template so we will never know whether or not they have the same issue, a good amount of new users have messed up with their installs in different way which require different method to fix issues.

since your issue seem solved, i'll close.
