### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Henovic** [OpenTabletDriver/OpenTabletDriver#1209]
# Support Request
 When i connect my Wacom CTL-4100 the driver detects the tablet but when my pen makes contact with the surface of the tablet it doesnt detect it anymore

## What I've already tried
 uninstalling and reinstalling, disconnecting and reconnecting the tablet, plugging into different USB port, restarting PC

**Comment by Mrcubix** [comment]
Fill the template by providing a diagnostic file

**Comment by Henovic** [comment]
> Fill the template by providing a diagnostic file

its a JSON file i cant it says not supported

**Comment by Mrcubix** [comment]
then zip it or .txt it???

**Comment by Henovic** [comment]
> then zip it or .txt it???

[fix.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6688073/fix.zip)

**Comment by Mrcubix** [comment]
File > reset to default, apply if this doesn't fix it, re-download OTD (portable) and try again

**Comment by Henovic** [comment]
> File > reset to default, apply. If this doesn't fix it, re-download OTD (portable) and try again

its fixed now thank you
