### ISSUE TITLE
.NET v5 runtime installed but not detected

### ISSUE THREAD

**Issue by numericOverflow** [OpenTabletDriver/OpenTabletDriver#1215]
## Description
I've installed .NETv5 (both x86 & x64 versions) yet it's not detected when I try to startup the driver.  It displays the error dialog asking me to download now.

How does the driver detect .NETv5 is installed? I've confirmed v5 is installed, and everything I've done suggests it's installed (see screenshots below).  I've tried bot the installer and portable versions of OpenTabletDriver, both function the same and give me the error about not having .NETv5 installed.

Thoughts?

I can provide additional debug info if needed/helpful, just let me know what you'd like to see.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Kernel version:            Windows 10 Enterprise
||Product type:              Professional
||Product version:           6.3
||Service pack:              0
||Kernel build number:       18363
| Software Version | 0.5.3.2
| Tablet           | Veikk A30

![Dotnet_v5_4_error](https://user-images.githubusercontent.com/3429424/123160096-67832280-d433-11eb-9bbc-4f44137eca63.jpg)
![Dotnet_v5_Installed_1](https://user-images.githubusercontent.com/3429424/123160119-69e57c80-d433-11eb-8e16-4b7858dd5493.jpg)
![Dotnet_v5_Installed_2](https://user-images.githubusercontent.com/3429424/123160113-694ce600-d433-11eb-94a0-6d83e4c776ff.jpg)
![Dotnet_v5_Installed_3](https://user-images.githubusercontent.com/3429424/123160107-68b44f80-d433-11eb-9ecd-a406f7b22657.jpg)

**Comment by Mrcubix** [comment]
AFAIK, OTD isn't only a console application so you need the right .NET version which is obviously ***DEKSTOP RUNTIME*** https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.7-windows-x64-installer

**Comment by numericOverflow** [comment]
@Mrcubix - That was exactly right.  I downloaded & installed from the link you included above and it is working perfectly so far.

I didn't realize there were console and desktop versions of .NETv5.

Thanks!

**Comment by Mrcubix** [comment]
Microsoft prompt is very bad in the sense that it doesn't tell one which one to download from one of these 3 if you land on this page :
![image](https://user-images.githubusercontent.com/39861216/123162318-c1560d80-d470-11eb-94de-60ab1febd98c.png)
(https://dotnet.microsoft.com/download/dotnet/5.0/runtime)
or this page :
![YEP](https://images-ext-2.discordapp.net/external/KkmbGmULxjoODy06D9-AEuw2UEjWJh5y0CCvqA_CJZg/https/i.fractured.pro/cKpAh.png?width=400&height=330)
(what you need there is in red on the right)
pretty confusing for new users ngl
