### ISSUE TITLE
Artist mode does not work properly in wayland (KDE)

### ISSUE THREAD

**Issue by aika-64** [OpenTabletDriver/OpenTabletDriver#1217]
## Description

The pen pressure doesn't work in absolute mode, so I switched to artist mode, but I can't even click with the pen
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Arch Linux
| Software Version | v0.5.3.2
| Tablet           | Gaomon M10K

**Comment by InfinityGhost** [comment]
Are you using the `opentabletdriver-git` package or the versioned `opentabletdriver` package?

**Comment by aika-64** [comment]
the -git package

**Comment by InfinityGhost** [comment]
Use the `opentabletdriver` package rather than the git version, as how it works is actively being changed.

**Comment by gonX** [comment]
Have you set your pen (and eraser, if applicable) tip binding to the Pen Passthrough binding? If you don't, nothing will happen.

![image](https://user-images.githubusercontent.com/421345/125004065-fb223900-e058-11eb-86bc-ef0602c5b0ce.png)

**Comment by InfinityGhost** [comment]
Resolved in latest master.

**Comment by ChristianHein** [comment]
> If you're still on master, have you set your pen (and eraser, if applicable) tip binding to the Pen Passthrough binding? If you don't, nothing will happen.

Please add this information to the project docs on your next release, so others can find this.

The main reason I use Artist Mode is for pen pressure support. Because this works in v0.5.3.3 without additional configuration, I had assumed that the lastest master was bugged because my pen stopped applying pressure entirely in Artist Mode. Spent quite a bit of time trying to figure out what was wrong.

**Comment by gonX** [comment]
> this works in v0.5.3.3 without additional configuration

If I remember correctly, 0.5.x did not have correctly working bindings when in artist mode.

There will likely be guides on how to set it up by the time the 0.6 release rolls around, but it sounds like we need to track this in a separate issue similar to #1585 except for Linux. An idea could be to notify the user if we're in artist mode and Pen Passthrough is not bound.

**Comment by aika-64** [comment]
> If you're still on master, have you set your pen (and eraser, if applicable) tip binding to the Pen Passthrough binding? If you don't, nothing will happen.

![sings](https://user-images.githubusercontent.com/67609865/141679808-e5b4e418-064d-48bd-94cc-f6e1afe3d80a.jpg)
