### ISSUE TITLE
Support Request: Gaomon S620 not being detected.

### ISSUE THREAD

**Issue by Aiptex** [OpenTabletDriver/OpenTabletDriver#1222]
# Support Request
My Gaomon S620 tablet is not getting detected by the software.

## What I've already tried
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Windows-FAQ#manual-cleanup
https://github.com/OpenTabletDriver/OpenTabletDriver/issues/405

## Diagnostic Information
[a.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6720544/a.txt)

**Comment by Mrcubix** [comment]
you said you tried https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Windows-FAQ#manual-cleanup except i still see vmulti and WinUSB installed.

https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0

run the script, should work.

**Comment by Aiptex** [comment]
I have ran the script and reconnected my tablet, but my tablet is still not being detected.

[b.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6720640/b.txt)

**Comment by Mrcubix** [comment]
run it as admin again, if it still doesn't work, right click on start button > device manager > view > device by container > find your tablet in there, open the container, screenshot device manager and upload it here

**Comment by Aiptex** [comment]
I tried running it as admin, but a command window appears then instantly disappears.

![image](https://user-images.githubusercontent.com/74780467/123525080-5ee15500-d69c-11eb-9371-e60f821c2332.png)

**Comment by Mrcubix** [comment]
uninstall razer synapse

**Comment by Mrcubix** [comment]
after that, right click that virtual HID minidriver collection > update > let me choose from a list > usb input device

**Comment by Aiptex** [comment]
I don't have razer synapse installed

![image](https://user-images.githubusercontent.com/74780467/123525172-d57e5280-d69c-11eb-9f62-e624294e9588.png)

**Comment by Mrcubix** [comment]
HID compliant device

**Comment by Aiptex** [comment]
It works now, thank you very much.
