### ISSUE TITLE
Support Request: I'm seeing two cursors on the screen at once (mac)

### ISSUE THREAD

**Issue by lukaneek** [OpenTabletDriver/OpenTabletDriver#1242]
# Support Request

For some reason whenever I try moving the tablet cursor around the cursor jumps around to two points on my screen making the tablet basically unusable.  I am on a mac.  I'm using the wacom CTL4100
## What I've already tried

I've tried deleting my old tablet drivers and finding a solution online but nothing comes up.

**Comment by InfinityGhost** [comment]
This means that two drivers are running simultaneously. Odds are, the wacom driver and OpenTabletDriver are clashing with one another.

**Comment by joshuah345** [comment]
make sure the wacom drivers aren't running.

open Terminal.app
run `pkill WacomTabletDriver` twice

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
