### ISSUE TITLE
Support Request: .net framework installation not recognized by installation program

### ISSUE THREAD

**Issue by SwordKneeMe** [OpenTabletDriver/OpenTabletDriver#1243]
I have been trying to install OpenTabletDriver on my Windows 10 laptop, and when I try to run the executable an error pops up with this message (direct quote):

" To run this application, you must install .NET.
The framework 'Microsoft.WindowsDesktop.App', version '5.0.0' was not found.
Would you like to download it now? "

So of course I tried downloading the software at the provided link, but even after installing it, the message was the same. Since it was technically version 5.0.7 on the site, I thought maybe it wasn't compatible, so I found version 5.0.0 on another site and installed it. Same error message again. I thought it may have been a conflict with other drivers, so I uninstalled my previous tablet drivers and tried this all again, to no change. I tried the auto installer as well as downloading the zip file. I have followed installation guides on YouTube as well to be absolutely sure I'm installing it correctly. The interface has not opened up to me whatsoever, the only thing I've seen is this error message.

I have tried everything I could think of and don't know how to resolve this issue. If anyone has solved this issue or has any idea on what I could do to fix this, I'd greatly appreciate it.

**Comment by Mrcubix** [comment]
![image](https://cdn.discordapp.com/attachments/615611007951306863/857715198088183868/unknown.png)
