### ISSUE TITLE
How can I use dark mode

### ISSUE THREAD

**Issue by aestheticqq** [OpenTabletDriver/OpenTabletDriver#1245]
I saw on several screenshots that you can use dark mode in this driver, but I looked all over the program and haven't found anything that could relay to dark mode, maybe there is some sort of a plugin that enables it? Anyway, I would like to thank everyone who helped me in solving this little issue

**Comment by InfinityGhost** [comment]
Dark mode is a GTK and MacOS feature, supported natively by the operating system. Windows doesn't support dark mode natively, so it has to be hardcoded in which takes way more work than it's worth.

tl;dr dark mode isn't available on Windows

**Comment by kz-n** [comment]
( It also works on Linux )

**Comment by gonX** [comment]
To clarify, this cannot be fixed in `0.6.x`, but will be solved on `avalonia` branch as we no longer depend on native GUI toolkits to provide GUI features.
