### ISSUE TITLE
There is no configuration VEIKK S640 V2 in configuration windows portable

### ISSUE THREAD

**Issue by Aqirito** [OpenTabletDriver/OpenTabletDriver#1256]
## Description
I have try add config manually. the device is detected but I still cannot move my pen. below is my console log:

<details>
  <summary>
    
    Console Log
  </summary>
  <div class="snippet-clipboard-content position-relative">
    <pre>

[Detect:Info]	Searching for tablet 'Gaomon 1060 Pro'
[Detect:Info]	Searching for tablet 'Gaomon M106K Pro'
[Detect:Info]	Searching for tablet 'Gaomon M106K'
[Detect:Info]	Searching for tablet 'Gaomon M10K'
[Detect:Info]	Searching for tablet 'Gaomon S56K'
[Detect:Info]	Searching for tablet 'Gaomon S620'
[Detect:Info]	Searching for tablet 'Huion 1060 Plus'
[Detect:Info]	Searching for tablet 'Huion G10T'
[Detect:Info]	Searching for tablet 'Huion GC610'
[Detect:Info]	Searching for tablet 'Huion H1060P'
[Detect:Info]	Searching for tablet 'Huion H1161'
[Detect:Info]	Searching for tablet 'Huion H430P'
[Detect:Info]	Searching for tablet 'Huion H610 Pro V2'
[Detect:Info]	Searching for tablet 'Huion H610 Pro'
[Detect:Info]	Searching for tablet 'Huion H640P'
[Detect:Info]	Searching for tablet 'Huion H950P'
[Detect:Info]	Searching for tablet 'Huion HC16'
[Detect:Info]	Searching for tablet 'Huion HS610'
[Detect:Info]	Searching for tablet 'Huion HS611'
[Detect:Info]	Searching for tablet 'Huion HS64'
[Detect:Info]	Searching for tablet 'Huion Kamvas 13'
[Detect:Info]	Searching for tablet 'Huion Kamvas 16'
[Detect:Info]	Searching for tablet 'Huion Kamvas Pro 13'
[Detect:Info]	Searching for tablet 'Huion New 1060 Plus'
[Detect:Info]	Searching for tablet 'Huion osu!tablet'
[Detect:Info]	Searching for tablet 'Huion Q11K V2'
[Detect:Info]	Searching for tablet 'Huion Q11K'
[Detect:Info]	Searching for tablet 'Huion Q620M'
[Detect:Info]	Searching for tablet 'Huion WH1409 V2'
[Detect:Info]	Searching for tablet 'VEIKK A15 Pro'
[Detect:Info]	Searching for tablet 'VEIKK A15'
[Detect:Info]	Searching for tablet 'VEIKK A30'
[Detect:Info]	Searching for tablet 'VEIKK A50'
[Detect:Info]	Searching for tablet 'VEIKK S640 V2'
[Detect:Info]	Found tablet 'VEIKK S640 V2'
[Settings:Info]	Output mode: Windows Ink Absolute Mode
[Settings:Info]	Display area: [1920x1080@<2022.8573, 540>:0°],
[Settings:Info]	Tablet area: [152.4x101.6@<76.2, 50.8>:0°],
[Settings:Info]	Clipping: Enabled
[Settings:Info]	Ignoring reports outside area: Disabled
[Settings:Info]	Filters: OpenTabletDriver.Plugin.NoiseReduction
[Settings:Info]	Tip Binding: [Mouse Button Binding: Left]@1%
[Settings:Info]	Pen Bindings: [0, ], [1, ]
[Settings:Info]	Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ], [6, ], [7, ]
[Settings:Info]	Driver is auto-enabled.
[Settings:Info]	Output mode: Absolute Mode
[Settings:Info]	Display area: [1920x1080@<2022.8573, 540>:0°],
[Settings:Info]	Tablet area: [152.4x101.6@<76.2, 50.8>:0°],
[Settings:Info]	Clipping: Enabled
[Settings:Info]	Ignoring reports outside area: Disabled
[Settings:Info]	Filters: OpenTabletDriver.Plugin.NoiseReduction
[Settings:Info]	Tip Binding: [Mouse Button Binding: Left]@1%
[Settings:Info]	Pen Bindings: [0, ], [1, ]
[Settings:Info]	Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ], [6, ], [7, ]
[Settings:Info]	Driver is auto-enabled.
[Settings:Info]	Output mode: Absolute Mode
[Settings:Info]	Display area: [1920x1080@<2022.8573, 540>:0°],
[Settings:Info]	Tablet area: [152.4x101.6@<76.2, 50.8>:0°],
[Settings:Info]	Clipping: Enabled
[Settings:Info]	Ignoring reports outside area: Disabled
[Settings:Info]	Filters: OpenTabletDriver.Plugin.NoiseReduction
[Settings:Info]	Tip Binding: [Mouse Button Binding: Left]@1%
[Settings:Info]	Pen Bindings: [0, ], [1, ]
[Settings:Info]	Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ], [6, ], [7, ]
[Settings:Info]	Driver is auto-enabled.
[Settings:Info]	Output mode: Absolute Mode
[Settings:Info]	Display area: [1920x1080@<2022.8573, 540>:0°],
[Settings:Info]	Tablet area: [152.4x101.6@<76.2, 50.8>:0°],
[Settings:Info]	Clipping: Enabled
[Settings:Info]	Ignoring reports outside area: Disabled
[Settings:Info]	Filters: OpenTabletDriver.Plugin.NoiseReduction
[Settings:Info]	Tip Binding: [Mouse Button Binding: Left]@1%
[Settings:Info]	Pen Bindings: [0, ], [1, ]
[Settings:Info]	Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ], [6, ], [7, ]
[Settings:Info]	Driver is auto-enabled.
</pre>
  </div>
</details>

and this is config I add manually:

<details>
  <summary>
    
    Custom Configuration
  </summary>
  <div class="snippet-clipboard-content position-relative">
    <pre>

{
  "Name": "VEIKK S640 V2",
  "DigitizerIdentifiers": [
    {
      "Width": 152.6,
      "Height": 101.6,
      "MaxX": 30480.0,
      "MaxY": 20320.0,
      "MaxPressure": 8191,
      "ActiveReportID": {
        "Start": 160,
        "StartInclusive": true,
        "End": 192,
        "EndInclusive": false
      },
      "VendorID": 12267,
      "ProductID": 1,
      "InputReportLength": 13,
      "OutputReportLength": 9,
      "ReportParser": "OpenTabletDriver.Vendors.SkipByteTabletReportParser",
      "FeatureInitReport": null,
      "OutputInitReport": "CQEE",
      "DeviceStrings": {},
      "InitializationStrings": []
    }
  ],
  "AuxilaryDeviceIdentifiers": [],
  "Attributes": {
    "libinputoverride": "1"
  }
}
</pre>
  </div>
</details>

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 64 bit 
| Software Version | v0.5.3.3
| Tablet           | VEIKK S640

**Comment by gonX** [comment]
Fixed in `master` with #1186
