### ISSUE TITLE
HS610 missing buttons in driver configurator

### ISSUE THREAD

**Issue by caseyjp11** [OpenTabletDriver/OpenTabletDriver#1259]
## Description
Missing auxillary buttons in configuration

While the driver works with tablet (except the wheel), the buttons in the configuration show only 8, while the HS610 has 13. (12 aux buttons + wheel button)
All of these buttons are configurable with xsetwacom commands.

## System Information:

| Name             | Value |
| ---------------- | ----- |
|Arch Linux|
|v0.5.3.3|
|Huion HS610          |

**Comment by InfinityGhost** [comment]
Resolved in #1252
