### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Haawkeyy** [OpenTabletDriver/OpenTabletDriver#1262]
# Support Request
 my designated area is not working.

Basically, i installed opentablet and followed the steps that people show on Youtube, chose my area but its not applying when i try to use it. when i try to use it it goes back to full area for some reason and as its my first tablet ever im not sure how to proceed. Its a Wacom 472 tablet (dont know if that helps at all). 
## What I've already tried
 tried searching for solutions in youtube but had no success. ive also tried to check the osu! settings but there's nothing about this

**Comment by Mrcubix** [comment]
Fill the template by providing a diagnostic file, no support will be provided until filled
![image](https://cdn.discordapp.com/attachments/615611007951306863/834491001480675378/export_diagnostic.gif)

**Comment by Haawkeyy** [comment]
this is the diagnostic.
[diagnostic 1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6811691/diagnostic.1.txt)

**Comment by Mrcubix** [comment]
Your tablet isn't plugged in or is plugged in a monitor / shitty USB hub.

**Comment by Haawkeyy** [comment]
yep that my bad, try now to check if something has changed at all
[diagnostics 3.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6811873/diagnostics.3.txt)

**Comment by Mrcubix** [comment]
See that one program in `add and remove programs` called `Wacom`, yeah, you need to uninstall their driver, should work fine after that if you didn't mess up with configs

**Comment by Haawkeyy** [comment]
all working fine right now. thank you for such a fast reply. appreciate it sir.
