### ISSUE TITLE
.NET not working for Winds 11?

### ISSUE THREAD

**Issue by Juansword** [OpenTabletDriver/OpenTabletDriver#1263]
## Description
I've already installed all the .NET 5... as shown below (Especially Desktop Runtime)
![Screenshot_2](https://user-images.githubusercontent.com/54497020/125519390-964ab321-0907-4d96-b0fd-e37c21c9601a.png)
![Screenshot_1](https://user-images.githubusercontent.com/54497020/125519391-d9011463-a045-4e43-9d36-aeba31f8f926.png)
But it still gives an error when trying both the installer and the portable... as shown below
![Screenshot_3](https://user-images.githubusercontent.com/54497020/125519541-f29fe793-22e9-422a-9927-5b3dc3d7fcca.png)

I'm not sure if it's an OS thing or if I'm doing something wrong... Can anyone clarify
## System Information:

| My PC             |  |
| ---------------- | ----- |
| Windows 11 Home | Windows Insiders Program
![Screenshot_4](https://user-images.githubusercontent.com/54497020/125519450-c4f7475b-aa13-4a76-9b1c-79d81cc98c6e.png)

**Comment by Mrcubix** [comment]
This is most likely an OS issue, not something we can fix

**Comment by X9VoiD** [comment]
OTD is already confirmed working for other users using Windows 11. If there would be something wrong in your setup then it would be the presence of a runtime when it's already included in the SDK, only install one or the other.
