### ISSUE TITLE
Huion Inspiroy H420X supported but not detected

### ISSUE THREAD

**Issue by YzooW** [OpenTabletDriver/OpenTabletDriver#1264]
## Description

I have a Huion Inspiroy H420X tablet and it is not being detected by the driver even though it is in the supported list. If I'm doing something wrong please let me know. I have uninstalled previous tablet drivers and used winusb clean up and followed the appropriate steps to remove hawku drivers as well.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 Home |
| Software Version | v0.5.3.3 |
| Tablet           | Huion Inspiroy H420X |
[Huion Inspiroy H420x.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6812416/Huion.Inspiroy.H420x.zip)

**Comment by gonX** [comment]
H420X support is only officially in `master` (0.6.x), so you need to add a custom configuration manually:

https://cdn.discordapp.com/attachments/628651971267788800/864643545108840448/H420X.json

Place this file in the `Configurations` folder of OpenTabletDriver

**Comment by YzooW** [comment]
Thanks for that
