### ISSUE TITLE
Support Request: can this be used with photoshop? like setting pressure sensitivity and stuff 

### ISSUE THREAD

**Issue by ToausTA** [OpenTabletDriver/OpenTabletDriver#1267]
# Support Request

**Comment by Mrcubix** [comment]
Provided you uninstall your previous vmulti if you ever used hawku or huion / XP-Pen / veikk / Gaomon / idfk drivers, then proceed to install the plugin windows ink and the requirement found in it's wiki which is also linked in the plugin manager.
