### ISSUE TITLE
Support Request: MacOS Catalina OTD not opening

### ISSUE THREAD

**Issue by nloxosu** [OpenTabletDriver/OpenTabletDriver#1278]
# Support Request
  Application not opening
 Every time I try to open it, it continues to give me "You can’t open the application “OpenTabletDriver” because it may be damaged or incomplete."

## What I've already tried
 Reinstalling .NET 5, and the driver.

**Comment by InfinityGhost** [comment]
Try [v0.5.3.2](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.2), this might be a packaging issue.

**Comment by nloxosu** [comment]
> Try [v0.5.3.2](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.2), this might be a packaging issue.

Thanks worked perfectly

**Comment by InfinityGhost** [comment]
Reopening this as I need to fix the v0.5.3.3 release asset

**Comment by InfinityGhost** [comment]
This should be resolved now.
