### ISSUE TITLE
can't open application

### ISSUE THREAD

**Issue by Petron84** [OpenTabletDriver/OpenTabletDriver#1279]
## Description
i can't open the application in anyway the application just dont do anything, it doesn't even send an error text
![image](https://user-images.githubusercontent.com/86767665/126318685-26cab6b8-acb9-4b4c-876d-8de37f3a01e7.png)
When i try to open the application via cmd, what else do i have to do after download dotnet from microsoft?
or is it system bug, or anything else?

## System Information:

| Name             | Petron84 |
| ---------------- | ----- |
| Win7 Ultimate |
| latest |
| Veikk S640           |

**Comment by SnowLire** [comment]
You need to download .NET 5 Desktop Runtime from Microsoft, install it, and afterwards run the UX.Wpf

**Comment by Petron84** [comment]
> You need to download .NET 5 Desktop Runtime from Microsoft, install it, and afterwards run the UX.Wpf
![image](https://user-images.githubusercontent.com/86767665/126321299-b0cce6a0-55ba-445f-b327-aa00d88c83bb.png)
after downloading .NET 5 Desktop Runtime, i tried to run the UX.Wpf and the same thing occured before with the driver
