### ISSUE TITLE
Add support for UGEE M708 v1

### ISSUE THREAD

**Issue by iZute** [OpenTabletDriver/OpenTabletDriver#1280]
# Tablet Information

| Name    UGEE M708 v1        | Value |
| --------------- | ----- |
| Manufacturer    | UGEE
| Product Name    | M708 v1
| Width          |  10"
| Height          | 6"
| Pressure Levels  | 2048
| LPI           | 5080

(Pretty much identical at least in looks to the XP-Pen Star03)
(I had to zip the diagnostics export since github apparently doesn't support uploading .json files)

## Diagnostic Information

[diagnostics.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6850642/diagnostics.zip)

**Comment by InfinityGhost** [comment]
Are you sure its UGEE rather than UGTABLET? We already have support for the UGTABLET M708, so this potentially is already implemented.

**Comment by iZute** [comment]
I only decided to suggest this after OTD wasn't recognizing the tablet
UGEE has this thing were their old tablets don't really like to get recognized by their new drivers and I have a feeling this might be one of the situations related to this
was the m708 added around 2018-2019?

**Comment by iZute** [comment]
I am stupid I don't use github ever I'm sorry

**Comment by iZute** [comment]
I don't use github I apologize for my stupidity

**Comment by InfinityGhost** [comment]
Use [this development build](https://github.com/OpenTabletDriver/OpenTabletDriver/suites/3269657981/artifacts/76130399) and it should work. Do note however that v0.5 settings are incompatible with this development build so it might conflict.

**Comment by iZute** [comment]
It still isn't detecting my tablet with the new development build you posted. Deleted old driver before attempting to run as well. Because of this, it probably is a different tablet than UGTABLET. Unless I'm doing something wrong.

**Comment by InfinityGhost** [comment]
Can you get me the diagnostics for that build?

**Comment by iZute** [comment]
[diagnosticsnew.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6859184/diagnosticsnew.zip)

**Comment by Mrcubix** [comment]
Not compatible until USB.NET is implemented

**Comment by iZute** [comment]
Ah I see. Well, thanks!

**Comment by Mrcubix** [comment]
as a side note, i would like to add that there are as much UGEE M708 variants as there are XP-Pen tablets since the only difference with these tablets are the name, the strings we will dump and the name in the simplified device manager if they feel like it

**Comment by Mrcubix** [comment]
Join the [discord server](https://discord.gg/P3GYdUS) when you have time, WinUSB support has been added in pre-release and it will be faster to get it compatible if you join

**Comment by jamesbt365** [comment]
This tablet has been supported since.
