### ISSUE TITLE
Add support for XP-PEN Deco Fun L

### ISSUE THREAD

**Issue by Mema122** [OpenTabletDriver/OpenTabletDriver#1282]
# Tablet Information

| Name            | Value |
| -------- | ----- |
| Manufacturer    | XP-PEN
| Product Name    | XP-PEN Deco Fun L
| Width           | 254mm
| Height          | 159mm
| Pressure Levels | 8.192
| LPI             | 5080

## Diagnostic Information

[Diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6874542/Diagnostic.zip)

**Comment by Mema122** [comment]
[Diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6873877/Diagnostic.zip)

**Comment by Mema122** [comment]
I made two configs that detects the tablet ( OpenTabletDriver & Devocub ) but there is a problem, I think Windows itself has a drive and use it instead of a custom driver
[Configs.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6874244/Configs.zip)

**Comment by Mrcubix** [comment]
[Deco CT1060.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6988956/Deco.CT1060.zip)
- Extract the content of this zip file in `[OTD Folder]\Configurations\XP-Pen`.
- Start OTD's UX, head to Tablets > Device String Reader, i need you to type the following values:
    - 10429
    - 2310
   and then click on Dump all, it will take a while, then you'll need to save it somewhere and upload it here
   only then we will be able to proceed
