### ISSUE TITLE
Multi-Binding support not showing up for Windows Build 

### ISSUE THREAD

**Issue by Gnomey123** [OpenTabletDriver/OpenTabletDriver#1292]
## Description

There is only the generic "Press a key or press a mouse button" prompt with a Clear and Cancel button.

![image](https://user-images.githubusercontent.com/34148010/127368058-54c3eae6-f96d-43da-b638-9c22e7ba5ec0.png)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win10 21H1 19043.1149
| Software Version | v0.5.3.3
| Tablet           | XP-Pen Deco 03

**Comment by Mrcubix** [comment]
modifier + key binding is only available natively in master.
In 0.5.3.3, you'll have to use Script runnier (available in the Plugin Manager) and ahk (You'll have to find out how to make multi key binds by yourself using the documentation)

**Comment by Gnomey123** [comment]
thanks for the clarification, got it working!
keep up the great work!
