### ISSUE TITLE
Support Request: Wacom Intuos CTL4100 no desktop input

### ISSUE THREAD

**Issue by Lorphex** [OpenTabletDriver/OpenTabletDriver#1294]
# Support Request
 OTD is not letting my Wacom Intuos CTL4100 input pen movement to desktop, but it is showing movement in the debugger visualizer.
 This started happening after updating to 0.5.3.3. I was not having this issue on 0.5.3.2 but I was having this issue on 0.5.3.1.

## What I've already tried
 Restarting PC, restarting OTD, uninstalling/reinstalling OTD, changing stylus nibs.

## Diagnostic Information

[OTDissue.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6897593/OTDissue.zip)

**Comment by Mrcubix** [comment]
Plug your tablet in and try again

**Comment by Lorphex** [comment]
> 
> 
> Plug your tablet in and try again (export diag once plugged in, cause it wasn't plugged when the diagnostic was exported)

Updated. Sorry been having this issue for a bit and just re-made the diag a few times.

**Comment by Mrcubix** [comment]
- Make sure valorant isn't running in background.
- Let me know if you see a warning about admin privileges when starting OTD
- Uninstall wacom drivers

**Comment by Lorphex** [comment]
Closing out of Riot Vanguard fixed it... I really don't want that to be the solution since I like to play Osu! in queues and such. Is there any way we could get around that?

**Comment by Mrcubix** [comment]
- First of all, complain to riot for making a mobile copy pasta with a shit kernel level anticheat.
- Second, you could use the windows ink plugin has well as it's [requirement](https://github.com/X9VoiD/vmulti-bin/releases/latest) and it's absolute mode, tho it will come with increase latency.
- fianlly, don't play valorant.

**Comment by Lorphex** [comment]
So I'll just take the fat L for this one I guess
I did submit a ticket about OTD being blocked by Vanguard, since controller players are in the highest ranks anyway so clearly it's not working to block alternative input devices.
I'll try the Windows Ink settings.

**Comment by Mrcubix** [comment]
if you have a mouse plugged in, then other devices won't work / properly, it doesn't prevent people from using controllers or hardware cheats, and doesn't even block some software cheats, in short, it's bad

**Comment by Lorphex** [comment]
That's good to know actually. I might be able to get away with just turning off my mouse while I play Osu!
Thanks for the help / info.

**Comment by Mrcubix** [comment]
But like you saw earlier, vanguard block input from OTD anywhere else.
what i was referring to is the fact you can't have multiple pointers devices connected at the same time without encountering issues

**Comment by Mrcubix** [comment]
i'll close this as it has basically been solved
