### ISSUE TITLE
ctl 480 1 tap registered as 3-10 taps

### ISSUE THREAD

**Issue by itongaa** [OpenTabletDriver/OpenTabletDriver#1296]
## Description

When i press on the tablet with the pen, 3 to 10 touches are recorded instead of 1 touch
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version |  0.5.3.3 and below
| Tablet           | CTL-480

**Comment by InfinityGhost** [comment]
How long have you had your tablet? Sounds like debouncing is needed on your pen tip.

**Comment by X9VoiD** [comment]
Don't use multiple interpolators, use just one.

**Comment by itongaa** [comment]
> Don't use multiple interpolators, use just one.

thank you
