### ISSUE TITLE
gaomon m10k pro is not detected

### ISSUE THREAD

**Issue by no6hope** [OpenTabletDriver/OpenTabletDriver#1301]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| S.O win 10 pro 64bits |
| Software Version https://github.com/OpenTabletDriver/OpenTabletDriver.Installer/releases/tag/v0.4.1 |
| Tablet     gaomon m10k pro      |

**Comment by MegaHello** [comment]
Have you installed the Gaomon Drivers before?

**Comment by no6hope** [comment]
I've installed it on my cousin's computer, and it works (gaomon driver) ,
but I've not installed the gaomon driver on my pc

**Comment by Mrcubix** [comment]
fill the template by providing a diagnostic file from OTD

**Comment by no6hope** [comment]
Is it? De: Gess1tEnviado: jueves, 5 de agosto de 2021 12:30Para: OpenTabletDriver/OpenTabletDriverCC: no6hope; AuthorAsunto: Re: [OpenTabletDriver/OpenTabletDriver] gaomon m10k pro is not detected (#1301) fill the template by providing a diagnostic file from OTD—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MegaHello** [comment]
Please don't use email to reply to the issue. It's gonna look really weird on our side.

**Comment by no6hope** [comment]
## Description


## System Information:

| Name             | Value |
| no6hope | ?|
| Operating System | OS Windows 10 pro [64bit]
| Software Version | OTD version v0.4.1
| Tablet           | Tablet gaomon m10k pro

## Diagnostic Information



(
[gaomon m10k pro.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6948612/gaomon.m10k.pro.txt)
)

**Comment by Mrcubix** [comment]
[M10K Pro.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6949246/M10K.Pro.zip)
extract the content of this archive in `[OTD Folder]\Configurations\Gaomon` (if you use portable as you should)
else you'll find the configuration folder at this path : `%localappdata%\opentabletdriver\bin\Configurations\Gaomon` (if you used the installer)

**Comment by no6hope** [comment]
thanks, now it is working :D
