### ISSUE TITLE
GUI: Switch active tab to Console whenever an error occurs

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#1303]
## Description

Users should be informed whenever an error occurs in the daemon - switching the active tab to Console could be a good solution.

Keep in mind that the daemon is sometimes log-spammy, so there's a chance that the error message may scroll out of view for the user, despite being redirected there.

requested FR'd in [discord convo (multi-topic)](https://discord.com/channels/615607687467761684/870841629727133716/870841631178387557)

**Comment by InfinityGhost** [comment]
> Keep in mind that the daemon is sometimes log-spammy, so there's a chance that the error message may scroll out of view for the user, despite being redirected there.

Might be worth automatically selecting the latest error in the log to avoid this situation
