### ISSUE TITLE
Huion tablet not being detected

### ISSUE THREAD

**Issue by AlphaWoofle** [OpenTabletDriver/OpenTabletDriver#1304]
## OpenTabletDriver cant detect my Huion HS64 Graphics Tablet 

Hello, I've been trying to use OpenTabletDriver on my Huion HS64 Graphics Tablet but its not being detected at all. Im on Linux Mint and i cant get it to work with my Huion tablet
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Linux Mint
| Software Version | 20 "Ulyana" - Cinnamon
| Tablet           | Huion HS64

**Comment by gonX** [comment]
Please update the Software Version in System information to say OTD's version, rather than your OS' version

**Comment by Mrcubix** [comment]
Also Please provide a diagnostic file, You seem to have deleted the most important part of this issue for some reason.
Here is how to export a diagnostic file, and add it to your first message:

- Download the right build according to your OS from the [Latest Release](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.3).
- Open the UX using `opentabletdriver` or open it using the desktop icon (if one exist)
- Read the guide if it's your first time trying this driver, and if after closing the guide, your tablet isn't detected, 
click on `Help` -> `Export Diagnostic` -> Save it wherever you want -> add .txt add the end
- Add the following template at the end of your first message:
```
## Diagnostic Information
<!-- Export diagnostics and attach or paste below -->
<!-- In the GUI, click Help -> Export Diagnostics -->
```
- Then upload your diagnostic file by either dragging and dropping it, selecting or pasting them.

**Comment by gonX** [comment]
@Mrcubix bug report templates do not currently have diagnostics information as a part of the template - support requests do. But yes, a diagnostics file would be nice here

**Comment by zooxs** [comment]
> Also Please provide a diagnostic file, You seem to have deleted the most important part of this issue for some reason.
> Here is how to export a diagnostic file, and add it to your first message:
> 
>     * Download the right build according to your OS from the [Latest Release](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.3).
> 
>     * Open the UX using `opentabletdriver` or open it using the desktop icon (if one exist)
> 
>     * Read the guide if it's your first time trying this driver, and if after closing the guide, your tablet isn't detected,
>       click on `Help` -> `Export Diagnostic` -> Save it wherever you want -> add .txt add the end of the file name
> 
>     * Add the following template part at the end of your first message:
> 
> 
> ```
> ## Diagnostic Information
> 
> 
> ```
> 
>     * Then upload your diagnostic file by either dragging and dropping it, selecting or pasting them.

i'v same issue, which one diagnostic file should you upload?

**Comment by Mrcubix** [comment]
in your own issue: 
![image](https://user-images.githubusercontent.com/39861216/134315497-1876f75c-f0a6-4f4a-a2b1-6d5dd36b087d.png)

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
