### ISSUE TITLE
Windows Ink Plugin adjust pressure sensitivity?

### ISSUE THREAD

**Issue by Balcke** [OpenTabletDriver/OpenTabletDriver#1312]
## Description

looking at bindings i cant find pressure sensitivity (theres tip pressure but it only triggers the tip button binding based on the pressure of the pen) is it in the plugin and just cant find it or it isnt there yet?

**Comment by Mrcubix** [comment]
Check your drawing software, it's only handled there.

**Comment by Mrcubix** [comment]
It's up to someone to decide if they want to implement a plugin for that as it won't be implemented into OTD directly,
but this is handled by the drawing software itself and an option should be available to adjust it,  therefore i'll close.
