### ISSUE TITLE
Support Request: Artisul A1201

### ISSUE THREAD

**Issue by azaz08967565** [OpenTabletDriver/OpenTabletDriver#1314]
# Support Request
I bought Artisul A1201, and this tablet is not supported, please add this tablet configuration into the tablet driver. This tablet have 440 pps rate.

**Comment by SnowLire** [comment]
In OTD, go to Help > Export Diagnostic, zip the file and send it here.

**Comment by azaz08967565** [comment]
[Artisul A1201.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6931485/Artisul.A1201.zip)

**Comment by Mrcubix** [comment]
[Artisul A1201.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6988924/Artisul.A1201.zip)
- Create a new folder in `[OTD Folder]\Configurations` called Artisul and extract the content of this zip file in it.
- Open OTD's UX, go to Tablets > Tablet debugger
- Move your pen around, you'll see that some values appear, on the right you'll see the value for position.
- I want you to tell me the maximum value for position you can get **by moving to the bottom right corner**

**Comment by azaz08967565** [comment]
[51689,34308]

**Comment by Mrcubix** [comment]
is this the complete max you can get?

**Comment by azaz08967565** [comment]
Yes, im pretty sure

**Comment by Mrcubix** [comment]
[Artisul A1201.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6989463/Artisul.A1201.zip)
- Remove the old config, extract this one to Configurations\Artisul
- Go to Tablet > Device String Reader > Dump all > save the file somewhere > add .txt at the end if necessary when uploading it here

**Comment by azaz08967565** [comment]
[Artisul A1201.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6989493/Artisul.A1201.txt)

**Comment by Mrcubix** [comment]
[Artisul A1201.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6989507/Artisul.A1201.zip)
same thing, except everything should be working now

**Comment by azaz08967565** [comment]
In this file I have 2 configurations, is this ok? Or i need to use the new one only?

**Comment by azaz08967565** [comment]
[Artisul A1201.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6989519/Artisul.A1201.txt)

**Comment by Mrcubix** [comment]
as i said, replace the old one, and test if your tablet work

**Comment by azaz08967565** [comment]
Sorry, my bad, its works.

**Comment by Mrcubix** [comment]
I need to you test everything from position, buttons, everything

**Comment by azaz08967565** [comment]
all buttons are working, cursor is moving normaly, i think its shoud be fine

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.
