### ISSUE TITLE
Minimize to tray on startup

### ISSUE THREAD

**Issue by EnanoFurtivo** [OpenTabletDriver/OpenTabletDriver#1315]
This would be a really nice addition. Personally I place this program in the startup folder because I always end up using it. Having to minimize it twice a day gets old fast.

![image](https://user-images.githubusercontent.com/31115763/128212008-4a0c09f2-fd9c-43aa-8229-986a565714e3.png)

**Comment by InfinityGhost** [comment]
Not all platforms use a tray icon (Linux is an example) so it's not really something I want to implement. However, we do provide an [option](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/General-FAQ#ui) to start the program minimized

**Comment by Mrcubix** [comment]
You can also go into the shortcut properties and in `Run`, select minimized

**Comment by EnanoFurtivo** [comment]
Thanks for the suggestion, I ended up using -m in the shortcut as InfinityGhost stated.
