### ISSUE TITLE
Support Request: what if i have a mod windows iso and i wanna install plugins?

### ISSUE THREAD

**Issue by marcusnaatla** [OpenTabletDriver/OpenTabletDriver#1318]
I saw online if you have a modded windows iso you cant install plugins bcs of an error it shows when opening the .exe, when i click on "open plugins manager" nothing appens.

**Comment by Mrcubix** [comment]
Enable UAC and reboot, if you still get a warning when OTD start then you won't be able to use the normal output modes as well as functionalities such as the plugin manager and you'll have to download the plugins manually from their authors's repos.

OR

- Create an account with no perms (if you don't have one)
- Move OTD to that account
- On the non-admin account, create a new .bat file, insert inside the following:
```bat
cd [path to OTD folder]
start OpenTabletDriver.UX.Wpf.exe
```

- Create a shortcut, in the path, paste the following: 
`"C:\Windows\System32\cmd.exe" /k runas /user:[enter non-admin account name here] [path to previous batch file]`

- Go into the property of the existing osu! shortcut (if you have one) and change the location to 
`"C:\Windows\System32\cmd.exe" /k runas /user:[enter non-admin account name here] [path to osu.exe here]`

Remember to replace all the bracketed arguments with their corresponding value. You may also need to use "quotes" for file paths.

OR

Just don't use Debloated OSes, cause they are mostly made by people who don't know what they are doing.
