### ISSUE TITLE
[Detect:Error]	The configuration directory 'C:\Users\corn_\Desktop\Configurations\Configurations' does not exist.

### ISSUE THREAD

**Issue by ItzKrypticOsu** [OpenTabletDriver/OpenTabletDriver#1321]
Hi im having issues with my gaomon s620, decided to switch from hawku drivers to otd but every time i tried to install it would say tablet is not detected, everytime im prompted with configurations does not exist. pls help

**Comment by Mrcubix** [comment]
extract the zip file
