### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by ElboyYT** [OpenTabletDriver/OpenTabletDriver#1326]
# Support Request: Using my tablet as a mouse

Using my tablet as a mouse in Valorant

I want to try using my Wacom CTL-472 as a mouse in Valorant. But when valorant is open, i can only "click" my tablet as "MOUSE 1" and not moving it. I tried Absolute mode and Relative mode. Both only let a click trough

## What I've already tried
Reinstalling OTD and Valorant. 
Trying using Hawku driver, cant use it

**Comment by Mrcubix** [comment]
Valorant use an ultra-intrusive kernel anticheat, therefore, you first need to install the `VmultiMode` plugin available in `Plugin > Plugin manager` as well as it's [requirements](https://github.com/X9VoiD/vmulti-bin/releases/latest).  
Don't forget to bind the button you want to use left click for to a vmultimode bind (click on the 3 dots to open the advanced binding menu and select VmultiMode as the first option).  
If it still doesn't work after getting VmultiMode working then Riot probably updated their anticheat to be even more intrusive and won't allow your tablet to be used
