### ISSUE TITLE
gaomon s620 not working anymore

### ISSUE THREAD

**Issue by Ominous15** [OpenTabletDriver/OpenTabletDriver#1329]
## Description

I use OTD all the time for osu but its not juist not wokring in general, i cant move to cursor or anything, i can tap with the pen but thats it
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |
| OpenTabletDriver Version | 
| Tablet                   |

**Comment by Mrcubix** [comment]
Does `Tablets > debugger` show the pen movement?

**Comment by durbin-164** [comment]
@Mrcubix  Yes, For may case Debugger working But no course move for actual use.

**Comment by Mrcubix** [comment]
- Make sure User Account control is enabled to one of the top options, reboot.
- Make sure you're not using the `Administrator` account,
- Make sure Valorant isn't running in the background (kill it in task manager)

**Comment by durbin-164** [comment]
@Mrcubix Thanks a lot. After rebooting my os. It working now. Really greatfull to you.

I am new in tablet and OTD. Would you like to suggest me some useful addons that help me for writing and drawing?

**Comment by Mrcubix** [comment]
recommended: Reconstructor .43
preference: smoothing or anti-chatter, i won't tell you how to setup these as they have a wiki and it's preference
