### ISSUE TITLE
MTE-450 ghost clicks

### ISSUE THREAD

**Issue by C0D3-M4513R** [OpenTabletDriver/OpenTabletDriver#1330]
## Description

When lifting the pen from the tablet, the tablet returns some Depth information in the place, where pen pressure is stored.
The Depth information doesn't get above 0x09 for me.
Note: This happens only, when approaching with the pen tip, not the eraser.

Looking at the tablet debugger, I am noticing something. 

When approaching the tablet, with my pen, the `02 XX` value changes, in order, as follows:
Note: The columns stable output/detected pen tip/pen over tablet are just the interpretation, of the raw value.

|no.|value|stable output|detected pen tip|pen over tablet|I see depth info|
|-|----|-----|----|----|----|
|1.|50|no|yes|no|yes
|2.|D0|yes|yes|yes|yes
|3.|9X|yes|no|yes|no

When approaching the tablet from outside the tablet field, the value is just 80/81, with no depth information.

To resolve this one would have to block pen clicks, if  the 'detected pen tip' flag is set. (I think)

Referencing this for information: https://github.com/OpenTabletDriver/OpenTabletDriver/pull/656#issue-556246908

## System Information:
| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10 and Linux 
| OpenTabletDriver Version | v.0.5.3.3 and in osu!lazer
| Tablet                   | MTE-450

**Comment by C0D3-M4513R** [comment]
Another fix could be, to just live, with a short detection depth, and set the Active Report ID to `[64..80)`.
For me, that just feels like a hotfix, that should not be done, unless it is absolutely impossible, to add what I proposed above.

**Comment by InfinityGhost** [comment]
v0.6 doesn't use report ID anymore, this should be implemented in the report parser.

**Comment by C0D3-M4513R** [comment]
Should. Yes. This is a hotfix. this should then be fixed before v0.6?

**Comment by C0D3-M4513R** [comment]
Made a change to the correct report parser. Hope this will do. Gonna game for now.
