### ISSUE TITLE
KAMVAS 22 PLUS Request support

### ISSUE THREAD

**Issue by Diediediediediediedie** [OpenTabletDriver/OpenTabletDriver#1336]
# Support Request

## Diagnostic Information

![image](https://user-images.githubusercontent.com/88857023/129291273-32529a9c-442f-4006-a277-4be9e01715c1.png)
![image](https://user-images.githubusercontent.com/88857023/129291288-c231c1c0-766d-448b-961d-3915e491a465.png)

**Comment by Mrcubix** [comment]
Fill the template, no support will be provided until filled
