### ISSUE TITLE
Support Request: KAMVAS 22 PLUS

### ISSUE THREAD

**Issue by Diediediediediediedie** [OpenTabletDriver/OpenTabletDriver#1338]
# Support Request

## Diagnostic Information

![image](https://user-images.githubusercontent.com/88857023/129291273-32529a9c-442f-4006-a277-4be9e01715c1.png)
![image](https://user-images.githubusercontent.com/88857023/129291288-c231c1c0-766d-448b-961d-3915e491a465.png)

**Comment by SnowLire** [comment]
Fill out the support template properly. There are steps written for you to follow.
And don't open the same issue twice.

**Comment by Diediediediediediedie** [comment]
Sorry~ I don’t know what a template is, but I know it doesn’t support KAMVAS 22 PLUS, so I want to ask for support.

**Comment by SnowLire** [comment]
Then it'd be easier if you join the discord server. You can leave this issue open until it's resolved.

**Comment by Diediediediediediedie** [comment]
Yes~ I joined discord but I don’t know where to ask

**Comment by SnowLire** [comment]
In #help-windows.
