### ISSUE TITLE
Plugins not showing up after downloading.

### ISSUE THREAD

**Issue by whorru** [OpenTabletDriver/OpenTabletDriver#1341]
## Description

Plugins don't show up even after downloading it through the Plugin Manager or downloading it manually.

https://streamable.com/9gxyph

## System Information:

| ---------------------------------- | 
| Operating System             | Manjaro Linux 21.1.0
| OpenTabletDriver Version | v0.5.3.1-r399.g1e366358
| Tablet                                 | Wacom CTH-680

**Comment by AbstractQbit** [comment]
Use `opentabletdriver` package instead of `opentabletdriver-git`. The latter builds from master and plugins don't support that yet.
