### ISSUE TITLE
Wacom CTL 472 N - no tablet detected

### ISSUE THREAD

**Issue by tinutt** [OpenTabletDriver/OpenTabletDriver#1342]
## Description

I installed the driver and uninstalled it a couple of times because of this and it decides to work sometimes and sometimes it doesn't, usually a couple days do it.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Windows 10         |
| v0.5.3.3 |
| wacom ctl 472 N                 |

**Comment by SnowLire** [comment]
Please provide a diagnostic file in OTD by doing `Help > Export diagnostic` and send it zipped.

**Comment by tinutt** [comment]
how do i send it zipped? sorry im kinda dumb

**Comment by SnowLire** [comment]
Right click the file > Send to > Compressed folder.
You can also just change the file extension from .json to .txt and send it as that.

**Comment by tinutt** [comment]
[issue.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6986301/issue.txt)

**Comment by SnowLire** [comment]
You have to extract the UX, Daemon and Configuration folder into its own folder, preferably on your Desktop and ***NOT*** run them straight from the zip file.

**Comment by tinutt** [comment]
it does the same thing
if you need a new diagnostic from where i extracted it-
[3.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6986322/3.txt)

**Comment by SnowLire** [comment]
Kill every OTD related process in Task Manager and run the extracted UX again.

**Comment by tinutt** [comment]
its fixed, TYSM <3
