### ISSUE TITLE
Support Request: Pen Buttons

### ISSUE THREAD

**Issue by Hamburgesaa** [OpenTabletDriver/OpenTabletDriver#1344]
In the hawku driver there was a option to turn off the pen buttons which let me to not click stuff when pressing down the pen, Is that feature somewhere in the open driver or will it be added later because i can't find it?

**Comment by SnowLire** [comment]
You just have to unbind the tip or pen button within the Bindings menu.

**Comment by Hamburgesaa** [comment]
thank u :)
