### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by mochi39** [OpenTabletDriver/OpenTabletDriver#1346]
# Support Request

Hello, Im new to this tablet driver and theres something wrong about it when i try launching it.

This picture below shows when i try starting it, it just exit the app and reopen it (i tried this many times but it still the same) but it doesnt show the inside of it like the picture B that ive shown. I need help please thanks in advance!

![Screenshot (93)](https://user-images.githubusercontent.com/88971452/129479537-50ab899f-40c2-4c37-a275-07239db21204.png) (picture A)

![Screenshot (94)](https://user-images.githubusercontent.com/88971452/129479590-34f0111d-9022-43e8-8fe0-fdaf22e17b87.png) (picture B)

**Comment by mochi39** [comment]
i already open the daemon, and it just showing me the cmd. (just wanted to show this so that nothing wrong happens on the daemon)

![Screenshot (95)](https://user-images.githubusercontent.com/88971452/129479766-9f3ecd50-a77b-41e7-868e-1271ac7780be.png)

**Comment by jamesbt365** [comment]
what tablet are you using?

**Comment by Mrcubix** [comment]
Don't use the installer, use the portable release https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.3 don't forget to extract the zip file to it's own folder

**Comment by mochi39** [comment]
> what tablet are you using?

im using the gaomon s620.

**Comment by mochi39** [comment]
> Don't use the installer, use the portable release https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.3 don't forget to extract the zip file to it's own folder.
> 
> if it still close when opening the UX then delete `%localappdata%\opentabletdriver` and try again.
> if it persist, let us know in this issue by just posting another message and i'll re-open.

okay, will try it

**Comment by mochi39** [comment]
Hello, i already try the portable one but i think its still have the same problem. ( i dont know if i did it right or wrong)

i try to run the daemon and then starting the UX, but it doesnt open/run the app. Then i try to delete the folder on the localappdata and try it again but still the same. (it only shows the Plugins folder on the localappdata)
![Screenshot (96)](https://user-images.githubusercontent.com/88971452/129506270-db59b5ae-2cbb-4813-9f67-a45eb95f5389.png) (picture A)

This picture below shows that the UX app doesnt appear on the task manager when i try running it.
![Screenshot (97)](https://user-images.githubusercontent.com/88971452/129506289-81d380b6-9365-46df-a34b-79445cc4a9ff.png) (picture B)

**Comment by Mrcubix** [comment]
do `dotnet --list-runtimes` in cmd and paste the result here

**Comment by mochi39** [comment]
> do `dotnet --list-runtimes` in cmd and paste the result here

C:\WINDOWS\system32>dotnet --list-runtimes
Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jamesbt365** [comment]
This is either, a stuck daemon, can be solved by killing it in task manager or restarting your pc, missing dotnet, which we can see that you have above or probably something missing between wpf applications which can be caused by debloating or otherwise damaging your windows install.
