### ISSUE TITLE
Support Request: Cursor doesn't utilize entire monitor on osu

### ISSUE THREAD

**Issue by Hamburgesaa** [OpenTabletDriver/OpenTabletDriver#1348]
My monitor is 2560 X 1440 but I always played osu on 1080 and had drivers set to 1920 X 1080 and worked fine, but right now the cursor only uses like half the screen instead of the full screen. and yes i turned off raw input

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/129494021-3326b8b1-b482-4ed9-bf89-9c43e45c3daa.png)
you'll need a setup similar to this, except the width will be 1920, height 1080, and the area need to be placed at the top left of the display in question

**Comment by Hamburgesaa** [comment]
fixed now thanks
