### ISSUE TITLE
Virustotal flags malware in windows portable v0.5.3.2 and above

### ISSUE THREAD

**Issue by pushkine** [OpenTabletDriver/OpenTabletDriver#1355]
Related #883 
* **v0.5.3.1** Safe https://www.virustotal.com/gui/file/b738d7f044d0be05013c64c0d3c490a7e2c803a897875df63147cdc0b1318acd/detection
* **v0.5.3.2** Unsafe https://www.virustotal.com/gui/file/99c2c9754cd9f637a890cae3ed55ab0e7b7cded7b9ed8ba8837365e2092e6d40/detection
* **v0.5.3.3** Unsafe https://www.virustotal.com/gui/file/42647f688074b8b1e15345ed08c8a9f2e682981a44c12b1ac5e6037876c911a3/detection

Edit: Actually even the 0.5.3.1 daemon gets flagged https://www.virustotal.com/gui/file/cda5a3d5bf6a13f2134fee8bf43f963cded4d70c317bf82e2b70d18458b9a3a7/detection

**Comment by InfinityGhost** [comment]
These are all false positives, we basically have to submit a request to have a manual review performed in order to get them to go away. It's inconvenient and plagues open source software as a whole.

**Comment by X9VoiD** [comment]
One or two detections doesn't mean the program is unsafe. That just means the AV is shit and reports false positive. Open this issue again when you see atleast 40% of the AVs reporting OTD as malware.
