### ISSUE TITLE
Huion h640p "Tablet not found"

### ISSUE THREAD

**Issue by TurtleDuck33** [OpenTabletDriver/OpenTabletDriver#1360]
I downloaded the driver to get a better time playing osu, but when i downloaded it, it just said that no tablets were connected. It said that the h640p was supported. Help please

**Comment by SnowLire** [comment]
Follow the steps here: https://opentabletdriver.net/Wiki/FAQ/Windows#uclogic-supported-undetected

**Comment by gonX** [comment]
Closing as stale support request
