### ISSUE TITLE
Stuck on full area.

### ISSUE THREAD

**Issue by platinumnova** [OpenTabletDriver/OpenTabletDriver#1363]
ive just downloaded it after getting my new tablet when i set my area but it was stuck on full.
| Operating System   | Windows
| OpenTabletDriver Version | v0.5.3.3
| Tablet    | Wacom CTH-480

**Comment by jamesbt365** [comment]
export diagnosis and send it here, to do that go to help > export diagnosis then save the file and send it here.

**Comment by Mrcubix** [comment]
I Would usually say That the template is not filled in this situation but james already said what has to be done and i'm pretty sure the reason why you have this issue is because:

- You didn't uninstall wacom drivers using the uninstaller

**Comment by X9VoiD** [comment]
Will close stale issue
