### ISSUE TITLE
Stuck on full area

### ISSUE THREAD

**Issue by uhmmoyo** [OpenTabletDriver/OpenTabletDriver#1366]
## Description
after a windows update - launching open tablet driver seems to do nothing. It detects the tablet fine, but it's stuck on full area and pen reacts to windows ink default settings.

i'll attach a diagnostic report 

## System Information:
| Operating System | Windows
| OpenTabletDriver Version | v0.5.3.3
| Tablet | Wacom CTH-480

**Comment by uhmmoyo** [comment]
[8.21.21Diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7026364/8.21.21Diagnostic.txt)

**Comment by Mrcubix** [comment]
uninstall wacom drivers

**Comment by uhmmoyo** [comment]
> uninstall wacom drivers

I don't have the wacom drivers installed. I re-installed them and uninstalled them again successfully and still nothin.

**Comment by Mrcubix** [comment]
export diagnostic again

**Comment by X9VoiD** [comment]
Will close stale issue.
