### ISSUE TITLE
Support Request: Area Star 06C

### ISSUE THREAD

**Issue by lofesed** [OpenTabletDriver/OpenTabletDriver#1372]
the area does not change, the entire tablet is always used, xp-pen drivers have been removed

**Comment by lofesed** [comment]
Okay, I've already decided this myself, but the cursor started to double

**Comment by Mrcubix** [comment]
you have another driver running or 2 interpolators enabled

**Comment by lofesed** [comment]
> У вас запущен другой драйвер или включены 2 интерполятора

the thing is that I tried with a clean Windows and there are no other drivers except opd, I suspect that this is due to the built-in pen control function from win. How to solve it?

**Comment by Mrcubix** [comment]
get this build https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/1113083538
extract it in it's own folder, create a folder named `userdata` and start the UX

**Comment by gonX** [comment]
Closing stale support request. Tablet is supported.
