### ISSUE TITLE
Support Request: veikk S640 wont detect 

### ISSUE THREAD

**Issue by mozurino** [OpenTabletDriver/OpenTabletDriver#1375]
# Support Request
 
new bought veikk S640 wont detect
 
![image](https://user-images.githubusercontent.com/89719875/131239314-ce10d101-dd04-4740-90f6-3dababfec706.png)

## What I've already tried

i tried restarting after unistalling the original veikk drivers and switching usb ports open tablet wont detect the tablet
## Diagnostic Information

[diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7071971/diagnostic.zip)

**Comment by X9VoiD** [comment]
This is already fixed in OTD master.

**Comment by mozurino** [comment]
> OTD master.

OTD master?

**Comment by jjhhgg100123** [comment]
> 
> 
> > OTD master.
> 
> OTD master?

The latest build. Click on actions and download from there.
