### ISSUE TITLE
Osu! game fix

### ISSUE THREAD

**Issue by Amirelox** [OpenTabletDriver/OpenTabletDriver#1377]
## Description

Hi,
I play osu! this is a rythmic game.
My tablet with OTD in windows desktop is good, normal, when I open Osu! game didnt detect tablet and drivers.
I used full screen and bordless, 1920:1080 and 1280:720 and didnt work. Pls help ^^
Best Regards Amir

## System Information:

| Name  Amir           | Value |
| ---------------- | ----- |
| Operating System  Win 10 64       |
| OpenTabletDriver Version | 5.3.3
| Tablet  Huion 1060 plus                 |

**Comment by jamesbt365** [comment]
Dont run osu! in administrator.

**Comment by Amirelox** [comment]
https://youtu.be/e3pD2ht5di4

**Comment by Amirelox** [comment]
Thank you
god
