### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by KuroiRyuOsu** [OpenTabletDriver/OpenTabletDriver#1385]
I used these drivers for months, after a incident that has occurred recently the driver was uninstalled from my PC. I tried reinstalling it only to get a virus warning, and the installation stops?  I don't know much about software so I'm confused.

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/131509251-3eda7429-fb98-44a8-bee6-31f35f5cbba7.png)


Reports were sent to AVs a long time ago, The only remaining "AVs" that still detect it, are either outdated or adwares which either haven't answered our report or we couldn't bother to send report to.

The only things i can say in this situation is add an exception or just stick to defender which will probably do a better job.
