### ISSUE TITLE
Valid inputs being dropped - Hover distance and area issues

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1401]
## Description

Many valid inputs are being ignored leading certain tablets to have their input cut off before it should be. This can lead to lowered hover distance, and certain parts of areas (specifically some parts of the area deadzones on wacom tablets) being unreachable or having input cut off too soon.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| OpenTabletDriver Version | 0.6.0 Pre-release
| Tablet                   | Tested on CTL-480 but many others likely affected

**Comment by jamesbt365** [comment]
How would i check for this on my xp pen G640 Rev a?

**Comment by Kuuuube** [comment]
> 
> 
> How would i check for this on my xp pen G640 Rev a?

Go to `tablets > tablet debugger` and check if theres any points where the `Raw Tablet Data` box still shows valid position bytes sent but there is no position shown in the `Tablet Report` box. 
Usually this should be around the edges of the tablet or when hovering nearly out of range.

**Comment by jamesbt365** [comment]
When moving out on one of the sides of my tablet and come back into range my cursor gets stuck even though it still moves on the tablet debugger, it says there for about a second unless i manually replace my pen. This only happens occasionally, however i have found no dead zones or spots on my G640 Rev A.

I don't think the hover is high enough to really be cut off but i haven't really done much testing on that regard. Going to do more testing when i come back from school tomorrow but i`m unsure if this is Wacom only.

**Comment by InfinityGhost** [comment]
This issue really needs to be narrowed down to track individual cases, right now we have no idea if this is resolved.

**Comment by Kuuuube** [comment]
I don't have time right now to test this on all my tablets and that will probably have to wait a week or so but I can give you this: The Wacom CTL-480 reports get ignored when it has `D0` in the second byte which cuts off a lot of the hover.

**Comment by gonX** [comment]
Likely fixed by #1698
