### ISSUE TITLE
Filters are not refreshed when new plugins are added

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1402]
## Description

Previously after installing a new plugin the filters tab would be refreshed and the plugin would be shown there. That seems to no longer be the case. 
I have only tested this with plugins manually installed through plugin manager and cannot yet verify if installing using the plugin repo has this issue as well.
Restarting OTD causes the plugin to show and it does work normally.

Tested using an updated version of Kuuube's Chatter Exterminator. [Download Here](https://cdn.discordapp.com/attachments/628651971267788800/884592400402632744/Kuuubes_CHATTER_EXTERMINATOR.dll)
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | 0.6.0 Pre-release

**Comment by jamesbt365** [comment]
I can confirm that this is not a one of thing and that it has happened multiple times for me.

**Comment by Kuuuube** [comment]
This appears to happen only when installing a plugin when there are no plugins currently loaded.

Two more plugins to help with testing this:
[Hover Distance Limiter](https://cdn.discordapp.com/attachments/628651971267788800/884604847805042788/Hover_Distance_Limiter.dll)
[Tablet Debounce](https://cdn.discordapp.com/attachments/628651971267788800/884604847981223956/Tablet_Debounce.dll)

**Comment by Kuuuube** [comment]
This is not fixed. Tested with 0.6.0rc2 on windows 10.

Here's Circular Area for 0.6.0 for testing: [2.0.0_release_Circular_Area.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7799849/2.0.0_release_Circular_Area.zip)

**Comment by Kuuuube** [comment]
0.6.0rc2 windows release was built off the wrong commit. This is fixed on the corrected 0.6.0rc2.
