### ISSUE TITLE
G430S has lower report rate on 0.6.0

### ISSUE THREAD

**Issue by coinworld** [OpenTabletDriver/OpenTabletDriver#1403]
## Description

G430S (and possibly other tablets) has lower report rate on 0.6.0, and cursor movement is significantly slower.
This doesn't happen on CTL-472, so I think it's because of some changes between these two versions.

---

![screenshot_20210907_143818](https://user-images.githubusercontent.com/9151706/132290078-f746c3b2-f41f-49ed-87e3-abfb66625f07.png)
^ 0.5.3.3

![screenshot_20210907_143646](https://user-images.githubusercontent.com/9151706/132290112-071568fd-84f7-4d69-a104-40a647b857c0.png)
^ 0.6.0 pre-release

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | openSUSE Tumbleweed
| OpenTabletDriver Version | 0.6.0 pre-release on discord
| Tablet                   | XP-Pen G430S

**Comment by iotku** [comment]
Can confirm, troubleshot this a fair bit on discord in #help-linux but didn't come to any meaningful conclusion. (Was planned to create an issue but I don't think one has been made prior to this.)

Same issue on my system.


Name | Value
-- | --
Operating System | Arch Linux
OpenTabletDriver Version | 0.6.0 pre-release on discord (and previously on master via opentabletdriver-git AUR Package)
Tablet | XP-Pen G430S

**Comment by iotku** [comment]
Of slight possible note v0.6.0.0 detects my tablet as "XP-Pen Star 430S", while v0.5.3.3 detects my tablet as "XP-Pen Star 430" (No S at the end) so it could potentially be using a different code-path? (or was just renamed)
