### ISSUE TITLE
Driver stops working when I open some programs.

### ISSUE THREAD

**Issue by nowonn** [OpenTabletDriver/OpenTabletDriver#1413]
## Description
When I open the Task Manager, for example, my cursor freezes, and I have to Alt+Tab for it to work again. Same thing with program installers and that "changes to your device" confirmation that pops up when opening stuff.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10 |
| OpenTabletDriver Version | v0.5.3.3 |
| Tablet                   | VEIKK S640 |

**Comment by InfinityGhost** [comment]
This is due to how the SendInput API works, it's for "security" so that programs can't click dialogs for you. The only workaround is to install the VMultimode plugin.
