### ISSUE TITLE
Soft handling of permission errors (when saving configs)

### ISSUE THREAD

**Issue by keksbg** [OpenTabletDriver/OpenTabletDriver#1430]
## Description
In the GUI part of the driver, when saving a configuration, if the user does not have permissions, the GUI will crash and not handle the permission error. This is partially a bug report and also an enhancement.
```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.UnauthorizedAccessException: Access to the path '/usr/share/OpenTabletDriver/gaming' is denied.
 ---> System.IO.IOException: Permission denied
 -- snip --
```
Preferably, this would be handled softly with an error prompt for the user. ~~now i know i should just be saving the configs elsewhere but shut up~~

**Comment by X9VoiD** [comment]
Already resolved by #1398
