### ISSUE TITLE
Add support for WoodPad 7 PF0730

### ISSUE THREAD

**Issue by YusufOzmen01** [OpenTabletDriver/OpenTabletDriver#1435]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer   | ViewSonic
| Product Name    | WoodPad 7 PF0730
| Width           | 162
| Height          | 101
| Pressure Levels | 4096
| LPI             | 5080

## Diagnostic Information
[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7162693/diagnostics.txt)

**Comment by Mrcubix** [comment]
viewsonic making tablets? *oh no* anyway, [join the discord server](https://discord.gg/P3GYdUS) so we can deal with this stuff in real time, GO in #Help-windows There create a new thread, with the name of your tablet as the title then ping me (Mrcubix on the server)
