### ISSUE TITLE
Add support for Vabnoo VB960

### ISSUE THREAD

**Issue by ShizuMog** [OpenTabletDriver/OpenTabletDriver#1443]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | Vabnoo/XP-Pen
| Product Name    | VB960
| Width           | 228.6mm
| Height          | 142.88mm
| Pressure Levels | 8192
| LPI             | 5080

## Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7186298/diagnostics.txt)

**Comment by jamesbt365** [comment]
to make a config lots of tests have to be made, if you can join our discord server and go into a help channel that applies to what operating system you are on.

**Comment by jamesbt365** [comment]
Closed due to no reply
