### ISSUE TITLE
Support Request:  I have set up my tablet to the area that i like and now every time I try to use it the cursor teleports to the top left and follows along that axis 

### ISSUE THREAD

**Issue by AsherHasArrived** [OpenTabletDriver/OpenTabletDriver#1444]
# Support Request

**Comment by jamesbt365** [comment]
You literally have given us no infromation.

**Comment by AsherHasArrived** [comment]
i dont know how to use this website sorry

**Comment by doubledge-spec** [comment]
ask in the discord server https://discord.gg/P3GYdUS

**Comment by SnowLire** [comment]
Fill out the issue or join the discord server to ask for help. Also you can easily search up similar issues in the repository or on the internet.
