### ISSUE TITLE
Gaomon S56K ReportParser problem

### ISSUE THREAD

**Issue by Patriot720** [OpenTabletDriver/OpenTabletDriver#1448]
## Description
idk if it's my specific gaomon s56k problem or not but
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/04adf913cdaa282ce97d86f0e8ebee12264ef17e/OpenTabletDriver/Vendors/UCLogic/UCLogicReportParser.cs#L6-L16
[tablet-data.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7191270/tablet-data.txt)

That bit is only 00 upon entering tablet "interactive area"
And most of the time it's not
``` json
{
      "VendorID": 9580,
      "ProductID": 110,
      "InputReportLength": 8,
      "OutputReportLength": null,
      "ReportParser": "OpenTabletDriver.Tablet.TabletReportParser",
      "FeatureInitReport": null,
      "OutputInitReport": null,
      "DeviceStrings": {
        "201": "HUION_T156_\\d{6}$"
      },
      "InitializationStrings": [
        200
      ]
}
```
Works fine if i set TabletReportParser manually in the s56k config
[Vid](https://puu.sh/IcqOF/9b0a219147.mp4)
[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7191632/diagnostics.txt)
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         Arch linux|
| OpenTabletDriver Version OpenTabletDriver v0.5.3.1-r460.g04adf913 |
| Tablet                   Gaomon S56K |

**Comment by X9VoiD** [comment]
There's no aux data recorded in the tablet-data.

**Comment by Patriot720** [comment]
> There's no aux data recorded in the tablet-data.

There are no buttons on that tablet why would there ever be aux data, unless i misunderstand what aux here means.

Also that's what Tablet debugger data recording outputs into a file, at least on my system.
Only raw tablet data there 
![image](https://user-images.githubusercontent.com/8457664/133934066-8cc0b5ca-0ef1-49cc-aa47-581f42e516c3.png)
