### ISSUE TITLE
Support Request: i've saved my tablet and it worked fine but after i downloaded visual studio i cant load that area again or any other area i save on my desktop

### ISSUE THREAD

**Issue by LavonDvivon** [OpenTabletDriver/OpenTabletDriver#1451]
# Support Request

**Comment by jamesbt365** [comment]
As in visual studio hijacks your .json files?

**Comment by SnowLire** [comment]
Please fill out the support template correctly in another issue. Closing for empty description.

**Comment by LavonDvivon** [comment]
> As in visual studio hijacks your .json files?

yeah

**Comment by jamesbt365** [comment]
Thats a visual studio thing not ours, either way use the file panel to open your jsons, windows has a option to change what apps open your files anyway.

**Comment by LavonDvivon** [comment]
> Thats a visual studio thing not ours, either way use the file panel to open your jsons, windows has a option to change what apps open your files anyway.

ohhhh ok thanks
