### ISSUE TITLE
Add support for UGEE 1910b

### ISSUE THREAD

**Issue by TheZero3546** [OpenTabletDriver/OpenTabletDriver#1462]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    |UGEE|
| Product Name    |1910b|
| Width           |406mm|
| Height          |254mm|
| Pressure Levels |2048|
| LPI             |5080|

## Diagnostic Information

[Diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7224585/Diagnostic.zip)

**Comment by Mrcubix** [comment]
This has the same vendorID and productID as the `XP-Pen Artist 22HD` which got merged in master, and i would also advise you to immediately get a refund as this tablet doesn't meet any of the advertised specs period other than the physical size

[99-opentabletdriver.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7730988/99-opentabletdriver.zip)
extract the content of that zip file with the following path `sudo mv [location] /etc/udev/rules.d/99-opentabletdriver.rules` (replace `[location]` with the file location).
Once done, do:
`sudo udevadm control --reload-rules`,
and for good measure, reload the daemon using:
`systemctl --user restart opentabletdriver.service`.

[Artist 22HD.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7731085/Artist.22HD.zip)

extract the content of this zip file to `/usr/share/OpenTabletDriver\Configurations`
