### ISSUE TITLE
GUI doesn't open on X11/KDE

### ISSUE THREAD

**Issue by C0D3-M4513R** [OpenTabletDriver/OpenTabletDriver#1470]
## Description

I am using a Arch computer, with KDE. On Wayland OTD causes plasmashell crashes (https://bugs.kde.org/show_bug.cgi?id=443003).
On X11 OTD works fine, but the gui won't open.

```
[user@archlinux ~]$ otd-gui  

(OpenTabletDriver.UX.Gtk:83950): Gtk-WARNING **: 11:59:41.623: Locale not supported by C library.
        Using the fallback 'C' locale.

#Shell is then hung here. No Window is open on any virtual desktop, nor did anything pop up in the tray.
```
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Arch 5.14.7-arch1-1
| OpenTabletDriver Version | 5.3.3-1
| Tablet                   | MTE-450

**Comment by X9VoiD** [comment]
This is a problem in your system and not of OTD, will close issue as this is external to OTD.

Set your locale correctly.

**Comment by C0D3-M4513R** [comment]
The notice with the locale I have been getting on every linux install ever.

That is with almost every prebuilt image, including ubuntu, arch, manjaro, dietpi, debian, raspbian.

I cannot name the affected programs. I've only ever thought: "The program works, and that is only a warning, I'll ignore that for now."

I do not think, that the locale is at fault here.
I can try and debug the gui crash in a IDE, and give the exact code line(if any) that gives this issue. (I'm a little busy atm, so might be a little while)

**Comment by jamesbt365** [comment]
its complaining of locale, its not us.

**Comment by C0D3-M4513R** [comment]
> its complaining of locale, its not us.

What do you want to say? I don't understand. What is it referring to? What is us referring to?
`us` as in the programm, and `it` as in the X server/linux kernel?
or `us` as in the contributers, and `it` as in the programm?

**Comment by jamesbt365** [comment]
`(OpenTabletDriver.UX.Gtk:83950): Gtk-WARNING **: 11:59:41.623: Locale not supported by C library.
        Using the fallback 'C' `locale.`

it doesnt like something to do with your locales, try making them fresh. Sometimes they fuck themselves up

**Comment by C0D3-M4513R** [comment]
A `sudo locale-gen` later and everything works again. Interesting... I'll keep that in my head. Ty.

**Comment by jamesbt365** [comment]
No problem.
