### ISSUE TITLE
Tablet stops working when games are opened

### ISSUE THREAD

**Issue by Sqweeblord** [OpenTabletDriver/OpenTabletDriver#1492]
## Description
Tablet is working perfectly when background applications are open (discord, steam, chrome, etc.) but once I open a game (osu, csgo, valorant) it stops moving all together. 
Video of the issue: https://youtu.be/od9HmtM74Bg
osu does not have any form of raw input enabled and also doesn't work in windowed fullscreen
this also wasn't happening before but I went to college and came back without changing anything and now it has sprung up

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7314846/diag.txt)

## System Information:
| Windows 10 Home Build 19042.1165|
| OTD version 0.5.3.3|
|Tablet CTH-480|

**Comment by X9VoiD** [comment]
Do not run those games as admin.

**Comment by Sqweeblord** [comment]
> Do not run those games as admin. Vanguard also prevents OTD from injecting any input to Valorant.

It doesn't work with or without running as admin or having vanguard running. Also isn't working even with games closed after having it closed for a couple hours and re-opening

**Comment by X9VoiD** [comment]
If that is the case, then are you seeing a warning when launching OTD? If there is then enable UAC.

**Comment by Sqweeblord** [comment]
> If that is the case, then are you seeing a warning when launching OTD? If there is then enable UAC.

No warnings but I can try and enable UAC anyway, how do I do that?
