### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by ericaorj** [OpenTabletDriver/OpenTabletDriver#1493]
hello i am having an issue since 2-3 days or more that shows up the message 'no tablet detected' whenever i open the driver
how can i fix that and go back to playing?

**Comment by ericaorj** [comment]
> first of all you didnt fill out the format and second what tablet
> 
> third export a diag in otd by going to help > export diagnosis, save the file then send it here

sorry im new user~~
tablet is Huion HS64
[HuionHS64.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7315378/HuionHS64.txt)

**Comment by jamesbt365** [comment]
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0

follow the steps on this

**Comment by jamesbt365** [comment]
no problem
