### ISSUE TITLE
Support Request: Huion 430p not detected 

### ISSUE THREAD

**Issue by DownFall1857** [OpenTabletDriver/OpenTabletDriver#1499]
I'm trying to use the driver but it is not working like it did a couple days ago. I've tried uninstalling and reinstalling.

**Comment by jamesbt365** [comment]
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0

try following the steps on this.

**Comment by DownFall1857** [comment]
thank you so much it worked!
