### ISSUE TITLE
Add support for Genius Pen 560

### ISSUE THREAD

**Issue by lolerfox** [OpenTabletDriver/OpenTabletDriver#1500]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | Genius
| Product Name    | G-Pen 560
| Width           | 152
| Height          | 114
| Pressure Levels | 1024
| LPI             | 2000

## Diagnostic Information
 

[diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7322970/diagnostic.zip)

**Comment by lolerfox** [comment]
Nothing...

**Comment by Mrcubix** [comment]
are there only 3 devices inside the container?

**Comment by lolerfox** [comment]
as I understand it, the experiment with genius tablets turned out to be a failure?

**Comment by lolerfox** [comment]
Still not...
I tried to run 0.5.3.3... the console gives this error... can this help in any way?
![изображение](https://user-images.githubusercontent.com/60233774/136848468-1bb84314-83e8-4ccb-b1f7-3ae42707500d.png)

**Comment by jamesbt365** [comment]
you need to run on the pre release https://cdn.discordapp.com/attachments/615939905566015493/890625738691211334/OpenTabletDriver.win-x64.zip
because .5.3.3 doesnt support multiple inits or winusb

**Comment by jamesbt365** [comment]
create a userdata folder when you extract it
put the config in the configurations folder located at this location

**Comment by jamesbt365** [comment]
Probably my error now, can you export another diag on the pre release build please?

**Comment by lolerfox** [comment]
Thanks for you help! I really appreciate your patience! If I were you, I would have already given up xd

[diag.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7325191/diag.zip)

**Comment by jamesbt365** [comment]
Can you go back onto zadig and check if winusb is installed on interface 0 please?

**Comment by lolerfox** [comment]
[cap1.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7325309/cap1.zip)
