### ISSUE TITLE
Tablet area its always full even after changing it.

### ISSUE THREAD

**Issue by KereSiQ** [OpenTabletDriver/OpenTabletDriver#1510]
## Description
I changed my old wacom drivers to the OpenTabletDriver. Before I did it I uninstalled the wacom drivers and used installation guide. After I opened the driver 1st I wanted to do is changing the tablet area but when I did it nothing happened.

## System Information:
Windows 10
| OpenTabletDriver Version | 0.5.3.1
| Tablet| Wacom Ctl-47

![Untitled](https://user-images.githubusercontent.com/92404515/137033804-0ebaca40-26be-44f7-bdc2-d30816afa575.png)

![Untitled](https://user-images.githubusercontent.com/92404515/137033909-205e13ff-b139-4dc6-8638-9f6316ba1013.png)

**Comment by jamesbt365** [comment]
You still havent uninstalled wacom drivers, you need to do it through apps and features
