### ISSUE TITLE
Support Request: XP-Pen Deco 01

### ISSUE THREAD

**Issue by qizuuu** [OpenTabletDriver/OpenTabletDriver#1537]
my deco 01 v1 is defined as deco 01 v2. And yet, I cannot adjust the anti-smoothing filter.
with any settings, I observe a very strong shaking of the cursor

**Comment by qizuuu** [comment]
[diag.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7392407/diag.json.txt)

i installed only OTD
And use only reconstructor filter

**Comment by jamesbt365** [comment]
Closed as this seems long abandoned. From "strong shaking" either 2 drivers were running or another form of interference was happening. If this issue still has attention to it then reopen.
