### ISSUE TITLE
Huion h430p not detecting

### ISSUE THREAD

**Issue by Hatry1337** [OpenTabletDriver/OpenTabletDriver#1545]
## Description
Huion H430P tablet not detecting on manjaro

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Linux Manjaro KDE, kernel: 5.14.10-1-MANJARO  |
| OpenTabletDriver Version | 0.5.3.3 |
| Tablet                   | Huion h430p |

Diagnostics:
[otdd.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7402589/otdd.txt)

**Comment by gonX** [comment]
Does #1705 fix your issue? Try with its associated action build if you don't know how to build it yourself.

**Comment by Hatry1337** [comment]
That's it! Thank a lot. Now tablet detects and work fine.
