### ISSUE TITLE
Hawku Smoothing Filter crashes OpenTabletDriver

### ISSUE THREAD

**Issue by PaulCoolDQueenLeon** [OpenTabletDriver/OpenTabletDriver#1561]
## Description

Open Tablet Driver does crashes without any warning, it does happens when Interpolator  Hawku Smoothing Filter is activated. 
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |Manjaro 
| OpenTabletDriver Version| v0.5.3.3
| Tablet                  | Wacom CTH-490

**Comment by gonX** [comment]
Relevant debug output:
```json
    {
      "Message": "Unable to construct object 'TabletDriverFilters.Hawku.Smoothing'",
      "Level": 3
    },
    {
      "Message": "No constructor found for 'TabletDriverFilters.Hawku.Smoothing'",
      "Level": 0
    }
```

Did you install the plugin from the plugin manager? I notice you have pretty much all plugins installed - does it help if you remove the ones you don't need?

**Comment by gonX** [comment]
Closing abandoned support request
