### ISSUE TITLE
Extremely High Memory Usage on Mac OS Big Sur

### ISSUE THREAD

**Issue by menmaa** [OpenTabletDriver/OpenTabletDriver#1565]
## Description
Memory usage of the OpenTabletDriver app in Mac OS seems to be constantly increasing. Reached as high as 6 GB of ram.

## System Information
| Name             | Value |
| ---------------- | ----- |
| Operating System         | macOS Big Sur 11.6.1 (Apple M1)
| OpenTabletDriver Version | v0.5.3.3
| Tablet                   | Wacom CTL-472

## Attachments
<img width="895" alt="Screenshot 2021-10-28 at 5 45 24 AM" src="https://user-images.githubusercontent.com/31330913/139178339-d6d8bab4-0d16-45ee-981b-adcdf627da67.png">

**Comment by jamesbt365** [comment]
Can you test if it is fixed in #1783

**Comment by jamesbt365** [comment]
Going to assume that this memory leak is solved in #1783 as no more complaints have been said since then.
