### ISSUE TITLE
When I open the OpenTabletInstaller and click start it just relaunches the app over an over again

### ISSUE THREAD

**Issue by AceCommatic** [OpenTabletDriver/OpenTabletDriver#1570]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |
| OpenTabletDriver Version |
| Tablet                   |

**Comment by jamesbt365** [comment]
Don't the the installer, use the portable builds instead.

**Comment by Mrcubix** [comment]
template not filled / properly + don't use installer + use [portable](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.3) + make sure you have the right version of [.NET](https://opentabletdriver.net/framework) installed
