### ISSUE TITLE
Tablet stops working when drivers open.

### ISSUE THREAD

**Issue by xriptox** [OpenTabletDriver/OpenTabletDriver#1574]
## Description

The tablet works fine before i open my driver but when i do it stops working. The tablet debug shows the pen moving but it doesnt work anywhere else
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | Newest
| Tablet                   | Gamoan s620

**Comment by Mrcubix** [comment]
Newest isn't a version + Fill the template with a diagnostic file (Help > Export diagnostics)

**Comment by jamesbt365** [comment]
@xriptox please fill out the issue correctly.

**Comment by jamesbt365** [comment]
Closed due to lack of information and no response.
