### ISSUE TITLE
Can't switch between OTD and Wacom driver

### ISSUE THREAD

**Issue by zeroeightam** [OpenTabletDriver/OpenTabletDriver#1582]
I really want to keep the Wacom driver for drawing and notetaking, since OTD is pretty buggy and only works great when I use it for OSU.

**Comment by jamesbt365** [comment]
Why don't you use otd for drawing? If you go I ot the plugin manager download the windows ink plugin and vmultl https://github.com/X9VoiD/VoiDPlugins/releases
Then you can use pressure with otd as wacom drivers misbehave with otd.
