### ISSUE TITLE
windows 11 cursor 30 fps bug

### ISSUE THREAD

**Issue by vetyalmao** [OpenTabletDriver/OpenTabletDriver#1598]
i updated to windows 11, and when i try to play with my tablet, it moves my cursor in 30 fps. not just in osu. to fix this, i need to minimize every single open application.

**Comment by jamesbt365** [comment]
Check in the debugger for report rate, go into tablet > tablet debugger and check the report rate  while moving

**Comment by Mrcubix** [comment]
I mean, there aren't anything to be done on our side.
Windows 11 is already a terrible OS, and i'm pretty sure your windows install is messed up in some way, as most other win 11 OTD users don't have issues.

**Comment by vetyalmao** [comment]
> Check in the debugger for report rate, go into tablet > tablet debugger and check the report rate while moving

when i lift up the pen it showed this. while moving i saw 132-133
![image](https://user-images.githubusercontent.com/85455663/140100594-d864fcbd-4081-41d8-8bee-a743841288e5.png)

**Comment by vetyalmao** [comment]
> I mean, there aren't anything to be done on our side. Windows 11 is already a terrible OS, and i'm pretty sure your windows install is messed up in some way, as most other win 11 OTD users don't have issues.

wtf do you mean "your windows install is messed up in some way" you cant fuck up a windows installation. jesusomega uses windows 11, otd and doesnt have this problem. ive had this problem on windows 10, on another pc, another tablet.

**Comment by jamesbt365** [comment]
Oh please shush about you fucking up a windows install, it is completely possible because we have seen it countless times, stop being arrogant and give us actual fucking proof about your claim before you shout shit at us.

record a fucking video or something before you start throwing false info at us.

**Comment by vetyalmao** [comment]
> Oh please shush about you fucking up a windows install, it is completely possible because we have seen it countless times, stop being arrogant and give us actual fucking proof about your claim before you shout shit at us.
> 
> record a fucking video or something before you start throwing false info at us.

sowwy

**Comment by jamesbt365** [comment]
Seems to be resolved in discord.
https://canary.discord.com/channels/615607687467761684/615611007951306863/905576247315271731

Closing issue now.
