### ISSUE TITLE
Add support for Parblo A640

### ISSUE THREAD

**Issue by BeanButCoffee** [OpenTabletDriver/OpenTabletDriver#1621]
# Tablet Information

| Name            | Parblo A640 |
| --------------- | ----- |
| Manufacturer    | Parblo |
| Product Name    | A640 |
| Width           | 6 inches |
| Height          | 4 inches |
| Pressure Levels | 8192 |
| LPI             | 5080 |

## Diagnostic Information

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7509495/diag.txt)

**Comment by gonX** [comment]
Duplicate of #586
