### ISSUE TITLE
Not working on star03 v2 (Not moving)

### ISSUE THREAD

**Issue by oOStarGodOo** [OpenTabletDriver/OpenTabletDriver#1637]
## Description

![螢幕擷取畫面 2021-11-12 222441](https://user-images.githubusercontent.com/68507221/141482260-4215e982-6b52-48fd-8b30-926b509d606b.png)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |
| OpenTabletDriver Version |
| Tablet                   |

**Comment by jamesbt365** [comment]
You haven't given any actual information, go help > export diagnostics and send that file here as a txt. make sure you don't have any other drivers installed and is this specifially one application or everywhere?

**Comment by jamesbt365** [comment]
Closed to due inactivity and lack of information
