### ISSUE TITLE
Launch when starting computer

### ISSUE THREAD

**Issue by Xboy29** [OpenTabletDriver/OpenTabletDriver#1653]
Add an option to launch OpenTabletDriver when starting computer just like the hawku driver

**Comment by Sublimelime** [comment]
This can already be done, just not through us:

(If you're on windows)

- Right click the OpenTabletDriver.UX.Wpf executable (should be either in appdata (if you used the now-deprecated installer), or just wherever you put the portable install)
- Create shortcut
- Right click shortcut -> Properties -> Run -> Minimized
- Press windows key + R, type `shell:startup` in the run box that appears
- A folder will open, move the shortcut into that folder

**Comment by X9VoiD** [comment]
This cannot be done in a cross-platform way.
