### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by ICHINOYA** [OpenTabletDriver/OpenTabletDriver#1654]
# Support Request
"OTD cannot connect to Internet. Only local plugins will be shown."
![image](https://user-images.githubusercontent.com/80412494/142270338-b0f98b67-f08b-4e43-9a87-c3587e4b2611.png)

## What I've already tried
UAC Enabled
PC Rebooted
Network Adapter Restarted

## Diagnostic Information
[1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7557542/default.txt)

**Comment by jamesbt365** [comment]
attach the diag as a txt please, don't just throw it in.

**Comment by ICHINOYA** [comment]
> attach the diag as a txt please, don't just throw it in.

Yeap

**Comment by jamesbt365** [comment]
Usually caused by a rate limit to github or something to do with your firewall.
