### ISSUE TITLE
Support Request: installed dotnet with spoon (package manager), did not run.

### ISSUE THREAD

**Issue by brickyosu** [OpenTabletDriver/OpenTabletDriver#1655]
# Support Request
i installed dotnet with spoon bc i wanna use my wacom tablet for school except i dont have admin on this school laptop.
i runned opentabletdriver wpf and it still prompts to install dotnet

## What I've already tried
installing with different package manager like chocolatey, did not work either.

## Diagnostic Information
nope, i cannot.

**Comment by jamesbt365** [comment]
This is probably due to you not having admin rights.

https://cdn.discordapp.com/attachments/843628282506379295/910552649798156339/win-x64.7z.001

This build of otd has dotnet embedded within it. Just extract it and go for it

**Comment by brickyosu** [comment]
> This is probably due to you not having admin rights.
> 
> https://cdn.discordapp.com/attachments/843628282506379295/910552649798156339/win-x64.7z.001
> 
> This build of otd has dotnet embedded within it. Just extract it and go for it

ok ill try, ill keep updating

**Comment by brickyosu** [comment]
> This is probably due to you not having admin rights.
> 
> https://cdn.discordapp.com/attachments/843628282506379295/910552649798156339/win-x64.7z.001
> 
> This build of otd has dotnet embedded within it. Just extract it and go for it

Thanks! It worked.

**Comment by jamesbt365** [comment]
Closing as resolved.

**Comment by brickyosu** [comment]
sadly i lost my wacom tablet pen, im trying my best to find it
