### ISSUE TITLE
Add support for Wacom intuos p s

### ISSUE THREAD

**Issue by Nomicals** [OpenTabletDriver/OpenTabletDriver#1659]
# Tablet Information

| Name  Wacom intuos ps    | Value | 100$
| --------------- | ----- |
| Manufacturer    | Wacom
| Product Name    | intuos ps
| Width           |
| Height          |
| Pressure Levels |
| LPI             |

**Comment by jamesbt365** [comment]
Please fill this out.

**Comment by SnowLire** [comment]
There's no need as this is the CTL-480 which is supported.
