### ISSUE TITLE
Relative drag / Hover disabler

### ISSUE THREAD

**Issue by crumpledmint** [OpenTabletDriver/OpenTabletDriver#1663]
## Relative drag mode
Addon for relative mode, so you can move cursor only when dragging
Would be useful in some first person games

**Comment by gonX** [comment]
[Kuuube's Hover Distance Limiter](https://github.com/Kuuuube/Hover_Distance_Limiter) does this for supported tablets (and if you're on a pre-release 0.6 version). What that can't do we can't really do either, its all up to the tablet to report hover states.

**Comment by gonX** [comment]
Also closing as duplicate of #1378
