### ISSUE TITLE
OpenTabletDriver didn't show in programs list in windows

### ISSUE THREAD

**Issue by zooxs** [OpenTabletDriver/OpenTabletDriver#1673]
## Description

Whenever i'm trying to open OpenTabletDriver i'v to installed it instead searching it in windows search features and run it.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | 0.4.1
| Tablet                   | Huion H430P

**Comment by jamesbt365** [comment]
1, your opentabletdriver version is outdated and 2 it isn't in the windows run as opentabletdriver is never installed.

**Comment by Mrcubix** [comment]
0.4.1 and you're trying to use the installer which is deprecated and unsupported, use the portable version instead https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.5.3.3/OpenTabletDriver.win-x64.zip

**Comment by zooxs** [comment]
Thanks @Mrcubix it's worked now. And thanks too @jamesbt365
