### ISSUE TITLE
OTD Console doesn't know the "help" command

### ISSUE THREAD

**Issue by jamesbt365** [OpenTabletDriver/OpenTabletDriver#1674]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Arch Linux
| OpenTabletDriver Version |  181b77b
| Tablet                   | XP-Pen Star G640

Doesn't know the help command yet shows help anyway.

![image](https://user-images.githubusercontent.com/22662856/143770596-0a01b60f-24a5-429d-8372-42648486c8b3.png)

**Comment by InfinityGhost** [comment]
`help` isn't a command, rather its an argument. We could add the command, however it is a little redundant.

**Comment by gonX** [comment]
There seems to be consensus that this isn't worth changing. Closing as `wontfix`.

[Discord convo](https://discord.com/channels/615607687467761684/628651971267788800/927257389982433312)
