### ISSUE TITLE
Add configuration linter

### ISSUE THREAD

**Issue by InfinityGhost** [OpenTabletDriver/OpenTabletDriver#1689]
## Description

A configuration linter would improve the configuration workflow to avoid cases like [this](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/1679#pullrequestreview-822969719) so that all configuration changes would have to clean in order to be merged.

Suggestions are welcome

**Comment by gonX** [comment]
Probably my bad for not searching, this seems like you want to check values for correctness? E.g. Xp-Pen -> XP-Pen and Veikk -> VEIKK?

I made another issue in #2421 that just wants to lint and make sure the formatting is good on json files, so I don't think they're exactly the same.

**Comment by X9VoiD** [comment]
> This seems like you want to check values for correctness? E.g. Xp-Pen -> XP-Pen and Veikk -> VEIKK?

This would be hard to do and maintain once it's up. We already do have some checks tho: if the config can be parsed by OTD, if it refers to an existent parser, and if it's not conflicting with other configs.

Closing in favor of #2421, re-open again if this will be repurposed as an issue to add value-based linting.

**Comment by gonX** [comment]
I believe there was interest in having value-based linting now

Such as having MaxX/MaxY always be floating point, while `jq` will display as integers if the float is 0.

 @InfinityGhost  confirm?

**Comment by gonX** [comment]
With #3027 we are now checking config values, though not strictly int-vs-float. I plan to fix this the coming days so that the entire file is linted and matches output produced by the JSON library we use in dotnet (so that `dotnet test` grabs this).
