### ISSUE TITLE
Support Request: No pen pressure on windows (Huion h640p)

### ISSUE THREAD

**Issue by xkakus** [OpenTabletDriver/OpenTabletDriver#1695]
# Support Request

## What I've already tried

I have tried to install vmulti

**Comment by jamesbt365** [comment]
you require https://github.com/X9VoiD/vmulti-bin/releases/tag/v1.0

and
https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk

once you have both, set the output modes and the pen tip.
You then change whatever application you are using to use the windows ink api
