### ISSUE TITLE
Support Request: Build failing 

### ISSUE THREAD

**Issue by TheAtomicBen** [OpenTabletDriver/OpenTabletDriver#1702]
# Support Request
After cloning the repo and then moving into the folder to build the driver, the build fails with the error: Could not find a part of the path '.../OpenTabletDriver/OpenTabletDriver/Configurations'

My Gaomon PD1161 is still not detected and the cursor is disconnected from the pen

Is there a fix for this?

Here is a screenshot of the traceback
![OpenTabletDriver build fail](https://user-images.githubusercontent.com/6806563/144907329-00c7ad3e-3ac0-4311-92b3-d0bfb8df5ec1.png)

## What I've already tried

I haven't found any references on the build fail, but I did try moving a Configuration file into the folder from the repo, which did not work.

I also tried to see if there was a Wacom driver interfering with anything, which there wasn't.

I'm not really sure what to do next.

OS: Ubuntu 21.10
Tablet: Gaomon PD1161

## Diagnostic Information

[OpenTabletDriverDiagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7662993/OpenTabletDriverDiagnostics.txt)

**Comment by InfinityGhost** [comment]
What build instructions are you following? This looks like you're trying to build the udev rules.

**Comment by Mrcubix** [comment]
the udev project is deprecated as far as i'm aware, tho you should be able to get the latest udevs as of now [here](https://github.com/OpenTabletDriver/OpenTabletDriver/suites/4562453983/artifacts/122607911)

**Comment by InfinityGhost** [comment]
> the udev project is deprecated as far as i'm aware, tho you should be able to get the latest udevs as of now [here](https://github.com/OpenTabletDriver/OpenTabletDriver/suites/4562453983/artifacts/122607911)

The udev project itself isn't, the old repository is. It should instead be run through `./generate-rules.sh` when you clone the repository.

**Comment by TheAtomicBen** [comment]
I was following the instructions at https://osu.ppy.sh/community/forums/topics/1340468?n=1

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/144909051-595d6d13-5592-42e4-88ed-ecb21e350516.png)
first thing i see

**Comment by TheAtomicBen** [comment]
OMG I FEEL LIKE AN IDIOT

**Comment by Mrcubix** [comment]
Also for your tablet, you should be able to make use of the plugin called `OTD.Backport` in stable (package `opentablerdriver`), either get it in the Plugin manager or get a more recent version [here](https://github.com/Mrcubix/OTD.Backport/releases/tag/1.0.2) and drag and drop the downloaded zip file as is in the Plugin manager
