### ISSUE TITLE
GAOMON M10K PRO

### ISSUE THREAD

**Issue by zakaria-chahboun** [OpenTabletDriver/OpenTabletDriver#1707]
Hey! I don't find my TABLET!
And yeah i use the final release!
it's `GAOMON M10K PRO`
i already reported about it #590 

![image](https://user-images.githubusercontent.com/18173275/145063356-7b7ef782-aeb4-4afe-a199-819b7d30371c.png)

**Comment by jamesbt365** [comment]
ALL CAPS doesn't help YOUR TABLET may be SUPPORTED ON PRE RELEALSE, check the BACKPORT PLUGIN in the PLUGIN MANAGER

**Comment by Mrcubix** [comment]
# Allow for detection of tablets that require backporting

- Download OTD.Backport.zip from [here](https://github.com/Mrcubix/OTD.Backport/releases/latest)
- Open OTD release (v0.5.3.3)
- Go to Plugins > Open Plugin Manager
- Drag and drop OTD.Backport.zip into the Plugin Manager window
- Go to Tools > OTD.Backport
- Check the Enable box
- Click Save
- Do Tablets > Detect tablet
