### ISSUE TITLE
Tablet Detected but cursor not moving. MacOS

### ISSUE THREAD

**Issue by nloxosu** [OpenTabletDriver/OpenTabletDriver#1711]
I'm currently on Mac and using your latest driver and the tablet is detected but the cursor doesn't move.

I've tried using a different area, restarting, and re downloaded the driver.

macOS Catalina 10.15

**Comment by jamesbt365** [comment]
What tablet are you using, and could you attach a diagnostic file please. Help > export diagnostic and then save that file and send it here a .txt or zip it.

**Comment by jamesbt365** [comment]
Closed due to no response.
