### ISSUE TITLE
Support Request: GAOMON S620

### ISSUE THREAD

**Issue by csc840219** [OpenTabletDriver/OpenTabletDriver#1712]
# Support Request

 I've follow the steps from the wiki to install the driver on Linux (I'm using elementary os 6.0, kernel 5.11).
But tablet does not work.
## What I've already tried

I tried the "Failed to open device streams" section from FAQ.
At least I tried this from https://osu.ppy.sh/community/forums/topics/1340468?n=1
    git clone https://github.com/InfinityGhost/OpenTabletDriver-udev.git
    cd OpenTabletDriver-udev
    git submodule update --init --remote
./build.sh
    sudo mv ./build/99-opentabletdriver.rules /etc/udev/rules.d/99-opentabletdriver.rules
    sudo udevadm control --reload-rules
After reboot the tablet works, but the app stills saying "Not detected tablet" and "not permissions for open a stream". So I can not configure or test the tablet on the app but it is working.
Any idea?

**Comment by jamesbt365** [comment]
That is outdated

use this
http://opentabletdriver.net/Wiki/FAQ/Linux

**Comment by csc840219** [comment]
I've already tried it, but nothing from there works for me.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jamesbt365** [comment]
`git clone https://github.com/OpenTabletDriver/OpenTabletDriver.git
cd ./OpenTabletDriver
sudo mv ./bin/99-opentabletdriver.rules /etc/udev/rules.d/99-opentabletdriver.rules
sudo udevadm control --reload-rules
cd ..
rm -rf OpenTabletDriver`

literally this script

**Comment by csc840219** [comment]
I've already tried that, but by the time I replace "/etc/udev/rules.d/99-opentabletdriver.rules" and reboot, the tablet stops working.

**Comment by jamesbt365** [comment]
try it again, i made a typo and have edited it.

**Comment by jamesbt365** [comment]
then after help > export diag in otd and send that file here

**Comment by Mrcubix** [comment]
it's all cool and all but i don't see the most fundamental piece of information that's also part of the template: the diagnostic file

**Comment by csc840219** [comment]
Hello. 
At last I tried something different. I've read that this tablet is detected by default and there is no need for any other software.
I tried "https://github.com/bigbigmdm/GAOMON-S620-in-LINUX" and it works ok. Also I could config all buttons.
Thanks for your time and attention.
