### ISSUE TITLE
NRE on any form of input

### ISSUE THREAD

**Issue by X9VoiD** [OpenTabletDriver/OpenTabletDriver#1719]
## Description

Reproduction:
- Do anything with the tablet.

```
[NullReferenceException:Error]	Object reference not set to an instance of an object.
   at OpenTabletDriver.Devices.DeviceReader`1.Main() in (schtuff)/OpenTabletDriver/Devices/DeviceReader.cs:line 106
```

**Comment by gonX** [comment]
Can't reproduce. Commit id and OS?

**Comment by andigandi** [comment]
Is this related to #1703 ? Are you using dotnet 6?

**Comment by X9VoiD** [comment]
> Can't reproduce on [4b9e63f](https://github.com/OpenTabletDriver/OpenTabletDriver/commit/4b9e63f58ba5c1a271daa995acdf51eb2fb623de). What your commit id and OS?

4b9e63f and Arch Linux

> Is this related to #1703 ? Are you using dotnet 6?

Not related, this is from a clean build with zero settings. And OTD.Daemon/UX only builds with .NET 6.

**Comment by X9VoiD** [comment]
It's an issue with the build script not clearing out the ./bin folder.
