### ISSUE TITLE
Add support for HUION Kamvas 20

### ISSUE THREAD

**Issue by jinkhya** [OpenTabletDriver/OpenTabletDriver#1722]
Hello, and thanks in advance :)

# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | HUION
| Product Name    | KAMVAS 20 ( GS1901) 
| Width           | 435mm
| Height          | 239mm
| Pressure Levels | 8192
| LPI             | 5080

## Diagnostic Information
[OpenTabletDriver.Console.deps.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7699325/OpenTabletDriver.Console.deps.txt)

**Comment by Mrcubix** [comment]
Hi, can you go to `Tablets > Device string reader` and enter the following info:

- 9580
- 110
- 200

then click on send request and send us back the output string

**Comment by gonX** [comment]
This is now supported in 0.6.x
