### ISSUE TITLE
OTD DarkMode?

### ISSUE THREAD

**Issue by TrueKevinGamer** [OpenTabletDriver/OpenTabletDriver#1740]
I know honestly this is a stupid suggested, but can you guys add dark mode?

**Comment by jamesbt365** [comment]
We are not going to add dark mode currently as Wpf does not support native theming, this is only a windows limitation. However in the future this may happen.

**Comment by TrueKevinGamer** [comment]
ok.

**Comment by gonX** [comment]
#1245 wontfix for now
