### ISSUE TITLE
It is not clear where to save preset

### ISSUE THREAD

**Issue by AkiSakurai** [OpenTabletDriver/OpenTabletDriver#1742]
When saving preset, it is not clear where to save.
The command "Save settings as" open user home folder by default.
I think it is better to have another command "Save Preset" or make the command "Save settings as" open presets folder by default.

**Comment by vedattt** [comment]
I'll try adding an item "Save preset as" under the File menu that opens the file dialog in the presets directory.
Will also look at adding a console command equivalent.
