### ISSUE TITLE
Change Max Pressure for XP-Pen Deco Mini 4.

### ISSUE THREAD

**Issue by Ivanoks** [OpenTabletDriver/OpenTabletDriver#1744]
## Description

I'm stupid, I already forgot how I wrote the value 2048 then, but the official website says 8192. So... Change please. :)
![image](https://user-images.githubusercontent.com/88715280/146331390-7f912cf1-785b-4933-a414-2be6860f7937.png)

## System Information:

I don't think this is necessary.

**Comment by gonX** [comment]
Can you test manually whether it reports 8191 or 8192 under full pressure? You can use the Tablet Debugger (OTD, Help -> Tablet Debugger) to test this

**Comment by Ivanoks** [comment]
> Can you test manually whether it reports 8191 or 8192 under full pressure? You can use the Tablet Debugger (OTD, Help -> Tablet Debugger) to test this

Oh.. In Tablet Debugger there will be no restriction due to config? And at the moment, my friend who has this tablet is at school right now. Xd

**Comment by Mrcubix** [comment]
If the tablet report 2047 pressure then 2047 it is, just gotra check in the debugger as manufacturers often lie about specs

**Comment by Ivanoks** [comment]
> If the tablet report 2047 pressure then 2047 it is. Just gotta check in the debugger as manufacturers often lie about specs

Okay, got it. Then I'll wait for my friend.

**Comment by Ivanoks** [comment]
> If the tablet report 2047 pressure then 2047 it is. Just gotta check in the debugger as manufacturers often lie about specs

![image](https://user-images.githubusercontent.com/88715280/146357439-fc89c54e-d378-480c-ba49-2e3161d0b492.png)

Okay, I ended up screwing up. That's 8191.

**Comment by jamesbt365** [comment]
fixed in #1746
