### ISSUE TITLE
`Detect tablet` doesn't destroy previous pipelines

### ISSUE THREAD

**Issue by AbstractQbit** [OpenTabletDriver/OpenTabletDriver#1745]
## Description
All the pipelines end up working simultaneously:

https://user-images.githubusercontent.com/38468635/146342182-65c7c94f-a9cc-4722-9da7-adf0bcec293d.mp4

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Bimbows 10
| OpenTabletDriver Version | ecc3218c49b5ca5796c434b994f730cd81d238e7

**Comment by gonX** [comment]
Can reproduce on Linux
