### ISSUE TITLE
32 Bit Version

### ISSUE THREAD

**Issue by NexushasTaken** [OpenTabletDriver/OpenTabletDriver#1749]
## Description

Make a 32 Bit Win7 Pls..

**Comment by jamesbt365** [comment]
We do have 32 bit support, but you have to build it yourself.

**Comment by X9VoiD** [comment]
Sorry but no official support will be given, and future versions will most likely break if not already broken.

**Comment by jamesbt365** [comment]
In case you just refuse to update your os to 64 bit, here:

https://canary.discord.com/channels/615607687467761684/724106667964366968/886949171196731463

**Comment by gonX** [comment]
#908 #907 etc
