### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by Sulikit** [OpenTabletDriver/OpenTabletDriver#1761]
https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.5.3.3/OpenTabletDriver.deb
I downloaded this file by accident, when i when to delete the file a pop up from windows defender appeared and stated that the file was a trojan.
Screenshot below
![Capture](https://user-images.githubusercontent.com/96341267/146646644-164d58e2-2414-4a77-9a85-c493e55c0053.PNG)

**Comment by jamesbt365** [comment]
This is a linux binary, it is not designed for windows and there is nothing we can do to stop it from being flagged. It is not a virus.
