### ISSUE TITLE
Error: RemoteMethodNotFound

### ISSUE THREAD

**Issue by hXtreme** [OpenTabletDriver/OpenTabletDriver#1764]
## Description
I recently tried to switch from xwacom drivers to OpenTabletDriver.
After removing xwacom driver and installing OpenTabletDriver and adding systemd units my tablet is no longer recognized and there's no response when I move the stylus or click the buttons. Furthermore when I open the OpenTabletDriver GUI I receive the following error message:

![Screenshot from 2021-12-18 19-57-50](https://user-images.githubusercontent.com/22425371/146659983-90b0d625-3885-4122-a79d-f928a9b1ed5b.png)

The tablet is still recognized to the point where it shows up on `lsusb`

```
$ lsusb
...
Bus 003 Device 007: ID 256c:006d HUION Huion Tablet_HS64
...
```

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |  Arch Linux (5.15.10-arch1-1) |
| OpenTabletDriver Version | v0.5.3.1-r971.gedcee3d2 |
| Tablet                   | HUION Huion Tablet_HS64 |

**Comment by Mrcubix** [comment]
i would advice against using `opentabletdriver-git` (master) right now as it has many issue, you should be able to get OTD from AUR with `opentabletdriver`

**Comment by hXtreme** [comment]
Switching to stable seems to have fixed it.

**Comment by X9VoiD** [comment]
This error happens when you're running an old daemon and a new ux.
