### ISSUE TITLE
Auxiliary Buttons on Huion HS64 do not work

### ISSUE THREAD

**Issue by Dastin26** [OpenTabletDriver/OpenTabletDriver#1765]
## Description

None of the 8 auxiliary buttons bindings correspond to any of the 4 buttons on the tablet, but the pen buttons do work.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10 21H1
| OpenTabletDriver Version | 0.5.3.3
| Tablet                   | Huion HS64

**Comment by gonX** [comment]
This looks like it's fixed in 0.6.x. Please update to the latest version.
