### ISSUE TITLE
Установил драйвера, а они не работают

### ISSUE THREAD

**Issue by GeromIy** [OpenTabletDriver/OpenTabletDriver#1773]
## Description

Драйвера видят планшет, но сам планшет, видимо, не видит драйвер. При изменении любых настроек никакой реакции. Настраиваю область, а планшет работает в заводском режиме (полная область). Как это пофиксить?
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | 5.3.3
| Tablet                   | Wacom CTL 471

**Comment by Mrcubix** [comment]
деинсталляция wacom

если не установлен
установить, затем удалить

**Comment by GeromIy** [comment]
> деинсталляция wacom
> 
> если не установлен установить, затем удалить

Удалил заранее, перед установкой. Комп ребутал

**Comment by Mrcubix** [comment]
экспорт диагностического файла

**Comment by GeromIy** [comment]
> экспорт диагностического файла

?

**Comment by Mrcubix** [comment]
`Help > Export diagnostics`

**Comment by GeromIy** [comment]
> `Help > Export diagnostics`

А куда это писать?

**Comment by GeromIy** [comment]
> `Help > Export diagnostics`
> 
> ![export_diagnostic](https://user-images.githubusercontent.com/39861216/146711117-b876de50-edea-4b86-8a7e-6f085ea296cc.gif)

Мне текст из файла скинуть?

**Comment by Mrcubix** [comment]
везде

добавить .txt

загрузите файл сюда

**Comment by GeromIy** [comment]
[11111.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7742532/11111.txt)

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/146711327-81f054a0-f902-4a7b-a55b-593abad1f697.png)

как вы удалили wacom

**Comment by GeromIy** [comment]
> ![image](https://user-images.githubusercontent.com/39861216/146711327-81f054a0-f902-4a7b-a55b-593abad1f697.png)
> 
> как вы удалили wacom

Через программы и компоненты. Потом открылся сам драйвер, спросил "Вы хотите удалить драйвера wacom?", я нажал "да", удалил и ребутнул пк

**Comment by Ivanoks** [comment]
Привет, давай я тебе попытаюсь помочь, скинь Дискорд, я через время тебе напишу. (Я поделаю банальную херню, мб поможет.)

**Comment by Ivanoks** [comment]
Привет, давай я тебе попытаюсь помочь, скинь Дискорд, я через время тебе напишу. (Я поделаю банальную херню, мб поможет.)

**Comment by GeromIy** [comment]
> Привет, давай я тебе попытаюсь помочь, скинь Дискорд, я через время тебе напишу. (Я поделаю банальную херню, мб поможет.)
Geromi#0539

**Comment by jamesbt365** [comment]
Going to assume this was resolved due to the last comment being 26 days ago and mentions of going to discord.
