### ISSUE TITLE
Support Request: plugins not working after Upgrading popOS 

### ISSUE THREAD

**Issue by JonaLK** [OpenTabletDriver/OpenTabletDriver#1782]
# Support Request
Opentabletdriver used to work very well on my popOS System (Used to be Ubuntu 21.04), after upgrading to 21.10, plugins stopped working with the error message  
## What I've already tried
*reinstalling OpenTabletDriver
*reinstalling netframwork
*updating everything
*opening a bug report for the plugin 
https://github.com/AbstractQbit/AbstractOTDPlugins/issues/2
Which was stupid because other plugins are also affected. 

## Diagnostic Information
[Settings:Info]	Driver is auto-enabled.
[Plugin:Debug]	No constructor found for 'TabletDriverFilters.Devocub.Antichatter'
[Settings:Info]	Interpolator: TabletDriverFilters.Hawku.Smoothing
[DllNotFoundException:Error]	Unable to load shared library 'librt' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibrt: cannot open shared object file: No such file or directory

**Comment by InfinityGhost** [comment]
This is a known issue, it's a unmarked dependency in our package. From a quick search with `apt-file` I was able to find a potential dependency, `libc6-dev` which should provide what's needed for interpolators.

**Comment by JonaLK** [comment]
Thanks for the quick response! 
Unfortunately a apt-get install shows 
libc6-dev is already the newest version (2.34-0ubuntu3).
Which means it is installed already :(

**Comment by InfinityGhost** [comment]
What's the output of `stat /usr/lib/librt.so*`? If it fails it may also be at `/lib/librt.so*`

**Comment by JonaLK** [comment]
both result in the same:
stat: cannot statx '/usr/lib/librt.so*?': No such file or directory
and
bash: /lib/librt.so*: No such file or directory

**Comment by InfinityGhost** [comment]
The only other thing that provides it is `libc6`, assuming that the v0.5.3.3 release doesn't rely on the headers. `LD_LIBRARY_PATH` might need updated to include `/usr/lib/x86_64-linux-gnu/` so that it can find that static library, but it really should not be required if the installation is correct.

**Comment by JonaLK** [comment]
It is actually driving me nuts, sorry to bother on Christmas eve, but export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/
still did not fix it.
libc6 is on the newest version, uninstalling is (obviously) not possible since it would break the OS :/
It's not even an Opentabletdriver problem but rather from my OS...
Thank's for the help though :)

**Comment by X9VoiD** [comment]
This is already fixed by #1592.

**Comment by JonaLK** [comment]
How do I apply it though? :(

**Comment by jamesbt365** [comment]
You download any build from this forward or patch it in yourself.
