### ISSUE TITLE
No tablet detected 

### ISSUE THREAD

**Issue by Chiefiene** [OpenTabletDriver/OpenTabletDriver#1792]
## Description

My tablet is not found. I already tried evrything that is written here. I have a wacom CTL-472
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System windows 10         |
| OpenTabletDriver Version |v0.5.3.3
| Tablet      wacom CTL-472             |

**Comment by SnowLire** [comment]
Can you provide a diagnostic file with a .txt extension?

**Comment by jamesbt365** [comment]
Closed because lack of information and activity
