### ISSUE TITLE
Tablet not detecting

### ISSUE THREAD

**Issue by ChickenHumanPerson** [OpenTabletDriver/OpenTabletDriver#1794]
I have a Huion 420 and it is not detecting the tablet. I am not sure if it is the version I am using or not. I am using version 0.5.3.3 and something I did notice was this, (see image)
![image](https://user-images.githubusercontent.com/53623885/147376680-4ddc5407-c1b3-47e5-8588-8f773cd00aca.png)
Please help me with this issue, I am completly lost.

**Comment by ChickenHumanPerson** [comment]
I have figured out the issue. I listed the wrong tablet and realized that the tablet I have is actually the Huion H420. So, I must now wait until it is fixed.

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/147377265-e1b85cd2-8c34-4357-bf21-3aa83cb8d971.png)
- Pre-Release: https://cdn.discordapp.com/attachments/615939905566015493/922902857060081684/OpenTabletDriver.win-x64.zip
- Zadig : https://github.com/pbatard/libwdi/releases/download/b755/zadig-2.6.exe

- Create a new folder called `Configurations` and extract the content of this zip file inside
