### ISSUE TITLE
Tablet not detected

### ISSUE THREAD

**Issue by frostishyper** [OpenTabletDriver/OpenTabletDriver#1797]
I Bought a new Veikk S640 yesterday its my first time using a tablet, I plug in my tablet and install OTB and the required framework for win 10 but when i open OTB it says no tablet detected

[frostishyper - diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7775567/frostishyper.-.diagnostics.txt)

**Comment by jamesbt365** [comment]
Install this:
https://download.visualstudio.microsoft.com/download/pr/1daf85dc-291b-4bb8-812e-a0df5cdb6701/85455a4a851347de26e2901e043b81e1/windowsdesktop-runtime-5.0.12-win-x64.exe

**Comment by jamesbt365** [comment]
Then follow:
https://mrcubix.github.io/OTD.Backport-Wiki/installation.html

**Comment by frostishyper** [comment]
> Then follow:
> https://mrcubix.github.io/OTD.Backport-Wiki/installation.html

Thanks It works now
