### ISSUE TITLE
No Tablet Detected - Linux (AUR) Artist 12

### ISSUE THREAD

**Issue by DonArt-Q** [OpenTabletDriver/OpenTabletDriver#1800]
I have an Artist 12 that I want to use with OpenTabletDriver (since the official XP-Pen drivers aren't giving me much luck) however, when I open up OTD, I get the message 'connecting to OpenTabletDriver daemon' and 'No Tablet Detected'. Trying to detect a tablet with Ctrl+D only causes it to crash, and so does trying to export diagnostics.

**Comment by jamesbt365** [comment]
Export diagnostic to a location otd actually has access to, like the desktop, home, documents, stuff like that.

**Comment by DonArt-Q** [comment]
The issue with that is that pressing the Export Diagnostics button crashes before I am able to choose where to export the diagnostic file to.

**Comment by gonX** [comment]
Try updating OpenTabletDriver to the 0.6.0.2 release and seeing if that works for you

**Comment by DonArt-Q** [comment]
It still doesn't work, but I get an error message when trying to detect the tablet. Out of curiosity, does OTD need systemd on linux, since I'm using s6.
![image](https://user-images.githubusercontent.com/68467371/151707715-e6590759-7164-4fba-9796-34d5b8c5e8d6.png)

**Comment by jamesbt365** [comment]
You need to start the daemon and no, otd doesn't need systemd.

**Comment by DonArt-Q** [comment]
How do I start the daemon?

**Comment by DonArt-Q** [comment]
nevermind, running otd in the terminal worked

**Comment by jamesbt365** [comment]
if you used a package manager `otd` will just work, otherwise you will need to specify the path.

**Comment by DonArt-Q** [comment]
my tablet still isn't detected though.

**Comment by jamesbt365** [comment]
Now export a diagnostic, you are probably missing udev.

**Comment by DonArt-Q** [comment]
Here's the diagnostic info:
[diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7966343/diagnostic.txt)

**Comment by DonArt-Q** [comment]
*sigh*

The issue was that I was supposed to connect the tablet after the daemon was started... Thanks for helping me with this though.
