### ISSUE TITLE
Support Request: cant use multiple tablets?

### ISSUE THREAD

**Issue by taquitosispog** [OpenTabletDriver/OpenTabletDriver#1807]
# Support Request
 ive got 2 tablets, both wacom tablet, (one by wacom) (wacom cintiq 16) and im wondering if its possible to use both with the same driver, since it doesnt seem to work when locating a tablet.

im using the ''one by wacom'' tablet for osu and the other one for drawing. 2 different tablet drivers glitch out osu, but when im using one tablet driver i cant locate another tablet when the other one is plugged out. help pls

**Comment by jamesbt365** [comment]
You can only use 1 driver at once and multi tablet support is in master/prerelease currently, soon this feature will be in the full stable release.
