### ISSUE TITLE
Add support for Deco Fun XS

### ISSUE THREAD

**Issue by pikokr** [OpenTabletDriver/OpenTabletDriver#1810]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer | XP-Pen |
| Product Name | Deco Fun XS |
| Width   | 4.8 inch |
| Height  | 3 inch |
| Pressure Levels | 8192 |
| LPI | 5080 |

**Comment by jamesbt365** [comment]
help > export diagnostic, save that file as a txt and send it here.

**Comment by jamesbt365** [comment]
Turns out this is already supported in #1173

for support in release go to https://mrcubix.github.io/OTD.Backport-Wiki/installation.html
