### ISSUE TITLE
daemon crash on launch due to updater?

### ISSUE THREAD

**Issue by OniCado** [OpenTabletDriver/OpenTabletDriver#1811]
## Description

daemon exits immediately after launching
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Win 10 Pro N 21H2 Build 19044.1415
| OpenTabletDriver Version |  d758023
| Tablet                   | ---

**Comment by OniCado** [comment]
[daemon.log](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7780832/daemon.log)

**Comment by jamesbt365** [comment]
Can repoduce on a windows virtual machine on d758023

**Comment by jamesbt365** [comment]
Is this an issue with macos or just windows?

**Comment by Manson-22** [comment]
im on an older version most likely and it works fine. just installed on a new computer and having same issue.

**Comment by gonX** [comment]
The stacktrace is in `WindowsUpdater.cs` so I'm assuming this is Windows-only for now.

**Comment by vedattt** [comment]
Inner stack trace
![image](https://user-images.githubusercontent.com/12011884/147554540-0a3544d6-0bad-460e-967e-16bd61a191c8.png)

**Comment by jamesbt365** [comment]
Is this a problem specifically always with the latest master trying to do something?

**Comment by vedattt** [comment]
> Is this a problem specifically always with the latest master trying to do something?

Yes, it is, and on both MacOS and Windows most likely. Will push a PR to fix it in a few moments though.
