### ISSUE TITLE
CTH-460 pen doesn't work

### ISSUE THREAD

**Issue by SuperKKPL** [OpenTabletDriver/OpenTabletDriver#1824]
I connected the tablet to the computer and the tablet stylus does not work, only the touch function.
When I try to bind the buttons on the tablet don't change.

**Comment by jamesbt365** [comment]
can you go to help > export diagnostics, save that file as a txt and send it here please?

**Comment by SuperKKPL** [comment]
[123.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7788957/123.txt)

**Comment by jamesbt365** [comment]
You have wacom drivers installed, you need to uninstall them through apps and features, if they are not there they were uninstall incorrectly and therefore you need to install them then uninstall through apps and features.

(also oem kill doesn't really do anything anymore)

**Comment by SuperKKPL** [comment]
ok, I'll try

**Comment by SuperKKPL** [comment]
I tried uninstalling every driver and still noting.
But I tried connecting the CTH-480 and it works, but I really want to play on CTH-460.
Can I do something else to the drivers?

**Comment by jamesbt365** [comment]
Restart otd and export another diag.

**Comment by SuperKKPL** [comment]
[4562.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7789174/4562.txt)

**Comment by jamesbt365** [comment]
close otd, does your tablet work?

**Comment by SuperKKPL** [comment]
When i close OTD my tablet does not work, only touch function work.

**Comment by SuperKKPL** [comment]
I also tried connecting tablet to the other PC which never before had tablet drivers and it's the same.

**Comment by jamesbt365** [comment]
Try this: https://mrcubix.github.io/OTD.Backport-Wiki/installation.html

**Comment by SuperKKPL** [comment]
It does not work too.

**Comment by jamesbt365** [comment]
remove the backport plugin then replace the config with this:
[AAAAAAAA.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7790529/AAAAAAAA.zip)

**Comment by SuperKKPL** [comment]
It does work! Thanks mate!
