### ISSUE TITLE
Support Request: Sorry to be annoying, but XP-Pen Deco fun S isn't being detected

### ISSUE THREAD

**Issue by Zerimm** [OpenTabletDriver/OpenTabletDriver#1828]
I recently changed tablet from XP-Pen g640 to this one, and it just isn't being detected.
I've tried reinstalling both the driver and .NET but it still isn't.

Here is diagnostic data
[Diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7790011/Diagnostic.txt)

**Comment by Sublimelime** [comment]
Did OTD generate the diagnostic like that, or did you strip the json formatting from the file? It's okay to upload it as txt, but the json formatting (all the brackets, the quotation marks, the indentation, etc) makes it easier to read.

**Comment by jamesbt365** [comment]
upload another diag, this time do not remove the json formatting, just rename it to a txt.

**Comment by Zerimm** [comment]
here
[Diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7790056/Diagnostic.txt)

**Comment by jamesbt365** [comment]
you will need to do this:
https://mrcubix.github.io/OTD.Backport-Wiki/installation.html

**Comment by Zerimm** [comment]
Sorry, but that still doesn't work

**Comment by Mrcubix** [comment]
export another diag

**Comment by Mrcubix** [comment]
nvm, this is a new variation, extract the content of this zip file in `Configurations/XP-Pen`, replacing the old config

[CT430.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7790095/CT430.zip)

**Comment by Zerimm** [comment]
Do I need to do anything else? Sorry but it still doesn't work

**Comment by Mrcubix** [comment]
export a diag and upload it here

**Comment by Zerimm** [comment]
[Diagnosjhos.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7790113/Diagnosjhos.txt)

**Comment by Mrcubix** [comment]
well i can definitely tell you that the new config hasn't been loaded, either try restarting or re-extract the config properly

**Comment by Mrcubix** [comment]
[CT640.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7790136/CT640.zip)
nvm, XP-Pen naming scheme suck ass, Should be S, M & L, not XS, S & L

**Comment by Zerimm** [comment]
It works now, thank you
