### ISSUE TITLE
Huion H420X Not Detected

### ISSUE THREAD

**Issue by OblivionGhoul** [OpenTabletDriver/OpenTabletDriver#1831]
## Description
I have a Huion Inspiroy H420X and it is not being detected. I already tried making a custom config in #1264, but it is still not detecting my tablet. 

## System Information:
| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10 Pro
| OpenTabletDriver Version | v0.5.3.3
| Tablet                   | Huion Inspiroy H420X

**Comment by jamesbt365** [comment]
help > export diagnostic, save that file as a txt and send it here

**Comment by OblivionGhoul** [comment]
[text.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7794612/text.txt)

**Comment by Mrcubix** [comment]
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0

**Comment by OblivionGhoul** [comment]
I just tried running that script. I know that it worked because when I ran the script again, it said "No Gaomon/Huion driver detected." But it is still not detecting my tablet. Maybe because my config file is incorrect, but I got it from #1264?

The Logs: [logs.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7794671/logs.txt)

**Comment by Mrcubix** [comment]
uninstall razer synapse if installed then right click on start menu > Device manager >View > Device by container > look for Gaomon Tablet there > open it's container (arrow on the left) > screenshot

**Comment by OblivionGhoul** [comment]
![Capture](https://user-images.githubusercontent.com/45471929/147790636-7c151886-ebf0-4840-af15-6e3f8519a13f.PNG)

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/147791000-3f8d703d-91f1-45aa-8335-b73cb0fb2bb8.png)

right click on this one > Update > Second option > Let me pick from a list > pick `HID compliant device`

**Comment by OblivionGhoul** [comment]
![image](https://user-images.githubusercontent.com/45471929/147792661-5b482088-9e2a-4ae8-92ad-9d7a20ae1014.png)
It was `USB Input Device`, so I installed the drivers and it looks like this now.

**Comment by Mrcubix** [comment]
alright now https://mrcubix.github.io/OTD.Backport-Wiki/installation.html

**Comment by OblivionGhoul** [comment]
Yes, it can now detect my tablet. Thank you!
