### ISSUE TITLE
Add support for Veikk S640 V2

### ISSUE THREAD

**Issue by Ere1n** [OpenTabletDriver/OpenTabletDriver#1835]
| Name            | Value |
| --------------- | ----- |
| Manufacturer    |Veikk
| Product Name    |Veikk S640 V2
| Width           |152.4
| Height          |101.6
| Pressure Levels |8192
| LPI             |5080

**Comment by jamesbt365** [comment]
resolved in #1186

**Comment by Mrcubix** [comment]
also in [OTD.Backport](https://mrcubix.github.io/OTD.Backport-Wiki/installation.html)
