### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by sampaii5** [OpenTabletDriver/OpenTabletDriver#1842]
:recently got a new tablet (wacom ctl 4100) and got the OpenTabletDriver. i noticed that in game my cursor would 'spike' (idk how to explain it but i first noticed when i had a long slider and it suddenly jumped??) sorry for the rough explanation, but any help would be greatly appreciated!

**Comment by jamesbt365** [comment]
Providing that no other drivers are installed this is just how the 4100 acts because of the hover smoothing, there is nothing we can do about it.
