### ISSUE TITLE
Switching Presets (Profile) using a new type of binding

### ISSUE THREAD

**Issue by Mrcubix** [OpenTabletDriver/OpenTabletDriver#1862]
## Description

- A new type of Binding should be implemented:
    - A new Type of Binding: Preset
    - A List of existing Presets should be available as properties

# Potential Problems:

- Property list might not be updated on change at the moment (require testing)

**Comment by X9VoiD** [comment]
Preset switching do not need a new type of binding if it's going to be the only binding dealing with presets. `IStateBinding` is enough for such purposes.

You most likely meant "Allow plugins to change current active preset" for the daemon side, and "Allow plugins to declare Preset property" for the UX side.

**Comment by InfinityGhost** [comment]
This has been merged with the DI rewrite.
