### ISSUE TITLE
wacom having a weird issue with setting a  dispalay 

### ISSUE THREAD

**Issue by JamBlueberry** [OpenTabletDriver/OpenTabletDriver#1863]
## Description
When seting  a display to use it freaks out like its fighting something else   .
and cause to mouse cursors to be on one or both monitors 

## System Information:
[hardinfo_report.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7805346/hardinfo_report.txt)

| OpenTabletDriver Version : 0.5.3.3 |
| Tablet  Wacom CTL-472  |

**Comment by JamBlueberry** [comment]
Fixed it by Blacklisting the defalut wacom driver shiped with mint

**Comment by JamBlueberry** [comment]
Main issue Fixed but Krita wont pick up pen presser ?

**Comment by jamesbt365** [comment]
Switch to artist and change the tip binding
