### ISSUE TITLE
Gaomon S620 not connecting

### ISSUE THREAD

**Issue by deadcupcake2112** [OpenTabletDriver/OpenTabletDriver#1864]
## Description

Hi, I need some help. I play osu! and i had a friend recommend this driver for me to use, it worked for a little bit but then all of a sudden my tablet (Gaomon S620) wouldn't connect to it. no matter how many times i unplugged it or restarted my pc. i have winusb and have tried literally everything
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |
| OpenTabletDriver Version |
| Tablet                   |

**Comment by jamesbt365** [comment]
https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0
If not check the cable, if still not you deleted the config folder. Also fill out the template
