### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Pettertv** [OpenTabletDriver/OpenTabletDriver#1873]
# Support Request
 install driver
I install all of them, the .NET 5 and the driver, but, when i execute the program, say this, 
![image](https://user-images.githubusercontent.com/95721529/148312286-3acbcda4-7cb3-47bf-9d1b-0f8df376ed5a.png)

i click on yes for more security and download that .NET, and again says the same throuble

**Comment by Pettertv** [comment]
sorry for my ingles.

**Comment by Mrcubix** [comment]
https://download.visualstudio.microsoft.com/download/pr/1daf85dc-291b-4bb8-812e-a0df5cdb6701/85455a4a851347de26e2901e043b81e1/windowsdesktop-runtime-5.0.12-win-x64.exe
