### ISSUE TITLE
i cant run the driver

### ISSUE THREAD

**Issue by syrex8428** [OpenTabletDriver/OpenTabletDriver#1888]
## Description

as i start the driver, it shows connecting to deamon~~~ and just disappear by itself
i guesse this is becoz of the desktop issue but cant find what is the exact problem ;ㅁ;
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System     win10   |
| OpenTabletDriver Version |
| Tablet            ctl-472       |

**Comment by Mrcubix** [comment]
it's says connecting to the daemon because how is it supposed to start the daemon if it's not in the same folder
