### ISSUE TITLE
open tablet driver

### ISSUE THREAD

**Issue by S3npai23** [OpenTabletDriver/OpenTabletDriver#1893]
## Description

cannot detect my tablet
## System Information:

| Name   S3npai23          | Value |
| ---------------- | ----- |
| Operating System  64-bit operating system       |
| OpenTabletDriver Version v0.5.3.3|
| Tablet   veikk s640                |

**Comment by SnowLire** [comment]
Follow this guide: https://mrcubix.github.io/OTD.Backport-Wiki/installation.html
Fill out the template correctly next time.
