### ISSUE TITLE
Plugin manager cannot find 0.6.0.0 plugins

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1898]
## Description

Reproduction steps:
1. Open the pre-release
2. Go to the plugin manager
3. Target a fork/branch that has 0.6.0.0 plugins (File > Use alternate source...)

Example fork to target:
`Kuuuube`
`Plugin-Repository`
`0.6.0.0-update`

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Win10
| OpenTabletDriver Version | 0.6.0rc4

**Comment by InfinityGhost** [comment]
This appears to be a cache issue, clearing the cache directory resolves it.
