### ISSUE TITLE
Add option to check for updates manually or change notification form

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1923]
## Description

Users with notifications disabled on windows will not get the notification used to trigger the updater. 

Either adding an option to check manually or integrating the update available message into an OTD dialog would fix this.

**Comment by InfinityGhost** [comment]
Is there any sort of way to check if notifications are enabled? This would save a lot of time and we could instead show a dialog rather than a notification if it can't.

**Comment by Kuuuube** [comment]
Not sure if this is helpful for our case but: https://devblogs.microsoft.com/oldnewthing/20200810-00/?p=104058
