### ISSUE TITLE
Force aspect ratio

### ISSUE THREAD

**Issue by Antside** [OpenTabletDriver/OpenTabletDriver#1930]
Could we get a button like in the Hawku's drivers that automatically changes your tablet area's height so that it fits your screen's aspect ratio according to the width? It would be useful. Have a nice day!

**Comment by X9VoiD** [comment]
OTD already has "lock aspect ratio".

**Comment by Antside** [comment]
For real? Where? I've never found it


Le jeu. 13 janv. 2022, à 09 h 36, X9VoiD ***@***.***> a
écrit :

**Comment by X9VoiD** [comment]
Right click Tablet Area -> Lock aspect ratio

![image](https://user-images.githubusercontent.com/10338031/149357287-089aab7d-a311-4da4-b053-e8a0bf585b65.png)

**Comment by Antside** [comment]
omg I never knew this, thanks a lot!
