### ISSUE TITLE
Update notification crashes Windows 11 explorer.exe

### ISSUE THREAD

**Issue by X9VoiD** [OpenTabletDriver/OpenTabletDriver#1934]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 11
| OpenTabletDriver Version | 0.6.x
| Tablet                   |

**Comment by InfinityGhost** [comment]
I guess we can just move to a popup window rather than a notification? We've had nothing but issues with notifications it seems.
