### ISSUE TITLE
It is impossible to disable lock aspect ratio in 0.6.0.x

### ISSUE THREAD

**Issue by Doksha** [OpenTabletDriver/OpenTabletDriver#1957]
## Description

Even when the application shows lock aspect ratio as disabled, the width and height are still linked making it impossible for the user to change the aspect ratio of the output.
(also for some reason the new release, 0.6.0.1 still shows as 0.6.0.0 in the application name and will notify you that there is a new version)
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | 0.6.0.x ???
| Tablet                   | Veikk A15

**Comment by InfinityGhost** [comment]
The version bug is known and is fixed for v0.6.0.2.

**Comment by Doksha** [comment]
Should I create a different issue for the aspect ratio thing or just keep it here?

**Comment by InfinityGhost** [comment]
Changing the title and editing the original issue report is enough.

**Comment by gonX** [comment]
This is now the issue on aspect ratio, since we need to track that anyway. v0.6.0.2 has just been released.

**Comment by gonX** [comment]
As a current workaround after disabling aspect ratio lock, you need to make sure to save your configuration and restart the GUI portion of the driver.

**Comment by jamesbt365** [comment]
fixed in #2352
