### ISSUE TITLE
Support Request: OpenTabletDriver does not work correctly.

### ISSUE THREAD

**Issue by Ltrinch** [OpenTabletDriver/OpenTabletDriver#1966]
# Support Request
On the 1st run of OpenTabletDriver I got [this error.](https://imgur.com/RaByTKQ) After that, the error went away, but OpenTabletDriver did not work correctly.
[Video with all the errors.](https://streamable.com/ty2ou5)
## What I've already tried
Tried to install libx11-dev, dotnet-sdk-6.0 libs, tried to reinstall OpenTabletDriver, but it didn't help...
I did everything from [this guide](https://opentabletdriver.net/Wiki/Install/Linux)(Ubuntu/Debian), but something went wrong...

## Diagnostic Information
I can't attach the Diagnostics because the program gives an error. (see video)

Name | Value
-- | --
Operating System | Linux Mint 20.3
OpenTabletDriver Version | 0.6.0.0
Tablet | XP-Pen G640 Rev.2

**Comment by gonX** [comment]
Please check that `libxrandr-dev` is installed

**Comment by Ltrinch** [comment]
Installed it, now everything works. Thank you!

**Comment by gonX** [comment]
This is a known packaging issue and is fixed for 0.6.0.2. Sorry for the inconvenience.
