### ISSUE TITLE
OpenTabletDriver doesn't launch after installing a plugin

### ISSUE THREAD

**Issue by apollo-dw** [OpenTabletDriver/OpenTabletDriver#1978]
## Description
I installed the Windows Ink plugin, configured and realized it wasn't working. I restarted the program and now it won't launch, regardless of whether I reinstall/install it, or whether I restart my computer.

https://streamable.com/440as2

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | v0.6.0.2
| Tablet                   |

**Comment by jamesbt365** [comment]
The plugin api changed slightly and windows ink hasn't been updated for it yet. Please revert back to v0.6.0.2 or don't use the plugin.
