### ISSUE TITLE
Won't startup without an internet connection.

### ISSUE THREAD

**Issue by grogcito** [OpenTabletDriver/OpenTabletDriver#1985]
## Description
Seems like it just closes itself without a valid internet connection. First time I've ever heard of an online-only driver.
Otherwise it has no problems when it's already started.
Unplug your internet cable to recreate the issue.

## System Information:
| Windows 10 pro 21H1)|
| v0.6.0.2 |
| Wacom CTL-4100 |

**Comment by InfinityGhost** [comment]
Can you provide your `daemon.log`? (Found at `%LOCALAPPDATA%\OpenTabletDriver\daemon.log`)

**Comment by grogcito** [comment]
I don't seem to have that file anywhere

**Comment by jamesbt365** [comment]
You probably had the old daemon running as this was patched in 0.6.0.1
