### ISSUE TITLE
Ignore input outside area does not function

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#1988]
## Description

Ignore input outside area clamps input or sends it to the bottom right of the monitor area instead of ignoring it.

This does not appear to have any workaround like #1957. They are broken no matter what is done.

Reproduction steps
1. Right click the area editor
2. Enable Ignore input outside area
3. Move your pen outside your tablet area and see that it still moves the cursor
4. Optionally you can set your area to something ridiculously small like 1mm x 1mm or drag the area beyond the bounds of the tablet for easier testing.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Win10
| OpenTabletDriver Version | 0.6.0.2

**Comment by gonX** [comment]
Probably not directly related to the issue, but to lock aspect ratio the user has to save the config and restart OTD entirely. Does that workaround work here?

**Comment by jamesbt365** [comment]
From what i saw in discord and what i tested myself this functionality just gets stuck and cannot be changed.

**Comment by Kuuuube** [comment]
From further testing it seems that only Ignore input outside area is affected. Instead of stopping input when outside the tablet area it appears to clamp or send the cursor to the bottom right instead of ignore.

I have appended the issue with this information and updated the reproduction steps to be more obvious.

**Comment by InfinityGhost** [comment]
Moving to v0.6.1 due to merging of #2035
