### ISSUE TITLE
Saying I'm missing frameworks .NET.

### ISSUE THREAD

**Issue by ScarletMoonz** [OpenTabletDriver/OpenTabletDriver#1996]
## Description
When I open up OpenTabletDriver it shows the updater. I click start, the program tells me that I am missing frameworks .NET. even though I have already download it. I have tried reinstalling .NET. again and trying again but It gives me the same issue

## System Information:

| Windows 10 21h2 |
| v0.6.0.2 |
| One By Wacom (that is the actual name of the tablet) |

**Comment by jamesbt365** [comment]
https://opentabletdriver.net/framework

also model number not the weird name given by wacom because there is multiple one by wacoms.
