### ISSUE TITLE
Add IGestureBinding

### ISSUE THREAD

**Issue by InfinityGhost** [OpenTabletDriver/OpenTabletDriver#200]
## Description

This would provide a method to gesture using pen movement and a button, adding ability for things such as scrolling with the pen and so on.

**Comment by InfinityGhost** [comment]
This is no longer needed as `IBinding` has been modified to pass the report itself. The report will contain the data needed in order to execute any sort of gesture.

**Comment by UlyssesZh** [comment]
So how to scroll with the pen now?

**Comment by InfinityGhost** [comment]
A scrolling binding has yet to actually be implemented. This issue was tracking an feature which allowed for dynamic input to invoke a binding, not scrolling itself.

**Comment by UlyssesZh** [comment]
> A scrolling binding has yet to actually be implemented. This issue was tracking an feature which allowed for dynamic input to invoke a binding, not scrolling itself.

Is there any plans that a scrolling binding will be added?

**Comment by UlyssesZh** [comment]
> So how to scroll with the pen now?

I think binding scrolling is a frequently requested feature. It is also requested in #1158.

**Comment by InfinityGhost** [comment]
It is still a work in progress, and I have a working technique on Linux. The issue is likely going to be the macOS implementation.

**Comment by UlyssesZh** [comment]
> It is still a work in progress, and I have a working technique on Linux. The issue is likely going to be the macOS implementation.

What about Windows? I am a Windows user, and I want that feature of binding scrolling.

**Comment by 3ab3z2** [comment]
Is scrolling with the pen implemented on linux yet? (wayland)
