### ISSUE TITLE
Support Request: OpenTabletDriver won't open

### ISSUE THREAD

**Issue by Niwa2D** [OpenTabletDriver/OpenTabletDriver#2016]
Hi there, I had been trying to open OpenTabletDriver, I open up the installer and it closes and nothing happens. I also tried to restart my pc, but it didn't work.

https://user-images.githubusercontent.com/81328965/151400061-4085722a-782e-44f9-ab12-ab31184c04e6.mp4

**Comment by jamesbt365** [comment]
The installer is deprecated, use the portable releases instead. And probably have to delete %localappdata%\OpenTabletDriver
