### ISSUE TITLE
OTD Wont launch/start

### ISSUE THREAD

**Issue by 999Solid** [OpenTabletDriver/OpenTabletDriver#2022]
## Description

When I try to start OTD it wont start, just pops into my Task manager and then close without any bugreport or anything
## System Information:

| Name  999Solid | Value |
| ---------------- | ----- |
| Operating System         |WIndows 10 Home
| OpenTabletDriver Version |I think the latest since I tried to redownload it again.
| Tablet                 | Wacom CTL-472

**Comment by jamesbt365** [comment]
1) latest isn't a version
2) don't use the installer, its deprecated, download the latest portable release and extract it to a folder.
