### ISSUE TITLE
OpenTabletDriver doesnt want to start working

### ISSUE THREAD

**Issue by JetFury** [OpenTabletDriver/OpenTabletDriver#2026]
## Description
When I try to open opentabletdriver it will just show the opentabletdriver updater and then close itself

## System Information: Windows 11

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 11
| OpenTabletDriver Version | 0.6.0.2
| Tablet                   | xp pen g640s

**Comment by jamesbt365** [comment]
Do not use the installer, we don't support it anymore, download and extract the portable release to a folder and use that instead.

**Comment by JetFury** [comment]
thanks
