### ISSUE TITLE
driver wont run/open up

### ISSUE THREAD

**Issue by uexr** [OpenTabletDriver/OpenTabletDriver#2042]
When I try to open up the driver it automatically closes. Is there any way to help fix this issue?

**Comment by Mrcubix** [comment]
- Don't use the installer,
- Extract OTD in it's own folder,
- Add a folder called `userdata` in the same folder as the exes
![image](https://user-images.githubusercontent.com/39861216/152445127-cff4ef6b-410d-4cde-8562-854b6de4f0ee.png)

**Comment by jamesbt365** [comment]
Can we use the template please?
If you are using the installer than do not, download the portable release and follow [this](http://opentabletdriver.net/Wiki/Install/Windows) and if still doesn't work follow what was said above.
