### ISSUE TITLE
Huion HS610 can't be detected by OpenTabletDriver

### ISSUE THREAD

**Issue by YukinaMishimoto** [OpenTabletDriver/OpenTabletDriver#2043]
Description :
I am in pain trying to search why my Huion HS610 can't be detected. I remove my Huion Driver, reinstall it, and everything. still not working. (it my first time on GitHub so sorry if i give info incorrectly)

System Information:
| Name             | Value |
| ---------------- | ------- |
| windows 10        |
| OpenTabletDriver V0.6.0.2 |
| Tablet           Huion HS610        |

**Comment by jamesbt365** [comment]
Try [this](https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0)

**Comment by YukinaMishimoto** [comment]
thx for the fast answer, it work now!
