### ISSUE TITLE
OpenTabletDriver Closes After Opening 

### ISSUE THREAD

**Issue by AwesomeGamer89** [OpenTabletDriver/OpenTabletDriver#2046]
## Description
I have no idea what causes this, I have the prerequisite dependencies installed aswell.
## System Information:

| Operating System | Windows 10 Pro |
| OpenTabletDriver Version | 0.6.0.3 |
| Tablet | XP Pen G640s |

Video:
https://user-images.githubusercontent.com/22873716/152661050-abb0423e-ca46-4bfe-8d44-c4d561113c36.mp4

**Comment by jamesbt365** [comment]
Create a `userdata` folder with the otd executables or remove `%localappdata%\OpenTabletDriver\Plugins\` and `%localappdata%\OpenTabletDriver\settings.json`
