### ISSUE TITLE
File already exists error when updating

### ISSUE THREAD

**Issue by xJon** [OpenTabletDriver/OpenTabletDriver#2051]
# Support Request

Hi! I was prompted when opening OpenTabletDriver to update from `0.6.0.2` to `0.6.0.3`. When trying to update, I got this error: https://pastebin.com/QGbANZtH

## What I've already tried
Looked through Discord & existing issues. Apparently this should work in `0.6.x.x`?

## Diagnostic Information

https://pastebin.com/1EySjV15

**Comment by SWAGEDGAR** [comment]
I have the same issue

**Comment by xJon** [comment]
I have fixed it by manually updating (replacing the files), but it might be better if the installer wouldn't try to update in this case.

**Comment by X9VoiD** [comment]
Fixed by #2563
