### ISSUE TITLE
crashes when using VmultiMode plugin

### ISSUE THREAD

**Issue by SaaSkleks** [OpenTabletDriver/OpenTabletDriver#2052]
## Description
I tried to set up my tablet to work with valorant, the vmultimode plugin should be able to work around the anti-cheat of valorant. Installed the plugin and then tried to set it up, the plugin didnt even seem to work, no settings get registered after pressing apply. When it seemed to work (still no mouse movement in valorant but settings getting applied), by closing and opening the program several times, i minimized opentabletdriver and then clicked on it again to open it, it crashed. Tried again, crash. Reinstalled the driver and the plugin and still crashed. Only fix was going back to my osu presets and not touching the plugin at all.

## System Information:
Operating System:              Windows 10 
OpenTabletDriver Version: 6.0.3 
Tablet:                                 Wacom CTH-670

**Comment by jamesbt365** [comment]
Vmulti and windows ink are not supported in 0.6 as of the current moment, you will have to downgrade to 0.5.3.3 then make a `userdata` folder by the executables
