### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by no6hope** [OpenTabletDriver/OpenTabletDriver#2060]
# Support Request

## What I've already tried

my last support request

## Diagnostic Information

[gaomos m10k is not detected.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8046207/gaomos.m10k.is.not.detected.txt)

**Comment by SnowLire** [comment]
Follow instruction on this page https://github.com/X9VoiD/WinUSBCleanup/releases/tag/v1.0
