### ISSUE TITLE
xp pen deco fun L (ct1060) relative mode issue

### ISSUE THREAD

**Issue by syrex8428** [OpenTabletDriver/OpenTabletDriver#2061]
## Description

it works well when on absolute mode, but the cursor doesnt move when i turn it on to relative mode
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | window 10
| OpenTabletDriver Version | v.0.6.0.3
| Tablet          xp pen deco fun L (ct1060)         |

**Comment by jamesbt365** [comment]
make sure the reset time for relative mode is higher tban 0

**Comment by jamesbt365** [comment]
Closing due to inactively, this was most probably caused by having the reset time at 0 which will halt the cursor completely.

**Comment by syrex8428** [comment]
that was exact thx for helping a lot

2022년 3월 10일 (목) 05:09, jamesbt365 ***@***.***>님이 작성:
