### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by no6hope** [OpenTabletDriver/OpenTabletDriver#2065]
# Support Request
hello, I've recently used OTD for my tablet (gaomon m10k pro) and I felt kinda input lag when I was using it but when I use my other tablet (wacom ctl-4100) is everything normal

## What I've already tried
I reconnected it, restarted my laptop, changed the cable, but the problem continued

## Diagnostic Information

[gaomon input lag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8054700/gaomon.input.lag.txt)

**Comment by jamesbt365** [comment]
Fill this out and explain this instead of leaving literally everything blank.

**Comment by no6hope** [comment]
hehe I forgot to remove the symbols "<-"  now it is fill
