### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by SWAGEDGAR** [OpenTabletDriver/OpenTabletDriver#2073]
## Description
It say's there is a new update and when I click update 2 errors pop up and the driver crashes.
https://ibb.co/y0sBsRr
https://ibb.co/3fBBvB8

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows
| OpenTabletDriver Version | 0.6.0.3
| Tablet                   | Wacom 472

**Comment by jamesbt365** [comment]
#2051

**Comment by xJon** [comment]
@jamesbt365 should my issue be considered a bug report then?

**Comment by jamesbt365** [comment]
? This issue was a duplicate of #2051 so it was closed
