### ISSUE TITLE
Support Request: Hovering with CTH-480 causes cursor to jump around

### ISSUE THREAD

**Issue by Exiledx** [OpenTabletDriver/OpenTabletDriver#2076]
When hovering with my pen the cursor freaks out and jumps all around. When pushed/dragged on the tablet it works fine. Any idea what might be causing this problem?

**Comment by jamesbt365** [comment]
Possibly other drivers, go to help > export diagnostics, save that file with the `txt` extension and send it here.

**Comment by Exiledx** [comment]
[helpgit.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8083606/helpgit.txt)

**Comment by jamesbt365** [comment]
"Console Log": [
    {
      "Time": "2022-02-16T16:13:34.5197013-05:00",
      "Group": "Detect",
      "Message": "Another tablet driver found: Wacom",
      "StackTrace": null,
      "Level": 2,
      "Notification": false
    },

**Comment by Exiledx** [comment]
I double checked and it should be uninstalled? Does it go by another name

**Comment by jamesbt365** [comment]
Either its installed or this is just chatter, a thing in physics. Get a video of it if possible.

**Comment by jamesbt365** [comment]
Closing due to no response, if you can supply what i have said above go ahead and do so and i'll reopen it.
