### ISSUE TITLE
Support Request: Old Version Download

### ISSUE THREAD

**Issue by DarkGears** [OpenTabletDriver/OpenTabletDriver#2077]
# Support Request
Im trying to use a pen on valorant and I was told to download OTD version 0.5.3.3 and I don't know how to download it
#2072 
## What I've already tried
I found the latest release of the OTD and then I changed the link so it would download/go to https://github.com/OpenTabletDriver/OpenTabletDriver/releases/ (version 0.5.3.3) instead, it uses aur.archlinux.org which I don't know how to download files from, I found a button called download snapshot but it downloaded 
![image](https://user-images.githubusercontent.com/92230591/154374711-e2f5fde0-6800-4112-bdbc-900509501792.png)
![image](https://user-images.githubusercontent.com/92230591/154374731-70746372-99b1-43b8-9926-424ff99a3e55.png)
![image](https://user-images.githubusercontent.com/92230591/154374502-bf7e38e2-d0b8-4262-bf26-5bcad7225ae4.png)

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/154377612-9d6b346c-d0e8-48c4-a030-6e02a5075e98.png)

**Comment by DarkGears** [comment]
thanks
