### ISSUE TITLE
Support Request: Windows Ink not working

### ISSUE THREAD

**Issue by aprchz** [OpenTabletDriver/OpenTabletDriver#2081]
# Support Request About VMulti WindowsInk and VMultiAbsolute

Hello, I've followed the procedure on the Vmulti page, and it worked, at first last night it was great, but when this morning I tried WindowsInk mode, the cursor wouldn't even move

What I've already tried
I checked the console, there was no sign that my computer lost vmulti ( yesterday I tried on another pc, it keeps giving warning that vmulti doesn't exist, even though i already installed it, then i made a fresh install on the main computer, without installing any pentablet drivers, and vmulti worked, then well, back on top), i checked the system32 directory , and the vmulti.inf file is still there, I also tried to delete vmulti again with the remove_hiddriver file, it disappeared, then I installed it again, and it worked, although the PC doesn't seem to restart? but in the OTD console, VMulti is successfully installed, without notification "vmulti not detected, please go to the following email"
what should I do?
Any help ?
## Diagnostic Information

![bukti2](https://user-images.githubusercontent.com/81733471/154782848-48a04e0d-dbad-45eb-99bb-21706772e273.png)
![bukti1](https://user-images.githubusercontent.com/81733471/154782875-31e1791b-f36c-4840-bb98-bbf95f4ae02c.png)

**Comment by Vyexk** [comment]
It only happens with version 0.6.x?

**Comment by jamesbt365** [comment]
> It only happens with version 0.6.x?

Yes.

**Comment by AncuL001** [comment]
alternatively, just use [v0.5.3.3](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.3.3) if you don't have multiple tablets (except if there's actually any vulnerabilities fixed on later versions because i didn't read the release notes. just correct me if there actually is)

**Comment by KLevnDarama** [comment]
i dont know if this is already mentioned or you guys already knew, but this is the error message that i took from the "OpenTabletDriver.Daemon.exe"
![image](https://user-images.githubusercontent.com/100375802/159105351-16821326-01d5-4467-99c8-da284218c449.png)
i run on Windows 11 and using Huion H640p, so idk if this occurs for other Windows version or other tablets.

i searched up on how to fix "NullReferenceException" and it said this:
![image](https://user-images.githubusercontent.com/100375802/159105589-3f09430e-3bf8-4516-bb94-3437249f7110.png)
i'm no expert in C#, and i barely understand what it means. but i have some experience in lua, so i assume this is relatively "easy" for you guys to fix it.

sorry if i'm wrong and/or if you guys already know this, i just want WindowsInk to get fixed so i get to draw stuff without changing tablet driver everytime.

**Comment by Sublimelime** [comment]
@KLevnDarama Appreciate the attempt to help, but it's not the error that's the issue. The issue stems from windows ink not being updated to work with the latest version of the driver, due to a breaking change made by the update. If your tablet doesn't need 0.6 to work, we currently recommend simply downgrading to 0.5.3.3 (as mentioned above in the comments of this issue), as that will work just fine.

If downgrading isn't an option, you can wait for the fix, which is coming in 0.6.1 (and will enable the author of the plugin to update it).

**Comment by X9VoiD** [comment]
@Sublimelime There's actually no need to update the plugin, it's literally just a breakage in OTD itself.

**Comment by jamesbt365** [comment]
Closing due to this being resolved.

**Comment by AncuL001** [comment]
is this "resolved"? i haven't known of a PR that fixes this issue (please tell me of one if there exists) and downgrading is certainly not a clean solution

**Comment by jamesbt365** [comment]
It is resolved, a workaround was done instead of changing something else.
