### ISSUE TITLE
XP-Pen Deco Fun XS not being detected

### ISSUE THREAD

**Issue by Axis4s** [OpenTabletDriver/OpenTabletDriver#2088]
Support Request

XP-Pen Deco Fun XS not detected....
EndeavourOS (Arch Linux)

I did tell the program to detect the tablets, but it says no tablets were detected

**Comment by jamesbt365** [comment]
Fill out the template.

**Comment by jamesbt365** [comment]
top of otd there is `help > export diagnostics` save that file with the `txt` file extension and send that file here.

**Comment by Axis4s** [comment]
> top of otd there is `help > export diagnostics` save that file with the `txt` file extension and send that file here.
[file.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8112546/file.txt)

**Comment by jamesbt365** [comment]
try out the config from #2085

**Comment by jamesbt365** [comment]
also you may need [this](http://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams)

**Comment by Axis4s** [comment]
> try out the config from #2085
> 
> Make a `Configurations` folder in `/usr/share/OpenTabletDriver/` move that config file there.

that's a link to a channel, not to a file

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/155038291-96dde162-f504-420e-bb7d-1a9572038f8a.png)

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/155038531-25132675-0627-4e81-8e1e-c84a4933bcca.png)
![image](https://user-images.githubusercontent.com/22662856/155038594-385dafb7-12bd-4f52-8e9d-c6f2e9f8333a.png)
then press `control + s`

**Comment by jamesbt365** [comment]
fixed in [discord](https://discord.com/channels/615607687467761684/723399565780189234/945466793437319260)
