### ISSUE TITLE
Add support for Huion HS611 tablet

### ISSUE THREAD

**Issue by TheDreamingOwl** [OpenTabletDriver/OpenTabletDriver#2094]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | Huion 
| Product Name    | Huion HS611
| Width           | 13 inches
| Height          | 8 Inches
| Pressure Levels | 8192 Levels
| LPI             | 5080

**Comment by jamesbt365** [comment]
Can you supply a diagnostic as the template requests please, go to `help > export diagnostic` and save that file with the `txt` file extension then upload it here.

**Comment by jamesbt365** [comment]
turns out i didn't check the supported list either. This is already supported and has been for a while.
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.Configurations/Configurations/Huion/HS611.json
