### ISSUE TITLE
Huion H640P not detected.

### ISSUE THREAD

**Issue by iambeingtracked** [OpenTabletDriver/OpenTabletDriver#2098]
# Support Request
My Huion H640P not being detected
Pretty simple, i plugged it in, and it says that no tablet detected

## What I've already tried
'Failed to open device streams'. Also tried to google my problem but didn't find anything useful 

## Diagnostic Information
For some reason github doesn't let me upload a .txt file so it's here for a day https://put.icu/kd3qyc24.txt -->

I installed the latest version from AUR on arch linux.

**Comment by jamesbt365** [comment]
http://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams
