### ISSUE TITLE
bug with tablet

### ISSUE THREAD

**Issue by NatteTosti69** [OpenTabletDriver/OpenTabletDriver#2099]
## Description
today i reinstalled my tabletdriver and now when i hit the top of my monitor, it glitches to the bottom and it feels way faster.
also a youtube link to see what happens. https://www.youtube.com/watch?v=ajIQYRCExxw

## System Information:

| Operating System         |Edition	Windows 10 Pro
Version	21H2
Installed on	‎2-‎11-‎2020
OS build	19044.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

| OpenTabletDriver Version | v0.6.0.3
| Tablet                   |Wacom CTL-4100

**Comment by jamesbt365** [comment]
Fill it out and explain.

**Comment by jamesbt365** [comment]
Your video is private, if this is only osu then turn off raw input, and if that doesn't solve it then `help > export diagnostic` save that file with the `txt` extension and upload that here.

**Comment by NatteTosti69** [comment]
[file.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8148976/file.txt)

**Comment by NatteTosti69** [comment]
https://www.youtube.com/watch?v=ajIQYRCExxw
its now public

**Comment by jamesbt365** [comment]
I see no other other than you have your display area letterboxed, depending on if you want to do that or not. You might have wacom drivers installed however i don't see hard evidence of this, otherwise file > reset to defaults and apply then see then.

**Comment by NatteTosti69** [comment]
resetting to default fixed the bug. thank you very much
