### ISSUE TITLE
Windows Ink working, but buttons doesn't work

### ISSUE THREAD

**Issue by VicoSilalahi** [OpenTabletDriver/OpenTabletDriver#2100]
## Description
I had windows Ink working, except that it can't use any button, like left-click or right-click, or even the side button. I have already installed the vmulti. Absolute mode is working fine as well as Relative. I only found this problem in windows ink absolute and relative.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10 64bit |
| OpenTabletDriver Version | v.0.5.3.3 |
| Tablet                   | Gaomon S620 |

**Comment by jamesbt365** [comment]
you need to use vmulti bindings in vmulti mode and windows ink bindings in windows ink mode. click the 3 dots by the binding that you want to set.
