### ISSUE TITLE
Pen Mouse Button binding doesn't work in Artist Mode

### ISSUE THREAD

**Issue by paherbst** [OpenTabletDriver/OpenTabletDriver#2112]
## Description
Mouse button binding to pen buttons on Gaomon S620 does not work when in Artist Mode.
The binding works when in Absolute mode, but then pressure sensitivity does not work.

## System Information:

| Name             | Value |
| ---------------- | ----- |
Linux Mint 20.2
| OpenTabletDriver Version 0.6.0.3 |
| Tablet    Gaomon S620               |

**Comment by jamesbt365** [comment]
You cannot use normal pen bindings in artist mode. You unbind the tip or use artist mode bindings. Here is an example
![image](https://user-images.githubusercontent.com/22662856/157725369-16c0c024-11ef-4635-9db0-85eba626d2d8.png)

**Comment by paherbst** [comment]
Thank you!  is this documented anywhere?

**Comment by jamesbt365** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver.Web/issues/40 to be done.

**Comment by gameboycjp** [comment]
Is there a reason why it doesn't work? Is it possible to support it? I have buttons on my tablet I just can't bind due to there being only 3 buttons to bind.

**Comment by gonX** [comment]
@gameboycjp Do you mean tablet pad buttons? You should be able to bind those to an arbitrary key under auxiliary buttons.

If you don't have an auxiliary tab in the driver and your tablet pad has buttons on it, please open a new bug report.

**Comment by gameboycjp** [comment]
The buttons are bindable, they just don't work.
