### ISSUE TITLE
Support Request: Pen button presses are detected, but ignored and not passed in Artist Mode on Linux

### ISSUE THREAD

**Issue by EntityinArray** [OpenTabletDriver/OpenTabletDriver#2113]
# Support Request
Hi, huge thanks for working on this amazing driver!
I have a wierd problem, not sure if it's a bug or is it intended:
Outside of Artist Mode all button presses are detected and working. However, when Artist Mode is active, pen button presses are still detected (they show up in Tablet Debugger), but are ignored and not passed through for some reason. Pressing pen buttons while in Artist Mode does nothing.

## What I've already tried
Tried looking through settings, but found nothing that could help me

## Diagnostic Information
OS: Arch Linux 5.16.13-arch1-1
Tablet: Wacom CTL-4100
OpenTabletDriver 0.6.0.3+1ac31a7
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8226112/diag.txt)

**Comment by jamesbt365** [comment]
#2112
