### ISSUE TITLE
Add support for XP-pen Artist 10S

### ISSUE THREAD

**Issue by Fledrox** [OpenTabletDriver/OpenTabletDriver#2116]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | XP-PEN
| Product Name    | Artist 10S
| Width           | 1280px
| Height          | 800px
| Pressure Levels | 2048
| LPI             | 5080

## Diagnostic Information

[artist10s-diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8234378/artist10s-diagnostic.txt)

**Comment by Ponywka** [comment]
Implemented in https://github.com/OpenTabletDriver/OpenTabletDriver/pull/3310 & https://github.com/OpenTabletDriver/OpenTabletDriver/pull/3311
