### ISSUE TITLE
Support Request: Pen detectable in tablet debugger but cursor can't move

### ISSUE THREAD

**Issue by robbiegumgum** [OpenTabletDriver/OpenTabletDriver#2119]
# Support Request
I'm using Wacom CTL-6100 wired (app shows CTL-6100WL ). On the tablets supported section I cant see CTL-6100 dunno if that's the issue.
My pen signals can be detected when touching tablet but i cant move cursor
I tried saving and applying and everything but to no avail. Here're the screenshots

![1](https://user-images.githubusercontent.com/66349307/158025844-8022a38d-f7eb-49a6-b1c5-e108aae3c8c2.png)
![2](https://user-images.githubusercontent.com/66349307/158025848-19f3ed74-5ecc-47d8-865d-b9b6416e701d.png)

Pls help

**Comment by jamesbt365** [comment]
Attach a diagnostic as shown in the template instead of cutting it off. `Help > export diagnostic`, save that file with a .txt extension and send that file here.

Also make sure valorant or vanguard isn't open and file > reset to default

**Comment by robbiegumgum** [comment]
> Attach a diagnostic as shown in the template instead of cutting it off. `Help > export diagnostic`, save that file with a .txt extension and send that file here.
> 
> Also make sure valorant or vanguard isn't open and file > reset to default

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8237937/diag.txt)

Here it is

**Comment by jamesbt365** [comment]
Fixed in `Configs` branch will be in a release soon, that or download an action build.
