### ISSUE TITLE
Support Request: WindowsInk not working

### ISSUE THREAD

**Issue by Audia2753** [OpenTabletDriver/OpenTabletDriver#2126]
![Screenshot (698)](https://user-images.githubusercontent.com/101726554/158612031-bc984229-084f-4165-b806-fd523d788112.png)
![Screenshot (697)](https://user-images.githubusercontent.com/101726554/158612044-700a2bd7-82a7-43bd-bec9-4517b4da5d9b.png)
hello i got this error,maybe someone can help me,appreciate it

**Comment by jamesbt365** [comment]
#2081
