### ISSUE TITLE
Driver doesnt work when quit MacOS

### ISSUE THREAD

**Issue by gamerturtlepoggers** [OpenTabletDriver/OpenTabletDriver#2131]
I downloaded this driver and it worked fine while the driver was open, but when I quit the application, it stopped working, and when I unplugged and replugged my tablet it was full area

**Comment by X9VoiD** [comment]
The application *is* the driver. Minimize it instead if you need to keep it. If you want this behavior to change then open a new issue detailing what behavior you want instead.

**Comment by gamerturtlepoggers** [comment]
oke 👍
