### ISSUE TITLE
I can't open plugin manager

### ISSUE THREAD

**Issue by NorvalBlast** [OpenTabletDriver/OpenTabletDriver#2134]
| Operating System Win 10|
| OpenTabletDriver Version 0.6.0.3|
| Tablet CTL-461 |

**Comment by jamesbt365** [comment]
follow the warning when opening opentabletdriver.

**Comment by NorvalBlast** [comment]
Nothing

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/159796794-0613217a-7925-4f2e-bbf4-0a15c92cb975.png)
 looks like this.

**Comment by NorvalBlast** [comment]
I think that I'm doing everything righе

**Comment by jamesbt365** [comment]
What user do you log in with?

**Comment by NorvalBlast** [comment]
I have 1 user on pc

**Comment by jamesbt365** [comment]
That wasn't the question, i asked what username

**Comment by NorvalBlast** [comment]
I badly understand english sry. Norval

**Comment by jamesbt365** [comment]
What is you're UAC setting set to?

**Comment by NorvalBlast** [comment]
I checked from lowest to highest, now lowest

**Comment by NorvalBlast** [comment]
Lol, i checked every level. I checked it again and its working

**Comment by NorvalBlast** [comment]
I'm sorry I wasted your time
