### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by fluteze** [OpenTabletDriver/OpenTabletDriver#2135]
## Description
Daemon aborts at startup with the following error:

Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

## System Information:
Linux <redacted> 5.16.15-201.fc35.x86_64 #1 SMP PREEMPT Thu Mar 17 05:45:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
OTD Version: 0.6.0.3+d18345a9

dotnet --version
6.0.201

Tablet: Gaomon PD1161

Startup log:

[<redacted>@<redacted> bin]$ ./OpenTabletDriver.Daemon 
[Plugin:Debug]	Loading plugin 'Precision Control'
[Plugin:Debug]	Loading plugin 'VMultiMode'
[Plugin:Debug]	Loading plugin 'Windows Ink'
[Detect:Info]	Searching for tablets...
[Detect:Debug]	Searching for tablet '10moon 1060N'
[Detect:Debug]	Searching for tablet 'Acepen AP 1060'
[Detect:Debug]	Searching for tablet 'Artisul M0610 Pro'
[Detect:Debug]	Searching for tablet 'Gaomon 1060 Pro'
[Detect:Debug]	Searching for tablet 'Gaomon M106K Pro'
[Detect:Debug]	Searching for tablet 'Gaomon M106K'
[Detect:Debug]	Searching for tablet 'Gaomon M10K Pro'
[Detect:Debug]	Searching for tablet 'Gaomon M10K'
[Detect:Debug]	Searching for tablet 'Gaomon M1220'
[Detect:Debug]	Searching for tablet 'Gaomon M1230'
[Detect:Debug]	Searching for tablet 'Gaomon PD1161'
[Device:Debug]	Initializing device 'Tablet Monitor' /sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.5/2-1.5:1.0/0003:256C:006D.0001/hidraw/hidraw0
[Device:Debug]	Using report parser type 'OpenTabletDriver.Configurations.Parsers.UCLogic.UCLogicReportParser'
[Device:Debug]	Initialized string index 200
[Detect:Info]	Found tablet 'Gaomon PD1161'
[Detect:Debug]	Searching for tablet 'Gaomon PD1560'
[Detect:Debug]	Searching for tablet 'Gaomon S56K'
[Detect:Debug]	Searching for tablet 'Gaomon S620'
[Detect:Debug]	Searching for tablet 'Gaomon S630'
[Detect:Debug]	Searching for tablet 'Genius G-Pen 560'
[Detect:Debug]	Searching for tablet 'Genius i608x'
[Detect:Debug]	Searching for tablet 'Huion 420'
[Detect:Debug]	Searching for tablet 'Huion G10T'
[Detect:Debug]	Searching for tablet 'Huion GC610'
[Detect:Debug]	Searching for tablet 'Huion GT-220 V2'
[Detect:Debug]	Searching for tablet 'Huion GT-221 Pro'
[Detect:Debug]	Searching for tablet 'Huion H1060P'
[Detect:Debug]	Searching for tablet 'Huion H1161'
[Detect:Debug]	Searching for tablet 'Huion H420'
[Detect:Debug]	Searching for tablet 'Huion H420X'
[Detect:Debug]	Searching for tablet 'Huion H430P'
[Detect:Debug]	Searching for tablet 'Huion H610 Pro V2'
[Detect:Debug]	Searching for tablet 'Huion H610 Pro'
[Detect:Debug]	Searching for tablet 'Huion H640P'
[Detect:Debug]	Searching for tablet 'Huion H950P'
[Detect:Debug]	Searching for tablet 'Huion HC16'
[Detect:Debug]	Searching for tablet 'Huion HS610'
[Detect:Debug]	Searching for tablet 'Huion HS611'
[Detect:Debug]	Searching for tablet 'Huion HS64'
[Detect:Debug]	Searching for tablet 'Huion Kamvas 13'
[Detect:Debug]	Searching for tablet 'Huion Kamvas 16 (2021)'
[Detect:Debug]	Searching for tablet 'Huion Kamvas 16'
[Detect:Debug]	Searching for tablet 'Huion Kamvas 20'
[Detect:Debug]	Searching for tablet 'Huion Kamvas 22 Plus'
[Detect:Debug]	Searching for tablet 'Huion Kamvas Pro 12'
[Detect:Debug]	Searching for tablet 'Huion Kamvas Pro 13'
[Detect:Debug]	Searching for tablet 'Huion Kamvas Pro 16'
[Detect:Debug]	Searching for tablet 'Huion Kamvas Pro 20'
[Detect:Debug]	Searching for tablet 'Huion New 1060 Plus (2048)'
[Detect:Debug]	Searching for tablet 'Huion New 1060 Plus'
[Detect:Debug]	Searching for tablet 'Huion Q11K V2'
[Detect:Debug]	Searching for tablet 'Huion Q11K'
[Detect:Debug]	Searching for tablet 'Huion Q620M'
[Detect:Debug]	Searching for tablet 'Huion WH1409 V2'
[Detect:Debug]	Searching for tablet 'Huion WH1409'
[Detect:Debug]	Searching for tablet 'Parblo A610 Pro'
[Detect:Debug]	Searching for tablet 'Parblo A640 V2'
[Detect:Debug]	Searching for tablet 'Parblo Intangbo M'
[Detect:Debug]	Searching for tablet 'Parblo Intangbo S'
[Detect:Debug]	Searching for tablet 'Parblo Ninos M'
[Detect:Debug]	Searching for tablet 'Parblo Ninos S'
[Detect:Debug]	Searching for tablet 'UC-Logic 1060N'
[Detect:Debug]	Searching for tablet 'UC-Logic PF1209'
[Detect:Debug]	Searching for tablet 'UGTABLET M708'
[Detect:Debug]	Searching for tablet 'VEIKK A15 Pro'
[Detect:Debug]	Searching for tablet 'VEIKK A15'
[Detect:Debug]	Searching for tablet 'VEIKK A30'
[Detect:Debug]	Searching for tablet 'VEIKK A50 V2'
[Detect:Debug]	Searching for tablet 'VEIKK A50'
[Detect:Debug]	Searching for tablet 'VEIKK S640 V2'
[Detect:Debug]	Searching for tablet 'VEIKK S640'
[Detect:Debug]	Searching for tablet 'VEIKK VK640'
[Detect:Debug]	Searching for tablet 'ViewSonic Woodpad PF0730'
[Detect:Debug]	Searching for tablet 'Wacom CTE-430'
[Detect:Debug]	Searching for tablet 'Wacom CTE-440'
[Detect:Debug]	Searching for tablet 'Wacom CTE-450'
[Detect:Debug]	Searching for tablet 'Wacom CTE-460'
[Detect:Debug]	Searching for tablet 'Wacom CTE-630'
[Detect:Debug]	Searching for tablet 'Wacom CTE-640'
[Detect:Debug]	Searching for tablet 'Wacom CTE-650'
[Detect:Debug]	Searching for tablet 'Wacom CTF-430'
[Detect:Debug]	Searching for tablet 'Wacom CTH-460'
[Detect:Debug]	Searching for tablet 'Wacom CTH-461'
[Detect:Debug]	Searching for tablet 'Wacom CTH-470'
[Detect:Debug]	Searching for tablet 'Wacom CTH-480'
[Detect:Debug]	Searching for tablet 'Wacom CTH-490'
[Detect:Debug]	Searching for tablet 'Wacom CTH-661'
[Detect:Debug]	Searching for tablet 'Wacom CTH-670'
[Detect:Debug]	Searching for tablet 'Wacom CTH-680'
[Detect:Debug]	Searching for tablet 'Wacom CTH-690'
[Detect:Debug]	Searching for tablet 'Wacom CTL-4100'
[Detect:Debug]	Searching for tablet 'Wacom CTL-4100WL'
[Detect:Debug]	Searching for tablet 'Wacom CTL-460'
[Detect:Debug]	Searching for tablet 'Wacom CTL-470'
[Detect:Debug]	Searching for tablet 'Wacom CTL-471'
[Detect:Debug]	Searching for tablet 'Wacom CTL-472'
[Detect:Debug]	Searching for tablet 'Wacom CTL-480'
[Detect:Debug]	Searching for tablet 'Wacom CTL-490'
[Detect:Debug]	Searching for tablet 'Wacom CTL-6100WL'
[Detect:Debug]	Searching for tablet 'Wacom CTL-671'
[Detect:Debug]	Searching for tablet 'Wacom CTL-672'
[Detect:Debug]	Searching for tablet 'Wacom CTL-680'
[Detect:Debug]	Searching for tablet 'Wacom CTL-690'
[Detect:Debug]	Searching for tablet 'Wacom DTC-133'
[Detect:Debug]	Searching for tablet 'Wacom ET-0405-U'
[Detect:Debug]	Searching for tablet 'Wacom ET-0405A-U'
[Detect:Debug]	Searching for tablet 'Wacom FT-0405-U'
[Detect:Debug]	Searching for tablet 'Wacom GD-0405-U'
[Detect:Debug]	Searching for tablet 'Wacom GD-0608-U'
[Detect:Debug]	Searching for tablet 'Wacom GD-0912-U'
[Detect:Debug]	Searching for tablet 'Wacom GD-1212-U'
[Detect:Debug]	Searching for tablet 'Wacom GD-1218-U'
[Detect:Debug]	Searching for tablet 'Wacom MTE-450'
[Detect:Debug]	Searching for tablet 'Wacom PTH-450'
[Detect:Debug]	Searching for tablet 'Wacom PTH-451'
[Detect:Debug]	Searching for tablet 'Wacom PTH-460'
[Detect:Debug]	Searching for tablet 'Wacom PTH-650'
[Detect:Debug]	Searching for tablet 'Wacom PTH-651'
[Detect:Debug]	Searching for tablet 'Wacom PTH-660'
[Detect:Debug]	Searching for tablet 'Wacom PTH-850'
[Detect:Debug]	Searching for tablet 'Wacom PTH-851'
[Detect:Debug]	Searching for tablet 'Wacom PTH-860'
[Detect:Debug]	Searching for tablet 'Wacom PTK-1240'
[Detect:Debug]	Searching for tablet 'Wacom PTK-440'
[Detect:Debug]	Searching for tablet 'Wacom PTK-450'
[Detect:Debug]	Searching for tablet 'Wacom PTK-540WL'
[Detect:Debug]	Searching for tablet 'Wacom PTK-640'
[Detect:Debug]	Searching for tablet 'Wacom PTK-650'
[Detect:Debug]	Searching for tablet 'Wacom PTK-840'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-1230'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-1231W'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-430'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-431W'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-630'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-631W'
[Detect:Debug]	Searching for tablet 'Wacom PTZ-930'
[Detect:Debug]	Searching for tablet 'Wacom XD-0405-U'
[Detect:Debug]	Searching for tablet 'Wacom XD-0608-U'
[Detect:Debug]	Searching for tablet 'Wacom XD-0912-U'
[Detect:Debug]	Searching for tablet 'Wacom XD-1212-U'
[Detect:Debug]	Searching for tablet 'Wacom XD-1218-U'
[Detect:Debug]	Searching for tablet 'XenceLabs Pen Tablet Medium'
[Detect:Debug]	Searching for tablet 'XP-Pen Artist 12 Pro'
[Detect:Debug]	Searching for tablet 'XP-Pen Artist 12 V2'
[Detect:Debug]	Searching for tablet 'XP-Pen Artist 12'
[Detect:Debug]	Searching for tablet 'XP-Pen Artist 15.6 Pro'
[Detect:Debug]	Searching for tablet 'XP-Pen Artist 22HD'
[Detect:Debug]	Searching for tablet 'XP-Pen CT1060'
[Detect:Debug]	Searching for tablet 'XP-Pen CT430'
[Detect:Debug]	Searching for tablet 'XP-Pen CT640'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco 01 V2 (variant 2)'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco 01 V2'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco 01'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco 02'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco 03'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco mini4'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco mini7'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco Pro Medium'
[Detect:Debug]	Searching for tablet 'XP-Pen Deco Pro Small'
[Detect:Debug]	Searching for tablet 'XP-Pen Innovator 16'
[Detect:Debug]	Searching for tablet 'XP-Pen Star 03'
[Detect:Debug]	Searching for tablet 'XP-Pen Star 05 V3'
[Detect:Debug]	Searching for tablet 'XP-Pen Star 06'
[Detect:Debug]	Searching for tablet 'XP-Pen Star 06C'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G430'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G430S V2'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G430S'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G540 Pro'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G540'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G640 V2'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G640'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G640S'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G960'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G960S Plus'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G960S'
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VoiDPlugins.Library.VoiD.GlobalStore`1.GetOrInitialize[U](TabletReference tabletReference, Func`1 initialValue) in /home/runner/work/VoiDPlugins/VoiDPlugins/src/VoiDPlugins.Library/VoiD/GlobalStore.cs:line 21
   at VoiDPlugins.OutputMode.VMultiAbsolutePointer..ctor(TabletReference tabletReference, IVirtualScreen virtualScreen) in /home/runner/work/VoiDPlugins/VoiDPlugins/src/OutputMode/VMultiMode/Pointer/VMultiAbsolutePointer.cs:line 19
   at VoiDPlugins.OutputMode.VMultiAbsoluteMode.Initialize() in /home/runner/work/VoiDPlugins/VoiDPlugins/src/OutputMode/VMultiMode/Output/VMultiAbsoluteMode.cs:line 25
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.TriggerEventMethods(Object obj, TabletReference tabletReference) in /usr/local/src/OpenTabletDriver/OpenTabletDriver.Desktop/Reflection/PluginSettingStore.cs:line 174
   at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.Construct[T](TabletReference tabletReference, Boolean trigger) in /usr/local/src/OpenTabletDriver/OpenTabletDriver.Desktop/Reflection/PluginSettingStore.cs:line 57
   at OpenTabletDriver.Daemon.DriverDaemon.SetSettings(Settings settings) in /usr/local/src/OpenTabletDriver/OpenTabletDriver.Daemon/DriverDaemon.cs:line 163
   at OpenTabletDriver.Daemon.DriverDaemon.LoadUserSettings() in /usr/local/src/OpenTabletDriver/OpenTabletDriver.Daemon/DriverDaemon.cs:line 222
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)

If you need any additional information or debug access, this can be provided.

**Comment by jamesbt365** [comment]
Answers given in the stack trace, vmulti plugin (broken on 0.6 and its windows only anyway), remove it from `~/.config/OpenTabletDriver/Plugins` you may also need to delete the settings file.

**Comment by fluteze** [comment]
Yes, it is a windows only plugin; however, it still generates an unhandled error exception on linux. It is the 'unhandled' part that I'm reporting as an error, not the existence of the problematic plugin.

**Comment by jamesbt365** [comment]
The unhandled exception happens on __all__ platforms because OpenTabletDriver changed the plugin api and the plugin couldn't be fixed and will be fixed soon:tm:
