### ISSUE TITLE
Support Request: Horrible delay on linux mint xfce (nvidia)

### ISSUE THREAD

**Issue by MattRBX** [OpenTabletDriver/OpenTabletDriver#2140]
there is a horrible and slightly visible delay when using my tablet on linux to play osu
it occurs basically no matter which tablet driver i use and it's not due to framedropping or anything since im running at least 1000+ fps at 0.45ms delay
also theres less delay when using a mouse but im a tablet player so i just suck

i tried looking at the FAQ on opentabletdriver.net for linux and since my laptop has a gtx-1660ti mobile i looked at the poor performance for nvidia to solve it but i cant find "Force full composition pipeline" in my nvidia settings
so then i tried looking up how to find it, get it, disable it through terminal and nothing really seemed to work

so now im stuck with a horrible delay that i'd say is about 50-100ms

**NOTE:** im not especially good with linux but i usually get stuff working with the right guides so try and keep it simple plz ty

Linux mint version: xfce 20.3
Nvidia driver: nvidia-driver-510 proprietary driver

Diagnostic Information:
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8373814/diag.txt)

**Comment by jamesbt365** [comment]
attach the diagnostic as a file, don't just throw it into the chat.
> it occurs basically no matter which tablet driver i use
not exactly an otd issue then, sounds like a configuration issue more than anything.

**Comment by X9VoiD** [comment]
This is not an OTD issue. Try asking around reddit, or other forums for solutions. Most likely solution is to disable your DE's compositor, and running osu! on fullscreen.
