### ISSUE TITLE
Support Request: NullReferenceException when attempting to set Windows Ink mode

### ISSUE THREAD

**Issue by Elinvynia** [OpenTabletDriver/OpenTabletDriver#2149]
# Support Request
I've recently got a Gaomon S620 tablet and wanted to try drawing with it, after some googling around I found that I need something called "Windows Ink", after installing that from within the plugin manager, it gave me a different error that it needs a "VMulti driver" which I also installed from the plugin manager. That unfortunately did not fix the issue and instead this cryptic error appeared.

Important note: I have installed OpenTabletDriver v0.6.0.3 from a COPR repo since installing it manually is a very painful process and RPM unfortunately isn't supported yet - https://copr.fedorainfracloud.org/coprs/cappyishihara/opentabletdriver/

I'm on Fedora 35, GNOME Wayland, but I guess all of this is in the exported diagnostics. Feel free to ask if you need anything else!

## What I've already tried
A few restarts and trying various other presets and configuration options within OTD.

## Diagnostic Information

https://pastebin.com/vTrsa0Ti

**Comment by jamesbt365** [comment]
Windows ink is, as in the title of the plugin, for Windows.
