### ISSUE TITLE
Add support for XP-Pen Deco Fun S and XS

### ISSUE THREAD

**Issue by Rondosu** [OpenTabletDriver/OpenTabletDriver#2151]
when I came here to download opentabletdriver for my deco fun S,
I realized that it only available for L (the largest size)

please add the S and XS for people who don't use the largest size like me

**Comment by jamesbt365** [comment]
We have the L and the XS, we are just missing the small. Fill out the template appropriately and we will get started.

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/161294254-509a3ca1-4749-4b7b-99db-bd0f44eebaf5.png)

**Comment by Rondosu** [comment]
so how do I install it?
I have my tablet plugged in and opentabletdriver opened
but it does not detect

**Comment by Rondosu** [comment]
> ![image](https://user-images.githubusercontent.com/22662856/161294254-509a3ca1-4749-4b7b-99db-bd0f44eebaf5.png)

so how do I install it?
I have my Deco Fun S (CT640 I think) and opentabletdriver on
but it not detecting my Deco Fun S
