### ISSUE TITLE
Support Request: Veikk A15 Pro not detected, no veikk drivers installed, clean windows installation (PLEASE FOR THE LOVE OF GOD ACTUALLY HELP ME)

### ISSUE THREAD

**Issue by DrunkenMasterTim** [OpenTabletDriver/OpenTabletDriver#2154]
# Support Request

## Diagnostic Information

[Diagnostic-A15 Pro.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8402530/Diagnostic-A15.Pro.txt)

**Comment by jamesbt365** [comment]
You already have an issue open for the same problem, don't make another. #2136
