### ISSUE TITLE
A15 pro,  Config file you gave me now detects tablet, but when pen is hovered over tablet cursor goes crazy up and down

### ISSUE THREAD

**Issue by DrunkenMasterTim** [OpenTabletDriver/OpenTabletDriver#2155]
# Support Request

## Diagnostic Information

[New Text Document.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8402865/New.Text.Document.txt)

**Comment by jamesbt365** [comment]
No point making **another** issue over the same combination of problems, i haven't gotten around to checking the configuration yet as its not complete.

**Comment by DrunkenMasterTim** [comment]
How am I supposed to know, I've never had an issue with the software until
now, and why would you give me an unfinished configuration file? Not trying
to be rude

**Comment by jamesbt365** [comment]
Can i finish a configuration file without knowing if it works at all in the first place? No i can't, how am i meant to predict if your variant of the tablet is going to work 100% as the previous one, no i can't, i can't predict and fix problems before they arise, wait patiently i'm busy.

**Comment by DrunkenMasterTim** [comment]
Thank you for the clarifications
