### ISSUE TITLE
Driver doesn't recognize my Huion 420

### ISSUE THREAD

**Issue by OwOrigins** [OpenTabletDriver/OpenTabletDriver#2156]
## Description
I installed OTD after hawku's old driver stopped working for no reason and now OTD isn't finding my tablet. I installed Zadig's USB thing on Interface 0 and it didn't changed anything.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Windows 10 Pro         |
| OpenTabletDriver Version 0.6.0.3|
| Huion 420                   |

**Comment by jamesbt365** [comment]
#2139
