### ISSUE TITLE
cursor isn't moving on my veikk a50

### ISSUE THREAD

**Issue by Az-r08** [OpenTabletDriver/OpenTabletDriver#2162]
im using arch linux with kde plasma and a veikk a50
the tablet got detected when i plug it in but it seems like the cursor isn't moving at all
i tried going into the tablet debugger and test it and the blue dot do move, pen pressure doing fine but still the cursor doesnt move on the desktop or even inputting anything
i tried booting up gimp and going in the input devices tabs and the tablet is not detected in there

**Comment by jamesbt365** [comment]
fill out the template properly.

**Comment by jamesbt365** [comment]
I didn't say close it?
