### ISSUE TITLE
Force Aspect Ratio feature

### ISSUE THREAD

**Issue by Naworm** [OpenTabletDriver/OpenTabletDriver#2165]
How can this feature still no exists ?
It is really boring to have to use calculator every time we need to change area

![image](https://user-images.githubusercontent.com/48997616/162073660-7729de40-84e8-4191-ae2c-3abdf47285df.png)

**Comment by jamesbt365** [comment]
? Right click.

**Comment by Naworm** [comment]
Alright thx, it's not really intuitive my bad

**Comment by Naworm** [comment]
@jamesbt365 where's the guide ? I ant see any on website or github

**Comment by jamesbt365** [comment]
Thats because its within the driver itself, it pops up if you don't have a settings file at all, you can retrigger this again by going to `help > open guide`
