### ISSUE TITLE
Huion 420 not being detected

### ISSUE THREAD

**Issue by Vortigern-source** [OpenTabletDriver/OpenTabletDriver#2167]
I am on Windows 11 and my tablet is simply not being recognised, in device manager i can see that "420" is recognised as a keyboard/mouse device and thats probably the problem.

[diagnositcs.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8439117/diagnositcs.txt)

**Comment by jamesbt365** [comment]
#2139
