### ISSUE TITLE
Support Request: Huion HS610 no being detected

### ISSUE THREAD

**Issue by soverte** [OpenTabletDriver/OpenTabletDriver#2169]
# Support Request

## What I've already tried
I was not able to remove WinUsb as this video shows - https://www.youtube.com/watch?v=35-Jz6_TZOc

![winusb uninstall](https://user-images.githubusercontent.com/33137831/162369470-6d966367-e481-49d1-b3ac-0bea1468b59d.png)

I try WinUsbCleanup "No Gaomon/huion driver detected"

## Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8448731/diagnostics.txt)
i also use the string reader with the huion device showed in the diagnostics:
[dump.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8448738/dump.txt)

**Comment by Sublimelime** [comment]
Please fill out the template.

**Comment by soverte** [comment]
> Please fill out the template.

sorry is miss click it, also dont speak english so im triyng

**Comment by jamesbt365** [comment]
Right click the windows logo > device manager > view > device by container > find your tablet > open the container > right click the entries inside > uninstall each of them, once you have done all of them then replug your tablet.

**Comment by soverte** [comment]
> Right click the windows logo > device manager > view > device by container > find your tablet > open the container > right click the entries inside > uninstall each of them, once you have done all of them then replug your tablet.

**Comment by soverte** [comment]
> Right click the windows logo > device manager > view > device by container > find your tablet > open the container > right click the entries inside > uninstall each of them, once you have done all of them then replug your tablet.

thanks dude it works.
