### ISSUE TITLE
Cursor not moving

### ISSUE THREAD

**Issue by Moouncat** [OpenTabletDriver/OpenTabletDriver#2173]
## Description

The cursor isn't moving when I try to use my tablet. It seems like the raw input is recognised but in practical use, the cursor doesnt move an inch. Everything else works (Buttons, pressure etc.)
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10
| OpenTabletDriver Version | v0.6.0.3
| Tablet                   | Wacom CTL-472

**Comment by jamesbt365** [comment]
Close valorant.
