### ISSUE TITLE
Unlocking aspect ratio doesn't work

### ISSUE THREAD

**Issue by fishysquidman** [OpenTabletDriver/OpenTabletDriver#2178]
## Description

Whenever I disable lock aspect ratio it still forces the aspect ratio to 1.7778. I can't figure out any work around for this issue on the current version of the driver.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 x64 |
| OpenTabletDriver Version | v0.6.0.3 |
| Tablet                   | Gaomon S620 |

**Comment by jamesbt365** [comment]
#1957

unlock, save, restart otd.
