### ISSUE TITLE
[DllNotFoundException:Error] Unable to load shared library 'libXrandr' or one of its dependencies

### ISSUE THREAD

**Issue by sigaloid** [OpenTabletDriver/OpenTabletDriver#2180]
## Description
I am getting this error: 
![image](https://user-images.githubusercontent.com/69441971/162824662-8008acbb-be42-49cd-97be-fc74f65d586a.png)

I get this while on X11 in both i3wm and Gnome X11. Notably not on Gnome Wayland probably because of Xwayland. 

I have installed all of the recommended packages with commands like `sudo dnf install libX11 libX11-devel libX11-common libX11-xcb libXrandr libXrandr-devel`, `sudo dnf install libX11-* libXr* libevdev*`, `sudo dnf install libX11-devel libXrandr-devel libevdev-devel`, etc. I believe I have installed every fedora equivalent of the requirements.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |Fedora 35 
| OpenTabletDriver Version |v0.6.0.3
| Tablet                   |Gaomon S620

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8467460/diagnostics.txt)

Note: NOT fixed by the answer at https://github.com/OpenTabletDriver/OpenTabletDriver/issues/1179 despite same symptoms

**Comment by jamesbt365** [comment]
Try making an rpm based off this pr:
https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging/pull/16

**Comment by sigaloid** [comment]
I thought I generated an RPM but then it deleted it: 
![image](https://user-images.githubusercontent.com/69441971/162828419-07169eb9-f296-48e9-bb99-0aca2c8e8b75.png)

Can you explain how to generate it?

**Comment by ken-soares** [comment]
Any update on how to fix the issue?

**Comment by jamesbt365** [comment]
its probably solved upstream, though nobody has generated an rpm off that pr and used it to see.
