### ISSUE TITLE
CTE-450 has wrong ReportParser preventing input

### ISSUE THREAD

**Issue by karelwgonzalez** [OpenTabletDriver/OpenTabletDriver#2186]
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/8e82e1b869cc9f5873cbbf10939b3d1f9b4b574d/OpenTabletDriver.Configurations/Configurations/Wacom/CTE-450.json#L28

CTE-450 Configuration has `ReportParser` set to `.Intuos.IntuosReportParser` but should be set to `.Bamboo.BambooReportParser` for correct operation.

**Comment by jamesbt365** [comment]
Yes? Its fixed in Configs branch.
