### ISSUE TITLE
idk what this is 

### ISSUE THREAD

**Issue by doctrine888** [OpenTabletDriver/OpenTabletDriver#2189]
## Description

it just wont open anymore 
![SharedScreenshot - Copy](https://user-images.githubusercontent.com/103708782/163503392-4273376c-0641-4ca3-b2de-5aac1e0e7392.jpg)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System      windows 10   |
| OpenTabletDriver Version |
| Tablet   xp pen g430s                |

**Comment by jamesbt365** [comment]
If you are experiencing crashing with OpenTabletDriver do this:
- First make sure that there is no Configurations folder if you are using any version higher than 0.5.3.3.
- Delete or move %localappdata%\OpenTabletDriver\settings.json
- Delete or move %localappdata%\OpenTabletDriver\Plugins

Also it is not a good idea to have OpenTabletDriver on the Desktop, its recommended to have it in its own folder, you can make a shortcut from there.
