### ISSUE TITLE
no tablets detected

### ISSUE THREAD

**Issue by cawakali** [OpenTabletDriver/OpenTabletDriver#2191]
[Detect:Info]	Searching for tablets...
[Detect:Info]	No tablets were detected.
[Settings:Info]	Driver is enabled.
[Settings:Info]	Presets have been refreshed. Loaded 0 presets.
[Detect:Info]	Searching for tablets...
[Detect:Info]	No tablets were detected.
[Settings:Info]	Driver is enabled.
[Detect:Info]	Searching for tablets...
[Detect:Info]	No tablets were detected.
[Settings:Info]	Driver is enabled.

huion 420

**Comment by jamesbt365** [comment]
#2139

**Comment by jamesbt365** [comment]
Install zadig then follow that.
