### ISSUE TITLE
Support Request: Not detecting the XP PEN Artist 15.6

### ISSUE THREAD

**Issue by Julian-Heidenreich** [OpenTabletDriver/OpenTabletDriver#2192]
# Support Request

The Tablet is not detected. I use an XP PEN Artist 15.6 and assumed that the entry in the supported list for the 15.6 pro includes mine too.

## What I've already tried

Cleaned up previous drivers.
Restarted my PC.
Reinstalled the Desktop Runtime.
Tryed diffrent USB ports (2.0, 3.0, 3.1)
All from the Official website

## Diagnostic Information

[otddia.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8500040/otddia.txt)
(GitHub doesn't accept json formatted file for upload)

**Comment by jamesbt365** [comment]
Isn't supported in master, but is in configs, let me adjust the configuration real quick.

**Comment by jamesbt365** [comment]
in a minute or 2, a windows action build should be available that will hopefully detect the tablet, however i'm not sure that aux buttons will work yet and have no clue if it will even work correctly with this configuration. Download it from [here](https://github.com/jamesbt365/OpenTabletDriver/actions/runs/2177013101), extract it to its own folder and it should pick up the tablet, if it does go into `tablet > tablet debugger` and get the max x and y coordinates at the bottom right of the tablet, (the visualizer may be incorrect so ignore it). Also check if the buttons work if they are bound.

**Comment by Julian-Heidenreich** [comment]
Ok the Tablet was detected properly and the buttons on the tablet are working too. But I am not sure if the debugger is working right. I open it and nothing is shown. (No device selected and no raw input)

**Comment by jamesbt365** [comment]
try this one. https://github.com/jamesbt365/OpenTabletDriver/actions/runs/2177145944

**Comment by Julian-Heidenreich** [comment]
The debugger works fine now.
The Aux buttons are getting registered in the debugger but I cant bind them in the Auxiliary Settings
Additionally to that the sensitivity of the pen isn't working anymore. That as well is working fine in the debugger but if I open photoshop f.e. it isn't working properly

TY for your help btw :)

**Comment by jamesbt365** [comment]
I still need the max x and y in the debugger (located at the bottom right of the tablet, i need these to be able to assign the correct size to the tablet if it is incorrect, as well as making sure the configuration is accurate), buttons should be in one of the tabs, should bind correctly. Pressure support you have to use a plugin for. Could you verify everything words accordingly?

**Comment by Julian-Heidenreich** [comment]
The max I got was X 34411 and Y 19460

**Comment by jamesbt365** [comment]
Check the tabs for the tablet buttons again, they should be there to bind.

**Comment by Julian-Heidenreich** [comment]
Ok I deserve punishment for not hitting apply after setting the bindings...

**Comment by jamesbt365** [comment]
lmao, all good. Everything work then?

**Comment by Julian-Heidenreich** [comment]
As I see yes. I still try to work out the sensitivity thing but I should get that on my own.
Just a question after that. Will this now go into the master branch after that? And until then I use this version you provided me? or how does this work now?

**Comment by jamesbt365** [comment]
A release will be coming out soon, either today or in the next few days. Once void merges this configuration into configs branch it will be pulled into master when the next version is released so you won't need to use the build anymore.

and for your other question:
https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk

**Comment by Julian-Heidenreich** [comment]
Ah ok it is this Plugin ty :D

Did I see this right you just added the identifier for the 15.6 2 days ago? What an coincidence xD

**Comment by jamesbt365** [comment]
_yep_

**Comment by Julian-Heidenreich** [comment]
Ok thank you so much for the help and have nice eastern ;D
