### ISSUE TITLE
Add support for Gaomon M6 Tablet

### ISSUE THREAD

**Issue by Stehsaer** [OpenTabletDriver/OpenTabletDriver#2198]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer | Gaomon  |
| Product Name | Gaomon M6  |
| Width | 254mm |
| Height | 158.8mm |
| Pressure Levels | 8192 |
| LPI | 5080 |

## Diagnostic Information

[diag.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8505575/diag.json.txt)

**Comment by jamesbt365** [comment]
Tablet > device string reader at the top of otd.

- 9580 top box
- 100 middle
- dump all

save that file and send it here

**Comment by Stehsaer** [comment]
[dump.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8505695/dump.txt)

**Comment by jamesbt365** [comment]
- Download [this](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8505738/M6.json.txt) file
- Make a `Configurations` folder next to the executables of otd.
- Move this file here
- tablet > detect tablet.

**Comment by Stehsaer** [comment]
![image](https://user-images.githubusercontent.com/54050160/163811033-0c44397f-f42c-43a1-8891-aeac1f565863.png)
tablet detected

**Comment by jamesbt365** [comment]
Go into tablet > tablet debugger, get the max x and y coordinates at the bottom right of the tablet. (ignore the visualizer)

while you are there, can you check if the pen buttons work properly in the debugger (there should be 2)

Can you get the max pressure as well by pressing the pen down

Does this tablet have tilt?

How many tablet buttons does this tablet have (not counting pen)?

**Comment by Stehsaer** [comment]
- Position: 
![image](https://user-images.githubusercontent.com/54050160/163811926-830679d8-9ae7-42fd-82cd-419c7fe2cced.png)
- Both pen buttons work well as expected
- Get a max pressure of 8191 when pushed hard against the surface
- The purchasing page of this tablet claims that it has tilt and I can see a significant change in the last 2 values of raw tablet data in the debugger when I tilt the pen at different directions
- It has 13 buttons in total which are arranged as shown:
![image](https://user-images.githubusercontent.com/54050160/163813098-135b214c-b256-4f62-832a-252982af07ca.png)

**Comment by jamesbt365** [comment]
[M6.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8505845/M6.json.txt)
 replace the configuration with this one, it should now have tilt in the debugger if you detect the tablet again, the input of the tablet should work correctly as well.

**Comment by Stehsaer** [comment]
Everything works perfectly except buttons
![image](https://user-images.githubusercontent.com/54050160/163813915-a9710255-1492-4dd3-9d54-e642ac017442.png)
12 out of 13 aux buttons are working, 1 missing
the touch wheel isn't working properly and outputs some combination of buttons when touched. it may be a good idea to temporarily disable it
does OTD support touch wheel?

**Comment by Stehsaer** [comment]
the missing aux button isn't shown in the auxiliary button setting tab
there is only 12 shown
![image](https://user-images.githubusercontent.com/54050160/163814948-cbba36d0-6a6c-4d87-a0d6-d2c18adcee73.png)

**Comment by jamesbt365** [comment]
go back into the debugger, do specific actions with the wheel, get the raw data when it changes.

- What is it when not touched at all
- What is it when the button is pressed
- what happens when you scroll the wheel counter clockwise
- what happens when you scroll the wheel clockwise

**Comment by Stehsaer** [comment]
The wheel doesn't output data saying whether it's rotating or not
Instead, it split itself into 12 different parts, with every part occupies 30 degrees on the wheel
These parts output a combination of aux buttons states when touched
This is how it works

When untouched:
![image](https://user-images.githubusercontent.com/54050160/163821440-d8e9ee5d-7be4-4911-92b0-0eaff463d9c9.png)

When touched, simply split the whole wheel into 12 parts:
![image](https://user-images.githubusercontent.com/54050160/163821760-3f7069ad-0e96-4eb5-baa2-8f601045d22e.png)
Look at the aux buttons states:
![image](https://user-images.githubusercontent.com/54050160/163821822-4f42fa6d-aac7-4875-abac-ddfb5be14aff.png)
Consider the last 4 values as a REVERSED binary number ( False for 0, True for 1 )
In the example above, it's 0b1100, "12" in decimal.
It means that i'm touching the part labeled "12" in the first image.
This rule stays the same when touched the other parts.

It's somehow complicated and I have no idea whether there's existing code in OTD supporting this feature or not.

**Comment by jamesbt365** [comment]
Can i have the raw data though, i would like to compare it to see if it fits along side a parser without breaking anything.

**Comment by Stehsaer** [comment]
When touching part 1:
![image](https://user-images.githubusercontent.com/54050160/163823576-59a0b07f-78d1-4077-8b46-1b27d3608c1a.png)
part 2:
![image](https://user-images.githubusercontent.com/54050160/163823626-15ce1626-a56f-48bb-b0b5-90a47c4db3db.png)
part 3:
![image](https://user-images.githubusercontent.com/54050160/163823676-e5a2bf55-d29a-4184-9abd-2a8da0547f37.png)
part 4:
![image](https://user-images.githubusercontent.com/54050160/163823820-b693a62a-f66f-4f1a-97ce-d038407782ea.png)
part 5:
![image](https://user-images.githubusercontent.com/54050160/163823962-e25d4d71-4d8a-498b-a890-b22f700fd79d.png)

is these enough?
I found that the 6th byte in the raw data also represents the part no. touched

**Comment by jamesbt365** [comment]
What about the button on on the wheel itself?

**Comment by Stehsaer** [comment]
not clicked:
![image](https://user-images.githubusercontent.com/54050160/163824673-dee92ce2-5be6-4eb9-b1bf-a957c0eac350.png)
clicked:
![image](https://user-images.githubusercontent.com/54050160/163824878-186bb784-2268-48a2-b295-f9ad0550dad1.png)
it should be noticed that the last byte in the raw data changes between 01 and FF at a constant pace (about 2Hz) when the button is clicked

**Comment by jamesbt365** [comment]
Can i have the raw data for every button when pressing individually please, starting from the wheel button and moving onwards through the rest.

**Comment by Stehsaer** [comment]
Wheel Center Button:
![image](https://user-images.githubusercontent.com/54050160/163826794-a9a92236-61b0-44a9-b778-e4305464d192.png)

12 buttons below the wheel, counting from the topleft corner, downwards to the bottomright corner
![image](https://user-images.githubusercontent.com/54050160/163827171-b4fcec3a-6dd7-4b06-ba00-407f445cd909.png)

Button 1:
![image](https://user-images.githubusercontent.com/54050160/163827216-5d2da8bc-8690-4070-881a-af16d32769f3.png)
Button 2:
![image](https://user-images.githubusercontent.com/54050160/163827278-af693185-eb39-4fa1-a66a-829c845b85ab.png)
Button 3:
Button 4:
Button 4:

**Comment by Stehsaer** [comment]
Like before, the last byte constantly changes when the button is hold
I guess it's an action of "forced refresh", and it may be ignored

**Comment by jamesbt365** [comment]
When this action run is complete, download the corresponding build, extract it to its own folder and test the features of the tablet. The tablet should now have all 13 buttons. https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/2184781618

**Comment by jamesbt365** [comment]
@Stehsaer can you confirm or not?

**Comment by Stehsaer** [comment]
> @Stehsaer can you confirm or not?

Yes, all feature are complete except the touch wheel.
The touch wheel false triggers other buttons when touched, which could cause some issues.
I suggest disabling the touch wheel

**Comment by X9VoiD** [comment]
Test this build if the issue still exist

https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/2192231712

**Comment by InfinityGhost** [comment]
Pulling this from v0.6.0.4 so we can release.

**Comment by jamesbt365** [comment]
#2203
