### ISSUE TITLE
Debian 11: dpkg error and uninstallable dependancies

### ISSUE THREAD

**Issue by Manga-Man** [OpenTabletDriver/OpenTabletDriver#2231]
# Support Request

Hewwo~ , Im using debian 11 and I keep getting 'E: Sub-process /usr/bin/dpkg returned an error code (1)' whenever I run the sudo apt install -y apt-transport-https command.
Ive tried skipping that error but I get uninstallable dependancy error:

![image](https://user-images.githubusercontent.com/72046004/167176594-f509fe4b-5640-4dbc-a16d-b7f18decf997.png)
![image](https://user-images.githubusercontent.com/72046004/167176839-ca6b6677-301d-4f44-93ec-b4358c786720.png)

## What I've already tried
Ive tried common things like force install and reconfiguring.

**Comment by jamesbt365** [comment]
Shouldn't explicitly be a packaging issue, many people use the .deb on all sorts of versions, this just is a conflicting package issue on your system assuming you actually followed [this](http://opentabletdriver.net/Wiki/Install/Linux#debian) install guide.

Dependencies you must have are (do keep in mind those are probably not the package names for the repository)
- libx11
- libxrandr
- libevdev2
- GTK+3
- (dotnet ofc)

Fix the dependency issues and OTD should install just fine.

**Comment by jxu** [comment]
Holding broken packages means dpkg messed up somewhere so fix that first

**Comment by jamesbt365** [comment]
Unclear if this is an opentabletdriver issue or not, if it isn't please say so i can close this issue if it isn't.

**Comment by InfinityGhost** [comment]
Packaging issues have been resolved AFAIK. Reopen if this is still a problem.
