### ISSUE TITLE
Error code for open tablet driver installation

### ISSUE THREAD

**Issue by tridentlmao** [OpenTabletDriver/OpenTabletDriver#2232]
## Description

so whenever i try to open up open tablet, an error message pops up. and when i press ok or close it, open tablet closes. someone explain how to fix it
## System Information: windows 10

| Name             | Value |
| trident | ----- |
| Operating System   Windows 10      |
| OpenTabletDriver Version  Latest release|
| Tablet       xp pen g640            |
![opentabletbroken](https://user-images.githubusercontent.com/88115303/167278571-8b08b7c1-c745-4b70-8981-041caada55f7.png)

**Comment by jamesbt365** [comment]
The daemon is crashing, remove the settings file in %localappdata%\OpenTabletDriver and also the plugins folder there.

**Comment by jamesbt365** [comment]
Closing due to no response or extra information and from what i can see the solution is above.

**Comment by Jupiterium** [comment]
> The daemon is crashing, remove the settings file in %localappdata%\OpenTabletDriver and also the plugins folder there.
Thanks, this helped. Had an issue with the JSON file, still not sure why it gave me an error, but thank you =)
