### ISSUE TITLE
Cursor teleporting.

### ISSUE THREAD

**Issue by bigfootsundee** [OpenTabletDriver/OpenTabletDriver#2234]
## Description

Even after disabling raw input in osu it still teleporting.
## System Information: 

| Name             | Value |
| ---------------- | ----- |
| Operating System         | windows
| OpenTabletDriver Version | 0.6.0.4
| Tablet                   | VEIKK VK640

**Comment by doubledge-spec** [comment]
Export Diagnostics and upload here.

**Comment by jamesbt365** [comment]
if it is everywhere and not just osu, and file > reset to defaults doesn't fix it then you most probably have another driver installed, the otd console tab should show this.

**Comment by bigfootsundee** [comment]
> 

how do i do that exactly?

**Comment by jamesbt365** [comment]
As you didn't clarify what bit you were replying to i'm assuming mine.
![image](https://user-images.githubusercontent.com/22662856/167322087-4ddf8c18-fd6b-428b-9d34-6a11330665ec.png)
it will say on the first few lines if you do or don't have another driver installed.

If you were after what @doubledge-spec said but didn't mention how then go `help > export diagnostics` save that file as a txt and send it here.

**Comment by bigfootsundee** [comment]
> reply to james

sorry this is really complicated, give me a moment

**Comment by jamesbt365** [comment]
just do the diagnostics and i'll look myself then.

**Comment by bigfootsundee** [comment]
> just do the diagnostics and i'll look myself then.

i cant send txt files

**Comment by jamesbt365** [comment]
Yes you can, make sure its not .txt.json. You'll know if you have file extensions on, if you can't figure that out just zip it quickly because i want to sleep

**Comment by bigfootsundee** [comment]
> 

i just noticed, my bad

**Comment by bigfootsundee** [comment]
> Yes you can, make sure its not .txt.json. You'll know if you have file extensions on, if you can't figure that out just zip it quickly because i want to sleep
[OTD diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8648097/OTD.diagnostic.zip)

**Comment by jamesbt365** [comment]
Uninstall veikk drivers.
```    },
    {
      "Time": "2022-05-08T20:28:46.1865707-04:00",
      "Group": "Detect",
      "Message": "Another tablet driver found: Veikk",
      "StackTrace": null,
      "Level": 2,
      "Notification": false
    },
    {
      "Time": "2022-05-08T20:28:46.1865799-04:00",
      "Group": "Detect",
      "Message": "Detection for Veikk tablets might be impaired",
      "StackTrace": null,
      "Level": 2,
      "Notification": false
    },```

If you don't see them in the apps and features menu, install them, then uninstall them.

**Comment by bigfootsundee** [comment]
> Uninstall veikk drivers.
> 
> ```
>     {
>       "Time": "2022-05-08T20:28:46.1865707-04:00",
>       "Group": "Detect",
>       "Message": "Another tablet driver found: Veikk",
>       "StackTrace": null,
>       "Level": 2,
>       "Notification": false
>     },
>     {
>       "Time": "2022-05-08T20:28:46.1865799-04:00",
>       "Group": "Detect",
>       "Message": "Detection for Veikk tablets might be impaired",
>       "StackTrace": null,
>       "Level": 2,
>       "Notification": false
>     },```
> 
> If you don't see them in the apps and features menu, install them, then uninstall them.
> ```

hm. thought i did that already, ill try and find out how to delete it

**Comment by bigfootsundee** [comment]
> Uninstall veikk drivers.
> 
> ```
>     {
>       "Time": "2022-05-08T20:28:46.1865707-04:00",
>       "Group": "Detect",
>       "Message": "Another tablet driver found: Veikk",
>       "StackTrace": null,
>       "Level": 2,
>       "Notification": false
>     },
>     {
>       "Time": "2022-05-08T20:28:46.1865799-04:00",
>       "Group": "Detect",
>       "Message": "Detection for Veikk tablets might be impaired",
>       "StackTrace": null,
>       "Level": 2,
>       "Notification": false
>     },```
> 
> If you don't see them in the apps and features menu, install them, then uninstall them.
> ```
thanks for helping sleep well. ill reply if i figure it out

**Comment by Sublimelime** [comment]
For the future, it's generally unnecessary/discouraged to quote-reply on github if you're replying to the most recent message, and especially if a conversation only involves two people. If you need to address someone, you can just @ them.
