### ISSUE TITLE
Updater unit tests failing at `Updater_PreventsUpdate_WhenAlreadyUpToDate_Async`

### ISSUE THREAD

**Issue by InfinityGhost** [OpenTabletDriver/OpenTabletDriver#2240]
Unit tests are now failing without any related code being changed.

- https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2238/checks#step:4:38

**Comment by jamesbt365** [comment]
skill issue

**Comment by X9VoiD** [comment]
Resolved by #2243
