### ISSUE TITLE
Auxiliary Buttons configuration not in GUI for HUION 420

### ISSUE THREAD

**Issue by Conando025** [OpenTabletDriver/OpenTabletDriver#2259]
## Description
For some reason the 3 Auxiliary Buttons on the HUION 420 are not configurable through the GUI
Configurations done through the settings json are working

## System Information:
| Name             | Value |
| ---------------- | ----- |
| Operating System         | Linux (Pop_os!) |
| OpenTabletDriver Version | 0.6.0.4 |
| Tablet                   | HUION 420 |

**Comment by jamesbt365** [comment]
The Huion 420 doesn't have buttons...

**Comment by Conando025** [comment]
Oh so then its not detecting right damn

**Comment by jamesbt365** [comment]
Nope, blame the firmware engineers at huion, they fucked it up like they do fuck things up, i'll send a config with buttons on but its huions fault

**Comment by jamesbt365** [comment]
- Make a folder in `/usr/share/OpenTabletDriver` called `Configurations`
- unzip and move the .json there. [420.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8744150/420.zip)
- Replug your tablet.

**Comment by Conando025** [comment]
Oh wow thanks for the quick response, now that i know what the issue is i found the configuration options sorry to bother you again
