### ISSUE TITLE
Updater Error

### ISSUE THREAD

**Issue by M1Ck3yCS** [OpenTabletDriver/OpenTabletDriver#2261]
When im installing the update with the built in updater, it said "Error: RemoteInvocationException 
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Window 10
| OpenTabletDriver Version | 0.6.0.3
| Tablet                   | CTL 480
![image](https://user-images.githubusercontent.com/68963674/169679938-be834b93-c5c8-45aa-834e-44d930ef715e.png)
![image](https://user-images.githubusercontent.com/68963674/169679941-7d36a842-8e49-4937-93f9-5c9537e5cd94.png)

**Comment by joshdee** [comment]
Got that same bug too, it's annoying.

[Windows 11, Gaomon S620]
![image](https://user-images.githubusercontent.com/35825246/169720429-de50ce0a-11cf-42ad-bbc4-19a9b0a30b07.png)

**Comment by jamesbt365** [comment]
Update manually, if it still doesn't work delete `%localappdata%\OpenTabletDriver` make sure all instances of otd are dead then start it again.

**Comment by GabrielSJones** [comment]
James' replay about deleting appdata\otd folder didnt work for me, here's how I was able to get it to work.
1) dl zip of newest install and extract
2) close daemon in task manager (daemon still runs even if you close gui application)
2.5) here i also deleted otd folders in appdata and appdata\temp
3) run new daemon exe first, and it will tell you if it installs properly
4) now running the regular gui app should work and not prompt updates

**Comment by X9VoiD** [comment]
OTD.Updater is no more. F
