### ISSUE TITLE
Infinitely "Connecting to OpenTabletDriver Daemon..."

### ISSUE THREAD

**Issue by UwUham** [OpenTabletDriver/OpenTabletDriver#2267]
## Description

OTD installs and launches fine, but when trying to configure it, the menu will not progress past "Connecting to OpenTabletDriver Daemon...".

Running jobs such as "Detect Tablet" in the menu will return errors such as "Object reference not set to an instance of an object." 

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Arch Linux x86_64 |
| OpenTabletDriver Version | 0.6.0.3-1 from AUR |
| Tablet                   | Wacom Intuos Small |

**Comment by fuomag9** [comment]
same issue here
