### ISSUE TITLE
Support Request: Wacom CTL-472 not detected on MacBook

### ISSUE THREAD

**Issue by softerdrinks** [OpenTabletDriver/OpenTabletDriver#2276]
Basically, I believe it was working a week ago. I updated my laptop to the latest version and all of a sudden no tablet is detected.  I am on mac btw.

[Detect:Info]	Searching for tablets...
[Detect:Info]	No tablets were detected.
[Settings:Info]	Presets have been refreshed. Loaded 0 presets.
[Detect:Info]	Searching for tablets...
[Detect:Info]	No tablets were detected.

**Comment by softerdrinks** [comment]
DId just that. It still does not work

**Comment by jamesbt365** [comment]
Follow the template then.

**Comment by softerdrinks** [comment]
# Support Request
OpenTabletDriver won't detect CTL-472 on MacOS. The current version of my Mac is the latest version 12.4 Monterey. 
![Screenshot 2022-06-01 at 5 55 36 PM](https://user-images.githubusercontent.com/102805708/171378446-b5da2dad-ff09-4e87-a221-9b562d65a99c.png)
![Screenshot 2022-06-01 at 5 55 43 PM](https://user-images.githubusercontent.com/102805708/171378457-fb61ea9a-fecc-40fd-8c3d-ecefa2139744.png)


## What I've already tried
I've tried restarting my computer, unchecking and rechecking Accessibility and Input Monitoring, replugging my tablet in, uninstalling tablet drivers, reinstalling tablet drivers, reinstalling Open Tablet Driver.

## Diagnostic Information
[Untitled.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8813078/Untitled.txt)

**Comment by softerdrinks** [comment]
i moved it but it still doesnt work. here is my diagnosti
[a.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8821727/a.txt)
c

**Comment by sealvessel** [comment]
It works for me. I added it to accessibility and input monitoring. Wait, this is resolved so this is a filler comment. Just saying it worked first time for me. Perhaps there needs to be a dialog on where to click. 
Like this: 
<img width="650" alt="Screen Shot 2022-06-04 at 12 50 24" src="https://user-images.githubusercontent.com/66351949/171983932-78fd64f9-66cb-43d7-9b13-c7b4a2cda725.png">
<img width="660" alt="Screen Shot 2022-06-04 at 12 51 04" src="https://user-images.githubusercontent.com/66351949/171983934-6cd1f467-2762-480a-b1f2-0cc6f8e77843.png">
<img width="648" alt="Screen Shot 2022-06-04 at 12 51 29" src="https://user-images.githubusercontent.com/66351949/171983935-95eaacfb-db8a-4704-9f52-79d371321d6f.png">
<img width="656" alt="Screen Shot 2022-06-04 at 12 51 54" src="https://user-images.githubusercontent.com/66351949/171983937-4654a408-2bf4-4e8b-a879-6b083576cdce.png">
<img width="659" alt="Screen Shot 2022-06-04 at 12 52 45" src="https://user-images.githubusercontent.com/66351949/171983938-aac238a5-127e-4ea7-8c53-419000f1c4ad.png">
<img width="684" alt="Screen Shot 2022-06-04 at 12 53 20" src="https://user-images.githubusercontent.com/66351949/171983940-4d1b3e95-cdf3-4e61-a442-a226e073a4a8.png">
<img width="661" alt="Screen Shot 2022-06-04 at 12 53 52" src="https://user-images.githubusercontent.com/66351949/171983941-b8348ae2-6324-488a-9776-c11ff2440220.png">
