### ISSUE TITLE
macos backspacing until nothingness crashes application

### ISSUE THREAD

**Issue by sealvessel** [OpenTabletDriver/OpenTabletDriver#2287]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         |macos
| OpenTabletDriver Version 0.6.0.4|
| Tablet            ctl472 wacom       |

**Comment by jamesbt365** [comment]
because you didn't fill out the template and explain i'm going to assume the solution is #2248

**Comment by sealvessel** [comment]
Sorry, I edited now to show where enter nothing it crashes. It is in default menu.
