### ISSUE TITLE
MacOS permissions help config file. 

### ISSUE THREAD

**Issue by sealvessel** [OpenTabletDriver/OpenTabletDriver#2290]
## Description
Perhaps a hyperlink in the original README.md for these files for adding permissions. 

Like this: 
<img width="650" alt="Screen Shot 2022-06-04 at 12 50 24" src="https://user-images.githubusercontent.com/66351949/171983932-78fd64f9-66cb-43d7-9b13-c7b4a2cda725.png">
<img width="660" alt="Screen Shot 2022-06-04 at 12 51 04" src="https://user-images.githubusercontent.com/66351949/171983934-6cd1f467-2762-480a-b1f2-0cc6f8e77843.png">
<img width="648" alt="Screen Shot 2022-06-04 at 12 51 29" src="https://user-images.githubusercontent.com/66351949/171983935-95eaacfb-db8a-4704-9f52-79d371321d6f.png">
<img width="656" alt="Screen Shot 2022-06-04 at 12 51 54" src="https://user-images.githubusercontent.com/66351949/171983937-4654a408-2bf4-4e8b-a879-6b083576cdce.png">
<img width="659" alt="Screen Shot 2022-06-04 at 12 52 45" src="https://user-images.githubusercontent.com/66351949/171983938-aac238a5-127e-4ea7-8c53-419000f1c4ad.png">
Press open below. 
<img width="684" alt="Screen Shot 2022-06-04 at 12 53 20" src="https://user-images.githubusercontent.com/66351949/171983940-4d1b3e95-cdf3-4e61-a442-a226e073a4a8.png">
Repeat previous step of adding "Opentabletdriver" below. 
<img width="661" alt="Screen Shot 2022-06-04 at 12 53 52" src="https://user-images.githubusercontent.com/66351949/171983941-b8348ae2-6324-488a-9776-c11ff2440220.png">

**Comment by jamesbt365** [comment]
<http://opentabletdriver.net/Wiki/FAQ/MacOS#cursor-not-moving> + an issue is out on the web repo for adding more to this.
