### ISSUE TITLE
[MacOS] Can't double click even with antichatter

### ISSUE THREAD

**Issue by sealvessel** [OpenTabletDriver/OpenTabletDriver#2291]
## Description
I first tried to click with mouse. It works. 
I then secondly tried to click with mouse while hovering over with pen. It works. 
Then I click myself with tablet pen on tablet, then tried clicking with on-pen button. Does not work. 

Since I tried to click while hovering and it works while steady, then it means that there is something wrong with the left click passing information to operating system. 

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | MacOS 12.4
| OpenTabletDriver Version | 0.6.0.4
| Tablet | Wacom CTL-472

With kuuube antichatter raw 2
1st try: with mouse, 2ndtry: with mouse click+ tablet hover, 3rd try: only with tablet pressing. 
https://user-images.githubusercontent.com/66351949/171984866-b8c160fe-1383-4c46-9427-4ab1bc485f76.mov

With no antichatter hovering with tablet, clicking with mouse
https://user-images.githubusercontent.com/66351949/171984973-e2eee5a3-e356-41fb-b0cf-5b91623fe6d7.mov

No antichatter, clicking with tablet only. 
https://user-images.githubusercontent.com/66351949/171984992-8b450343-e05a-4508-b843-cfa4133ca51d.mov

**Comment by X9VoiD** [comment]
OTD uses MacOS's own APIs for sending left clicks, as seen from [here](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/437f1c25fcc2b24f7846e00615851667a75c044d/OpenTabletDriver.Native/OSX/Input/CGMouseButton.cs#L5) for declaring what to send and [here](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/437f1c25fcc2b24f7846e00615851667a75c044d/OpenTabletDriver.Desktop/Interop/Input/MacOSVirtualMouse.cs#L154) for how it's sent. There are no further variations for this code, and as such the problem lies on either the user clicking too slowly or the operating system.

**Comment by sealvessel** [comment]
> OTD uses MacOS's own APIs for sending left clicks, as seen from [here](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/437f1c25fcc2b24f7846e00615851667a75c044d/OpenTabletDriver.Native/OSX/Input/CGMouseButton.cs#L5) for declaring what to send and [here](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/437f1c25fcc2b24f7846e00615851667a75c044d/OpenTabletDriver.Desktop/Interop/Input/MacOSVirtualMouse.cs#L154) for how it's sent. There are no further variations for this code, and as such the problem lies on either the user clicking too slowly or the operating system.

I have tried kuuube antichatter at option 200, still does not work with tablet clicking. 

https://user-images.githubusercontent.com/66351949/172045531-3d3625ae-2097-485e-b9d8-4bf87495cefd.mov

**Comment by mateowatson** [comment]
I have the same issue I believe. I cannot double click on anything. It just doesn't register as a double click even when double click speed is set all the way low.

**Comment by jamesbt365** [comment]
because macos has to have a separate thing (because its stupid) for double clicking.

**Comment by woutervanwijk** [comment]
So double clicking on MacOS doesn't work at all? (For me indeed not)

**Comment by jamesbt365** [comment]
Yes, as you can see above that is the case.

**Comment by jamesbt365** [comment]
Platform specific options are not currently on the menu, sorry. You can use script runner and an application in the meantime that can send a double click.

**Comment by subfighter3** [comment]
I see, thanks for the quick reply @jamesbt365 
Do you know if the such application exists already? I don't know how to develop a proper script to do that, but if there is an app able to emulate this behaviour. Also, the pan/scroll feature is something really needed, and if it would be possible to emulate with some external app to use with the script runner it would be great

**Comment by subfighter3** [comment]
Opening back this issue because it is not completed at all!
Can somebody post here the necessary scripts to enable double click and possibly the pan feature? Thanks in advance

**Comment by jamesbt365** [comment]
Did you test on the latest 0.6.x branch (which is NOT the latest release)

**Comment by subfighter3** [comment]
not really, but I can't understand from where to download that version for MacOS. 
From Releases I can only download the 0.6.4.0 from the Master branch…

**Comment by subfighter3** [comment]
Yep this is what I did to swap branch, but the Releases link on the right sidebar still refers to the master branch, so how can I download a release from the 0.6.x branch?

**Comment by jamesbt365** [comment]
> Yep this is what I did to swap branch, but the Releases link on the right sidebar still refers to the master branch, so how can I download a release from the 0.6.x branch?

The *releases* section shows *releases* of the driver, they do not update per commit on a branch and there are not different releases per branch. As 0.6.5.0 has not been released, theres no release for the commits past 0.6.4.0 available from 0.6.x yet.


Either download an [action](https://github.com/OpenTabletDriver/OpenTabletDriver/actions?query=branch%3A0.6.x) or compile it yourself.

**Comment by subfighter3** [comment]
Ok thanks for your reply, I see what you mean, sadly I don't know how to compile nor run an action in order to get an executable app :( can somebody run the action and just link here the app?

@jamesbt365 thanks anyway for pointing that out :)

**Comment by jamesbt365** [comment]
> Ok thanks for your reply, I see what you mean, sadly I don't know how to compile nor run an action in order to get an executable app :( can somebody run the action and just link here the app?

I linked you precompiled actions, you just need to click on one.

**Comment by subfighter3** [comment]
Thanks, but nope, I tried some and I can't find builds, just source files. Some older actions has something that looks like builds but they are expired and not downloadable, but also 1 year old so prolly not what I'm looking for

**Comment by jamesbt365** [comment]
Please come down to [our discord server](https://discord.gg/9bcMaPkVAR) if you want extra guidance, support via GitHub is slow and we're just repeatedly hitting peoples inboxes over something that has already been fixed at this point.

If you don't have a Discord account or do not want to join our Discord server, wait until the next release of OpenTabletDriver that will be releasing over the coming weeks.
