### ISSUE TITLE
cannot bind the pen on the GUI

### ISSUE THREAD

**Issue by g1bus** [OpenTabletDriver/OpenTabletDriver#2296]
OS: Endeavor os
Tablet: Wacom CTL-472 

Hey,
I just go the Tablet driver working today, and its great. I just cannot bind the buttons, or the tip of the pen. it appears that i have set the binds, But in testing, it has not varied from the default settings.
I states : [Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: None]@100% ; in the console but there is no affect
I just want to clarify if I'm missing something, or if there is a actual fix for this.
everything else on the GUI works flawlessly.
thanks

**Comment by jamesbt365** [comment]
Fill out the template properly.

**Comment by jamesbt365** [comment]
From your edit i can see that you have a 100% threshold on, this means you have to push the pen **ALL** of the way down for it to activate the binding. Attach a diagnostic as shown in the template or i will not be able to help you further.

**Comment by sealvessel** [comment]
put it on 99% and it may work

**Comment by jamesbt365** [comment]
Closing as it entirely looks like user error and the lack of providing a diag.
