### ISSUE TITLE
Support Request: I cannot bind my pens buttons

### ISSUE THREAD

**Issue by g1bus** [OpenTabletDriver/OpenTabletDriver#2297]
# Support Request

hey, 
Today, I installed the TabletDriver. I cannot bind my pen tip or side buttons. it appears that I'm changing it visually, However this has no affect.
I saw a previous issue about the pen stating that artist mode disables the pen buttons (which is the result i want), its just that it completely disables my ability to click on my mouse, or touch pad.

Heres my console
[Detect:Warning]	Another tablet driver found: Wacom
[Detect:Error]	Detected input coming from Wacom driver
[Detect:Info]	Searching for tablets...
[Detect:Info]	Found tablet 'Wacom CTL-472'
[Detect:Warning]	Failed to find auxiliary device, express keys may be unavailable.
[Wacom CTL-472:Info]	Output mode: Artist Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: Left]@100%
[Settings:Info]	Driver is enabled.
[Settings:Info]	Presets have been refreshed. Loaded 0 presets.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [OpenTabletDriver.Desktop.Binding.LinuxArtistMode.LinuxArtistModeButtonBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Key Binding: A]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Key Binding: A]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [VoiDPlugins.Filter.PrecisionControlBinding]@0%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: Left]@100%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: Left]@100%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: Left]@100%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: Left]@100%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: Left]@100%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: None]@100%
[Settings:Info]	Driver is enabled.
[Wacom CTL-472:Info]	Output mode: Absolute Mode
[Wacom CTL-472:Info]	Display area: [1366x768@<683, 384>:0°],
[Wacom CTL-472:Info]	Tablet area: [127x71.40263@<63.5, 59.29868>:0°],
[Wacom CTL-472:Info]	Clipping: Enabled
[Wacom CTL-472:Info]	Ignoring reports outside area: Disabled
[Wacom CTL-472:Info]	Filters: Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_SMOOTH, Kuuube_s_Chatter_Exterminator.Kuuube_s_CHATTER_EXTERMINATOR_RAW, Pressure_Debounce.Pressure_Debounce
[Wacom CTL-472:Info]	Tip Binding: [Mouse Button Binding: None]@100%
[Settings:Info]	Driver is enabled.

Here's a screenshot
![Screenshot_20220607_210419](https://user-images.githubusercontent.com/107075401/172472347-9d3d18ad-c248-439d-bfeb-e7d30c5ad8d2.png)

**Comment by jamesbt365** [comment]
Guess what, you still missed HALF the template, also don't open another issue for the same problem, also your binding isn't even set
![image](https://user-images.githubusercontent.com/22662856/172472675-2590add9-a5cd-496e-ba91-e2846b9ef7bf.png)

```[Detect:Warning] Another tablet driver found: Wacom
[Detect:Error] Detected input coming from Wacom driver```
also http://opentabletdriver.net/Wiki/FAQ/Linux#ghost-cursor
