### ISSUE TITLE
otd-gui crash when go filters tab with devocubfilters installed

### ISSUE THREAD

**Issue by DaGDNoob** [OpenTabletDriver/OpenTabletDriver#2311]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

Install devocubfilters from plugin manager
go to filters tab and select devocub antichatter

https://youtu.be/I94et4ssk-8 devocub filters only
https://youtu.be/nZn8tqcs4FU with other filters

### Expected Behavior

Show filter options

### Observed Behavior

Gui crashes

### Tablet Device

wacom ctl-480 (But same with other tablets)

### Diagnostic Information

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8904708/diag.txt)

**Comment by jamesbt365** [comment]
likely confusing OpenTabletDriver because of the installing and uninstalling of things, restart the daemon.

**Comment by DaGDNoob** [comment]
It happens upon startup and restarting the daemon doesnt change anything

**Comment by jamesbt365** [comment]
logs from the daemon please

**Comment by jamesbt365** [comment]
Try removing ~/.config/OpenTabletDriver

**Comment by DaGDNoob** [comment]
Same thing happens
[log2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8913532/log2.txt)

**Comment by DaGDNoob** [comment]
fixed for some reason
