### ISSUE TITLE
Add support for Bamboo Pad CTH-301

### ISSUE THREAD

**Issue by fhilipecrash** [OpenTabletDriver/OpenTabletDriver#2312]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Manufacturer

Wacom

### Product Name

CTH-301

### Device Width

141.4mm

### Device Height

166.5mm

### Diagnostic Information

[log.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8934621/log.txt)

**Comment by jamesbt365** [comment]
For ease of reading upload the diagnostic as a txt instead of just pasting it into box, makes reading 10x  easier.

**Comment by jamesbt365** [comment]
download this file, remove the .txt at the end of it then move it to `/etc/udev/rules.d`
[99-opentabletdriver.rules.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8986540/99-opentabletdriver.rules.txt)
after you move it run the following commands

sudo udevadm control --reload-rules
sudo udevadm trigger
systemctl --user restart opentabletdriver

After you do this export a diagnostic again.

**Comment by fhilipecrash** [comment]
Here is the new log
[log.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9034718/log.txt)

**Comment by jamesbt365** [comment]
fixed by #2545
