### ISSUE TITLE
OTD not detecting Huion HC16 (despite system logs detecting it)

### ISSUE THREAD

**Issue by IgnisFlamme** [OpenTabletDriver/OpenTabletDriver#2314]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. start OTD
2. no tablet detected

### Expected Behavior

Tablet should be detected

### Observed Behavior

Tablet is not detected.
Note, the logs show that the tablet was detected and works normally BEFORE installing opentabletdriver which causes it to not work and not be detected. It still outputs the same in the journal so I'm not sure why it isn't detecting it.

18 Jun 2022 14:31:06	acpid	input device has been disconnected, fd 6
18 Jun 2022 14:31:08	kernel	usb 1-9: new full-speed USB device number 11 using xhci_hcd
18 Jun 2022 14:31:08	kernel	usb 1-9: New USB device found, idVendor=256c, idProduct=0064, bcdDevice= 1.12
18 Jun 2022 14:31:08	kernel	usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
18 Jun 2022 14:31:08	kernel	usb 1-9: Product: Huion Tablet_HC16
18 Jun 2022 14:31:08	kernel	usb 1-9: Manufacturer: HUION
18 Jun 2022 14:31:08	kernel	hid-generic 0003:256C:0064.0013: hiddev98,hidraw3: USB HID v1.10 Device [HUION Huion Tablet_HC16] on usb-0000:00:14.0-9/input0
18 Jun 2022 14:31:08	kernel	input: HUION Huion Tablet_HC16 Pen as /devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.1/0003:256C:0064.0014/input/input45
18 Jun 2022 14:31:08	kernel	hid-generic 0003:256C:0064.0014: input,hiddev99,hidraw4: USB HID v1.10 Device [HUION Huion Tablet_HC16] on usb-0000:00:14.0-9/input1
18 Jun 2022 14:31:08	kernel	input: HUION Huion Tablet_HC16 as /devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.2/0003:256C:0064.0015/input/input46
18 Jun 2022 14:31:08	kernel	hid-generic 0003:256C:0064.0015: input,hidraw5: USB HID v1.10 Keyboard [HUION Huion Tablet_HC16] on usb-0000:00:14.0-9/input2
18 Jun 2022 14:31:08	mtp-probe	checking bus 1, device 11: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-9"
18 Jun 2022 14:31:08	mtp-probe	bus: 1, device: 11 was not an MTP device

### Tablet Device

Huion HC16

### Diagnostic Information

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8933067/diag.txt)

**Comment by jamesbt365** [comment]
https://canary.discord.com/channels/615607687467761684/723399565780189234/987661247690457108
