### ISSUE TITLE
Support Request: Veikk a15 not detected

### ISSUE THREAD

**Issue by Mekao48** [OpenTabletDriver/OpenTabletDriver#2317]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

driver not detect my tablet but it in support list

### What have you tried?

i've tried uninstall veikk driver

### Diagnostic Information

[veikk a15.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/8933589/veikk.a15.txt)

**Comment by jamesbt365** [comment]
you still have veikk drivers installed and #2212
