### ISSUE TITLE
OpenTabletDriver not detecting Huion H420 on Archlinux

### ISSUE THREAD

**Issue by cindrmon** [OpenTabletDriver/OpenTabletDriver#2338]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

Assuming you have Archlinux and an AUR helper installed:
1. Install `digimend-kernel-drivers-dkms` using `yay` (or any AUR helper)
2. Install `opentabletdriver-git`
3. Enable user daemon with `systemctl --user enable --now opentabletdriver.service`
4. Restart Computer
5. Launch OpenTabletDriver

### Expected Behavior

It should detect Huion H420 when launching OpenTabletDriver just as on Windows.

### Observed Behavior

It appears as if the tablet is not detected at all, even though it is already plugged in.

### Tablet Device

HUION H420

### Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9035313/diagnostics.txt)

**Comment by jamesbt365** [comment]
User error not a bug. Don't run 2 drivers at the same time.
http://opentabletdriver.net/Wiki/FAQ/Linux#argumentoutofrangeexception
Also set your udev rules up correctly.
http://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams
