### ISSUE TITLE
Support Request for Wacom cintiq 16

### ISSUE THREAD

**Issue by nukeCrayon** [OpenTabletDriver/OpenTabletDriver#2344]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

OpenTabletDriver doesn't detect wacom cintiq DTK1660K0A through wayland.

### What have you tried?

I tried restarting it but it says it doesn't detect cintiq

### Diagnostic Information
[test.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9080049/test.txt)

**Comment by jamesbt365** [comment]
upload the file as a txt please.

**Comment by nukeCrayon** [comment]
[test.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9080046/test.txt)
here.

**Comment by InfinityGhost** [comment]
Bumping, diag was provided but there was never a response.

**Comment by jamesbt365** [comment]
#2384

**Comment by jamesbt365** [comment]
Also rmmod wacom
