### ISSUE TITLE
Support for Wacom CTH-480 Touch Capabilities with Multitouch Features

### ISSUE THREAD

**Issue by kesumin** [OpenTabletDriver/OpenTabletDriver#2360]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

As an addition to the current configuration and the entirety of OpenTabletDriver, I'd like support for touch input for Windows and the configuration of multitouch gestures similar to Wacom's builtin menu: [Wacom Standard Gestures](http://101.wacom.com/userhelp/en/StandardGestures.htm)
I currently use Wacom's CTH-480 and don't have the desk space for my mouse and my tablet. Due to this, I'm now moving my tablet off my mousepad to use my mouse but not both at the same time. Because of this, I'd like to access the touch mode using the physical switch on my tablet with support from OpenTabletDriver.

Thanks for any input on whether you decide to add this feature or not. 
Always appreciate the work put into this project. Again, thank you.

**Comment by jamesbt365** [comment]
#1664
