### ISSUE TITLE
Add support for Deco fun S

### ISSUE THREAD

**Issue by roland3564** [OpenTabletDriver/OpenTabletDriver#2372]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

Since I’m using Nix-OS, installing the official drivers doesn’t seem an option, and  deco fun S is my tablet of choice, please add support to it.

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/182027491-6ea515df-e20b-4db8-8288-b84f34446405.png)
