### ISSUE TITLE
Support Request: Issues while converting wacom tablet area

### ISSUE THREAD

**Issue by byczekfernand7603** [OpenTabletDriver/OpenTabletDriver#2373]
### Acknowledgements

- [x] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

Hello, after i converted my tablet area from Wacom drivers to OpenTabletDrivers my area feels a little bit smaller than with the previous drivers. This happened to me twice: in july 2021 and july 2022 (now).  
![image](https://user-images.githubusercontent.com/110342295/182031307-3be0de3a-99f9-4a74-9a37-bb0a011c3292.png)
![image](https://user-images.githubusercontent.com/110342295/182031323-ea2a7d11-c208-45ce-b178-083b46755f23.png)
I hope my problem is able to be solved.

### What have you tried?

I tried finding help on internet and uninstalling all plugins from OpenTabletDrivers, but it didn't help.

### Diagnostic Information

[nwm.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9229076/nwm.txt)

**Comment by jamesbt365** [comment]
If you used the inbuilt converter by right clicking the area > convert area this is the fact that wacom drivers have inbuilt smoothing so otd feels different because it doesn't.

**Comment by byczekfernand7603** [comment]
okay, thank you for your help ^^
