### ISSUE TITLE
[Linux] Mention in the README that kernel must have CONFIG_INPUT_UINPUT enabled

### ISSUE THREAD

**Issue by RomaVis** [OpenTabletDriver/OpenTabletDriver#2376]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

On Linux, OpenTabletDriver requires _CONFIG_INPUT_UINPUT_ to be set in the kernel configuration for _/dev/uinput_ to be present, which is then used to create virtual input devices via libevdev. On kernels without UINPUT, OTD reports following mysterious error, with tablet being non-operational:
```
[Evdev:Error] Failed to initialize virtual tablet. (error code ENOENT)
```

I think this option should be mentioned in README file in Linux dependencies section, together with any other special<sup>1</sup> kernel options that are required by OTD (that may be discovered in the future by other users).

---

<sup>1</sup> By special I mean options which, although possibly enabled in majority of stock kernels, have a high probability of being left out in custom-configured kernels. UINPUT is a good example:
- Located in an obscure place: `Device Drivers ---> Input Device Support ---> Miscellaneous devices`
- By default it is disabled
- Description reads _"Say Y here if you want to support user level drivers for input subsystem accessible under char device 10:223 - /dev/input/uinput."_ and that doesn't give me a slightest hint as to why I would ever need this
- I've been using two Linux laptops daily in the past 10 years and I never had to enable UINPUT in my custom kernels. Seems LinuxWacom driver stack also doesn't need it

**Comment by jamesbt365** [comment]
The README dependencies are for building from source. At most this should be documented on OpenTabletDriver.Web which i will open an issue on.
