### ISSUE TITLE
Add support for veikk VK430

### ISSUE THREAD

**Issue by kabanery228** [OpenTabletDriver/OpenTabletDriver#2381]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Manufacturer

veikk

### Product Name

VK430

### Device Width

200

### Device Height

150

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Diagnostic Information

[123.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9277519/123.txt)

**Comment by jamesbt365** [comment]
#2227.

**Comment by pp0236** [comment]
it said 'No tablets were detected'
but i have vk430 connected

**Comment by jamesbt365** [comment]
Because its not in the latest version yet, add the configuration from configs branch with a `Configurations` folder next to the executables of otd.

**Comment by pp0236** [comment]
> Because its not in the latest version yet, add the configuration from configs branch with a `Configurations` folder next to the executables of otd.

thanks you, it working now
