### ISSUE TITLE
Fails to detect tablet on Manjaro with the linux519 kernel.

### ISSUE THREAD

**Issue by Solhex** [OpenTabletDriver/OpenTabletDriver#2388]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

To note linux515 and linux518 work perfectly fine.

1. Boot Manjaro with the Linux 5.19.1-2 kernel
2. Install OTD using either of the recommended arch installation guides
3. Open OTD and plug in your tablet (XP-PEN STAR 06 in my case)
4. It should show "No tablets are detected."

### Expected Behavior

The connected tablet should be detected.

A similar end result with linux518
![image](https://user-images.githubusercontent.com/66540788/184817713-ff78cd3a-41dc-402d-9d26-2412a402ae7b.png)

### Observed Behavior

The connected tablet is not detected.

End result with linux519
![Screenshot_2022-08-16_07-54-23](https://user-images.githubusercontent.com/66540788/184817875-9b66f321-c3d1-4ec9-8c7e-7ea2f9bef9f2.png)

### Tablet Device

XP-PEN STAR 06

### Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9348573/diagnostics.txt)

**Comment by SnowLire** [comment]
According to the diagnostic, it seems like while changing kernel, your udev rules and modprobe blacklist got messed up somehow. Follow these steps to [regenerate the udev rules](https://opentabletdriver.net/Wiki/FAQ/Linux#fail-device-streams) and [readd the `hid_uclogic` module to blacklist](https://opentabletdriver.net/Wiki/FAQ/Linux#argumentoutofrangeexception). I would also suggest checking the Console tab when this happen as it usually have the error printed out.
