### ISSUE TITLE
OpenTabletDriver is detecting tablet but when touching with the pen it says "No tablets are detected." | Linux Mint

### ISSUE THREAD

**Issue by noemsus** [OpenTabletDriver/OpenTabletDriver#2396]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

https://streamable.com/ut5tsc# 

### Expected Behavior

It shouldn't show "No tablets are detected." when pressing/dragging with the pen on the tablet.

### Observed Behavior

When you press or drag on the tablet it shows: "No tablets are detected."

### Tablet Device

CTL-480

### Diagnostic Information

[Diagnostic_Information.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9395010/Diagnostic_Information.txt)
,

**Comment by jamesbt365** [comment]
http://opentabletdriver.net/Wiki/FAQ/Linux#ghost-cursor

**Comment by InfinityGhost** [comment]
Closing as there has been no update and FAQ pages provide a solution.
