### ISSUE TITLE
Need support for Huion 1060Pro

### ISSUE THREAD

**Issue by radudek332** [OpenTabletDriver/OpenTabletDriver#2398]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

The driver does not have support for the Huino 1060Pro tablet, I have actually done my research and turns out, 1060Plus and 1060Pro are not the same. Could it be possible to get support for this tablet in a near update?

**Comment by jamesbt365** [comment]
Open an issue with the correct template
