### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by turnheel** [OpenTabletDriver/OpenTabletDriver#2414]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

an error appears me when i update the driver, named "Error: ConnectionLostException" and i have no idea wich means here is the screenshot with the error : [https://imgur.com/a/IAfFLjE](url)

### What have you tried?

i tried unnistalling and reinstalling the driver but nothing happened the same error still here and i have no idea how to fix it 

### Diagnostic Information

la conexion de JSON-RPC con la parte remota se perdio antes de que se pudiera completar la solicitud
  at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type exoectedResultType, CancellationToken cancellationToken)
              at
 StreamJsonRpc.JsonRpc.Invoke.CoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments,
IReadOnlyList`1 positionalArgumentDeclaredTypes
IReadOnlyDictionary`2 namedArgumentDeclaredTypes
CancellationToken cancellationToken, Boolean
isParameterObject
   at OpenTabletDriver.UX.MainForm.CheckForUpdates()
   at OpenTabletDriver.UX.MainForm.<.ctor>b__0_
   0()

**Comment by jamesbt365** [comment]
Delete %localappdata%\OpenTabletDriver. Next time search the existing issues (follow the boxes instead of checking them) first.
