### ISSUE TITLE
Eraser not working

### ISSUE THREAD

**Issue by sharanoth** [OpenTabletDriver/OpenTabletDriver#2415]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

Using the eraser button on a CTH-480/680 pen does nothing

### Expected Behavior

For the eraser to register an input.

### Observed Behavior

The eraser doesnt register any inputs, only detects the pen in proximity.

### Tablet Device

CTH-680

### Diagnostic Information

[test.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9462834/test.txt)

**Comment by jamesbt365** [comment]
From other people with this tablet and pen it does work, either you are using windows ink incorrectly or the wires connecting the pressure sensor on your pen is broken.
