### ISSUE TITLE
Cannot get pressure sensitivity and side buttons to work on OS Monterey

### ISSUE THREAD

**Issue by Sesamme** [OpenTabletDriver/OpenTabletDriver#2424]
I have a Wacom Intuos 4 tablet, that stopped working when I upgraded my Mac to OS Monterey. I installed OTD and it recognizes the tablet, but I don't understand how to get pressure sensitivity to work. 
The other issue is I cannot set up side buttons on the pen. When I try to set pen binding in the Pen Buttons tab, it doesn't react - it doesn't show any side buttons clicks...

**Comment by jamesbt365** [comment]
#2371 

Also use the templates.
