### ISSUE TITLE
windows ink tilt and rotation support

### ISSUE THREAD

**Issue by alkeryn** [OpenTabletDriver/OpenTabletDriver#2427]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

hey would it be possible to add tilt and rotation support to windows ink ?
i know it relies on the vmulti driver (which by default don't support tilt) and i myself modified it to add tilt support, however, i don't have signing certificates
i'd be more than willing to give you my fork of vmulti if in exchange you can sign and release it !

thank you very much !

**Comment by jamesbt365** [comment]
It has tilt and rotation support.

https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk

**Comment by alkeryn** [comment]
realy ?
i saw no mention of it in the plugin code :thinking: 
![image](https://user-images.githubusercontent.com/11599075/190389206-d0633cf1-66c8-41d4-864c-8777253d0f02.png)

**Comment by jamesbt365** [comment]
![image](https://user-images.githubusercontent.com/22662856/190389939-75ee3447-0392-4b27-8262-3e5025583c51.png)
it very much has tilt

**Comment by alkeryn** [comment]
@jamesbt365 thanks !
what file is it though ?
