### ISSUE TITLE
OpenTabletDriver doesn't see Huion 1060Plus

### ISSUE THREAD

**Issue by arlecchinosimp** [OpenTabletDriver/OpenTabletDriver#2432]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

OpenTabletDriver doesn't see Huion 1060Plus

### What have you tried?

I tried to install zadig on interface1, reinstall drivers, reinstall OpenTabletDriver

### Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9634442/diagnostics.txt)

**Comment by jamesbt365** [comment]
Uninstall the huion driver

**Comment by arlecchinosimp** [comment]
> Uninstall the huion driver

Uninstalled, still not detecting

**Comment by jamesbt365** [comment]
Uninstall zadig as well, you aren't meant to have that with this tablet.

If it still doesn't work after get a string dump with 9580 in the top box and 110 in the middle and a string index of 200. If it isn't HUION_T174_6numbers then something is actually wrong.

Closing now due to user error.

**Comment by arlecchinosimp** [comment]
How to get that string? I didn't know how to do that

**Comment by jamesbt365** [comment]
tablet > device string reader.

**Comment by arlecchinosimp** [comment]
Index 1: HUION
Index 2: PenTablet
Index 3: LuoYong70558
Index 200: 왰؀|῿Ꮨః
Index 201: HUION_T167_180808
Index 202: HUION Animation Technology Co.,ltd

пт, 23 сент. 2022 г. в 23:30, jamesbt365 ***@***.***>:

**Comment by jamesbt365** [comment]
All is fine there, it matches a tablet, uninstall zadig and you're good to go.

**Comment by arlecchinosimp** [comment]
[image: image.png]
I already deleted it, have everywhere HIDusb how it was, but still
OpenDriver didn't want to work properly on my laptop, idk what to do. i'm
really sorry for wasting your time...

пт, 23 сент. 2022 г. в 23:38, jamesbt365 ***@***.***>:

**Comment by jamesbt365** [comment]
Care to screenshot that for me?

**Comment by arlecchinosimp** [comment]
[image: image.png]
also deleted in download folder/in windows/inf folder too

пт, 23 сент. 2022 г. в 23:45, jamesbt365 ***@***.***>:

**Comment by jamesbt365** [comment]
You didn't upload an image.

**Comment by arlecchinosimp** [comment]
![image](https://user-images.githubusercontent.com/114240833/192056492-2cd0421c-f601-4506-828d-9526df82ff5e.png)

**Comment by arlecchinosimp** [comment]
or what should i to upload?

**Comment by jamesbt365** [comment]
view > device by container > find your tablet > open the container > screenshot

**Comment by arlecchinosimp** [comment]
![image](https://user-images.githubusercontent.com/114240833/192057392-b2719850-775c-48de-b185-bf0c0391709e.png)
prolly that it is

**Comment by arlecchinosimp** [comment]
![image](https://user-images.githubusercontent.com/114240833/192057441-ea022e4b-6402-43aa-a577-4246839c60c0.png)

**Comment by jamesbt365** [comment]
Sending that twice is not following the instructions, go to view > device by container > find your tablet > open the container > screenshot.

**Comment by arlecchinosimp** [comment]
![image](https://user-images.githubusercontent.com/114240833/192058404-f83a8dfc-1944-4c2d-8158-db636153155e.png)

**Comment by jamesbt365** [comment]
Again, you didn't read. I never asked for ANY right clicking.
![image](https://user-images.githubusercontent.com/22662856/192058527-26d754f8-1be9-4baa-ac7e-7ffe98cbd62d.png)

**Comment by arlecchinosimp** [comment]
![image](https://user-images.githubusercontent.com/114240833/192058632-b572cac9-c506-458c-a08b-f20468009abe.png)
like this? im so freaking stupid, my bad

**Comment by jamesbt365** [comment]
help > export diagnostic, save it with a txt extension and upload it here.

**Comment by arlecchinosimp** [comment]
[diagnostics2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9637166/diagnostics2.txt)

**Comment by jamesbt365** [comment]
Fixed in master.

**Comment by arlecchinosimp** [comment]
> Fixed in master.
What should i do next? I'm dumb

**Comment by Sublimelime** [comment]
Simply wait for the next release. Alternatively, build OTD yourself from the master branch, there's info on how to do this in our contributing.md file.

**Comment by arlecchinosimp** [comment]
Ok, thank you.
