### ISSUE TITLE
Daemon Crashing [Linux]

### ISSUE THREAD

**Issue by Soggy-Pancake** [OpenTabletDriver/OpenTabletDriver#2439]
Trying to launch the daemon in the terminal shows this error message: 
![image](https://user-images.githubusercontent.com/54160598/192362610-47433c59-def0-4760-bbf7-aa181a060a9b.png)

system info (neofetch):
![image](https://user-images.githubusercontent.com/54160598/192362727-efdfe19d-cec7-4c2c-af1a-eae68b2c6d33.png)

**Comment by jamesbt365** [comment]
remove ~/.config/OpenTabletDriver
