### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by fluenwrz** [OpenTabletDriver/OpenTabletDriver#2440]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

 I played with this driver for 4 months and everything was fine, but at one point something happened and smoothing and delay appeared. Tell me, what should I do?

### What have you tried?

 I tried reinstalling windows and changing the driver to another one, but nothing has changed. Now it is very inconvenient to play.

### Diagnostic Information

N/A

**Comment by jamesbt365** [comment]
random smoothing is your brain fucking with you, as it is shown even after a windows reinstall. You'll have to cope until it goes away.
