### ISSUE TITLE
Support Request: Tablet Area Doesn't change after upgrading to windows 11

### ISSUE THREAD

**Issue by JMTTE** [OpenTabletDriver/OpenTabletDriver#2442]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

Tablet Area doesn't change after upgrading from win 10 to win 11
my tablet is cth-480 from wacom

### What have you tried?

1. clicking apply and save button for several times
2. reinstalling driver / clearing caches and registry using program called CCleaner
3. Tried WinUSBCleanup in "Windows FAQ" page but doesn't work because it only supports gaomon/huion
4. disabling windows ink
5. tried installing WinUSB
6. googled existing issues but doesn't help at all
7. reinstalling device through device manager

### Diagnostic Information

[info.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/9685639/info.txt)

**Comment by jamesbt365** [comment]
Updating to windows 11 installed the wacom driver for you. Install it to get the uninstaller then go into apps and features and uninstall it.

Also CCleaner isnt good, don't use it.
