### ISSUE TITLE
Support Request: Installation help on Fedora 36 (KDE X11) No official Installation Instructions.

### ISSUE THREAD

**Issue by SbRhubarbPie** [OpenTabletDriver/OpenTabletDriver#2447]
### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

I need help getting past the connecting to opentabletdriver daemon screen while using fedora (KDE x11). Unfortunately there is no official installation instructions for fedora.

### What have you tried?

I tried installing using this https://discussion.fedoraproject.org/t/cappyishihara-opentabletdriver/36203 although my attempt was unsuccessful after getting stuck on the connecting to opentabletdriver daemon screen, which seems to have documented fixes for most main distros of linux, but not for fedora.

### Diagnostic Information

When attempting to retrieve diagnostics, the following message appears

Error: NullReferenceException

Object reference not set to an instance of an object.
at OpenTabletDriver.UX.MainForm.ExportDiagnostics()

**Comment by jamesbt365** [comment]
#1945 https://github.com/hwsmm/OpenTabletDriver.Packaging/releases/download/test/OpenTabletDriver.rpm
