### ISSUE TITLE
"No frameworks were found" while trying to start.

### ISSUE THREAD

**Issue by I-LEO-CHAN-I** [OpenTabletDriver/OpenTabletDriver#2469]
### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What have you tried?

I tried to install opentabletdriver on two machines (let it be "mach1" and "mach2")

On mach2:
I installed dotnet6 by standart way
- sudo apt install dotnet6

installed opentabletdriver
- sudo dpkg -i opentabletdriver.deb

and tried to start it.

On mach1:
I tried to install opentabletdriver with installation instructions, but get some error;
After that, i deleted (with "apt purge") packages-microsoft-prod.deb and all dotnet packeges
(dotnet-apphost-pack-6.0  dotnet-host    dotnet-hostfxr-6.0   dotnet-runtime-6.0   dotnet-sdk-6.0    dotnet-targeting-pack-6.0    dotnet-templates-6.0   dotnet6)

After that i've done things that i made with mach2.

### What do you need help with?

On mach2 everything is good.

On mach1 i had home errors:

After installing by official instructions:
~$ dotnet --info
A fatal error occurred. The folder [/usr/share/dotnet/host/fxr] does not exist

~$ opentabletdriver
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/usr/share/OpenTabletDriver/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.22.04-x64&apphost_version=6.0.4
  

  
After reinstalling:
~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.110
 Commit:    ce0a42998a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.110 [/usr/lib/dotnet/dotnet6-6.0.110/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

~$ opentabletdriver
You must install or update .NET to run this application.

App: /usr/share/OpenTabletDriver/OpenTabletDriver.UX.Gtk
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/OpenTabletDriver/

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.22.04-x64

Why it doesn't work on mach1? What did i do wrong?

**Comment by jamesbt365** [comment]
#2468
