### ISSUE TITLE
OTD giving me an ms store redirect that doesnt work upon opening

### ISSUE THREAD

**Issue by Brainlit04** [OpenTabletDriver/OpenTabletDriver#2490]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

The tablet driver doesn't seem to open properly as per the instructions provided and shows my an ms store redirect that doesnt go anywhere images provided below, however I am using windows 11 and cannot return to windows 10.

![image](https://user-images.githubusercontent.com/118008415/201388166-15a7933e-3739-428a-bbd1-f44392128d9f.png)

### What have you tried?

I have tried following the redirect, uninstalling and reinstalling as per the instructions provided and I have also unzipped the files as told, however I found that for a while before the most recent update to windows 11 as of me writing this, If i did not unzip the 2 files provided the driver would work just fine however that is no longer the case.

### Diagnostic Information

Cannot launch app, cannot provide diagnostics.

**Comment by jamesbt365** [comment]
Try extracting the archive with a good program like 7zip

**Comment by Brainlit04** [comment]
> Try extracting the archive with a good program like 7zip

This worked, thank you very much.
