### ISSUE TITLE
bar with file, tablets, plugins, and help is missing on windows 11 when no tablet is detected.

### ISSUE THREAD

**Issue by jamesbt365** [OpenTabletDriver/OpenTabletDriver#2516]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

- Open otd when no tablet is plugged in
- no bar

### Expected Behavior

Bar

### Observed Behavior

No bar
![image](https://user-images.githubusercontent.com/22662856/204404890-604c9414-ecd7-4252-96dd-c5a95f561eca.png)

### Tablet Device

N/A

### Diagnostic Information

N/A

No clue if it works on master, but it doesn't work on 0.6.0.4.

**Comment by X9VoiD** [comment]
Closing as it cannot be repro'd anymore.
