### ISSUE TITLE
`OpenTabletDriver` cannot be built on iOS platform

### ISSUE THREAD

**Issue by frenzibyte** [OpenTabletDriver/OpenTabletDriver#2524]
### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. Create a .NET 6 iOS project
2. Add reference to `OpenTabletDriver` package
3. Build project

### Expected Behavior

Project builds successfully.

### Observed Behavior

Project fails building during linking stage:

![CleanShot 2022-12-07 at 23 46 30](https://user-images.githubusercontent.com/22781491/206292039-879a126a-e3e4-4281-9058-5ddce4b5fd8e.png)

---

This is happening as a result of `OpenTabletDriver` referencing `OpenTabletDriver.Native` which includes P/Invokes to the `Quartz` framework. This causes dotnet to attempt including the framework during the linking stage, despite that framework being macOS-only.

I do not intend on requesting `OpenTabletDriver` to have complete support on iOS, only asking for it to at least pass the building stage.

### Tablet Device

–

### Diagnostic Information

–

**Comment by 32-bit-link** [comment]
+1 on this personally. Having OpenTabletDriver support on iOS would be really useful.

**Comment by frenzibyte** [comment]
One solution I can think of would be to move the macOS P/Invokes to a separate project that's referenced by `OpenTabletDriver.Desktop` directly instead, and while it's *somewhat* ugly, it completely fixes the issue for me: https://github.com/OpenTabletDriver/OpenTabletDriver/compare/master...frenzibyte:OpenTabletDriver:separate-macos-pinvokes (@X9VoiD thoughts on this would be appreciated).

**Comment by AkiSakurai** [comment]
There is a workaround on xamarin issues tracker.

https://github.com/xamarin/xamarin-macios/issues/15118#issuecomment-1141893683
