### ISSUE TITLE
Add support for Xp-pen Deco Fun XS

### ISSUE THREAD

**Issue by sodiel** [OpenTabletDriver/OpenTabletDriver#2530]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Manufacturer

XP-PEN

### Product Name

Deco Fun XS

### Device Width

4.8inch

### Device Height

3inch

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

it detects it as xp-pen ct430 and everything works

### Diagnostic Information

[diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10195414/diagnostic.txt)

**Comment by jamesbt365** [comment]
I don't see why this issue is open, the XP-Pen Deco Fun XS is the CT430, which you said it detects as and works. I'm going to close this.
