### ISSUE TITLE
Move "acknowledgements" from issue template further down for Discord webhook readabilitys sake

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#2537]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

This looks terrible:
![image](https://user-images.githubusercontent.com/421345/208191718-62895e89-34b9-4809-800a-6fc6408adb98.png)

**Comment by jamesbt365** [comment]
These should technically be the first things you read while opening an issue, can we really move them without causing extra problems?

**Comment by InfinityGhost** [comment]
They're all required to be checked in the template so there's no useful information there.
