### ISSUE TITLE
Support Request: can not detect tablet

### ISSUE THREAD

**Issue by holahapi** [OpenTabletDriver/OpenTabletDriver#2547]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [x] I have written a concise and meaningful title.

### What do you need help with?

can not detect tablet GM156HD

### What have you tried?

install .net runtime 6.0.12
uninstall gaomon, wacom by Settings app or Control Panel
ran WinUSB.cleanup.script\cleanup.bat

### Diagnostic Information
[otd_diag.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10285022/otd_diag.json.txt)

**Comment by jamesbt365** [comment]
Fixed in #2391. You may take this configurations file and move it into a folder called `Configurations` next to the executables of otd.

**Comment by holahapi** [comment]
> Fixed in #2391. You may take this configurations file and move it into a folder called `Configurations` next to the executables of otd.

thank you~
