### ISSUE TITLE
i dont know how to bind a key on my pen on gaomon s620 because i want to play valorant on i

### ISSUE THREAD

**Issue by iplayfpswithgaomons620** [OpenTabletDriver/OpenTabletDriver#2550]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

i dont know how to bind a key on my pen on gaomon s620 because i want to play valorant on i

### What have you tried?

i tried evrething i reinstalled the driver and i realy did evrething

### Diagnostic Information

i dont know how to bind a key on my pen on gaomon s620 because i want to play valorant on i

**Comment by jamesbt365** [comment]
http://opentabletdriver.net/Wiki/FAQ/Windows#vmulti

Also your issue is confusing as shit. If i'm not understanding what you're saying its not my fault.
