### ISSUE TITLE
XP Pen Incorrect area size

### ISSUE THREAD

**Issue by Hunnus** [OpenTabletDriver/OpenTabletDriver#2560]
### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

Run OpenTabletDriver
Try to use the full area of the Deco 01 v2
It won't work correctly.

### Expected Behavior

Access to the full available area.

### Observed Behavior

Around 75% of the actualy area can be used.

### Tablet Device

XP Pen Deco 01 v2

### Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10314786/diagnostics.txt)

**Comment by jamesbt365** [comment]
This cannot be avoided with the way that otd detects tablets currently. There is other issues regarding this topic with solutions.
