### ISSUE TITLE
Support Request: Star G430S ArgumentOutOfRangeException fix? Device cannot be detected.

### ISSUE THREAD

**Issue by MemeHero** [OpenTabletDriver/OpenTabletDriver#2572]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

I started the application and couldn't detect my tablet (Star G430S). It's a newly bought device and I haven't been on Linux for long, so I'd appreciate any help. Thanks!

OS: EndeavourOS
Kernel: linux-tkg-pds
Session: X11
OTD Version: AUR (v0.6.0.4+19803e0)
Tablet: XP-PEN Star G430S 
![image](https://user-images.githubusercontent.com/70021885/210295668-82dfee75-2976-4b01-92cb-5ef46fb2e709.png)
![image](https://user-images.githubusercontent.com/70021885/210295680-627e8aa6-42bc-4779-bc98-96156a1b50e4.png)

### What have you tried?

I saw this thread, but I'm not sure if this person has the same issue because I can't view the paste. [https://github.com/OpenTabletDriver/OpenTabletDriver/issues/128](url)

### Diagnostic Information

[StarG430S.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10334162/StarG430S.txt)

**Comment by jamesbt365** [comment]
Check for duplicates next time. This is also covered on the wiki. You have the kernel driver loaded.
