### ISSUE TITLE
Update to GTK4 for Linux GUI

### ISSUE THREAD

**Issue by orowith2os** [OpenTabletDriver/OpenTabletDriver#2574]
### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Description

Currently OTD uses GTK3 for the UI on Linux, which is fine, but GTK4 can provide some goodies (such as efficiency) that GTK3 doesn't have.

I'd like to use this issue to track what's needed to update to GTK4, if the work lies in OTD.

Using libadwaita+GTK4 might also be able to be done, and could be better for tweaking the UI in the future (as it's done via .ui files) but just GTK4 would be fine.

**Comment by hwsmm** [comment]
This isn't something that can be done by ourselves since Eto, the GUI library we use, is not supporting GTK4 yet.
I think we will eventually support GTK4 once Eto/GtkSharp starts supporting it, but I doubt it will happen soon enough
