### ISSUE TITLE
Mouse shaking

### ISSUE THREAD

**Issue by cyberbasty** [OpenTabletDriver/OpenTabletDriver#2581]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

i just use open driver normally

https://user-images.githubusercontent.com/82098265/211165095-04291495-e437-4167-b951-927d35bf3ec8.mp4

### Expected Behavior

no shaking

### Observed Behavior

my mouse is shaking a lot

### Tablet Device

Wacom ET-0405-U

### Diagnostic Information

N/A

**Comment by jamesbt365** [comment]
it is a part of physics. Nothing here is a bug.

**Comment by jamesbt365** [comment]
Apply smoothing if you don't like it.

**Comment by cyberbasty** [comment]
> Apply smoothing if you don't like it.

i have an other pc wich didn't has the bug
i use the same tablet for both

**Comment by jamesbt365** [comment]
Then you have some emi caused by devices close by or have some software interfering. As you didn't provide diagnostic information, i cannot help you further on this.

**Comment by cyberbasty** [comment]
diagnostc infos ?

**Comment by jamesbt365** [comment]
Yes.

**Comment by cyberbasty** [comment]
i cant export becuz it's json

**Comment by cyberbasty** [comment]
i cant send becuz it's json

**Comment by jamesbt365** [comment]
Rename it to txt or zip it then.

**Comment by cyberbasty** [comment]
[aaaaaa.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10367090/aaaaaa.zip)

**Comment by jamesbt365** [comment]
not an otd issue then. Refer to what i said above about emi or other software.

**Comment by cyberbasty** [comment]
what's an emi

**Comment by jamesbt365** [comment]
Electromagnetic Interference.

**Comment by cyberbasty** [comment]
Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________
De : jamesbt365 ***@***.***>
Envoyé : samedi 7 janvier 2023 à 19:23
À : OpenTabletDriver/OpenTabletDriver ***@***.***>
Cc : cyberbasty ***@***.***>; Author ***@***.***>
Objet : Re: [OpenTabletDriver/OpenTabletDriver] Mouse shaking (Issue #2581)


it is a part of physics. Nothing here is a bug.

**Comment by cyberbasty** [comment]
![20230107_210137](https://user-images.githubusercontent.com/82098265/211168582-661f3413-5927-40fd-8558-3681b1055785.jpg)

**Comment by cyberbasty** [comment]
is there somethig that's emi ?

**Comment by X9VoiD** [comment]
@cyberbasty This is not a bug in OpenTabletDriver, the hardware itself is weak and so its raw tracking capability. If you want to smooth out your cursor then use any smoothing filters from plugin manager.
