### ISSUE TITLE
High CPU usage after minimizing on "output" tab

### ISSUE THREAD

**Issue by BK8000L** [OpenTabletDriver/OpenTabletDriver#2609]
### Acknowledgements

- [x] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

case 1:
start otd and minimize it

case 2:
start otd, select "filters" tab and minimize it

### Expected Behavior

0% cpu usage in a minimized app that does nothing

### Observed Behavior

case 1:
3% of cpu usage

case 2:
0% of cpu usage

### Tablet Device

ctl-470

### Diagnostic Information

[jason.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10419469/jason.txt)

**Comment by BK8000L** [comment]
only process hacker can detect such cpu usage (calculates it differently)
https://processhacker.sourceforge.io/nightly.php

**Comment by BK8000L** [comment]
Occurs only with "run: minimized" in shortcut properties

**Comment by InfinityGhost** [comment]
@BK8000L Give this [CI build](https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/4410789924) a shot, this should fix it.

**Comment by jamesbt365** [comment]
its not our issue, please do not cross post.

**Comment by BK8000L** [comment]
> please do not cross post

what do you expect since you locked that issue?

> its not our issue

no driver: works fine
wacom driver: works fine
devocub/hawku: works fine
otd: doesn't work properly

**Comment by InfinityGhost** [comment]
Again, that issue is not something within our control and out of scope of this issue. See https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2619#issuecomment-1403804188
