### ISSUE TITLE
OpenTabletDriver cannot detect Huion RTM-500.

### ISSUE THREAD

**Issue by KaikuraF** [OpenTabletDriver/OpenTabletDriver#2612]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [x] I have written a concise and meaningful title.

### Steps to Reproduce

1.Opening OpenTabletDriver.
2.Trying to find my tablet.
3.Tablet not detected.

### Expected Behavior

I expected opentabletdriver to detect my tablet.

### Observed Behavior

OpenTabletDriver didn’t detect my tablet, despite the fact that it is listed as supported.

### Tablet Device

Huion RTM-500

### Diagnostic Information

[Diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10451275/Diagnostics.txt)

**Comment by jamesbt365** [comment]
Not supported in the latest version.

**Comment by jamesbt365** [comment]
You can take the configuration from #2282 and put it in a folder called `Configurations` next to the executables of otd.

**Comment by KaikuraF** [comment]
Thank you so much!

**Comment by jamesbt365** [comment]
Export a diagnostic in the help menu at the top of otd.

**Comment by KaikuraF** [comment]
[Diagnostic1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10452292/Diagnostic1.txt)

**Comment by jamesbt365** [comment]
Plug your tablet in.

**Comment by KaikuraF** [comment]
I connected the tablet, however, an identical error occurs.
[Diagnostic2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10452322/Diagnostic2.txt)

**Comment by jamesbt365** [comment]
Tablet > device string reader
9580
100
201
dump all.

**Comment by KaikuraF** [comment]
[Dump.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10452376/Dump.txt)

**Comment by KaikuraF** [comment]
Oh my God! Thank you very much.
It finally worked!
