### ISSUE TITLE
Cursor stuck in top-left corner, XP-Pen Deco 01 V2

### ISSUE THREAD

**Issue by timius100** [OpenTabletDriver/OpenTabletDriver#2629]
### Acknowledgements

- [x] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. Connect tablet
2. Open OpenTabletDriver

### Expected Behavior

Tablet area matches display area, top-left corner on tablet is top-left corner on display, bottom-right corner on tablet is bottom-right corner on display.

### Observed Behavior

Cursor stuck in top-left part of the display and I can't move it more.
However, if I set width to 127 and height to 79.375 (original X and Y position), and move area to the top-left corner, then tablet area will match display area and everything will work correctly.

Default area settings. What's also strange, is that in the tablet debugger, the dot is in the center, but my pen is actually in bottom-right corner.
![image](https://user-images.githubusercontent.com/74375674/216686677-5077936b-129a-442a-aca9-e6f08090a1b3.png)

Proper area settings
![image](https://user-images.githubusercontent.com/74375674/216687857-e89ed0cb-75fa-4c45-864b-22b01d923645.png)

### Tablet Device

XP-Pen Deco 01 V2

### Diagnostic Information

[OTD_Diagnostics_3-2-2023.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10582039/OTD_Diagnostics_3-2-2023.txt)

**Comment by jamesbt365** [comment]
Top left quadrant only? If so look for duplicates.
