### ISSUE TITLE
OpenTabletDriver can't open a missing preset directory

### ISSUE THREAD

**Issue by jamesbt365** [OpenTabletDriver/OpenTabletDriver#2630]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

- Open OpenTabletDriver
- Go to file > presets > open preset directory
- Nothing happens because the directory doesn't exist.

### Expected Behavior

The folder should be created or a warning should be displayed that the folder is missing.

### Observed Behavior

It doesn't open if the folder is missing.

### Tablet Device

N/A

### Diagnostic Information

N/A

**Comment by gonX** [comment]
"Open preset directory" seems absent from `0.6.3.0`, but can confirm this behavior is still the case on `master` (6c4ffacb91997ef0).
