### ISSUE TITLE
Huion Inspiroy Giano (g930l) not found on windows 11

### ISSUE THREAD

**Issue by MartinSitta** [OpenTabletDriver/OpenTabletDriver#2640]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

Upon starting the driver, it doesnt detect my Huion G930L. Hitting the Detect Tablet button doesnt find the Tablet. Open running the Diagnostics I found out that my device is listed there.
Sorry in advance for my bad english

### What have you tried?

I have used WinUSBcleanup to get rid of potentual remainders of the official Huion Driver Installation.
I followed the FAQ steps related in the windows faq.
As I have not found any information on this problem I was not able to find any information to this problem or simular problems with the Huion g930l products on windows 11.
EDIT NR1: I've tried manually generating the configuration for the device but nothing happened

### Diagnostic Information

[OpenTabletDriver_Diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10769399/OpenTabletDriver_Diagnostic.txt)

**Comment by jamesbt365** [comment]
This wasn't supported in a release when this issue was opened. Fixed in #2604 which is in the 0.6.1 release onwards.
