### ISSUE TITLE
Driver does not work on Visual Studio installer

### ISSUE THREAD

**Issue by Renjian-buchai** [OpenTabletDriver/OpenTabletDriver#2644]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1.  Open Visual Studio Installer. 
1.  Focus on it (i.e. select it)
This only applies to Visual Studio Installer. Visual studio is not affected. 

### Expected Behavior

The tablet driver should track the stylus. 

### Observed Behavior

It does not move. 

### Tablet Device

Wacom CTL 4100

### Diagnostic Information

[a.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10810055/a.txt)

**Comment by jamesbt365** [comment]
OpemTabletDriver runs as the user, the installer for visual studio runs as admin, user applications can't mess with admin applications, this is a security thing.

If you have an absolute requirement to use otd on top of admin apps use the vmulti plugin.
