### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Pr3jn4** [OpenTabletDriver/OpenTabletDriver#2663]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### What do you need help with?

I wanted to ask if you could add EasyPen i405x to supported tablet list, i know the tablet is kinda old and everything but i know couple of people who are using it to play osu, me being one of them, and i just wanted to ask if you could do me that favor.

### What have you tried?

yep

### Diagnostic Information

dasd

**Comment by jamesbt365** [comment]
Already completed in #2238 , you didn't check for duplicates, you didnt use the right template, or follow this one correctly and you don't have a concise and meaningful title.
