### ISSUE TITLE
[Plugin:Error]	Unable to construct object 'OpenTabletDriver.Desktop.Output.AbsoluteMode'

### ISSUE THREAD

**Issue by yue-dongchen** [OpenTabletDriver/OpenTabletDriver#2664]
I'm on Wayland Kubuntu 22.10. The relative mode works, but the above error is given when I switch to absolute or artist mode. The tablet is completely unresponsive.

**Comment by jamesbt365** [comment]
As you decided to ignore the templates, help > export diagnostic, save the file and send it here.

**Comment by yue-dongchen** [comment]
Yeah, my bad. I missed it. Later I ungraded Plasma to 5.26, which has the Wayland drawing tablet kcm. I'll close this as no one else seems to have this problem.

**Comment by sbstratos79** [comment]
Could you please re-open the issue. I am also getting this error. Here's the log:
[otd.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11041253/otd.txt)

**Comment by X9VoiD** [comment]
@sbstratos79 you don't have the same underlying issue. Make sure that the user you're running the daemon from has access to `/run/user/1000/:0`.
