### ISSUE TITLE
Bugged key bindings

### ISSUE THREAD

**Issue by proxer05** [OpenTabletDriver/OpenTabletDriver#2665]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. Add Key binding "Left Bracket" or "Shift+Left Bracket"

### Expected Behavior

It should output "[" or "{"

### Observed Behavior

It output "\" or "|" instead.
On latest CI build([ca6771f](https://github.com/OpenTabletDriver/OpenTabletDriver/commit/ca6771f8f6e074f48f0841db01399cf2a3cb2ab4)) working as expected but plugin support is broken.

### Tablet Device

Huion New 1060 Plus

### Diagnostic Information

[diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11008816/diagnostic.txt)

**Comment by X9VoiD** [comment]
Already fixed in `master` branch.
