### ISSUE TITLE
No input after waking from sleep (linux)

### ISSUE THREAD

**Issue by Agreeable-f** [OpenTabletDriver/OpenTabletDriver#2670]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. turn on pc and log in. (not sure if it is required to plug in the tablet first for this to happen) 
2. put pc to sleep (for me i clicked log out > sleep)
3. turn pc back on and log in

### Expected Behavior

cursor movement from my tablet after waking my pc from sleep

### Observed Behavior

my tablet (ctl 472) detects input shown on the led but my cursor isn't moved on my pc

### Tablet Device

Wacom CTL-472

### Diagnostic Information

OS: Arch Linux
DE: KDE Plasma 5.27.3
WM: Kwin (X11)

[OTD_diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11021439/OTD_diagnostics.txt)

**Comment by Agreeable-f** [comment]
i'd like to say yes. most recent aur package
![image](https://user-images.githubusercontent.com/56764592/226436747-ddb1d066-5b18-4ec3-a9be-eb78feea6bd7.png)

**Comment by jamesbt365** [comment]
Thats not master, that's the latest release. Master is latest git.

**Comment by Agreeable-f** [comment]
doesn't seem to happen on latest master as of this comment but latest master also did this when loading my area
![image](https://user-images.githubusercontent.com/56764592/227071850-e6139a39-e730-4212-bb97-729a9cae42e7.png)

**Comment by Agreeable-f** [comment]
it's also unable to properly load stable's settings.json. just sets everything to either nan or 0

**Comment by X9VoiD** [comment]
> ... but latest master also did this when loading my area

Known issue: #2409

> it's also unable to properly load stable's settings.json. just sets everything to either nan or 0

That's expected for now, master changed settings format.

**Comment by X9VoiD** [comment]
Will close since this is not reproducible on `master`
