### ISSUE TITLE
Relative Mode rotation is not working.

### ISSUE THREAD

**Issue by niksingh710** [OpenTabletDriver/OpenTabletDriver#2690]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

I have the device wacom by one listed as `Wacom CTL-472`

I want use it in a vertical orientation.

try putting it in relative mode with rotation value to `-90deg or 90deg` or any value it will not work

### Expected Behavior

Should rotate the orientation of the tablet input.

### Observed Behavior

remained same no changes were Observer

### Tablet Device

Wacom CTL-472

### Diagnostic Information

For some Reason Github didn't allowed me to put the json txt here
so putting the [log](http://ix.io/4so7)s

[otdlog.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11128970/otdlog.txt)

**Comment by gonX** [comment]
Rotation does work, but it seems broken for the same reason as #2441

Closing as duplicate - fixing that issue will also fix this.
