### ISSUE TITLE
Multi-Key Binding: Control+Shift+Alt+Minus doesn't work

### ISSUE THREAD

**Issue by LEAWIND** [OpenTabletDriver/OpenTabletDriver#2692]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [x] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. Tablet: Huion H320M
2. System: Windows 11 22H2
3. OpenTabletDriver: v0.6.0.4
4. Set Auxiliary Binding 7:
        Multi-Key Binding: (Keys: Control+Shift+Alt+Minus)
5. Set Auxiliary Binding 8:
        Multi-Key Binding: (Keys: Control+Shift+Alt+Equal)
![image](https://user-images.githubusercontent.com/49919003/229337280-d170e747-ef73-4c59-bcce-69929416370d.png)

6. Open OneNote
7. Press the keys on tablet

### Expected Behavior

Zoom out when I press key 7                on   tablet.
Zoom out when I press Ctrl+Shift+Alt+Minus on keyboard.
Zoom  in when I press key 8                on   tablet.
Zoom  in when I press Ctrl+Shift+Alt+Equal on keyboard.

### Observed Behavior

Nothing happened when I press key 7 on tablet.
Zoom out when I press Ctrl+Shift+Alt+Minus on keyboard.
Zoom  in when I press key 8                on   tablet.
Zoom  in when I press Ctrl+Shift+Alt+Equal on keyboard.

### Tablet Device

Huion H320M

### Diagnostic Information

[diag.json.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11131346/diag.json.txt)

**Comment by proxer05** [comment]
Fixed on hotfix https://github.com/OpenTabletDriver/OpenTabletDriver/commit/7adb452dfe72013409fe9efebbe8ea412bfa9b9d
