### ISSUE TITLE
Fetching plugin metadata timed-out. Only local plugins will be shown

### ISSUE THREAD

**Issue by Linkachus17** [OpenTabletDriver/OpenTabletDriver#2709]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

There is no steps to reproduce as I did this on a fresh install of OpenTabletDriver and also fresh install of Windows 11
![Screenshot 2023-04-21 000841](https://user-images.githubusercontent.com/50126684/233440042-a997eff0-a81d-4706-8cfc-d57aba1669f6.png)

### Expected Behavior

Should've open the plugin lists

### Observed Behavior

Instead it throws fetching problem

### Tablet Device

Wacom CTL-472

### Diagnostic Information

[Diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11288800/Diagnostic.zip)

**Comment by gonX** [comment]
This is caused by your computer being unable to reach Github's servers from inside of OpenTabletDriver. Check your firewall and antivirus - it is not something we can solve.
