### ISSUE TITLE
No Mouse Button action works with UGEE S640 on Fedora 38 / XFCE

### ISSUE THREAD

**Issue by polemon** [OpenTabletDriver/OpenTabletDriver#2729]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

In Settings in 'Pen' or 'Auxiliary',

Select 'Mouse Button Binding'
Select whichever button except 'none'

click 'Apply' and 'Save'

### Expected Behavior

Whichever physical button (be it on the pen or any of the auxiliary buttons) should now be bound to the selected mouse button.

### Observed Behavior

No effect.

I checked behavior with `xev` but `xev` also reports no action at all.
The Log tab in the configuration application reports settings have been correctly accepted.

### Tablet Device

UGEE S640

### Diagnostic Information

[report.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11400505/report.txt)

**Comment by jamesbt365** [comment]
You are in artist mode, regular mouse buttons do not work in artist mode unless anything changed in master.

Depending on if anything has changed you either unbind the tip or set a binding using the artist mode bindings.
