### ISSUE TITLE
OpenTabletDiver doesn't save/apply when it's pressed

### ISSUE THREAD

**Issue by Shizara** [OpenTabletDriver/OpenTabletDriver#2735]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

https://github.com/OpenTabletDriver/OpenTabletDriver/assets/132929728/6ba4e27c-ce59-4371-98f5-f7f6fadd8e7e

### Expected Behavior

when i tap the save/or apply button the tablet should only work on one monitor, not both.

### Observed Behavior

even if i set the display to a specified area, i can still move my tablet in the other area, which means that full area will be split.

### Tablet Device

Wacom CTH-680

### Diagnostic Information

N/A

**Comment by jamesbt365** [comment]
Diagnostic information is applicable, please send it.

**Comment by jamesbt365** [comment]
To get rid of the wacom driver follow this part of our wiki: https://opentabletdriver.net/Wiki/FAQ/Linux#ghost-cursor

After make sure you reboot because OTD isn't doing anything at all because you just installed it.

**Comment by Shizara** [comment]
> To get rid of the wacom driver follow this part of our wiki: https://opentabletdriver.net/Wiki/FAQ/Linux#ghost-cursor
> 
> After make sure you reboot because OTD isn't doing anything at all because you just installed it.

solved, thanks
