### ISSUE TITLE
UGEE S640 not detected 

### ISSUE THREAD

**Issue by vSteppY** [OpenTabletDriver/OpenTabletDriver#2782]
### Steps to Reproduce

1. OpenTabletDriver v0.6.03
2. Tablet not immediately detected 
3. CTRL + D to detect tablet nothing happens 

- Fedora 38 + KDE Plasma 5.27.5 
- UGEE Driver not installed 
- OTD installed through these steps: https://discussion.fedoraproject.org/t/cappyishihara-opentabletdriver/36203

### Expected Behavior

UGEE S640 works fine with OTD

### Observed Behavior

UGEE S640 doesnt show up in OTD

### Tablet Device

UGEE S640

### Diagnostic Information

https://haste.pinofett.de/n7uavodgdz.json

### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
"fixed" in #2316.

If you're interested in using it, take the configuration from that pull request and put it in a folder called `Configurations` next to the otd executables.
