### ISSUE TITLE
Support Request: cannot find fakeroot binary error when installing Arch (steamdeck)

### ISSUE THREAD

**Issue by ihastoes31** [OpenTabletDriver/OpenTabletDriver#2788]
### What do you need help with?

trying to use the arch linux installation guide as that is what steamos is based off of, and I didnt use the AUR helper.
first line works properly but when i type in the second line (cd opentabletdriver && makepkg -si) it gives me the error:
==> ERROR: Cannot find the fakeroot binary.

### What have you tried?

have not tried much, dont know where to go from here

### Diagnostic Information

no diagnostics, error before full installation

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Install base-devel or just fakeroot.
