### ISSUE TITLE
Support Request: Yo! i cant download plugin

### ISSUE THREAD

**Issue by CathTheRainboW** [OpenTabletDriver/OpenTabletDriver#2789]
### What do you need help with?

truing to download Reconstructor, any different filters cause same error

### What have you tried?

i tried to clear OpenTabletDriver Temp files, doesent work

### Diagnostic Information

[Plugin:Info]	Installing plugin 'Reconstructor'
[Plugin:Warning]	Plugin 'Reconstructor, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Could not load type 'OpenTabletDriver.Plugin.Tablet.IFilter' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.4, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
[Plugin:Warning]	Plugin 'Reconstructor, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Could not load type 'OpenTabletDriver.Plugin.Tablet.IFilter' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.4, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
Do NOT snip the diagnostics file. You removed information needed to diagnose this issue. I assume you're using OTD 0.7.0.0. No plugins support it yet and this is not an OTD issue.
