### ISSUE TITLE
Make rpm package installable on openSUSE/SUSE

### ISSUE THREAD

**Issue by PhoenixEmik** [OpenTabletDriver/OpenTabletDriver#2794]
### Description

As https://github.com/X9VoiD/OpenTabletDriver/pull/7 mentioned, `libevdev` is `libevdev2` on SUSE (and it is `libevdev` on RHEL/Fedora).
Currently, openSUSE/SUSE users can't install the rpm package directly. Need to use '--nodeps' option to dodge.
```
$ sudo rpm -ivh OpenTabletDriver.rpm
error: Failed dependencies:
        libevdev is needed by opentabletdriver-0.6.1.0-1.fc38.x86_64
```

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
Fixed by #2813
