### ISSUE TITLE
Add support for Parblo N4

### ISSUE THREAD

**Issue by Buzzie3** [OpenTabletDriver/OpenTabletDriver#2812]
### Manufacturer

parblo 

### Product Name

n4

### Device Width

101.6

### Device Height

76.2

### Pressure Levels

8192

### Lines per Inch (LPI)

5080 

### Additional Information

You can add support for parblo n4 without OTD is not pleasant to play on it

### Diagnostic Information

1

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
Duplicate of #2756

**Comment by Keyunge** [comment]
The same problem, down to the pixel

**Comment by Keyunge** [comment]
The same problem, down to the pixel
