### ISSUE TITLE
CTL-472 - Shaking cursor

### ISSUE THREAD

**Issue by removespread** [OpenTabletDriver/OpenTabletDriver#2833]
### Steps to Reproduce

Video demonstration - https://youtu.be/2ZDi1L4eBuI

### Expected Behavior

Expected to work correctly

### Observed Behavior

Curson in system / osu is shaking without reasons.

### Tablet Device

Wacom CTL-472

### Diagnostic Information

[test.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11969977/test.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Its a biproduct of physics and not a bug. If its unbareable increase area or apply antichatter.
