### ISSUE TITLE
Keyboard input not working after sleep

### ISSUE THREAD

**Issue by francois072** [OpenTabletDriver/OpenTabletDriver#2835]
### Steps to Reproduce

1. Put laptop to sleep by closing lid.
2. Open lid and attempt to input login password.
3. Repeat if expected behavior is observed.

### Expected Behavior

Pressing keys on the keyboard should insert the appropriate characters into the login screen text field.

### Observed Behavior

No output is observed in the login screen text field when pressing keys.

### Tablet Device

XP-PEN Deco Mini 7

### Diagnostic Information

[XP-Pen Deco Mini 7 OpenTabletDriver Diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11998176/XP-Pen.Deco.Mini.7.OpenTabletDriver.Diagnostics.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
OpenTabletDriver cannot and never will interfere with normal keyboard strokes.
