### ISSUE TITLE
Modifier keys for buttons

### ISSUE THREAD

**Issue by jonhoo** [OpenTabletDriver/OpenTabletDriver#2836]
### Description

It'd be great to be able to map buttons to modifier + mouse button combos. For example, map auxiliary button 1 to shift + left mouse button!

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Duplicate of #1769.
