### ISSUE TITLE
GUI stuck at "Connecting to OpenTabletDriver Daemon" screen

### ISSUE THREAD

**Issue by user202729** [OpenTabletDriver/OpenTabletDriver#2854]
### Steps to Reproduce

Similar issue: https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2267

In my case, the symptom is different.

* I have `sudo ./bin/OpenTabletDriver.Daemon` run in a separate terminal.
* The daemon does print out `[IPC:Debug]     Connected to a client.` when the GUI starts.
* Exiting the GUI will make the daemon print out `[IPC:Debug]     Disconnected from a client.`.
* The problem fixes itself when the daemon is restarted.

Nevertheless, I believe this is a bug. Next time if I see it, how can I diagnose it (stack trace, etc.)?

### Expected Behavior

-

### Observed Behavior

-

### Tablet Device

Doesn't matter.

### Diagnostic Information

It's impossible to get diagnostic information when the client is not connected to the daemon.

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
*Never* run the daemon as root.
