### ISSUE TITLE
Support Request:  The driver doesn't work with my tablet (Its in the list of the supported tablets)

### ISSUE THREAD

**Issue by Goddesmus** [OpenTabletDriver/OpenTabletDriver#2885]
### What do you need help with?

OpenTabletDriver doens't recognize my tablet wich is the Wacom CTL-6100WL and idk and im new of this type of things and i want some help, the driver just show me my wacom drivers but still unable to recognize my tablet, please help ;c

### What have you tried?

I downloaded .net the latest version and i tried zadig like the page explained but still doens't working

### Diagnostic Information

[Diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/12387058/Diagnostics.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
You have the wacom driver installed.
