### ISSUE TITLE
Support Request: OTD doens't recognize my Wacom CTL-6100WL

### ISSUE THREAD

**Issue by Goddesmus** [OpenTabletDriver/OpenTabletDriver#2888]
### What do you need help with?

OTD just can't detect my tablet 

### What have you tried?

I tried to download .NET and still doesn't working also i tried zadig but still with the issue.
I tried with the wacom drivers and OTD just detect the wacom drivers but not the tablet, i want to use OTD for the less input lag that offers the driver for osu! and i tried also uninstall the wacom driver and still not working.

### Diagnostic Information

[Diagnostics (1).txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/12388728/Diagnostics.1.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
The diagnostic you have provided still shows that you have the wacom driver installed. You should uninstall it, you can do it with this tool here: https://github.com/X9VoiD/TabletDriverCleanup/releases/tag/v4.0.3

And I'm going to close this issue, if you have any further issues, comment on your original issue which is: #2885.
