### ISSUE TITLE
Support Request: Parblo Ninos N7 not detecting

### ISSUE THREAD

**Issue by plyshax** [OpenTabletDriver/OpenTabletDriver#2893]
### What do you need help with?

Parblo Ninos N7 not detecting

### What have you tried?

not detecting

### Diagnostic Information

just not detecting

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Not supported in the latest version, wait until the next release which should happen within the next few days.
