### ISSUE TITLE
Touch not going through on the tablet after opening the drivers. 

### ISSUE THREAD

**Issue by Zoruso** [OpenTabletDriver/OpenTabletDriver#2929]
### Steps to Reproduce

When ever I go to play osu or draw in photoshop my tablet works until I open the drivers. I just wen to go do a GFX request in photoshop and I am unable to start it as my tablet is not registering my touches. 
![Screenshot 2023-09-16 003203](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/103226169/68991025-10bd-43b2-a438-35261df63f5a)

### Expected Behavior

I was expecting to be able to start my drawing request but I was unable to due to this issue. I do not know what is blocking the input from going through as it was working perfectly fine until I opened the driver. 

### Observed Behavior

I do not know why but it says its detecting it however nothing is happening when I go to draw/use the tablet for its intended use. 

### Tablet Device

Gaomon S620

### Diagnostic Information

[Tablet diagnostic info.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/12639769/Tablet.diagnostic.info.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
https://opentabletdriver.net/Wiki/FAQ/Windows#win-ink
