### ISSUE TITLE
Click Doesnt register

### ISSUE THREAD

**Issue by osuaimer** [OpenTabletDriver/OpenTabletDriver#2946]
### Steps to Reproduce

Like the title says clicks dont register, only when im in vmulti relative mode in absolute mode it works fine but when i go to tablet debugger there is pressure registering while in vmulti mode
![tablet debugger](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/95691552/47d42cd1-1d9e-40af-979d-47c4bc12d3c1)

![tablet debugger 2](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/95691552/2f2b0b53-ec61-49d3-939b-a458accfb5b7)
i have tried playing around with tip thresh hold using every number on the slider still nothing

### Expected Behavior

When i press down on my tablet it should left click

### Observed Behavior

nothing happens 

### Tablet Device

Wacom 672

### Diagnostic Information

System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at OpenTabletDriver.UX.MainForm.ExportDiagnostics() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\MainForm.cs:line 641

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by gonX** [comment]
Just to make sure, you're unable to click while using VMulti? If so, you need to change the click bindings to use VMultiMode. See the wiki page on VMultiMode here: https://github.com/X9VoiD/VoiDPlugins/wiki/VMultiMode

**Comment by osuaimer** [comment]
ahhh thank you fixed it
