### ISSUE TITLE
First interaction of a pen with my tablet makes the driver lose detection and throws an error in the daemon.

### ISSUE THREAD

**Issue by Wudanty** [OpenTabletDriver/OpenTabletDriver#2954]
### Steps to Reproduce

1. Open the driver
2. Open wpf gui
3. Looks good
![obraz](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/68469194/b6c4c19e-5d9a-449b-a1d4-f525a4c0d583)
4. After touching my tablet with pen
![obraz](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/68469194/373694fb-06ce-4495-a386-60b273a00de7)
![obraz](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/68469194/b18aa90f-f5a2-4193-9aa3-5b049f45975b)

### Expected Behavior

The detected tablet shouldn't suddenly stop being detected. It shouldn't drop that error either

### Observed Behavior

Last week everything was working as intended. I've been using your driver on the same machine for almost a year now with no issues. I think it started after I downloaded an update. Tried redownloading the driver and still the same issue.

### Tablet Device

Wacom ONE S/CTL-472

### Diagnostic Information

[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/12809212/diagnostics.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Uninstall flip axis, restart OTD, install the plugin again. Running outdated plugins on OTD is not supported.
