### ISSUE TITLE
Wacom CTL-472 glitching when applying pressure to tablet with small area (in osu! lazer)

### ISSUE THREAD

**Issue by yesseruser** [OpenTabletDriver/OpenTabletDriver#2965]
Note: I have reported this to osu! itself and they redirected me to create the issue here.
osu! uses OpenTabletDriver as a dependency.

### Steps to Reproduce

1. Open osu!
2. Make your tablet area smaller than the screen size. (The lower the area, the more the issue becomes observable) - The area aspect ratio is different from the display aspect ratio.
4. Apply pressure to the pen while clicking or dragging.
5. Observe the issue.

### Expected Behavior

The tablet should click normally without the cursor being teleported back and forth.

### Observed Behavior

The cursor seems to be teleported back and forth diagonally.

Here's a short video of how the issue looks:
https://github.com/OpenTabletDriver/OpenTabletDriver/assets/67008763/30aa4e7d-f658-4243-ac42-e86e5669aefe

### Tablet Device

Wacom CTL-472

### Diagnostic Information

Here are the logs that osu! generates:
```
2023-09-10 15:46:50 [verbose]: [Tablet] Detect: Searching for tablets...
2023-09-10 15:46:50 [verbose]: [Tablet] Tablet detected (vid1386), searching for usable configuration...
2023-09-10 15:46:51 [important]: [Tablet] Device: Failed to set device feature: 02-02
2023-09-10 15:46:51 [verbose]: [Tablet] Detect: Found tablet 'Wacom CTL-472'
2023-09-10 15:46:51 [verbose]: [Tablet] Detect: Searching for tablets...
2023-09-10 15:46:51 [important]: [Tablet] Device: Failed to set device feature: 02-02
2023-09-10 15:46:51 [verbose]: [Tablet] Detect: Found tablet 'Wacom CTL-472'
```

### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Could we get a diagnostic with full fat OTD and not just the logs within the game please? I would like to know if this happens outside the game itself. (help > export diagnostics > save that file and send it here)

**Comment by gonX** [comment]
Reading the original discussion linked in the osu issue, it seems to me like you are already using the stock driver. Disabling either the stock driver (e.g. by installing OpenTabletDriver) or disabling the tablet driver in Lazer should fix your issue.

The error `Device: Failed to set device feature: 02-02` is usually caused by the tablet already being initialized by another driver.

**Comment by yesseruser** [comment]
@gonX's solution seems to have fixed it.
