### ISSUE TITLE
vk640 graphics  tablet button not working (pen button working), and pen presser dont work 

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [OpenTabletDriver/OpenTabletDriver#2969]
### Description

vk640 graphics  tablet button not working,
actually i am not sure is it a bug or feature not included there is only pen setting option 
and options are 
![graphics2023-10-20_18-11](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/121858831/5f0b2f0d-d395-4a3e-88df-0860aa970731)

 pen presser dont work 
i have tried a lot of plug in and expecting maybe it will fix my issue but didnt work at all 

![zz2023-10-20_18-12](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/121858831/4821bca7-477b-4295-ad15-3acec725176a)

i know its disable bcz it dont work so i put it disable 

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by View-my-Git-Lab-krafi** [comment]
even though if developer dont have plan to include those feature just tell me how can try to do that  by myself give me some other graphics tablet programming example

**Comment by jamesbt365** [comment]
OTD version?

**Comment by jamesbt365** [comment]
Looking back on the code this was added over a year ago at this point. Update to the latest version of OTD. This was fixed way back in #2294.
