### ISSUE TITLE
OTD Backport "can't be loaded and is likely out of date"

### ISSUE THREAD

**Issue by minisat0shi** [OpenTabletDriver/OpenTabletDriver#2976]
### Steps to Reproduce

Drag and drop OTD Backport zip into the pugin manager - you'll see it show up and uninstall button become actionable. However nothing further happens. Viewing the console, I get the error in the title. Though it thinks it is Version 1.0.0.0, even though from github I am downloading 1.0.6. I have tried 1.0.5 as well, same exact error.

### Expected Behavior

OTD Backport to install properly

### Observed Behavior

OTD Backport does not install

### Tablet Device

H420x

### Diagnostic Information

[diogs.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13062048/diogs.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
OTD.backport is designed to backport changes from 0.6.x to **0.5.3.3** if you read the notes surrounding the plugin. You are on **0.6.3**.

The plugin failed to load because its not compatible with the version of OTD you are on, remove it, there is also nothing to backport because you are on the latest version.
