### ISSUE TITLE
Wiki is missing installation instruction for rpm-based distributions

### ISSUE THREAD

**Issue by RDKRACZ** [OpenTabletDriver/OpenTabletDriver#2985]
https://opentabletdriver.net/Wiki/Install/Linux has no mention of a package for Fedora/openSUSE but it does exist https://github.com/OpenTabletDriver/OpenTabletDriver/releases/download/v0.6.3.0/OpenTabletDriver.rpm

**Comment by jamesbt365** [comment]
Wrong repository for web issues, and a duplicate of ones on the right repository that already exist. See OpenTabletDriver/OpenTabletDriver.Web#105 and OpenTabletDriver/OpenTabletDriver.Web#115
