### ISSUE TITLE
Question - Should I use this program if my tablet works fine with the kernel driver?

### ISSUE THREAD

**Issue by RDKRACZ** [OpenTabletDriver/OpenTabletDriver#2986]
I'm asking this question because I did not find much information in the FAQ section.
I have Huion 580x and I'm using it on Fedora 38. It worked out of the box. Is there any reason to use this tool?

What is the difference between the "Absolute mode", "Artist mode" and "Relative mode"?

The "output" tab in the GUI is missing a "reset" button in case I fuk thing up.

**Comment by X9VoiD** [comment]
1. Unified interface, extensive configuration.
2. Absolute Mode - absolute positioning
Relative Mode - relative positioning
Artist Mode - Absolute Mode with pressure support (and more)
3. File -> Reset Settings
