### ISSUE TITLE
Tablet Support CTC6110WL

### ISSUE THREAD

**Issue by chbya** [OpenTabletDriver/OpenTabletDriver#2993]
### Description

https://estore.wacom.com/en-de/wacom-one-pen-tablet-ctc-hm.html
^^
link to tablet idk

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
All tablet configuration requests should use the configurations template and this is fixed within #2902

**Comment by gonX** [comment]
Fixed by #2902 (backported in #3022)
