### ISSUE TITLE
Unable to bind mouse click to any pen button on XP-Pen Deco 01 v2

### ISSUE THREAD

**Issue by Anseryde** [OpenTabletDriver/OpenTabletDriver#2996]
### Steps to Reproduce

1. Using a XP-Pen Deco 01 v2 on NixOS, bind the right/left mouse click to any pen button
2.  Switch to Artist Mode
3. Open an art program like Krita

### Expected Behavior

Inside Krita, clicking the pen button assigned to right mouse click should open the pop-up palette assigned to right mouse click by default in Krita.

### Observed Behavior

Inside Krita, clicking the pen button bound to right mouse click fails to open the pop-up palette assigned to right mouse click in Krita, but other bindings that were not to left/right mouse click on the pen buttons such as forward slash to switch between previous brush and current brush quickly work just fine. Right mouse click bound to pen button suddenly works when using any other mode such as Absolute  Mode or Relative Mode, but this is not ideal as pressure sensitivity is unavailable in those modes.

### Tablet Device

XP-Pen Deco 01 v2

### Diagnostic Information

[diagnostics.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13315136/diagnostics.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by X9VoiD** [comment]
Mouse bindings does not work with `Artist mode`, use artist mode pen bindings instead.
