### ISSUE TITLE
Add support for Viewsonic Woodpad PF1030

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#3040]
PF0730 was added in #1450, this one should be easy.

### Discussed in https://github.com/OpenTabletDriver/OpenTabletDriver/discussions/2718

<div type='discussions-op-text'>

<sup>Originally posted by **differentpieces** April 26, 2023</sup>
There is pf0730 in the list of supported tablets, but not pf1030. Is there a possibility to add it?</div>

**Comment by jamesbt365** [comment]
Fixed by #2620.
