### ISSUE TITLE
Support Request: for UGEE S1060 and S1060W

### ISSUE THREAD

**Issue by xKRISTOFx** [OpenTabletDriver/OpenTabletDriver#3053]
### Description

Those are analog tablets to UGEE S640. They use one driver from producer's page, only difference is that they are bigger and have 2 more action buttons. There also is version S640W, which as with bigger brother is wireless analog. I'm in need using Open source driver because producers driver doesn't support 2 tablet setup and I have 32:9 monitor, so I need two.

### Acknowledgements

- [X] I am on the latest version of OpenTabletDriver.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
We cannot support tablets without the relevant information. Please open another issue using the **configurations** template, not the enhancement template, or post the relevant information on that template here and I'll reopen this issue.
