### ISSUE TITLE
Huion KAMVAS Pro 13 (2.5K) Missing Device String

### ISSUE THREAD

**Issue by J05HM0N5TER** [OpenTabletDriver/OpenTabletDriver#3069]
### Steps to Reproduce

1. Connect Huion KAMVAS Pro 13 (2.5K) to computer
2. Wait for device to be detected
3. It never connects, it says it is missing devices.

### Expected Behavior

1. Connect Huion KAMVAS Pro 13 (2.5K) to computer
2. Wait for device to be detected
3. Device connects and works correctly.

### Observed Behavior

1. Connect Huion KAMVAS Pro 13 (2.5K) to computer
2. Wait for device to be detected
3. It never connects, it says it is missing devices.

### Tablet Device

Huion KAMVAS Pro 13 (2.5K)

### Diagnostic Information

The debug information just listed trying to detect my device against all the configurations, but I figured that was not worth putting here because I have already worked it out. I just don't know the way that your workflow works to commit the changes.

I changed [DeviceString in Kamvas Pro 13 (2.5k).json](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/da80f70893c01d407e4fa0633c4ea9508c77d5e4/OpenTabletDriver.Configurations/Configurations/Huion/Kamvas%20Pro%2013%20(2.5k).json#L30C15-L30C15) to `HUION_M213_\\d{6}$` instead (changing a single character 0→3) and it detected the device correctly. I also tried copying the existing block in `DigitizerIdentifiers` and changing only one of them, and it worked correctly after I built and ran it.

I found this out by placing a breakpoint at `OpenTabletDriver/Driver.cs:93` on the correct device and seeing where the logic didn't match up.

There are a few other problems I have currently, I will list them here, but they might belong better in separate issued, just tell me if that is the case, and I'll move them and include any diagnostic info that is relevant.

1. The screen output selector needs to be set to the size that encompasses both screens I have plugged in (4480x1600), which is the height of the tablet, but the witch of the tablet + my 1080p monitor. This is because if I have it set to only the size of one screen, then it squishes the tablet area so it only covers one half of one screen. This might be a wayland problem, but I don't see any other issues for it, so it might be specific to this device.
2. The tilt of the pen goes the opposite way it is meant to in Krita, I have not tried any other software, but there is no option to reverse it in there anyway, so I figured it was a driver problem.

System Information:
OS: Arch linux
Version: 0.6.3.0-3, git: da80f70893c01d407e4fa0633c4ea9508c77d5e4 manually built and run. The git version is what I used to modify it, but the bugs were on both.
Desktop manager: KDE Plasma, Wayland

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Feel free to submit a pull request with the string addition.

**Comment by jamesbt365** [comment]
> May I ask what you mean by that?

Either have plasma select every display, or OTD select every display, if you don't have your displays in a square configuration this may not be possible, but I also don't think its possible for you to disable plasma messing around with tablets nicely either. 

> Is there some configuration I can set to make the tilt direction reversed?

No, see #1841 (better solution is needed than parser reversal)

If possible I would prefer this string change be submitted ASAP as we plan on releasing a new hotfix release soon. The string is from the device, so if that is what you get from the device string reader when requesting string 201 (which is what OTD is doing when checking the string anyway, meaning that if it is detecting, its right and no need to check further) then submit this change, no need to dig into logs.
