### ISSUE TITLE
Add support for Wacom CTC6100WL

### ISSUE THREAD

**Issue by WRLNH** [OpenTabletDriver/OpenTabletDriver#3101]
### Manufacturer

Wacom

### Product Name

CTC6100WL

### Device Width

216

### Device Height

135

### Pressure Levels

4096

### Lines per Inch (LPI)

2540

### Additional Information

This tablet also features bluetooth 5.1 connection

### Diagnostic Information

[opentab.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13628147/opentab.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Duplicate of #2993

Fixed by #2902
