### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by FranBatti** [OpenTabletDriver/OpenTabletDriver#3110]
### What do you need help with?

My tablet does not reach 1000 Hz polling rate, unless I use some smoothing filter (I want it to reach 1000 natively)
![image_2023-12-17_144849114](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/105406179/fdca022f-6274-474c-852a-ac3f5e731e33)

### What have you tried?

Sin tener ningún filtro de suavizado activo, logré tener una frecuencia de sondeo de 130 Hz. Y cuando uso el filtro Hawku o el filtro Devocub, puedo alcanzar los 1000 hz.

Me gustaría poder alcanzar una tasa de sondeo de 1000 Hz de forma nativa, sin utilizar ningún filtro suavizante.

### Diagnostic Information

[OTD diagnostic.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13697208/OTD.diagnostic.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
You can't reach 1000 natively, your tablet does not poll at 1000hz. No tablet does.
