### ISSUE TITLE
Support new tablet

### ISSUE THREAD

**Issue by Wei1710** [OpenTabletDriver/OpenTabletDriver#3126]
### Description

I will like so opentabletdriver also support this tablet: Wacom One (2023) 

ressource link:
https://estore.wacom.com/en-us/wacom-one-pen-tablet.html?Top=ACK44929GZ&Base=ACK44930GZ&Cable=ACK45006Z&Choose%20Tablet=CTC6110WLW1A

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by hwsmm** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.6.4.0

**Comment by hwsmm** [comment]
CTC-4110WL and CTC-6110WL are the new Wacom One

**Comment by X9VoiD** [comment]
Already supported
