### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by Wei1710** [OpenTabletDriver/OpenTabletDriver#3127]
### Description

I want so on windows, opentabletdriver can be dark mode instead of the white.

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Duplicate of #1245 and #1740. Instead of simply ticking a box, save us both some time and get the answer you are looking for without opening duplicates. This is also resolved in #2772.
