### ISSUE TITLE
Wrong Tablet Area Bug

### ISSUE THREAD

**Issue by mycustomusername** [OpenTabletDriver/OpenTabletDriver#3135]
### Steps to Reproduce

1. Open driver
2. Check if there is a bug
I dont deal with this bug every time I open the driver, but it happened a lot of times before

### Expected Behavior

Almost Full Tablet Area

### Observed Behavior

Wrong Tablet Area. like 2/3 of area that I want to work with

https://github.com/OpenTabletDriver/OpenTabletDriver/assets/100908480/34fcb58d-36ac-41a8-afdf-a8efc7ca0cdb

### Tablet Device

Wacom CTH-480

### Diagnostic Information

N/A

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Diagnostic information is extremely useful in circumstances like this, please provide it.

**Comment by mycustomusername** [comment]
[bug.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13766145/bug.json)

my desktop resolution is 1680x1050 and my osu game is running on 1280x800
i figured out that if opentabletdriver load while osu is an active window, it changes area size to fit in-game resolution. 

driver looks like this if i alt tab then
![1](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/100908480/19891688-287d-4cf4-a564-e27a29bac760)

and if i drag display area it turns to this. expected to have area that i set
![2](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/100908480/197f0b36-22d5-478e-a2d8-64887ca4151f)

**Comment by jamesbt365** [comment]
OpenTabletDriver is unaware of display resolution changes, see #1143
