### ISSUE TITLE
When my pen goes into the hover distance, the cursor teleports

### ISSUE THREAD

**Issue by MalAllie** [OpenTabletDriver/OpenTabletDriver#3160]
### Steps to Reproduce

2. Enable Relative Mode in OpenTabletDriver
3. Put your pen in hover distance
4. Put your pen out of hover distance
5. Put your pen in hover distance again. It should teleport based on how far your pen is from the last time your pen exited out of hover distance

https://github.com/OpenTabletDriver/OpenTabletDriver/assets/155217642/4131cd93-9897-44ce-a06d-7dd851538303

### Expected Behavior

The pen stays there and moves where the pen is going

### Observed Behavior

The pen teleports, but the cursor doesn't. I'm using my drawing tablet for fps games. So, my camera teleports and I can't move my camera to see what is behind me. 

### Tablet Device

Huion NEW 1060 Plus (8192)

### Diagnostic Information

[Diagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13797330/Diagnostic.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by X9VoiD** [comment]
Not a bug, tablet debugger shows raw data. Use VMulti Relative Mode for FPS games. They don't accept regular relative mode. There's also no jumping on the OS cursor like what you've recorded here as expected from relative mode.
