### ISSUE TITLE
Support Request: pen tip and buttons not registering 

### ISSUE THREAD

**Issue by bobmango26** [OpenTabletDriver/OpenTabletDriver#3181]
### What do you need help with?

I have a Wacom CTL-4100WL and have set up open tablet driver without fail so far. however when i went to click any button including tap my pen on the screen the tap doesn't register.

### What have you tried?

I have tried: restarting my computer, unplugging tablet etc. I have also tried to remap my buttons and that didn't work. When debugging the drivers clearly show that the pen is producing pressure of up to 4096. Does anyone know how to fix this?

### Diagnostic Information

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13954675/diag.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
You must set up vmulti correctly:
https://github.com/X9VoiD/VoiDPlugins/wiki/VMultiMode
