### ISSUE TITLE
Add support for Huion HST640

### ISSUE THREAD

**Issue by FloatingMind12** [OpenTabletDriver/OpenTabletDriver#3183]
### Manufacturer

Huion

### Product Name

HST640

### Device Width

160mm

### Device Height

102mm

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

The tablet seems to be a rip-off version of Huion HS64 as they are entirely similar

### Diagnostic Information

[hst640.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13969497/hst640.txt)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
tablet > device string reader
9580
110
dump all, upload that file here.

**Comment by FloatingMind12** [comment]
Which number goes where?
There are DeviceID, ProductID and String Index

**Comment by jamesbt365** [comment]
The numbers are in order of which you need to place them and you don't need an index because you are dumping *all* indexes.

**Comment by FloatingMind12** [comment]
But nothing happens when I press Dump All

**Comment by jamesbt365** [comment]
The dumping processes takes a while on some tablets. Give it a few minutes, if it still doesn't prompt you to save a file, send a request for index 200 and 201.

**Comment by FloatingMind12** [comment]
Here is the file
[dump.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13969812/dump.txt)

**Comment by jamesbt365** [comment]
[HS64.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13970205/HS64.json)
place this in `~/.local/share/OpenTabletDriver/Configurations` (you need to create this directory), then replug your tablet and go into the tablet > tablet debugger.

Get the max x and y when moving your pen to the bottom right of the debugger, get the max pressure as well and check if the pen and tablet buttons go to true when you press them.

**Comment by FloatingMind12** [comment]
Max X: 32000
Max Y: 20400
Max Pressure: 8191
Pen Buttons work fine
About tablet buttons: there's nothing written about them in the tablet report section but some text that I couldn't catch flicker there when I press them

**Comment by jamesbt365** [comment]
TIP: If you dont have your pen on the tablet you can see the aux reports better.

**Comment by FloatingMind12** [comment]
Everything works, thanks for the support

**Comment by FloatingMind12** [comment]
I don't know if I should continue it here or post a new issue but I have encountered an issue where the cursor get stuck when I resize brush in krita.
I don't know if it's krita related but it worked with huion legacy driver
The huion legacy driver lags a lot so it's not an option

**Comment by jamesbt365** [comment]
How are you resizing the brush?

**Comment by FloatingMind12** [comment]
Shift + Drag
