### ISSUE TITLE
Devocub Filters can't work

### ISSUE THREAD

**Issue by baicai492** [OpenTabletDriver/OpenTabletDriver#3186]
### Steps to Reproduce

1.set to vmulti relative mode
2.enable devocub filters plugin
3.pick up the pen and place it

[video.mp4](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/45510274/b4506b94-1be2-4c6d-9cdf-f56d260277ce)

![problem](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/45510274/59a12f07-7596-4a0e-b19b-efe0c7c14972)
![problem2](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/45510274/fc6964f8-12da-416c-bfc8-32fe361b948d)

### Expected Behavior

When I set it to relative mode, enabling the Devocub Filters plugin and achieve the effect that when I pick up the pen and place it, the cursor doesn't teleports.

### Observed Behavior

When I set to relative mode and have the Devocub Filters plugin enabled, I pick up the pen and place it, it goes back to the previous position and the cursor teleports to a different location, but when I disable the Devocub Filters plugin it has the desired effect.

### Tablet Device

Gaoman M6

### Diagnostic Information

[1.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13991307/1.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Closing on behalf of an issue on the repository containing the filters.
