### ISSUE TITLE
Support Request: cursor is flying all over the place

### ISSUE THREAD

**Issue by expect4tion** [OpenTabletDriver/OpenTabletDriver#3190]
### What do you need help with?

my cursor is just flying all over the place and i dont know how to fix it i use wacom ctl 472

https://github.com/OpenTabletDriver/OpenTabletDriver/assets/143913335/09228579-40e5-4a3d-939d-c49748a9ddff

### What have you tried?

i tried restarting the driver my computer

### Diagnostic Information

```[asdasdasd.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14055796/asdasdasd.json)```

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
`sudo rmmod wacom` then rebuild initramfs if it happens again on reboot.

The troubleshooting steps are on our website at https://opentabletdriver.net/
