### ISSUE TITLE
Undetected Huion H430P with error "Cannot create device for 'long hexadecimal stuff'"

### ISSUE THREAD

**Issue by M-TTI** [OpenTabletDriver/OpenTabletDriver#3211]
### Steps to Reproduce

Plug the tablet, open OpenTabletDriver. (I am running on windows 10)

### Expected Behavior

the tablet should be detected and you should be able to acces your tablet settings.

### Observed Behavior

The tablet isnt detected, no matter if i unplug and replug it.
This is the console right after openning the driver's app.
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/47825688/ff90adc0-4255-4cf0-98e3-73726a05e4a5)

Now this is after a quick unplug/replug
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/47825688/bb22b771-edb1-4d54-9081-51065765c9c8)

This is after pressing CTRL + D
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/47825688/b91e5d3f-d79f-42b2-a750-07ae03aee741)

### Tablet Device

Huion H430P

### Diagnostic Information

[opentabletdriver_diagnostics.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14239850/opentabletdriver_diagnostics.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
You have another driver installed, this is not a bug.

Run TabletDriverCleanup, its on our wiki.
