### ISSUE TITLE
Add support for Huion RTS-300

### ISSUE THREAD

**Issue by BetaRibut** [OpenTabletDriver/OpenTabletDriver#3219]
### Manufacturer

Huion

### Product Name

RTS-300

### Device Width

160

### Device Height

100

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Diagnostic Information

no tablets detected

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by gonX** [comment]
Duplicate of #2798
