### ISSUE TITLE
Support Request: binding mouse scroll wheel to pen buttons not working

### ISSUE THREAD

**Issue by dysie** [OpenTabletDriver/OpenTabletDriver#3231]
### What do you need help with?

binding any mouse bind using the mouse button binding type to my pen buttons doesn't seem to work. setting a keyboard bind does work however. not sure why its not working, so any help is appreciated :)

for reference, i have a HUION RDS-160 using vmulti driver.

### What have you tried?

tried restarting the app and pc, looked into other threads but couldn't get any useful information. 

### Diagnostic Information

n/a

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
You are either in a VMulti Output Mode, Windows Ink Output Mode or Artist Mode, which are not conventional mice and thus do not support these bindings, use the respective binding of each output mode instead. You can find these in the advanced binding editor (the 3 dots to the right of each binding)

And scroll bindings are not supported, see #1381.
