### ISSUE TITLE
XP-Pen Star 03 / UC-Logic 1060N variant not detected

### ISSUE THREAD

**Issue by Jopp-gh** [OpenTabletDriver/OpenTabletDriver#3237]
### Steps to Reproduce

Since linux Mint does not allow the configuration of multiple tablet profiles I installed OpenTabletDriver.

1. I installed your *.deb package
2. after rebooting I connected my tablet (Xp-Pen Star 03) - and yes, my model is supported on your device list
3. I launched OpenTabletDriver from the applications panel in Mint
4. OpenTabletDriver tells me: "Connecting to OpenTabletDriver deamon" but aborts after a timeout
5. Now I checked Mint's System settings > tablet and surprise! now, Mint is unable to see my tablet 

Before the installation of OpenTabletDriver my tablet was working fine and Mint detected my tablet and pen immediately, in addition, every time I connect my tablet, my mouse cursor disappears. 

### Expected Behavior

A working driver that doesn't mess with my mouse and gives me a way to setup multiple tablet profiles.

### Observed Behavior

I didn't do anything wrong with your installer - the installation of OpenTabletDriver is fool proof.
All I know is that OpenTabletDriver messed up my default tablet settings (deactivating wacom drivers) as described in your wiki:
```
Currently, two kernel modules are also unloaded as they interfere with OpenTabletDriver. These are:

wacom
hid_uclogic
```
and deactivating my damn cursor, which is even more upsetting!

Then I tried to install yet another time in the hope to get a "complete installation" of your driver. Nothing changed after rebooting.
Guys, you probably you need to check better how you write your installers, because I don't use a small insignificant distro with all kind of issues, so the fault is clearly on your side. Sorry to come up to ask this, but did you actually do some little check if your installer worked fine on major distros like Mint, **at least** ?

Since this installation is such a birth, I just ask you to tell me how to reactivate my wacom drivers so mint can see again my tablet and the uninstaller for OpenTabletDriver. 

### Tablet Device

XP-Pen Star 03

### Diagnostic Information

`lsusb` yes I can see my tablet:
`Bus 001 Device 015: ID 5543:0081 UC-Logic Technology Corp. TABLET 1060N`

there is nothing related to OpenTabletDriver in these folders: 
```
/dev/uinput #uinput does not exist
~/.config/
/etc/udev/rules.d/
~/.config/OpenTabletDriver 
```

here's the log from `~/.config/OpenTabletDriver`
```
[
{
  "Time": "2024-03-11T11:26:53.4500529+01:00",
  "Group": "Detect",
  "Message": "Searching for tablets...",
  "StackTrace": null,
  "Level": 1,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4672761+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet '10moon 1060N'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4679634+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Acepen AP 1060'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4680586+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Adesso Cybertablet K8'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4680782+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Artisul A1201'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4680831+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Artisul AP604'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4680927+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Artisul M0610 Pro'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4804868+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'FlooGoo FMA100'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.480502+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Gaomon 1060 Pro'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4805117+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Gaomon GM116HD'",
  "StackTrace": null,
  "Level": 0,
  "Notification": false
},
{
  "Time": "2024-03-11T11:26:53.4805202+01:00",
  "Group": "Detect",
  "Message": "Searching for tablet 'Gaomon GM156HD'",
  "StackTrace": null,
  "Level": 0,
  "Notification": fal
```

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
The UI wills timeout if the daemon isn't running, but now the daemon is so it shouldn't timeout anymore.

You won't see the tablet in the system settings because its not being controlled by that anymore.

The reason OTD isn't working is likely because we need to completely change our detection scheme, your tablet (likely) has more than 1 identical identifier and thus OTD may randomly select the wrong one, see #3011.

This is unrelated to Linux Mint, isn't a problem with the installer/deb, the fault isn't *really* on us, more just an artifact of poor manufacturer choices. And yes, obviously we have checked if it works on these distros, no need to get rude at us over it all, I understand that this may be a frustrating time for you there's absolutely no need to point fingers here.

If you want me to confirm if its the issue above, export a diagnostic from the UI (help > export diagnostics) and send that file here, otherwise I can only go off the partial information the logging gives me.

**Comment by jamesbt365** [comment]
> But this is absurd, before I registered OpenTabletDriver.Daemon via terminal and it did not launch on reboot.

It does not do this by default, we mention this on [the installation guide](https://opentabletdriver.net/Wiki/Install/Linux) and tell you to set this up.

Place this file in `~/.local/share/OpenTabletDriver/Configurations` you will need to create this directory.

[1060N.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14558063/1060N.json)

**Comment by jamesbt365** [comment]
> This is the missing part in my installation.
Your wiki is very quick and easy to read but I didn't see any article to tell me how I've to create this path and to add this particular json file. Did I oversee something? If no, would you add this step to your wiki?

There isn't really a point adding this to the wiki, the configuration above was created by me, on the fly to fix a conflict between 2 tablets, and will be promptly added to the driver provided nothing else goes wrong, however, before I can do this I need you to verify a few pieces of information for me.

Configuration overrides must be created and unless a conflict exists which cannot be distinquished between it will be added to the driver, unless you know how to diagnose, create, modify and test overrides there isn't really a point listing the override directories.

It will eventually happen when we get around to creating documentation for adding supports to tablets but right now this is on our backlog. 

Right now I need you to get these values (open `Tablet > Tablet Debugger`):
- Max X and Y coordinates (move your pen to the bottom right of the physical tablet, ignore the visualiser)
- Max pressure (press the pen tip down all the way
- if the pen buttons work when pressing them
- If the auxiliary keys on the tablet work

TIP: don't have your pen on the tablet while you are testing the auxiliary keys, it'll make the display for them easier to see.

I'm also pretty sure the only dotnet telemetry that exists is when building dotnet applications, which you are completely able to opt out and only applies when working with source code, which you aren't. See this: https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry

From a quick search dotnet-suggest is a completely related tool.

**Comment by jamesbt365** [comment]
> but I've still to launch the OpenTabletDriver.Daemon manually, otherwise openTablet doesn't start.
setup autostart in your DE then, your environment is not providing what OTD needs.

You missed the max x and y coordinates, and you should see the auxiliary button presses when you press the buttons on the tablet, they'll appear in an array on the debugger window, similar to the pen buttons.

**Comment by jamesbt365** [comment]
I'm also going to need a string dump. Tablet > device string reader
21827
129
leave blank
dump all, save that file and send it here.

**Comment by jamesbt365** [comment]
Tablet > tablet debugger, turn on data recording and press the auxiliary keys one by one, then disable data recording, close the debugger and send the file from `~/.config/OpenTabletDriver/tablet-data.txt`

**Comment by jamesbt365** [comment]
I've gone ahead and opened a pull request that'll fix this in future driver releases.

Its a long story, I don't think pressure was originally verified back when this configuration was created back in 2021. And somewhere along the lines a migration must have broke support for this tablet on Linux by changing one of the report lengths that the configuration looks for on the tablet.

Nothing more should have to be done on our end and the release of the next version of OpenTabletDriver should allow you to remove the configuration override I provided you, but right now you'll probably want to change the `8191` to `2047` in the configuration file I sent. Otherwise everything should be working correctly now?

**Comment by jamesbt365** [comment]
@Jopp-gh could you export another diagnostic please? I might be able to improve this further.

**Comment by jamesbt365** [comment]
Could you send the current configuration you are using? I don't see why it is matching 2 identifiers at once.

**Comment by jamesbt365** [comment]
I didn't need your settings I needed the configuration file you are using in `~/.local/share/OpenTabletDriver/Configurations` exactly how it is now.

**Comment by jamesbt365** [comment]
The flatpak cannot handle the system side of things, therefore no udev or blacklisting of kernel modules, alongside the need for your tablet to have custom versions of these things, it won't exactly work without manual intervention. 

And to get the aux functionality to be predictable it would require a USB packet capture done on windows with the OEM driver installed.

**Comment by jamesbt365** [comment]
Unfortunately right now I'm juggling *multiple* configurations for different tablets, a PR that allows for a rework of the detection scheme, this tablet, and a variant of this tablet with a firmware bug and a few other things just related to the project, alongside IRL things I can't guarantee that I can work on this constantly.

Some variants of this tablet do work, and this doesn't mean that we are going to cut support *entirely*. Lots of tablets have variants, new variants are created for old tablets all the time. Does that mean we should remove all the configurations from OTD and make users create them for their tablet that they want to use on their own with no support? No of course not that doesn't make sense at all.

If you are not going to provide the details to make this work properly of course its not going to work properly, I can only work with as much information as *you* provide me with, I do not have your physical tablet and therefore cannot get the information on my own. I understand that I am not always available but this will never get done if you don't get the right information, I can look into the Linux Wacom kernel project but our detection schemes are different, we are different drivers.

**Comment by mercifulboss** [comment]
I have a Huion H610Pro tablet. It doesn't work with the driver (I also get a timeout message on wayland). It is not detected by lsusb but is detected by kwin because some of the buttons on the tablet can be mapped but i the pen does not.

In addition the path `~/.config/OpenTabletDriver` did not exist. I created it and the folder remains empty even after reinstalling the driver via the AUR

**Comment by gonX** [comment]
I renamed the issues title to make the exact issue a bit clearer. You are making a lot of points that are better addressed in individual issues (or discussions).

As for website documentation, if you have anything concrete you want changed (or explained better), please open an issue on our website's GitHub: https://github.com/OpenTabletDriver/opentabletdriver.github.io

To continue addressing support of the variant of this tablet, please see #3238.
