### ISSUE TITLE
Veikk A15 has no aux button support

### ISSUE THREAD

**Issue by adhdandy** [OpenTabletDriver/OpenTabletDriver#3280]
### Description

I have made the necessary changes to fix the issue for myself, but I don't know how to implement them in a way that would work as a PR for the project without breaking support for other Veikk tablets.
Could someone look at the changes I made in my fork and add them properly?

Fork: https://github.com/adhdandy/OpenTabletDriver

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Just submit a parser under a new name and evidence that it works, provide data recordings of movement on both the X and Y axis in your PR alongside pressure if possible.

**Comment by jamesbt365** [comment]
#3284.
