### ISSUE TITLE
Add support for XP-Pen Deco Pro LW gen 2

### ISSUE THREAD

**Issue by AT-Geist** [OpenTabletDriver/OpenTabletDriver#3281]
### Manufacturer

XP-Pen

### Product Name

MT1172B

### Device Width

333mm

### Device Height

258.1mm

### Pressure Levels

16384

### Lines per Inch (LPI)

5080

### Additional Information

This tablet can use either wired or bluetooth connectivity.

### Diagnostic Information

When plugged in via usb
[DecoProLWG2.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14969138/DecoProLWG2.json)

When connected via bluetooth
[DecoProLWG2_bluetooth.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14969168/DecoProLWG2_bluetooth.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by AT-Geist** [comment]
Added in #3228

**Comment by DENG-XC** [comment]
Hello, I'm thinking about to buy this tablet. I saw on Reddit that the official drivers don't support Bluetooth on Linux. Just wondering, does OTD have Bluetooth support for this tablet?

**Comment by jamesbt365** [comment]
It doesn't.
