### ISSUE TITLE
Error with PluginManager

### ISSUE THREAD

**Issue by Ostenarchy** [OpenTabletDriver/OpenTabletDriver#3282]
### Steps to Reproduce

When i open PluginManager it give me this error.
1) I use the latest version of OpenTabletDriver
2) Before installation I used the "TabletDriverCleanUp" [(https://github.com/X9VoiD/TabletDriverCleanup/releases/tag/v4.0.3.1](url))
3) I install this version of .NET: [https://opentabletdriver.net/Framework](url) (Windows x64)
4) My OS is Windows LTSC (screenshot down below)

![OpenTabletDriver UX Wpf_6lwR8FMkNE](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/101494828/eccc8c03-be65-431f-89ef-58831adb5838)
![OpenTabletDriver UX Wpf_TaMZxo2InT](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/101494828/69dc415d-e1aa-426b-a85c-ac97aa1167f0)
![explorer_XFbk2IDzol](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/101494828/47660189-0ba6-460e-a672-9360b08f43af)

### Expected Behavior

I expect of plugin manager will open.

### Observed Behavior

It gives me the error message and do not open.

### Tablet Device

Wacom CTL-480

### Diagnostic Information

[DIAGNOSTIC.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/14988092/DIAGNOSTIC.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Your computer was unable to make a connection to GitHub correctly.

**Comment by jamesbt365** [comment]
If you can't get it working, youll need to manually install plugins from our website.
