### ISSUE TITLE
Drag option on mac doesnt duplicate

### ISSUE THREAD

**Issue by gegagome** [OpenTabletDriver/OpenTabletDriver#3287]
### Steps to Reproduce

I am using Wacom CTH-680 on a mac and using Open tablet Driver

Drag a file in your desktop while pressing down the option click.

### Expected Behavior

It should show a green plus icon right under the pointer, signifying that you intend to duplicate this clicked file.

### Observed Behavior

Dragging is only performed. It results in moving this clicked file.

### Tablet Device

Wacom CTH-680

### Diagnostic Information

Got this error:
There was an error creating your Issue: body is too long (maximum is 65536 characters).

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Its likely the same underlying issue as #2291, and will be fixed with #2894. Closing as duplicate for now, if this isn't the case and isn't resolved by using the PR mentioned, I'll reopen.
