### ISSUE TITLE
Tablet does not work; unable to construct object 'OpenTabletDriver.Desktop.Output.AbsoluteMode'

### ISSUE THREAD

**Issue by Maritsu** [OpenTabletDriver/OpenTabletDriver#3308]
### Steps to Reproduce

0. Install OTD from the AUR
1. Start the OTD daemon via `systemctl --user start opentabletdriver`
2. Plug in a tablet

### Expected Behavior

The tablet works properly.

### Observed Behavior

Nothing works. The diagnostic logs output `Unable to construct object 'OpenTabletDriver.Desktop.Output.AbsoluteMode'` and `Connection refused /run/user/1000/wayland-1` (I'm not even in a Wayland session).

### Tablet Device

XP-Pen Star G430S

### Diagnostic Information

[otd.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/15219985/otd.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by hwsmm** [comment]
Your systemd user environment probably doesn't have `DISPLAY` or `WAYLAND_DISPLAY` set. Try using `otd-daemon` instead of systemctl?
