### ISSUE TITLE
Run application on button press

### ISSUE THREAD

**Issue by BunnyTub** [OpenTabletDriver/OpenTabletDriver#3327]
### Description

I've been looking for a way to open applications when I click one of my aux buttons.
I tried looking through OTD's settings, but no luck. Not even any plugins I could find.

I would simply like to open an application from my auxiliary.

### Acknowledgements

- [x] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
What would this provide better than script runner?

**Comment by BunnyTub** [comment]
I made it a plugin instead
