### ISSUE TITLE
Add support for Huion Kamvas 19 Pro (GT-1902)

### ISSUE THREAD

**Issue by C1ares** [OpenTabletDriver/OpenTabletDriver#3333]
### Manufacturer

Huion

### Product Name

GT-1902

### Device Width

448.9mm

### Device Height

272.4mm

### Pressure Levels

16384

### Lines per Inch (LPI)

5080

### Additional Information

Have some issues with the official driver, especially on MacOS, would be happy if you could add support for this newish tablet

### Diagnostic Information

[GT-1902.json](https://github.com/user-attachments/files/15746492/GT-1902.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Fixed by #3416.
