### ISSUE TITLE
Add support for Parblo Ninos N7B 

### ISSUE THREAD

**Issue by archev727** [OpenTabletDriver/OpenTabletDriver#3334]
### Manufacturer

Parblo

### Product Name

Ninos n7b

### Device Width

248

### Device Height

150

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Diagnostic Information

[Parblo Ninos N7B Diagnostics.json](https://github.com/user-attachments/files/15774037/Parblo.Ninos.N7B.Diagnostics.json)
[Parblo Ninos N7B Diagnostics txt file.txt](https://github.com/user-attachments/files/15774047/Parblo.Ninos.N7B.Diagnostics.txt.file.txt)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Duplicate of #3187
