### ISSUE TITLE
Support Request: CTL-470 detected but not working

### ISSUE THREAD

**Issue by DJshelfmushroom** [OpenTabletDriver/OpenTabletDriver#3345]
### What do you need help with?

OpenTabletDriver detects my tablet, and when I go into the debugger, when i put my pen down it changes a number, but nothing else changes when I move it.

### What have you tried?

i tried restarting and running tabletdrivercleanup.

### Diagnostic Information

[tabletdiag.json](https://github.com/user-attachments/files/15938297/tabletdiag.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [x] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by DJshelfmushroom** [comment]
Good to note that the default wacom drivers (both current and recommended for device) also didn't work.

**Comment by jamesbt365** [comment]
If you have them installed now, uninstall them, preferably by running TDCleanup after.

After this, go to tablet > tablet debugger, move your pen around. If you don't raw data changing and a blue dot, then the problem lies external to us.

**Comment by DJshelfmushroom** [comment]
the default drivers? yeah I ran TDCleanup.

**Comment by DJshelfmushroom** [comment]
i see data changing but no dot so...
