### ISSUE TITLE
Add support for xp pen deco gen 2 large

### ISSUE THREAD

**Issue by Zac12887** [OpenTabletDriver/OpenTabletDriver#3350]
### Manufacturer

Ep pen

### Product Name

Deco gen 2

### Device Width

435

### Device Height

300

### Pressure Levels

?

### Lines per Inch (LPI)

?

### Additional Information

Please add support for this device cheerd

### Diagnostic Information

?

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Closing this as it has blatantly ignored the requirements for requesting to supports for tablets, this is obviously rushed and ignores the section and instructions for providing the necessary information for us to support the tablet.

Feel free to open another issue with the correct issue in the future, it is **mandatory** not optional.
