### ISSUE TITLE
XP-Pen Star G960S Not Detected

### ISSUE THREAD

**Issue by SunRizzze** [OpenTabletDriver/OpenTabletDriver#3354]
### Steps to Reproduce

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/9877a8c2-f4ed-4058-b883-351b67bd196a)
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/13021500-dea9-4998-a3c6-481b01fc6a82)
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/d587d41a-ab1f-492f-abd1-642f8259b45f)

### Expected Behavior

Should be detected by the OTD

### Observed Behavior

Just connected fresh tablet, and no detection

### Tablet Device

XP-Pen Star G960S

### Diagnostic Information

[g960s.json](https://github.com/user-attachments/files/16112455/g960s.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Have you tried rebooting?

**Comment by SunRizzze** [comment]
> Have you tried rebooting?, Rebuild your initramfs then reboot.

still the same.

**Comment by jamesbt365** [comment]
export diagnostic again.

**Comment by SunRizzze** [comment]
[xppen960s.json](https://github.com/user-attachments/files/16112839/xppen960s.json)

**Comment by SunRizzze** [comment]
> export diagnostic again.

here:
[xppen960s.json](https://github.com/user-attachments/files/16112840/xppen960s.json)

**Comment by SunRizzze** [comment]
> export diagnostic again.

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/1be8bc75-38e2-4454-a8ac-57a105eb01a1)

btw, official driver work fine

**Comment by jamesbt365** [comment]
Its not working on OTD because you have the XP-Pen driver installed.

**Comment by SunRizzze** [comment]
> Its not working on OTD because you have the XP-Pen driver installed.

im installed it after OTD, to check if it is detected

**Comment by jamesbt365** [comment]
An interface is completely missing, the one OTD wants to use, OTD cannot use that interface because another driver is using it.

**Comment by SunRizzze** [comment]
> An interface is completely missing, the one OTD wants to use, OTD cannot use that interface because another driver is using it.

uninstalled pentablet driver, still the same

**Comment by jamesbt365** [comment]
The interface that OTD is trying to access is not available, its not even visible to the driver because its in use elsewhere.

This problem is external to OpenTabletDriver it simply does not have the permissions because its already in use. There is nothing I can do about that, there is no change in the driver I can make, there is no change to the configuration I can make, the interface that OTD needs to use is **not available**.

Once its uninstalled, rebuild your initramfs and reboot again, I don't know if it made any changes to the modules on your system.

**Comment by SunRizzze** [comment]
> The interface that OTD is trying to access is not available, its not even visible to the driver because its in use elsewhere.
> 
> This problem is external to OpenTabletDriver it simply does not have the permissions because its already in use. There is nothing I can do about that, there is no change in the driver I can make, there is no change to the configuration I can make, the interface that OTD needs to use is **not available**.
> 
> Once its uninstalled, rebuild your initramfs and reboot again, I don't know if it made any changes to the modules on your system.

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/697124db-ac9a-4cbb-bd0c-570c4f6a226d)
here my old g430 easily detected
(Official Pen Tablet installed, but disabled)

**Comment by jamesbt365** [comment]
As you are insistent on it being the drivers fault, run the driver as root.

**Comment by SunRizzze** [comment]
> As you are insistent on it being the drivers fault, run the driver as root.

Same happens on Windows, where i didnt had PenTabletDriver installed

OTD just doesn't detect my G960S

**Comment by jamesbt365** [comment]
Export diagnostics on windows.

**Comment by SunRizzze** [comment]
> Export diagnostics on windows.

[windows g960s.json](https://github.com/user-attachments/files/16120643/windows.g960s.json)

here, i want OTD to work cuz i hate drivers from XP-Pen

**Comment by jamesbt365** [comment]
You have a new variant, doing this will not fix it on Linux until you fix the issue with the interface not being available but this will remedy it on Windows.


Download [this](https://github.com/user-attachments/files/16120651/Star.G960S.json) file, create a folder called `Configurations` next to OpenTabletDriver, then place that file inside the folder, finally replug your tablet.

**Then** go to tablet > tablet debugger:
- get the highest x and y coordinates you can by moving your pen to the bottom right of your tablet
- get the max pressure by pressing the pen nib in
- check if the pen buttons go to true when you press them and check the tablet buttons for the same.

**Comment by SunRizzze** [comment]
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/a82ee688-40fa-49f6-bfa2-31f795e95962)
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/7d66952b-492a-47e2-a3a0-a2c05d14ac59)
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/a95479eb-490f-4d72-ad3a-f30e13d6f256)
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/8530df13-8249-4b0f-a5aa-77f104b86af5)

now detected

**Comment by SunRizzze** [comment]
> You have a new variant, doing this will not fix it on Linux until you fix the issue with the interface not being available but this will remedy it on Windows.
> 
> Download [this](https://github.com/user-attachments/files/16120651/Star.G960S.json) file, create a folder called `Configurations` next to OpenTabletDriver, then place that file inside the folder, finally replug your tablet.
> 
> **Then** go to tablet > tablet debugger:
> 
>     * get the highest x and y coordinates you can by moving your pen to the bottom right of your tablet
> 
>     * get the max pressure by pressing the pen nib in
> 
>     * check if the pen buttons go to true when you press them and check the tablet buttons for the same.

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/8a763327-41b4-45e9-8fa6-a770b98ebad7)

**Comment by jamesbt365** [comment]
None of your screenshots verify the last 2 bullet points.

**Comment by SunRizzze** [comment]
> None of your screenshots verify the last 2 bullet points.

yes, they all work
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/d914befd-3742-4ec2-8c09-e6d3f443bd47)

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/fe3082b2-c7d0-4c14-bc76-f61748043fea)

**Comment by jamesbt365** [comment]
You still missed a bullet point.

**Comment by SunRizzze** [comment]
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/e94f2a6d-6052-4d1f-990b-6c7e7da6bb78)

pressure

**Comment by SunRizzze** [comment]
> You still missed a bullet point.

btw, what was the issue?

**Comment by jamesbt365** [comment]
Your original issue? Like I said, interface isn't there because of permissions.

The *current* issue? Your tablet didn't match the identifiers in OTD.
