### ISSUE TITLE
G960S failed detection

### ISSUE THREAD

**Issue by SunRizzze** [OpenTabletDriver/OpenTabletDriver#3355]
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/88379879/697124db-ac9a-4cbb-bd0c-570c4f6a226d)
here my old g430 easily detected
(Official PenTabletDriver installed, but disabled)

i hope that you can fix g960s detection

_Originally posted by @SunRizzze in https://github.com/OpenTabletDriver/OpenTabletDriver/issues/3354#issuecomment-2211710490_

**Comment by jamesbt365** [comment]
Like I told you, this has nothing to do with the driver, please keep everything in one issue.

**Comment by SunRizzze** [comment]
> Like I told you, this has nothing to do with the driver, please keep everything in one issue.

so it means that my issue will be ignored and not resolved?
