### ISSUE TITLE
Support Request for Huion Inspiroy 2 L

### ISSUE THREAD

**Issue by Oncemaged** [OpenTabletDriver/OpenTabletDriver#3365]
### Manufacturer

Huion

### Product Name

H1061P / Inspiroy 2 L 

### Device Width

10.5

### Device Height

6.52

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

It does have a scroll wheel and other buttons but if the pad itself worked thatd save me another hundredish dollars lol. Thank you for your time !

### Diagnostic Information

[Opentabletdriverdiagnosticinfo.json](https://github.com/user-attachments/files/16154866/Opentabletdriverdiagnosticinfo.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Dupliacte of #3182.
