### ISSUE TITLE
opentabletdriver.daemon high cpu usage macos

### ISSUE THREAD

**Issue by aseotuh** [OpenTabletDriver/OpenTabletDriver#3388]
### Steps to Reproduce

launch opentabletdriver

### Expected Behavior

for it to not eat up my cpu

### Observed Behavior

uses large amounts of my cpu, often almost the entirety

### Tablet Device

wacom ctl 472

### Diagnostic Information

[Untitled2.json](https://github.com/user-attachments/files/16355115/Untitled2.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by aseotuh** [comment]
i want to add that i also had to quit opentabletdriver as it started using almost 300% CPU according to activity monitor, not sure this is 100% accurate, but my temps were up to ~110º C

**Comment by jamesbt365** [comment]
Whats your settings on all your active filters?

**Comment by aseotuh** [comment]
![Screenshot 2024-07-23 at 19 22 30](https://github.com/user-attachments/assets/c37ad417-f12b-4e23-80f4-b76c86702e2b)

**Comment by jamesbt365** [comment]
Try disabling it, saving and restarting OTD.

Do you still see the increased cpu usage?

**Comment by aseotuh** [comment]
it goes down to ~0.1% cpu usage after I disable it

**Comment by aseotuh** [comment]
i kinda need the antichatter cuz my aim is just shaky af without it tho so disabling it isn't really an option for me, is there a way I could use antichatter and not have it eat up my CPU?

**Comment by jamesbt365** [comment]
Closing in favour of #3389.

**Comment by aseotuh** [comment]
what

**Comment by jamesbt365** [comment]
There is no native timer for MacOS in the latest version of the driver, but there is in the unstable branch.

However, its unstable and there are no filters for it. Either do not use filters, accept the CPU usage or if you know how to program feel free to backport the native timer.

**Comment by aseotuh** [comment]
when i turn off the filter opentabletdriver itself starts using half my CPU

**Comment by jamesbt365** [comment]
Filters are not cleaned up between saves of OTD, this is why I said to restart the driver when I told you to originally turn it off.
