### ISSUE TITLE
Add support for ugee M708 tablet

### ISSUE THREAD

**Issue by Rezall** [OpenTabletDriver/OpenTabletDriver#3394]
### Manufacturer

ugee

### Product Name

ugee M708

### Device Width

359mm

### Device Height

210mm

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Diagnostic Information

[diag.txt](https://github.com/user-attachments/files/16401695/diag.txt)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/TABLETS.md?plain=1#L62
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/TABLETS.md?plain=1#L174

**Comment by gonX** [comment]
V1 added in #1203, V2 added in #2268, both prior to this issue. V3 support was recently added in #4266 - assuming fixed by that issue.
