### ISSUE TITLE
Support Request: No cursor movement with Huion Kamvas Pro 13

### ISSUE THREAD

**Issue by CyberGh0st-droid** [OpenTabletDriver/OpenTabletDriver#3429]
### Manufacturer

Huion

### Product Name

Kamvas Pro 13

### Device Width

388

### Device Height

219

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

It detects the tablet. It detects that it has aux buttons but it just doesn't detect pen movement.
I'm also unsure but I don't think it's even recognized as a screen tablet

feel free to ask for any necessary additional info

### Diagnostic Information

[OTD-Kamvas pro 13 diagnostics.json](https://github.com/user-attachments/files/16659027/OTD-Kamvas.pro.13.diagnostics.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
**Configuration** requests are for tablets that are currently **not** supported, you are looking for the **support request** label and template.

This is likely caused by your settings. File > reset to defaults, save.
