### ISSUE TITLE
No tablets are detected Gaomon s620

### ISSUE THREAD

**Issue by anatadake** [OpenTabletDriver/OpenTabletDriver#3430]
### Steps to Reproduce

![1](https://github.com/user-attachments/assets/156bde69-3c42-4898-8707-97663c437f60)
![2](https://github.com/user-attachments/assets/7c0838ab-6cba-425d-97b0-a67a02534e7e)

### Expected Behavior

I want to play osu but the tablet doesn’t see it

### Observed Behavior

Doesn't see my tablet even though I did everything according to the instructions

### Tablet Device

Gaomon S620

### Diagnostic Information

[1.json](https://github.com/user-attachments/files/16661461/1.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Not a bug, you have the gaomon driver installed and from OTDs perspective your tablet isnt even plugged in

This could be because:
- You are using a USB Hub
- You are using a cable that doesnt support data transfer
- The gaomon driver is messing with the device drivers hiding it from OTD.

**Comment by anatadake** [comment]
And what do I need to do

**Comment by jamesbt365** [comment]
Uninstall the gaomon driver and ensure your tablet is connected properly, you can check its connected properly in device manager by going to `view > device by container`

**Comment by jamesbt365** [comment]
By using the uninstaller in apps and features.

**Comment by anatadake** [comment]
So, in theory, I have deleted everything related to Gaomon, what should I do next?

**Comment by jamesbt365** [comment]
And how did you "delete" it, delete and uninstall mean different things.

**Comment by anatadake** [comment]
I deleted it using unis

**Comment by jamesbt365** [comment]
No, you *uninstalled* it using the uninstaller, deleting would be going into file explorer and manually deleting files, they are different terms and you don't delete installed applications, let alone drivers.

Is your device in device manager when you do the steps I previously provided?

**Comment by anatadake** [comment]
No, it is not located

**Comment by jamesbt365** [comment]
Then the tablet is not plugged in.

**Comment by anatadake** [comment]
Should it be connected while deleting everything?

**Comment by jamesbt365** [comment]
Again, you are using the wrong terminology, it is absolutely imperative that you are speaking clearly, you are supposed to *uninstall*, not *delete*.

It shouldn't matter, but it may be impossible for uninstallers to undo changes to device drivers when the device is not plugged in, regardless **the tablet must be plugged in for OpenTabletDriver** to use it anyway, so the end result is the same, the device **must be plugged in**.

**Comment by anatadake** [comment]
I just don’t understand English well, that’s why I communicate through a translator
So I connected the tablet, what should I do next, I deleted gaomon everywhere it was located

**Comment by jamesbt365** [comment]
If your device is **not present in device manager** when you go to **view > device by container** it is not plugged in, and therefore this issue has absolutely nothing to do with OTD.

I have already given you some possible remedies in this chat.

**Comment by anatadake** [comment]
It's connected there

**Comment by jamesbt365** [comment]
Screenshot.

**Comment by anatadake** [comment]
![3](https://github.com/user-attachments/assets/f2e39581-a473-4bec-9b68-2fc1195c98d8)

**Comment by jamesbt365** [comment]
If running this program and removing everything it asks for doesn't help, then there isn't anything else I can do here because of the language barrier, this problem is with your setup and doesn't have anything to do with OpenTabletDriver, at all.

https://opentabletdriver.net/Wiki/FAQ/Windows#driver-cleanup

**Comment by anatadake** [comment]
I did everything you suggested but nothing helped
