### ISSUE TITLE
Add support for Huion H950P Inspiroy Please and thanks for even reading this! 

### ISSUE THREAD

**Issue by Juniorator** [OpenTabletDriver/OpenTabletDriver#3431]
### Manufacturer

Huion

### Product Name

H950P Insproy

### Device Width

260

### Device Height

147.7

### Pressure Levels

8191

### Lines per Inch (LPI)

5080

### Additional Information

I dont know if its important but im using the Lord mobiles version of the tablet

### Diagnostic Information

Im sorry i dont know what you mean..
Mb if this is really important

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
> Im sorry i dont know what you mean..
Mb if this is really important

It is *the* most important part of the entire thing and we even provide instructions on how to do it, it is absolutely impossible for us to even create a configuration without this information. Please **carefully** read the instructions if you happen to open an issue in the future.
![image](https://github.com/user-attachments/assets/f1a7daa6-a42a-47f5-a3e1-a3fc6a77904e)

Additionally, this is **already supported** upstream and will be in the next release of the driver. See #3418.
