### ISSUE TITLE
Install Impossible on Ubuntu 24.04

### ISSUE THREAD

**Issue by MichaelDevon** [OpenTabletDriver/OpenTabletDriver#3434]
### Steps to Reproduce

After it failed to install on a fresh install of ubuntu 24, i started following the guide, then i realized i might need the microsoft packages prod .deb file, to obtain dotnet sdk 6. After followinf those instructions and i have had it set up correctly, it still wont install OTD with the error of no installation candedite for dotnet 6 sdk.

I tried really hard multiple times to install it following the guide but i think i did everything correctly.

### Expected Behavior

dotnet sdk 6 available from either ubuntu's or microsoft's repos.

### Observed Behavior

Package unavailable

### Tablet Device

N/A

### Diagnostic Information

N/A

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
This is a problem with the repositories of your operating system removing dotnet 6 (despite it not being EOL) you can use the dotnet backports until the next release of OpenTabletDriver releases which uses .NET 8

```
sudo add-apt-repository ppa:dotnet/backports
sudo apt update
```
