### ISSUE TITLE
Add support for Parblo Intangbo X7

### ISSUE THREAD

**Issue by archev727** [OpenTabletDriver/OpenTabletDriver#3436]
### Manufacturer

Parblo

### Product Name

Intangbo X7

### Device Width

271

### Device Height

166

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

The configuration has already been completed and verified, so all that remains is to add

### Diagnostic Information

[Intangbo X7.json](https://github.com/user-attachments/files/16731628/Intangbo.X7.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
> Diagnostic Information
Diagnostic information should be information from OTD itself showing the identifiers and other information about the tablet, it is the file generated from `help > export diagnostics`.

It should not just be an already completed configuration, if you wish to add this configuration directly, open a pull request containing the configuration.

**Comment by jamesbt365** [comment]
Just to let you know I won't just be adding this configuration because you posted it here, I need actual, hardproof (through a pull request too) that this is right and follows our spec properly, until then I cannot safely pull this configuration.

**Comment by archev727** [comment]
Sorry jamesbt365, I just started learning github so I just don't understand how to create pull requests and other things. Also, github works terribly in Russia, which adds even more problems. A little later I will definitely learn everything, and after that I will do everything right. Sorry to bother you
