### ISSUE TITLE
Request for making configurations out of the executable file

### ISSUE THREAD

**Issue by RainyLave** [OpenTabletDriver/OpenTabletDriver#3470]
### Description

Considering inconvenience when adding configurations to this project, maybe we could put the configuration files out of the executable files so that we can add our  configuration files without recompiling

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
This.. already exists!
On windows, create a folder called `Configurations` next to the executables

On Linux, you can do the same or place them in `~/.local/share/OpenTabletDriver/Configurations`

On MacOS, this isnt supported yet, but theres already an issue tracking that.

**Comment by RainyLave** [comment]
Tks very much~
