### ISSUE TITLE
Double Cursor Bug

### ISSUE THREAD

**Issue by Taxuma** [OpenTabletDriver/OpenTabletDriver#3472]
### Steps to Reproduce

I'm on steam deck and therefore using SteamOS, I've installed OpenTabletDriver through the discovery store as all efforts through any other method seem futile. I installed and seemed fine until i set my area and actually attempted to use the driver.

### Expected Behavior

Expected it to run fine as it seemed to be the first time i could actually even install it.

### Observed Behavior

Basically it turns up with a double cursor, it flickers between the two making it pretty much unusable. It seems to work fine on full area only but that's not what i use or want. Looks like one cursor may be a full area cursor, and one is from the area i set. I've seen other people have this issue on other devices using the official instructions and no one has seemed to have a fix that I've seen.. i've attached a video showing the issue. thanks.
[2024-09-17 17-52-10.webm](https://github.com/user-attachments/assets/b5a88533-48da-4d04-884f-b00bd134e5a3)
Looking at the debugger visualiser, it shows the assumed full area on it rather than the area i've set.

### Tablet Device

Wacom CTH-480

### Diagnostic Information

Can't retrieve diagnostics.

### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Flatpak is not a supported package and it requires its own setup, either uninstall it and make your system mutable (using `steamos-readonly disable`) and install the AUR package or make your system mutable and manually install the udev rules and kernel module blacklists following the instructions on the flatpak manifest.
