### ISSUE TITLE
Add support for Huion HS610

### ISSUE THREAD

**Issue by AnAngelsDemon** [OpenTabletDriver/OpenTabletDriver#3477]
### Manufacturer

Huion

### Product Name

HS610

### Diagnostic Information

[Huion HS610 Diagnostics.json](https://github.com/user-attachments/files/17090380/Huion.HS610.Diagnostics.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Its already supported, nor did you try and look for any duplicates.
https://opentabletdriver.net/Tablets

Having other drivers installed is not supported.
