### ISSUE TITLE
Support Request: it is not detecting daemonds

### ISSUE THREAD

**Issue by DoriteLover** [OpenTabletDriver/OpenTabletDriver#3491]
### What do you need help with?

OpenTabletDriver cant detect its daemon thing

### What have you tried?

reading wiki and installing flatpak version which verification failed but tried but also failed

### Diagnostic Information

cant find anything

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
The flatpak is not an officially supported package, do not open issues for it here.
