### ISSUE TITLE
Add support for Huion 680TF

### ISSUE THREAD

**Issue by 4444443** [OpenTabletDriver/OpenTabletDriver#3502]
### Manufacturer

Huion

### Product Name

Huion 680TF

### Device Width

203

### Device Height

152

### Pressure Levels

2048

### Lines per Inch (LPI)

5080

### Diagnostic Information

[huion 680TF 1.json](https://github.com/user-attachments/files/17484795/huion.680TF.1.json)
[string dump.txt](https://github.com/user-attachments/files/17484799/string.dump.txt)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
You will not make another issue, there was no need to do this. Simply add the informaation on your old issue either by editing the post or by replying to my message. You cannot make a new issue every time you need to add something. Config creation is a lot of back and forth and I will not let you do this.

Dupliacte of #3501. Go add the required information there.
