### ISSUE TITLE
Add support for AP 906

### ISSUE THREAD

**Issue by Gitroidjs** [OpenTabletDriver/OpenTabletDriver#3516]
### Manufacturer

Ace Pen

### Product Name

AP 906

### Device Width

 158 mm

### Device Height

 97 mm

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Diagnostic Information

[diagnostic.json](https://github.com/user-attachments/files/17697757/g.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
#3133.
