### ISSUE TITLE
OpenTabletDriver not installable on Fedora 41

### ISSUE THREAD

**Issue by LucasGGamerM** [OpenTabletDriver/OpenTabletDriver#3524]
### Steps to Reproduce

It is not possible to install OpenTabletDriver on fedora 41 due to missing dotnet6 dependencies (they are too old), and I had to manually grab an old dotnet6 rpm to install OpenTabletDriver on fedora.

### Expected Behavior

It should install without issue on fedora 41.

### Observed Behavior

It doesn't install because of the dotnet6 missing dependencies.

### Tablet Device

Wacom CTL 472

### Diagnostic Information

Dnf complaining about the missing dotnet6 dependency.

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
#3513, #3510.
