### ISSUE TITLE
XP-Pen Deco LW

### ISSUE THREAD

**Issue by awing2x** [OpenTabletDriver/OpenTabletDriver#3565]
### Manufacturer

XP-Pen

### Product Name

XP-Pen Deco LW

### Device Width

254

### Device Height

152.4

### Pressure Levels

8181

### Lines per Inch (LPI)

5080

### Additional Information

 XP-Pen Deco LW is identical to model XP-Pen Deco L but has **Bluetooth** support.

All other specs are identical, so should be possible to pretty much re-use existing configuration file from  XP-Pen Deco L.

Update: See [this post](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2912#issuecomment-2309897753) where someone already worked out the new configuration file that can be added. Also another configuration has been posted on Discord [here](https://discord.com/channels/615607687467761684/1195014337090310226/1195014337090310226).

P.S. NOT to be confused with XP-Pen Deco **Pro** LW **Gen2**

### Diagnostic Information

**Reuse BELOW from  XP-Pen Deco L?**
{
  "Name": "XP-Pen Deco L",
  "Specifications": {
    "Digitizer": {
      "Width": 254,
      "Height": 152.4,
      "MaxX": 50800,
      "MaxY": 30480
    },
    "Pen": {
      "MaxPressure": 8191,
      "ButtonCount": 2
    },
    "AuxiliaryButtons": {
      "ButtonCount": 8
    }
  },
  "DigitizerIdentifiers": [
    {
      "VendorID": 10429,
      "ProductID": 2357,
      "InputReportLength": 10,
      "OutputReportLength": 33,
      "ReportParser": "OpenTabletDriver.Configurations.Parsers.XP_Pen.XP_PenOffsetPressureReportParser",
      "OutputInitReport": [
        "ArAE"
      ]
    }
  ],
  "Attributes": {
    "libinputoverride": "1"
  }
}

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
This diagnostic information is useless and you said it yourself theres an existing post for this tablet.
