### ISSUE TITLE
Add support for Wacom  IntuosPro Medium PTH-660

### ISSUE THREAD

**Issue by hhazer11** [OpenTabletDriver/OpenTabletDriver#3568]
### Manufacturer

Wacom

### Product Name

PTH-660

### Device Width

338

### Device Height

219

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

I want to play оsu laser blyat

### Diagnostic Information

[1234.json](https://github.com/user-attachments/files/17964629/1234.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jjhhgg100123** [comment]
This tablet already has a config and is supported. You will need to remove the existing Wacom drivers to get OpenTabletDriver working, as stated in your diagnostics output. Please refer to the wiki in the future, and also check the support list before opening an issue for tablet support.
