### ISSUE TITLE
Tip Binding VMulti Mode: (Button: Left) input getting overridden by keyboard inputs

### ISSUE THREAD

**Issue by WabiSabi47** [OpenTabletDriver/OpenTabletDriver#3574]
### Steps to Reproduce

I have the tablet on VMulti Relative Mode since the regular Relative Mode does not work on the program I'm trying to use the tablet on, which is Genshin Impact. Only via VMulti Relative Mode are the inputs actually being recognized by the game, there simply is no response via the regular Relative Mode which is why I have set it to VMulti Relative Mode.

### Expected Behavior

I expected that tapping the pen on the tablet would be similar to clicking on a mouse, that the clicks would be prioritized or even be parallel with the keyboard inputs. In this way, in this particular game, I can hold down a movement direction while attacking simultaneously and that is where my character's attack direction would also be.

### Observed Behavior

But every time a key is pressed on the keyboard, it seems to override any of the pen tablet clicks. No matter how much I tap the pen on the tablet, it doesn't register a single click. Only when I release the keys/no keyboard inputs are being sent does the pen tablet register clicks again, and even then it would take a few milliseconds after releasing the keyboard inputs for the game to register the pen tablet clicks. Just for additional information, the mouse movement is unaffected, it still registers movement fine, it really is just the clicks which are seemingly affected by any keyboard input. 

### Tablet Device

Wacom CTL-472

### Diagnostic Information

[ctl472.json](https://github.com/user-attachments/files/17979850/ctl472.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
If this is a problem specific to the plugin, this should be reported to that plugins repository first, only then should it be posted here if its deemed a problem with the plugin api.
