### ISSUE TITLE
Add support on Alpine Linux AKMS

### ISSUE THREAD

**Issue by GamePlayer-8** [OpenTabletDriver/OpenTabletDriver#3581]
### Description

Support on Alpine Linux with AKMS (DKMS alternative) in order to install the driver for Linux kernel.

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [ ] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
OpenTabletDriver is not a kernel driver.
