### ISSUE TITLE
Support Request: Cursor not responding to pen activity outside debug mode

### ISSUE THREAD

**Issue by xT1lapia** [OpenTabletDriver/OpenTabletDriver#3585]
### What do you need help with?

I have a Wacom Intuos Pro (CTL-4100WL) that is recognized by the OpenTabletDriver (wireless). However, the cursor does not respond to pen input when I try to use it on my computer or in osu. While troubleshooting, I noticed that pen activity is correctly registered in debug mode, but the cursor does not move or interact outside of it.

### What have you tried?

- Removed all Wacom drivers, uninstalled OpenTabletDriver completely, and reinstalled it.
- Used OpenTabletDriver’s debug mode, where the pen activity is registered, but the pen does not work outside the program.

### Diagnostic Information

-

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Diagnostic information is not optional as it includes lots of information that helps us solve your issue.

You either have an application like valorant or league running (check your background processes in task manager) which use an anticheat that prevents more than 1 mouse and 1 keyboard working at once.

Or, your settings are broken. File > reset to defaults, save.
