### ISSUE TITLE
Support Request: Add support for Wacom CTL-6100WL

### ISSUE THREAD

**Issue by Cloudax722** [OpenTabletDriver/OpenTabletDriver#3608]
### What do you need help with?

My Wacom Intuos BT M doesn't work with the software. Please add support for it. It doesn't work without me going through a tedious driver uninstall process.

### What have you tried?

I found a tutorial video that explained step by step how to get OpenTabletDriver to work with my tablet on youtube:
https://www.youtube.com/watch?v=35-Jz6_TZOc
(This still works for the latest version of OpenTabletDriver)

This worked for me and I can use my tablet in games like osu without any issues:
![Image](https://github.com/user-attachments/assets/84ebb933-6301-4cc7-be9d-15de9fcf7c20)

### Diagnostic Information

[Before tutorial.json](https://github.com/user-attachments/files/18155477/Before.tutorial.json)

[After following the tutorial having the tablet working.json](https://github.com/user-attachments/files/18155478/After.following.the.tutorial.having.the.tablet.working.json)

### Acknowledgements

- [x] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [x] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [x] I have searched the existing issues and this new issue is not a duplicate of any.
- [x] I have written a concise and meaningful title.
- [x] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
1. This is supported (because it detects in the driver)
2. You were looking at a 4 year old guide that is outdated
3. We have a much more concise set of troubleshooting that works basically every time that isn't tedious [on our website](https://opentabletdriver.net/Wiki/FAQ/Windows#troubleshooting)

**Comment by Cloudax722** [comment]
Hi @jamesbt365, thank you for linking the site. I had no idea there was more on the site to help me with my issue. 

Would it be possible for that site to be added as part of the post-install section? With the post-install just liking to a FAQ I didn't expect it to have anything for when the soft didn't up my tablet at all.

**Comment by jamesbt365** [comment]
It *does* say exactly:
> Take a look at the [FAQ](https://opentabletdriver.net/Wiki/FAQ/Windows) if you encounter any problems.

I think its clear enough that if something isn't working as you would expect it to that you should check the FAQ.

**Comment by Cloudax722** [comment]
Fair enough. It's my fault if I didn't look deeper into it. Thanks again for the assistance.
