### ISSUE TITLE
Automatically re-detect monitors when changing layout

### ISSUE THREAD

**Issue by grhw** [OpenTabletDriver/OpenTabletDriver#3649]
### Description

I use OTD for osu! on Linux, and to get better FPS, I have to turn my secondary monitor off due to Wine VSync shenanigans. 
Can there be a feature to *automatically* re-detect monitors whenever a new one is turned off/on? So far what I've had to do is restart `otd-daemon` to get it to realize the 2nd monitor has been turned off/on. Thankies!!

### Acknowledgements

- [x] I have searched the existing issues and this new issue is not a duplicate of any.
- [x] I have written a concise and meaningful title.
- [x] I am on the latest version of OpenTabletDriver.

**Comment by gonX** [comment]
> I have to turn my secondary monitor off due to Wine VSync shenanigans

Worth noting this is likely just the classic X11 defect of mismatching monitor refresh rates. Try using Wayland - it has tearing support nowadays anyway. You are welcome to open a separate issue discussing this.
