### ISSUE TITLE
Support for UGEE M708 Tablet 

### ISSUE THREAD

**Issue by ppalgankkoch** [OpenTabletDriver/OpenTabletDriver#430]
I have an UGEE M708 tablet

**Comment by InfinityGhost** [comment]
Please use the correct template, it helps us a lot when creating configurations.
![image](https://user-images.githubusercontent.com/39218853/98444891-6db1d200-20e2-11eb-8370-bfb9ed516184.png)

We need the following:

- Width
- Height
- Pressure Levels
- LPI

We also need you to click in the menus

- Help -> Export Diagnostics

Then save the file and send it here.

**Comment by ppalgankkoch** [comment]
Sorry. I could not see the templates (probably because I just didn't look hard enough).

Width: 254 mm
Length: 152.4 mm
Pressure Level: 0-2048
LPI: 5080

[diag.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5504974/diag.txt)

**Comment by Mrcubix** [comment]
https://cdn.discordapp.com/attachments/628651971267788800/774680987400798238/UGEE_M708.json

this should be enough to detect the tablet at least, it will either work or it won't and your cursor won't move, but your area will appear in OTD, to initialize it, you'll need to use the latest master devbuild: 

https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/350695372

go to tablet > string reader > 21827 in the first text field, 129 in the second field, 201 in the third field before the button, and then hit that button and paste here what you get

**Comment by ppalgankkoch** [comment]
Hello

When I try to put in the values you sent, it shows this error:
![image](https://user-images.githubusercontent.com/74100458/98447632-37924380-211e-11eb-9c70-722f703e4802.png)
Translated to English: Error
Error: The calling thread cannot access this object because it is owned by another thread.
Any way to fix this ?

**Comment by Mrcubix** [comment]
alright, string reader in dev build is somehow busted so let's do it the old way, download 
[getstring-dump.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5505196/getstring-dump.zip)
also download and install https://dotnet.microsoft.com/download/dotnet-core/current/runtime
when you done installing .net core runtime 3.1, extract the dump zip file, start it, and wait until string 254 and then copy the whole console content here

**Comment by ppalgankkoch** [comment]
Dump
VendorID:
21827
ProductID:
129
Found Device
GetString (1): UC-LOGIC
GetString (2): Digitizer
GetString (3): F401-HK708-STD
GetString (4): F401-HK708-STD
GetString (5): UC-LOIC
GetString (6): TABLET 1060
GetString (7): F401-HK708-STD
GetString (8): F401-HK708-STD
GetString (9): F401-HK708-STD
GetString (10): F401-HK708-STD
GetString (11): F401-HK708-STD
GetString (12): F401-HK708-STD
GetString (13): F401-HK708-STD
GetString (14): F401-HK708-STD
GetString (15): F401-HK708-STD
GetString (16): F401-HK708-STD
GetString (17): F401-HK708-STD
GetString (18): F401-HK708-STD
GetString (19): F401-HK708-STD
GetString (20): F401-HK708-STD
GetString (21): F401-HK708-STD
GetString (22): F401-HK708-STD
GetString (23): Test
GetString (24): F401-HK708-STD
GetString (25): F401-HK708-STD
GetString (26): F401-HK708-STD
GetString (27): F401-HK708-STD
GetString (28): F401-HK708-STD
GetString (29): F401-HK708-STD
GetString (30): F401-HK708-STD
GetString (31): F401-HK708-STD
GetString (32): F401-HK708-STD
GetString (33): F401-HK708-STD
GetString (34): F401-HK708-STD
GetString (35): F401-HK708-STD
GetString (36): F401-HK708-STD
GetString (37): F401-HK708-STD
GetString (38): F401-HK708-STD
GetString (39): F401-HK708-STD
GetString (40): F401-HK708-STD
GetString (41): F401-HK708-STD
GetString (42): F401-HK708-STD
GetString (43): F401-HK708-STD
GetString (44): F401-HK708-STD
GetString (45): F401-HK708-STD
GetString (46): F401-HK708-STD
GetString (47): F401-HK708-STD
GetString (48): F401-HK708-STD
GetString (49): F401-HK708-STD
GetString (50): F401-HK708-STD
GetString (51): F401-HK708-STD
GetString (52): F401-HK708-STD
GetString (53): F401-HK708-STD
GetString (54): F401-HK708-STD
GetString (55): F401-HK708-STD
GetString (56): F401-HK708-STD
GetString (57): F401-HK708-STD
GetString (58): F401-HK708-STD
GetString (59): F401-HK708-STD
GetString (60): F401-HK708-STD
GetString (61): F401-HK708-STD
GetString (62): F401-HK708-STD
GetString (63): F401-HK708-STD
GetString (64): F401-HK708-STD
GetString (65): F401-HK708-STD
GetString (66): F401-HK708-STD
GetString (67): F401-HK708-STD
GetString (68): F401-HK708-STD
GetString (69): F401-HK708-STD
GetString (70): F401-HK708-STD
GetString (71): F401-HK708-STD
GetString (72): F401-HK708-STD
GetString (73): F401-HK708-STD
GetString (74): F401-HK708-STD
GetString (75): F401-HK708-STD
GetString (76): F401-HK708-STD
GetString (77): F401-HK708-STD
GetString (78): F401-HK708-STD
GetString (79): F401-HK708-STD
GetString (80): F401-HK708-STD
GetString (81): F401-HK708-STD
GetString (82): F401-HK708-STD
GetString (83): F401-HK708-STD
GetString (84): F401-HK708-STD
GetString (85): F401-HK708-STD
GetString (86): F401-HK708-STD
GetString (87): F401-HK708-STD
GetString (88): F401-HK708-STD
GetString (89): F401-HK708-STD
GetString (90): F401-HK708-STD
GetString (91): F401-HK708-STD
GetString (92): F401-HK708-STD
GetString (93): F401-HK708-STD
GetString (94): F401-HK708-STD
GetString (95): F401-HK708-STD
GetString (96): F401-HK708-STD
GetString (97): F401-HK708-STD
GetString (98): F401-HK708-STD
GetString (99): F401-HK708-STD
GetString (100): ??♥??
GetString (101): ?
GetString (102): UC-Logic TechnologyCorp.
GetString (103): F401-HK708-STD
GetString (104): F401-HK708-STD
GetString (105): F401-HK708-STD
GetString (106): F401-HK708-STD
GetString (107): F401-HK708-STD
GetString (108): F401-HK708-STD
GetString (109): F401-HK708-STD
GetString (110): 0
GetString (111): F401-HK708-STD
GetString (112): F401-HK708-STD
GetString (113): F401-HK708-STD
GetString (114): F401-HK708-STD
GetString (115): F401-HK708-STD
GetString (116): F401-HK708-STD
GetString (117): F401-HK708-STD
GetString (118): F401-HK708-STD
GetString (119): F401-HK708-STD
GetString (120): F401-HK708-STD
GetString (121): DFS-UI F401-2011102
GetString (122): ?
GetString (123): HK On
GetString (124): HK Off
GetString (125): F401-HK708-STD
GetString (126): F401-HK708-STD
GetString (127): F401-HK708-STD
GetString (128): F401-HK708-STD
GetString (129): F401-HK708-STD
GetString (130): F401-HK708-STD
GetString (131): F401-HK708-STD
GetString (132): F401-HK708-STD
GetString (133): F401-HK708-STD
GetString (134): F401-HK708-STD
GetString (135): F401-HK708-STD
GetString (136): F401-HK708-STD
GetString (137): F401-HK708-STD
GetString (138): F401-HK708-STD
GetString (139): F401-HK708-STD
GetString (140): F401-HK708-STD
GetString (141): F401-HK708-STD
GetString (142): F401-HK708-STD
GetString (143): F401-HK708-STD
GetString (144): F401-HK708-STD
GetString (145): F401-HK708-STD
GetString (146): F401-HK708-STD
GetString (147): F401-HK708-STD
GetString (148): F401-HK708-STD
GetString (149): F401-HK708-STD
GetString (150): F401-HK708-STD
GetString (151): F401-HK708-STD
GetString (152): F401-HK708-STD
GetString (153): F401-HK708-STD
GetString (154): F401-HK708-STD
GetString (155): F401-HK708-STD
GetString (156): F401-HK708-STD
GetString (157): F401-HK708-STD
GetString (158): F401-HK708-STD
GetString (159): F401-HK708-STD
GetString (160): F401-HK708-STD
GetString (161): F401-HK708-STD
GetString (162): F401-HK708-STD
GetString (163): F401-HK708-STD
GetString (164): F401-HK708-STD
GetString (165): F401-HK708-STD
GetString (166): F401-HK708-STD
GetString (167): F401-HK708-STD
GetString (168): F401-HK708-STD
GetString (169): F401-HK708-STD
GetString (170): F401-HK708-STD
GetString (171): F401-HK708-STD
GetString (172): F401-HK708-STD
GetString (173): F401-HK708-STD
GetString (174): F401-HK708-STD
GetString (175): F401-HK708-STD
GetString (176): F401-HK708-STD
GetString (177): F401-HK708-STD
GetString (178): F401-HK708-STD
GetString (179): F401-HK708-STD
GetString (180): F401-HK708-STD
GetString (181): F401-HK708-STD
GetString (182): F401-HK708-STD
GetString (183): F401-HK708-STD
GetString (184): F401-HK708-STD
GetString (185): F401-HK708-STD
GetString (186): F401-HK708-STD
GetString (187): F401-HK708-STD
GetString (188): F401-HK708-STD
GetString (189): F401-HK708-STD
GetString (190): F401-HK708-STD
GetString (191): F401-HK708-STD
GetString (192): F401-HK708-STD
GetString (193): F401-HK708-STD
GetString (194): F401-HK708-STD
GetString (195): F401-HK708-STD
GetString (196): F401-HK708-STD
GetString (197): F401-HK708-STD
GetString (198): F401-HK708-STD
GetString (199): F401-HK708-STD
GetString (200): F401-HK708-STD
GetString (201): F401-HK708-STD
GetString (202): F401-HK708-STD
GetString (203): F401-HK708-STD
GetString (204): F401-HK708-STD
GetString (205): F401-HK708-STD
GetString (206): F401-HK708-STD
GetString (207): F401-HK708-STD
GetString (208): F401-HK708-STD
GetString (209): F401-HK708-STD
GetString (210): F401-HK708-STD
GetString (211): F401-HK708-STD
GetString (212): F401-HK708-STD
GetString (213): F401-HK708-STD
GetString (214): F401-HK708-STD
GetString (215): F401-HK708-STD
GetString (216): F401-HK708-STD
GetString (217): F401-HK708-STD
GetString (218): F401-HK708-STD
GetString (219): F401-HK708-STD
GetString (220): F401-HK708-STD
GetString (221): F401-HK708-STD
GetString (222): F401-HK708-STD
GetString (223): F401-HK708-STD
GetString (224): F401-HK708-STD
GetString (225): F401-HK708-STD
GetString (226): F401-HK708-STD
GetString (227): F401-HK708-STD
GetString (228): F401-HK708-STD
GetString (229): F401-HK708-STD
GetString (230): F401-HK708-STD
GetString (231): F401-HK708-STD
GetString (232): F401-HK708-STD
GetString (233): F401-HK708-STD
GetString (234): F401-HK708-STD
GetString (235): F401-HK708-STD
GetString (236): F401-HK708-STD
GetString (237): F401-HK708-STD
GetString (238): F401-HK708-STD
GetString (239): F401-HK708-STD
GetString (240): F401-HK708-STD
GetString (241): F401-HK708-STD
GetString (242): F401-HK708-STD
GetString (243): F401-HK708-STD
GetString (244): F401-HK708-STD
GetString (245): F401-HK708-STD
GetString (246): F401-HK708-STD
GetString (247): F401-HK708-STD
GetString (248): F401-HK708-STD
GetString (249): F401-HK708-STD
GetString (250): F401-HK708-STD
GetString (251): F401-HK708-STD
GetString (252): F401-HK708-STD
GetString (253): F401-HK708-STD
GetString (254): F401-HK708-STD

**Comment by Mrcubix** [comment]
https://cdn.discordapp.com/attachments/628651971267788800/774691175532724264/UGEE_M708.json
put this in your config folder

**Comment by ppalgankkoch** [comment]
![image](https://user-images.githubusercontent.com/74100458/98448054-5e9e4480-2121-11eb-8380-56d69fce9d3d.png)
Is it just fine here ?

**Comment by Mrcubix** [comment]
nope, forgot to tell you to put it in the huion folder

**Comment by ppalgankkoch** [comment]
Done.

**Comment by Mrcubix** [comment]
just restart OTD and check if your tablet work now

**Comment by ppalgankkoch** [comment]
[Detect:Info]	No tablet found.
![image](https://user-images.githubusercontent.com/74100458/98448148-0fa4df00-2122-11eb-946b-7b17a945dcaa.png)

**Comment by Mrcubix** [comment]
go to tablet debugger, drag your pen around and tell me if values appear

**Comment by ppalgankkoch** [comment]
Nothing appears; just blank.

**Comment by Mrcubix** [comment]
https://cdn.discordapp.com/attachments/628651971267788800/774696911252226098/UGEE_M708.json

this config should work this time

**Comment by ppalgankkoch** [comment]
I check the console and there is something:
[Detect:Warning]	More than 1 matching digitizer has been found.
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_01&col01#7&3d498ea&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_02&col01#7&1704b528&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd).
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_00&col01#7&2c3f46b3&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_00&col02#7&2c3f46b3&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_01&col03#7&3d498ea&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[NullReferenceException:Error]	Object reference not set to an instance of an object.
[NullReferenceException:Error]	Object reference not set to an instance of an object.

Does this help anything ?

**Comment by Mrcubix** [comment]
so your tablet is detected, now i just have to figure out how to pen the stream

**Comment by ppalgankkoch** [comment]
Okay.

**Comment by ppalgankkoch** [comment]
just asking, any update ?

**Comment by ppalgankkoch** [comment]
![image](https://user-images.githubusercontent.com/74100458/99884710-3be35400-2c28-11eb-9ce9-b70c83d0f2e3.png)
?

**Comment by X9VoiD** [comment]
Do you mind if you elaborate more on that question mark?

**Comment by ppalgankkoch** [comment]
My bad. Just didn't know what to type. The tablet area shows, and then I went and deleted the drivers that were originally with the tablet. Restarted OTD, area shows but when I put the pen on the tablet Windows Ink appears.

**Comment by Mrcubix** [comment]
use 0.4.2, the process bug is fixed there

**Comment by Mrcubix** [comment]
then follow https://youtu.be/35-Jz6_TZOc?t=536

**Comment by ppalgankkoch** [comment]
[IOException:Error]	Can't write to this device.

**Comment by Mrcubix** [comment]
oh i forgot your case is that the init string is 200

**Comment by Mrcubix** [comment]
so the issue right now is first, determining the device string

**Comment by ppalgankkoch** [comment]
![image](https://user-images.githubusercontent.com/74100458/99885730-f7a78200-2c2e-11eb-8fd6-feccb14d11c0.png)
Checked the Device String Reader again.
String: 鱀巀߿ྠ

**Comment by Mrcubix** [comment]
for you to understand why i struggle making this tablet working is because a usual huion tablet dump is like this https://pastebin.com/KFxPn9aZ
you can see `GetString (200): ??O???`
and then the device string which is `OEM02_T18e_190814`

**Comment by ppalgankkoch** [comment]
What line would I find the device string on ?

**Comment by Mrcubix** [comment]
that is the question

**Comment by ppalgankkoch** [comment]
Is there anyway to get a full dump instead of having to type what line it is every time
would getstring-dump work again ?

**Comment by Mrcubix** [comment]
it would return the same thing as you can find above in the previosu message, but you can try again and paste it into a pastebin

**Comment by ppalgankkoch** [comment]
getstring-dump just quits as soon as I open it

**Comment by Mrcubix** [comment]
did you installed .net 5 and started the dump after extracting the zip file?

**Comment by ppalgankkoch** [comment]
Yes, and it still crashes.

**Comment by ppalgankkoch** [comment]
^ It crashed because I needed to use .net 3.1 instead of .net 5

**Comment by Mrcubix** [comment]
the init string is indeed 200, for the device string try these:

- gonna update in 2s

**Comment by ppalgankkoch** [comment]
[RegexParseException:Error]	Invalid pattern '?' at offset 1. Quantifier {x,y} following nothing.
[RegexParseException:Error]	Invalid pattern '?' at offset 1. Quantifier {x,y} following nothing.

**Comment by Mrcubix** [comment]
try another one

**Comment by ppalgankkoch** [comment]
"121": "DFS-UI F401-2011102" and "103": "F401-HK708-STD" come back with the same error: [IOException:Error]	Can't write to this device.

**Comment by Mrcubix** [comment]
last try : `"3": "F401-HK708-STD"`

**Comment by ppalgankkoch** [comment]
Nope, doesn't work. Sucks.
I have two config files (one made from "Generate configuration..." and the other one which is the one you made.
The console for the one file you made: https://pastebin.com/NUrYKRz5 vs the file which was generated through "Generate configuration...": https://pastebin.com/5aGV5TUT

**Comment by Mrcubix** [comment]
alright, so we'll do a USB dump now, download this https://desowin.org/usbpcap/thankyou.html?file=1.5.4.0/USBPcapSetup-1.5.4.0.exe install it,
once that's done, close OTD and download the Manufacturer driver for your tablet, tell me when done

**Comment by ppalgankkoch** [comment]
Done

**Comment by Mrcubix** [comment]
alright, start manufacturer driver, then go to` C:\Program File\USBPcap` open `USBPcapCMD.exe`
once you started it, screenshot the black windows

**Comment by ppalgankkoch** [comment]
![image](https://user-images.githubusercontent.com/74100458/99887180-0a738400-2c3a-11eb-9332-b9cec48d7292.png)

**Comment by Mrcubix** [comment]
alright, so type one, then type the name of the file you want then do these steps:

- move your pen for 7s
- unplug your tablet
- wait 3s
- replug your tablet
- move your pen for 7s
- press Q to quit

then upload the generated file located in the same folder here

**Comment by ppalgankkoch** [comment]
Should I change the file extension to .txt ?

**Comment by Mrcubix** [comment]
nope

**Comment by ppalgankkoch** [comment]
https://www.filehosting.org/file/details/907610/uiFrxIPcRYsJPhAj/usbpcap.pcap

**Comment by X9VoiD** [comment]
Updated configuration: [M708.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5579143/M708.zip)

Delete or move your other M708 configs to somewhere else then extract this as `Configurations\UGEE\M708.json`

This contains the exact initialization sequence from the oem driver. Might or might not work depending on which interface of the device HidSharp (a library that OTD uses) will see first.

**Comment by ppalgankkoch** [comment]
[Detect:Info]	Searching for tablet 'UGEE M708'
[Detect:Warning]	More than 1 matching digitizer has been found.
[Detect:Debug]	Using device 'TABLET 1060'.
[Detect:Debug]	Using report parser type 'OpenTabletDriver.Tablet.TabletReportParser'.
[Detect:Debug]	Device path: \\?\hid#vid_5543&pid_0081&mi_01&col01#7&144dace4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_01&col01#7&144dace4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[Detect:Info]	Found tablet 'UGEE M708'

**Comment by Mrcubix** [comment]
now go to tablet > tablet debugger
move your pen around and tell us if values change

**Comment by ppalgankkoch** [comment]
It's blank

**Comment by X9VoiD** [comment]
Download and setup [#425's dev build](https://github.com/InfinityGhost/OpenTabletDriver/actions/runs/348464123)
And then use this configuration instead: [M708.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5579570/M708.zip)

This will directly try to open the vendor interface

**Comment by ppalgankkoch** [comment]
Same error

**Comment by X9VoiD** [comment]
Send the log, it should atleast say now that it's trying to open `mi_00&col02`

**Comment by ppalgankkoch** [comment]
[Detect:Info]	Searching for tablet 'UGEE M708'
[Detect:Warning]	More than 1 matching digitizer has been found.
[Detect:Debug]	Using device 'TABLET 1060'.
[Detect:Debug]	Using report parser type 'OpenTabletDriver.Tablet.TabletReportParser'.
[Detect:Debug]	Device path: \\?\hid#vid_5543&pid_0081&mi_00&col02#7&2c113929&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_00&col02#7&2c113929&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[Detect:Info]	Found tablet 'UGEE M708'

**Comment by X9VoiD** [comment]
More progress being made in HidSharpCore [#14](https://github.com/InfinityGhost/HIDSharpCore/pull/14). Also checking on the provided dumps for the possibility that it's using other methods for initialization.

**Comment by ppalgankkoch** [comment]
👍

**Comment by X9VoiD** [comment]
Just to test it out, use the same build that i previously linked you, then use this [M708.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5579750/M708.zip)

Make sure that the other oem driver is uninstalled and that you restart OTD after replacing the config.

This config uses the full sequence that the original driver does. I've double checked the dump and no other communication from computer to device was made other than what's in the current config now

```js
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 102, 100, 101, 110,
        98, 122, 123, 98,  102
```

**Comment by ppalgankkoch** [comment]
[Detect:Info]	Searching for tablet 'UGEE M708'
[Detect:Warning]	More than 1 matching digitizer has been found.
[Detect:Debug]	Using device 'TABLET 1060'.
[Detect:Debug]	Using report parser type 'OpenTabletDriver.Tablet.TabletReportParser'.
[Detect:Debug]	Device path: \\?\hid#vid_5543&pid_0081&mi_00&col02#7&2c113929&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 102
[Device:Debug]	Initializing index 100
[Device:Debug]	Initializing index 101
[Device:Debug]	Initializing index 110
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 122
[Device:Debug]	Initializing index 123
[Device:Debug]	Initializing index 98
[Device:Debug]	Initializing index 102
[Device:Error]	Failed to open stream.
[DeviceIOException:Error]	Unable to open HID class device (\\?\hid#vid_5543&pid_0081&mi_00&col02#7&2c113929&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}).
[Detect:Info]	Found tablet 'UGEE M708'

**Comment by X9VoiD** [comment]
If possible would you like to join the [discord server](https://discord.com/invite/P3GYdUS)? And then we carry out further tests there.

**Comment by ppalgankkoch** [comment]
I have already joined, username is chae#6368

**Comment by jamesbt365** [comment]
added in #1203
