### ISSUE TITLE
WinUSB support

### ISSUE THREAD

**Issue by X9VoiD** [OpenTabletDriver/OpenTabletDriver#475]
## Description

WinUSB support is required to some devices where all of it's available HID usages are exclusively opened by Windows. Using a winusb filter driver will let us bypass this restriction by not allowing Windows to open it.

## Related Issues

#394
#430
#1101

and most of Huion and Gaomon that have left-over drivers.

**Comment by gonX** [comment]
Fixed with #1313 if I'm not mistaken. Reopen if not.
