### ISSUE TITLE
Add support for Wacom DTK-1300 (Cintiq 13HD)

### ISSUE THREAD

**Issue by Joromonni** [OpenTabletDriver/OpenTabletDriver#524]
Don't know if it's even possible to work with this thing but here's the details

# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    |Wacom
| Product Name    |DTK-1300
| Width           | 375mm
| Height          |248mm
| Pressure Levels |2048
| LPI             | 5080

## Diagnostic Information

[Diagnostics.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5661016/Diagnostics.zip)

**Comment by Mrcubix** [comment]
[Uploading DTK-1300.zip…]()

**Comment by Joromonni** [comment]
I dragged the config to the configurations > wacom - folder, and when I restarted the prgoram now it just immediately closes after I get to the main window (after pressing start) and then the program just re-opens to the uninstall/start window.
![THhj03bsLm](https://user-images.githubusercontent.com/40163855/101529724-a1aa3c80-3999-11eb-87bb-eee72dc6e464.gif)

**Comment by Joromonni** [comment]
I did find another page of the tablet and it has listed the active area as 299 x 171mm (maybe its irrelevant idk). I also tried uninstalling and placing the config file into the folder before starting it, didn't change. As long as the DTK-1300 config was in the folder the program would just keep restarting itself after getting into the main window.

**Comment by X9VoiD** [comment]
Did you extract the file? It should be a .json

**Comment by Joromonni** [comment]
Okay now it boots up to the main window and doesnt close on start if the config is in there so maybe I had extracted incorrectly (sometimes I just drag files from the zip instead of properly extracting first). But now when I use detect tablet it closes.

**Comment by X9VoiD** [comment]
If you want, you may join our [discord server](https://discord.gg/P3GYdUS) so we may assist you better.

**Comment by Joromonni** [comment]
Joined.

**Comment by InfinityGhost** [comment]
Any progress on this? Did we get a working configuration?

**Comment by Joromonni** [comment]
I dont think so, I think we were waiting on some hid-thing to be added so we can troubleshoot/figure out more.

**Comment by jamesbt365** [comment]
#2241
