### ISSUE TITLE
Will this work on macOS Big Sur?

### ISSUE THREAD

**Issue by jklmao** [OpenTabletDriver/OpenTabletDriver#576]
## Description

Hi, I recently updated my mac and now running Big Sur. I was just wondering if future support for Big Sur will come available because everytime I try running OpenTabletDriver, it refuses to open.
## System Information:

| Name             | Value |
| ----- | ----- |
| macOS Big Sur |
| Latest |
| Veikk s640|

**Comment by InfinityGhost** [comment]
There's a couple known bugs in Big Sur related to a dependency of OpenTabletDriver. It *may* work by v0.5.0, but no guarantees because we don't have any way to test it right now.

**Comment by JWOK0** [comment]
I'm having the same issue with Big Sur, installed the .NET 5 Runtime but I'm still getting the same error message while trying to open it 
![image](https://user-images.githubusercontent.com/40817393/105148958-fbda0980-5ad0-11eb-984b-fa45095ee64d.png)

Hopefully you can get it working, but do take your time

**Comment by InfinityGhost** [comment]
> I'm having the same issue with Big Sur, installed the .NET 5 Runtime but I'm still getting the same error message while trying to open it
> ![image](https://user-images.githubusercontent.com/40817393/105148958-fbda0980-5ad0-11eb-984b-fa45095ee64d.png)
> 
> Hopefully you can get it working, but do take your time

Will fix soon, something bugged out with my packaging script.

**Comment by InfinityGhost** [comment]
So I fixed the packaging, but we have a major breaking bug right now on MacOS, #690. It will have a fix with v0.5.1

**Comment by InfinityGhost** [comment]
Issue appears to be dead, haven't had many reports from big sur users either. Assuming resolved.
