### ISSUE TITLE
Add configuration for Gaomon M10K Pro

### ISSUE THREAD

**Issue by zakaria-chahboun** [OpenTabletDriver/OpenTabletDriver#590]
#### Hi!
First of all i want to say thanks to this project because it's really good
I hope you support **Gaomon M10K Pro**!

- lsusb: `256c:006d` (like Huion HS610)
- Vendor: `Gaomon`
- Product: `M10K Pro`
- Specs: `10″×6.25″, 5080 LPI, 266 RPS , 8192 PL, tilt-sensitive, Frame controls 10 buttons, touch ring with a center button`
- Os: Linux (pop!_Os)

Gaomon M10K Pro - https://www.gaomon.net/Pen_Tablet/M10KPRO.html

#### Image
![image](https://user-images.githubusercontent.com/18173275/103158741-89bc2080-47c1-11eb-9b2c-9d56af250f4b.png)

#### Resources
[descriptors.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743612/descriptors.txt)
[frame_buttons.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743613/frame_buttons.txt)
[pen_buttons.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743614/pen_buttons.txt)
[pen_coords.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743615/pen_coords.txt)
[pen_pressure.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743616/pen_pressure.txt)
[pen_tilt.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743618/pen_tilt.txt)
[probe.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743619/probe.txt)
[touch_ring.anti-clockwise.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743620/touch_ring.anti-clockwise.txt)
[touch_ring.center_key.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743621/touch_ring.center_key.txt)
[touch_ring.clockwise.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743622/touch_ring.clockwise.txt)
[touch_ring.directions.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5743623/touch_ring.directions.txt)

**Comment by Mrcubix** [comment]
an actual diagnostic from Inside OTD itself is required to make any config, in OpenTbaletDriver.UX.Wpf.exe, go to help > export diagnostic, and upload it here

**Comment by zakaria-chahboun** [comment]
@Mrcubix 
This is my diagnostic file:



[diagnostics.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5748848/diagnostics.txt)

**Comment by Mrcubix** [comment]
alright, i'll be working on it, coming back in 10 min

**Comment by Mrcubix** [comment]
[M10K Pro.zip](https://github.com/InfinityGhost/OpenTabletDriver/files/5748931/M10K.Pro.zip)

**Comment by zakaria-chahboun** [comment]
@Mrcubix This is the string `OEM02_T19n_200311` i will copy it in discrod #configs

**Comment by gonX** [comment]
Select Artist Mode from the the drop down in the bottom left of the Output tab. Pressure will work with that enabled.

**Comment by zakaria-chahboun** [comment]
@gonX That's true! Thanks!

**Comment by InfinityGhost** [comment]
I remember merging a PR for this tablet, isn't this implemented now?

**Comment by X9VoiD** [comment]
There's the M106K Pro, and then there's the M10K, without the Pro. This one is M10K Pro.

**Comment by zakaria-chahboun** [comment]
This is the last `M10K Pro` configuration file from @X9VoiD  
[M10K_Pro.json.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6176995/M10K_Pro.json.zip)

**Comment by zakaria-chahboun** [comment]
@InfinityGhost Why you don't add this tablet to project section https://github.com/OpenTabletDriver/OpenTabletDriver/projects/4

**Comment by InfinityGhost** [comment]
This was resolved a while back, not sure why its still open.
