### ISSUE TITLE
problem with opening and deleting

### ISSUE THREAD

**Issue by ilya1237** [OpenTabletDriver/OpenTabletDriver#595]
## Description

i am having a problem with opening opentabletdriver when i try and open it it says conecting with opentabletdriver but it doesn't load i wanted to try and delete it an instal it again but know i cant delete it of of my desktop
## System Information:

| Name   ilya          | Value |
| ---------------- | ----- |
| Operating System | windows
| Software Version |  newest windows 10
| Tablet    xp pen g640       |

**Comment by X9VoiD** [comment]
Restart your computer, or open Task Manager -> Details then close `OpenTabletDriver.Daemon`.

**Comment by X9VoiD** [comment]
No response after 3 months, will assume fixed.
