### ISSUE TITLE
Inverted aspect ratio, and locked area location

### ISSUE THREAD

**Issue by NotMizxy** [OpenTabletDriver/OpenTabletDriver#674]
## Description
When I first installed (not updated) v0.5.0 and tried to set my area instead of having the aspect ratio what it should be it inverted and appeared to be at a 90degree rotation. After a couple restarts the issue no longer occurred, but a new issue came up that locked the where my area was to either the left edge or the right edge, I was unable to move it away from the edge.  Both issues went away after a couple restarts and a combination of toggling different settings on and off repeatedly with restarts/saves/applies in between. 

## System Information:
| Name             | Value |
| OpenTabletDriver | v0.5.0 |
| Windows 10 |
| v0.5.0 |
| Gaomon S620  |

**Comment by X9VoiD** [comment]
Please provide a clear and defined steps to reproduce the error so we may debug and fix it.

**Comment by InfinityGhost** [comment]
Retry this on v0.5.1, still have yet to see anyone else with this issue.

**Comment by NotMizxy** [comment]
Alright, I will try to replicate it, I didn't do anything special during the first install so I'll just install normally.

    On Wednesday, February 3, 2021, 10:23:47 PM CST, InfinityGhost <notifications@github.com> wrote:  
 
 


Retry this on v0.5.1, still have yet to see anyone else with this issue.

**Comment by InfinityGhost** [comment]
Issue appears to be stale, will close in 7 days if nothing comes of it.
