### ISSUE TITLE
[Linux] Cursor not moving in osu

### ISSUE THREAD

**Issue by Fxsch** [OpenTabletDriver/OpenTabletDriver#707]
## Description

The cursor is moving perfectly fine on my desktop and in every other application except for osu! and osu! lazer. When I set the game to windowed, move my cursor outside the window and then move it back inside osu! with my tablet, it works aswell but it won't work in fullscreen or in borderless mode. It also works in other programs when they're in fullscreen, just not any of the two osu! versions.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Manjaro Gnome, Gnome version 3.38.3, newest Manjaro version
| Software Version | 0.5.0.r40.ge7bd0e5-1
| Tablet           | Veikk S640

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics

**Comment by Fxsch** [comment]
[Diagnostics.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5857291/Diagnostics.txt)

**Comment by Fxsch** [comment]
After switching between fullscreen, borderless and windowed a few times it suddenly works as long as I don't go out of the window but as soon as I go out of osu and into osu again it stops working

**Comment by Arthur095** [comment]
Try to not launch game in admin mode if you did.

**Comment by ghdht** [comment]
Same issue on Lazer.
[Diagnostics.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5900505/Diagnostics.txt)
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Arch Gnome 3.38.3
| Software Version | v0.5.1-r0.gbccf6af
| Tablet           | CTH-480

**Comment by Mrcubix** [comment]
don't run osu as admin, re-enable UAC to the 2nd top level, disable all option related to raw input ingame and you should be set

**Comment by ghdht** [comment]
Only happens on wayland for me

**Comment by InfinityGhost** [comment]
Odd that it only happens on wayland, since we're using libevdev. Maybe actually a lazer issue?

**Comment by Fxsch** [comment]
In osu! lazer it is possible to move the cursor on the second screen and then back onto the main screen with the tablet to make it work but osu! stable can't be the "selected" application to make it work. If I switch the window to something else and still have osu! opened, I can also move the cursor in osu! with my tablet but as soon as I click on it and osu! becomes the selected window again, I can only move it with my mouse

**Comment by X9VoiD** [comment]
I think this is an issue outside OTD's scope, as OTD uses `/dev/uinput` for reporting input and if OTD miscommunicates something, then it shouldn't be working for all linux users. The input reports are then to be consumed by `libinput` so there's nothing that OTD can do if something happens between `/dev/uinput` and `libinput`.

**Comment by Fxsch** [comment]
I found a workaround: If osu! and OpenTabletDriver are both opened, press the Windows key and select OpenTabletDriver, osu! will then put itself in the foreground anyways and the cursor can be moved with the tablet

**Comment by Fxsch** [comment]
After switching to Manjaro with KDE, which doesn't use Wayland, it works perfectly fine

**Comment by InfinityGhost** [comment]
Really doesn't make sense why this only happens on Wayland, unless SDL2 is at fault here

**Comment by VeryLongNicknameSuchWow** [comment]
Having the same issue on Gnome 3.38.3 with Wayland. Under X11 everything works fine.
Only lazer is affected, standard is fine on both.

**Comment by VeryLongNicknameSuchWow** [comment]
This is now fixed with the OTD integrated into osu! Works fine on wayland.

**Comment by osufan11** [comment]
> ## Description
> 
> The cursor is moving perfectly fine on my desktop and in every other application except for osu! and osu! lazer. When I set the game to windowed, move my cursor outside the window and then move it back inside osu! with my tablet, it works aswell but it won't work in fullscreen or in borderless mode. It also works in other programs when they're in fullscreen, just not any of the two osu! versions.
> ## System Information:
> Name 	Value
> Operating System 	Manjaro Gnome, Gnome version 3.38.3, newest Manjaro version
> Software Version 	0.5.0.r40.ge7bd0e5-1
> Tablet 	Veikk S640

Try turning off High Precision Mouse in osu settings.

**Comment by osufan11** [comment]
> This is now fixed with the OTD integrated into osu! Works fine on wayland.

If it is fixed the author  or a member of the organization should close this.

**Comment by GreenTeaSeb** [comment]
Having the same issues right now on arch wayland with wine osu. Lazer works.

**Comment by jamesbt365** [comment]
may sure the raw input is off, if this is one specific application and not everything then this isn't an otd issue.

**Comment by GreenTeaSeb** [comment]
yep, raw input is off. And you're right, it's not an OTD issue. The pen input works for clicking, but not more movement. While the default kernel drivers work. 
The moment I focus into the app with OTD it stops moving the pen, only registering the clicks.

**Comment by Valoriks** [comment]
> Interestingly enough, only happens on absolute mode, artist mode works.

You're right, it works when I switch to artist mode! Thanks! I can finally play osu! on Wayland

**Comment by jamesbt365** [comment]
Dismissed? this is not our issue, we cannot fix it or do anything about it. Just use artist mode, its now the default output mode and is better supported on wayland because most compositors can handle tablet input, but not so many have implemented support for absolute mice.
