### ISSUE TITLE
Button Binds on Huion HS 611 Tablet does not work

### ISSUE THREAD

**Issue by NoahDavid18** [OpenTabletDriver/OpenTabletDriver#708]
## Description

The Auxiliary Button Binds do not work with any of the buttons on the tablet. Only the pen buttons work.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | windows 10 64 bit
| Software Version | 0.5
| Tablet           | Huion HS611

**Comment by InfinityGhost** [comment]
This bug has not since been reported again, and the configuration has been modified since. Assuming this is resolved. If this is a mistake, you can reopen the issue.
