### ISSUE TITLE
Add support for xp-pen artist 24

### ISSUE THREAD

**Issue by tabletedpolum** [OpenTabletDriver/OpenTabletDriver#721]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    |
| Product Name    |
| Width           |
| Height          |
| Pressure Levels |
| LPI             |

**Comment by Mrcubix** [comment]
Please fill the template, it's there for a reason

**Comment by tabletedpolum** [comment]
xp pen
artiste 24 pro
23.8 inch
8192
idk what lpi is

heres their site https://www.storexppen.com/buy/artist-24-pro.html?gclid=Cj0KCQiAmL-ABhDFARIsAKywVadmPshsO9gdN_xWd0MxQyMVMGFHtqpy20J-L-FADHVVR2ctTPiR6zwaAvzJEALw_wcB

**Comment by Mrcubix** [comment]
we still need the diagnostic obtained inside Of OpenTabletDriver.UX.Wpf (on windows), or .Gtk on unix based OSes

In the Ux, click on help > export diagnostic and upload it here, zip it if necessary for upload

**Comment by X9VoiD** [comment]
@tabletedpolum OTD -> Help -> Export Diagnostics, upload the generated file here

**Comment by jamesbt365** [comment]
Closing as this has been completely abandoned and the :bread: has gone completely stale :(

**Comment by evertedsphere** [comment]
@Mrcubix @jamesbt365 I have the same model. 

Here is a diagnostics dump.
[artist24pro.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11990793/artist24pro.txt)
