### ISSUE TITLE
Bug with Locked Aspect Ratio and Loading Settings

### ISSUE THREAD

**Issue by Suubwey** [OpenTabletDriver/OpenTabletDriver#762]
## Description

When loading settings from JSON files, switching from a setting file that had "locked aspect ratio" on to one with it off, the area loaded would still be locked to monitor aspect ratio. Loading the new settings file would also cause incorrect width values.

#### Steps to Reproduce
1. Use any area setting that has the option "locked aspect ratio" on
2. Load a new setting with a new area size with a different ratio
3. The resulting ratio shown in OpenTabletDriver should remain to be locked at the aspect ratio previously locked, which results in an incorrect area with an incorrect width.

The temporary fix is just to reopen OpenTabletDriver making sure that "locked aspect ratio" is off.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 1909 |
| Software Version | OpenTabletDriver v0.5.1 |
| Tablet           | Gaomon S620 |

**Comment by InfinityGhost** [comment]
Potentially fixed by #779 if it merges
