### ISSUE TITLE
Device Input Logger

### ISSUE THREAD

**Issue by X9VoiD** [OpenTabletDriver/OpenTabletDriver#788]
## Description

This feature allows us to capture input from all accessible endpoints of a device. It'll be a great tool for parsers and adding support to unknown tablets with confusing endpoint layout.

A suggested implementation would be a `Dictionary<{int VID, int PID}, List<HIDDevice>>` to enumerate the `HIDDevice` with `Dictionary.Keys`. Open all of the `HIDDevice` on the list and then probably save it into a json file per `HIDDevice` to avoid cluttering a single file.

**Comment by InfinityGhost** [comment]
Resolved in #1258
