### ISSUE TITLE
XP-Pen Star G430S not detected

### ISSUE THREAD

**Issue by Maritsu** [OpenTabletDriver/OpenTabletDriver#791]
## Description

I plugged in my G430S, started the driver app and the drivers don't detect my tablet. I can see that they searched for it, except they didn't detect it.

## Images
!["Searching for tablet"](https://i.ibb.co/ZKgWFGD/obraz-2021-02-21-185617.png)
!["No tablet found"](https://i.ibb.co/jZQVq4c/obraz-2021-02-21-185717.png)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Ubuntu 20.04.2 LTS
| Software Version | v0.5.1
| Tablet           | XP-Pen Star G430S

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload it as a file.

**Comment by Maritsu** [comment]
I can't upload, it returns me an empty file
