### ISSUE TITLE
Some context menu entries are not updated

### ISSUE THREAD

**Issue by adamsoltan** [OpenTabletDriver/OpenTabletDriver#818]
## Description
After enabling area aspect ratio lock and loading settings that have it unlocked it becomes impossible to disable it (even though the checkbox isn't checked) and the area isn't the same as saved. The only way is to disable the lock is to do it before loading the settings.

## System Information:
| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10 64-bit 10.0.19042 Build 19042 |
| Software Version | 0.5.0 |
| Tablet           | Wacom CTL-472 |

**Comment by X9VoiD** [comment]
Use OTD v0.5.1 instead and test again, and btw, this issue is not reproducible on v0.5.1 on my end.

**Comment by adamsoltan** [comment]
I tried it with 0.5.1, still the same:

Start with unlocked aspect ratio:
![](https://i.imgur.com/BIVNI9D.png)

Enable aspect ratio lock:
![](https://i.imgur.com/iALG5wS.png)

Load settings without it:
![](https://i.imgur.com/I8GqYIn.png)

It is now locked (I changed only the width) and the only way to unlock it is to restart the driver and unlock before loading:
![](https://i.imgur.com/mzgjSda.png)

**Comment by X9VoiD** [comment]
Ah, you mean aspect ratio lock is still applied when loading settings with unlocked aspect ratio.

**Comment by adamsoltan** [comment]
> Ah, you mean aspect ratio lock is still applied when loading settings with unlocked aspect ratio.

Yes, in the loaded settings aspect ratio lock is disabled.

**Comment by X9VoiD** [comment]
Rename issue to -> `Aspect ratio lock always applied on first load`

**Comment by X9VoiD** [comment]
Root cause of the issue discovered. You may rename it to -> "Some context menu entries are not updated"

Affected entries:
- "Lock aspect ratio"
- "Area clipping"
- "Ignore input outside area"

**Comment by InfinityGhost** [comment]
This has since been resolved since we changed to binding-based settings.
