### ISSUE TITLE
Add support for q620m

### ISSUE THREAD

**Issue by ColdBytes** [OpenTabletDriver/OpenTabletDriver#822]
# Tablet Information
| Name            | Value |
| --------------- | ----- |
| Manufacturer  | Huion
| Tablet  | Inspiroy Dial Q620M
| Width 266.7mm         | 66.7mm 
| Height 166.7mm        | 166.7mm
| Pressure Levels  | 8192
| LPI     | 5080

Report Rate: ＞233PPS
8 Programmable Press Keys + Dial

[diagnostic.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6071802/diagnostic.zip)

**Comment by Mrcubix** [comment]
zip fiel appear to be corrupted, re-upload a working one so we can proceed rn

**Comment by Mrcubix** [comment]
Go to Programs and features > search for winUSB, attempt uninstall, 

if a windows cover the left side of your screen:
          reinstall huion driver and proceed again, 
else, 
           it will just uninstall, you can then uninstall huion driver

redo a diagnostic once done

**Comment by Mrcubix** [comment]
Hi this is a reminder that you opened a ticket for support, i provided all the steps necessary toward getting your tablet closer to working state, i still need informations after proceeding with these steps such as, going again to help > export diagnostic and uploading the new diagnostic file potentially containing new information useful to make this tablet work with OTD.

**Comment by jamesbt365** [comment]
Supported now
