### ISSUE TITLE
Cursor jumping to wrong position

### ISSUE THREAD

**Issue by Sudo-kun** [OpenTabletDriver/OpenTabletDriver#828]
## Description

The cursor jumps irregularly from the position my cursor is to position * 5/4 in X direction and position * 3/4 in Y position.
This input jump does not show up on the debug monitor.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |Manjaro Linux (Kernel 5.10)|
| Software Version |0.5.1-r164.gec360a1|
| Tablet           |Wacom CTL-4100|

**Comment by Sudo-kun** [comment]
The old wacom drivers still ran in the background, but even after removing xsetwacom it still happend, what do I need to do to only use otd?

**Comment by X9VoiD** [comment]
Read [FAQ](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position)

**Comment by Sudo-kun** [comment]
... oh.
Sorry and thanks
