### ISSUE TITLE
OEM Kill not working with Wacom drivers

### ISSUE THREAD

**Issue by NotKenZ** [OpenTabletDriver/OpenTabletDriver#847]
## Description

Oem Kill doesn't turn off the
 Wacom drivers when I use OTD.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows
| Software Version | 10.0.19042 Build 19042
| Tablet         |  CTH-480

**Comment by adryzz** [comment]
this issue should be reported on the plugin repository [here](https://github.com/X9VoiD/VoiDPlugins/issues)

**Comment by InfinityGhost** [comment]
Yeah this is an issue that should be taken there, closing this because I don't have permissions to transfer the issue there.
