### ISSUE TITLE
Cursor isn't moving.. CTL-490 / windows 20H2 / portable 0.5.2.1

### ISSUE THREAD

**Issue by Fejkej** [OpenTabletDriver/OpenTabletDriver#849]
## Description
I'm on portable version v0.5.2.1. 
Tablet is detected but cursor isn't moving at all even on desktop. Everything is set (tablet area, display area etc.). 

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |  Windows 20H2 |
| Software Version | 0.5.2.1 |
| Tablet | Wacom CTL-490 |

**Comment by AbstractQbit** [comment]
Can you try using this configuration?
[CTL-490.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6116240/CTL-490.zip)

**Comment by Fejkej** [comment]
okay.. now its moving but randomly and extrealmy fast... at least tablet debugger shows that it reports something

**Comment by AbstractQbit** [comment]
Try this build, should fix everything https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/639869126

**Comment by Fejkej** [comment]
thanks! it works now
