### ISSUE TITLE
Crash caused by setting express key to accented character  

### ISSUE THREAD

**Issue by GaPala** [OpenTabletDriver/OpenTabletDriver#863]
## Description
Adding an accented character as a key binding to express key in a profile JSON, loading that profile JSON and then pressing that express key results in the driver crashing.

## System Information:

| Name                     | Value                              |
| -------------------- | -------------------------- |
| Operating System | Windows 10 (2004)         |
| Software Version   | OpenTabletDriver v0.4.2 | 
| Tablet                    | Gaomon S620                 |

**Comment by Mrcubix** [comment]
first use the latest version of OTD aka 0.5.2.2, then try again

**Comment by InfinityGhost** [comment]
Accented characters aren't supported because it isn't part of the VirtualKey enumerations for any of the platforms, and likely never will be. Try this again on the latest version, if it still occurs (which it likely will) we'll make it silently fail.

**Comment by GaPala** [comment]
Confirming that the issue does occur on v0.5.2.2

I personally wouldn't bother with a anti-crash fix, since it's impossible to assign an accent as a key binding with the provided GUI since you need to press ctr+alt+[vowel], but that'd assign the binding to just 'ctrl' anyway (but I guess that's not my choice). The faulty binding is also pretty easy to undo it if you do force it through the JSON, since the driver can still start up and you can change the binding from there as long as you don't use the faulty binding before applying that change.

When support for modifiers in key bindings arrives (#740) that'd basically solve this anyway, since you add accents to vowels like ctrl+alt+e and so just adding ctrl+alt+e as a hotkey will do the same thing as just setting it to output é.

Thanks

**Comment by Mrcubix** [comment]
Try using the script runner plugin and ahk to circumvent that issue
