### ISSUE TITLE
Wacom CTL-472 not being detected on Ubuntu 18.04. 2 LTS

### ISSUE THREAD

**Issue by makkarakka3** [OpenTabletDriver/OpenTabletDriver#866]
## Description
Hello! I am trying to get the driver working on Ubuntu 18.04. 2 LTS, but it always says no tablet detected, but i have my tablet plugged in.
## System Information:
| Operating System | Linux Ubuntu
| Software Version | 18.04. 2 LTS
| Tablet           | CTL-472

**Comment by Mrcubix** [comment]
use the [latest master action build ](https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/651492004) and see if it's any different

**Comment by Mrcubix** [comment]
Check the console for errors message present in the [wiki](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ)

**Comment by makkarakka3** [comment]
Did not find in the wiki
Here is the only error i got [DeviceIOException:Error]	Unable to open HID class device (OK).

**Comment by Mrcubix** [comment]
![image](https://user-images.githubusercontent.com/39861216/111282049-da634d00-863d-11eb-8f14-45048edfa97c.png)
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception

**Comment by makkarakka3** [comment]
Oh im blind
