### ISSUE TITLE
Double click pen | CTL-490 | v0.5.2.3

### ISSUE THREAD

**Issue by Fejkej** [OpenTabletDriver/OpenTabletDriver#874]
## Description
When both AnitChatter filter (devocub filter) and Smoothing filter (hawku filter) are active, pressing pen nib causes lmb double click.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 20H2 |
| Software Version | 0.5.2.3 |
| Tablet           | Wacom CTL-490 |

**Comment by X9VoiD** [comment]
Running two interpolators won't be allowed in the future as that spawns two separate cursors, resulting into the behaviour that you are experiencing right now. Being able to run more than one interpolator is not intended.
