### ISSUE TITLE
gaomon s620 dosent get detected

### ISSUE THREAD

**Issue by itzjustas0** [OpenTabletDriver/OpenTabletDriver#875]
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Ubuntu 20.04.2 LTS|
| Software Version |v0.5.2.3|
| Tablet           |Gaomon s620|

**Comment by InfinityGhost** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Windows-FAQ#my-gaomonhuion-tablet-isnt-detected-but-is-listed-as-supported

**Comment by Mrcubix** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ ghost linked the wrong page

**Comment by itzjustas0** [comment]
thanks for helping it's now working :D
