### ISSUE TITLE
Hang on connecting to OpenTabletDriver Daemon

### ISSUE THREAD

**Issue by outerex** [OpenTabletDriver/OpenTabletDriver#877]
## Description

When i try to run opentabletdriver all i get is it saying Connecting to OpenTabletDriver Daemon.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | ArchLinux x86_64
| Software Version | 0.5.2.3
| Tablet           | Wacom CTL-472

**Comment by tytan652** [comment]
Did you reboot after install ?

**Comment by outerex** [comment]
Yep.

**Comment by tytan652** [comment]
Dis you followed those instructions ?
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Installation-Guide#arch-linux-installation

**Comment by outerex** [comment]
Oh i did not, thanks, now it works fine.
