### ISSUE TITLE
XP PEN recognized wrong tablet

### ISSUE THREAD

**Issue by gotin24** [OpenTabletDriver/OpenTabletDriver#878]
## Description

When I turn on OTD it says XP-Pen G430 detected while I'm using the XP-Pen G430S
## System Information:

| Name Gotin | 
| Operating System | WIndows 10
| Software Version | v0.5.2.3
| Tablet           | XP-Pen G430S

**Comment by X9VoiD** [comment]
Go to OTD -> Tablet -> Device string reader -> Dump string.

Upload dump file here.

**Comment by gotin24** [comment]
[g430s.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6176691/g430s.txt)
sorry for sending it late

**Comment by X9VoiD** [comment]
Closing this and will track instead on #698
