### ISSUE TITLE
Daemon is a virus

### ISSUE THREAD

**Issue by Mrturtlenugget** [OpenTabletDriver/OpenTabletDriver#882]
## Description

The Daemon service file is counted as a trojan virus Wactac.B!ml What do i do
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | OpenTabletDriver v0.5.2.3
| Tablet           | Gaomon S620

**Comment by InfinityGhost** [comment]
It's a false positive

**Comment by Mrturtlenugget** [comment]
so should i allow it

**Comment by X9VoiD** [comment]
Yes
