### ISSUE TITLE
False anti-malware detections

### ISSUE THREAD

**Issue by LavaDesu** [OpenTabletDriver/OpenTabletDriver#883]
OpenTabletDriver is now being flagged as the trojan `Gen:Variant.Ulise` by numerous anti-malware software, notably BitDefender.

## Possible Causes

The first commit to get flagged is d52aa65, relating to the implementation of the plugin manager. A speculation would be how OTD downloads and run assemblies (in this case plugins) which can seem suspicious and trojan-like.

## Notes
Release artifacts have an extra detection by **Windows Defender** as `Trojan:Win32/Zpevdo.B` (0.5.2.3) or `Trojan:Win32/Wacatac.B!ml` (0.5.2). I have not checked releases 0.5.2.1 or 0.5.2.2.
Only the .zip archives have this extra detection, the extracted .exes do not.
The on_push workflow's artifacts also do not have this extra detection. 

## Workarounds
Lock future releases to be built on dotnet-sdk 5.0.1-101 temporarily as only builds on dotnet-sdk >=5.0.2-102 will get flagged for some reason (though there will still be one AV detection as "unsafe")

## Links
[Release artifact 0.5.2](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.2): [Virustotal](https://www.virustotal.com/gui/file/968ece0b7f831d1cc6f5d5b977407153a5af7f548ac467858e1bb1ade7b60a89/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111806257-627a7880-8904-11eb-8660-96797fe7bc27.png)
[Release artifact 0.5.2.3](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.2.3): [Virustotal](https://www.virustotal.com/gui/file/a203d4286c5f1a463bb4beb69997a7dc2b715e72f657229cd53995632e61769c/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111806540-abcac800-8904-11eb-9a72-77bf2dee610e.png)
[Workflow Actions](https://github.com/OpenTabletDriver/OpenTabletDriver/actions/runs/659562888) (8ade463): [Virustotal](https://www.virustotal.com/gui/file/7ae680e1c1c1a6cd47ebc1d142e046c4cc6ecd6ab0532d1c4ac424e61f65cbad/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111806809-f0566380-8904-11eb-96f2-2fd9f10c7175.png)
[My build with sdk5.0.4-201 on 0.5.2.3](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6172593/OpenTabletDriver.Daemon-0.5.2.3-sdk5.0.4_201.zip): [Virustotal](https://www.virustotal.com/gui/file/19832b1a475fc433c68574bf5af94dbaf643bf145bb0dca368a727d3573d6534/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111809811-f3068800-8907-11eb-9e82-5d203ad11e26.png)
[My build with sdk5.0.1-101 on 0.5.2.3](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6172583/OpenTabletDriver.Daemon-0.5.2.3-sdk5.0.1_101.zip): [Virustotal](https://www.virustotal.com/gui/file/80f15a596710998d9064cf89347cadfd14274def451252d2fc7cd65415182cd0/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111810260-627c7780-8908-11eb-8416-e503c1594331.png)
[My build with sdk5.0.4-201 on](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6172675/OpenTabletDriver.Daemon-d52aa65-sdk5.0.4_201.zip) d52aa65: [Virustotal](https://www.virustotal.com/gui/file/1b29fc3a9ea98adeb73e349ef86a69e46eb9dcc1ef817191558274a75c0340c0/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111811481-a8860b00-8909-11eb-8675-793d0d4c5ab4.png)
[My build with sdk5.0.4-201 on](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6172682/OpenTabletDriver.Daemon-eefe925-sdk5.0.4_201.zip) eefe925: [Virustotal](https://www.virustotal.com/gui/file/7af87dacd936ca42ff70c2cf36b78c4f90b9043bfbb836cd53b4eeea692d4ec9/detection) | [Detections at the time of writing](https://user-images.githubusercontent.com/56823419/111811693-e71bc580-8909-11eb-8594-e02f353b7a3f.png)

Command used for my build:
```sh
dotnet publish OpenTabletDriver.Daemon -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=embedded --self-contained false -f net5 -o ./build
```

**Comment by X9VoiD** [comment]
We already resolved the false positives as of v0.5.3.1 so will close this issue now. Will re-open in case we get flagged again by AVs.
