### ISSUE TITLE
Add Support for Wacom PTH-460

### ISSUE THREAD

**Issue by pasi123567** [OpenTabletDriver/OpenTabletDriver#891]
Does not get detected yet

[Diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6175434/Diagnostics.txt)

  "DevicePath": "\\\\?\\hid#vid_056a&pid_0392&mi_00#8&38875c26&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
  "VendorID": 1386,
  "ProductID": 914,
  "CanOpen": true,
  "ReleaseNumberBcd": 265,
  "ReleaseNumber": "1.9",
  "ProductVersion": 265,
  "Manufacturer": "Wacom Co.,Ltd.",
  "ProductName": "Wacom Intuos Pro S",
  "SerialNumber": "0LQ0111002200",
  "MaxInputReportLength": 192,
  "MaxOutputReportLength": 0,
  "MaxFeatureReportLength": 2561

**Comment by X9VoiD** [comment]
#588
