### ISSUE TITLE
my pen pressure dosent work 

### ISSUE THREAD

**Issue by itzjustas0** [OpenTabletDriver/OpenTabletDriver#894]
## Description

when I go to draw my pen pressure doesn't work I tried messing with the pen pressure settings and it didn't do anything 
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |Ubuntu 20.04.2 LTS|
| Software Version |v0.5.2.3|
| Tablet           |Gamon s620|

**Comment by X9VoiD** [comment]
Enable Artist Mode

**Comment by itzjustas0** [comment]
> Change Absolute Mode to Artist Mode.

thx it worked
