### ISSUE TITLE
Add support for Wacom PTZ-630

### ISSUE THREAD

**Issue by soreyo** [OpenTabletDriver/OpenTabletDriver#903]
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | wacom
| Product Name    | ptz-630
| Width           | 345
| Height          | 262
| Pressure Levels | 1024
| LPI             | 5080

## Diagnostic Information
[diagnostics.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6190098/diagnostics.zip)

**Comment by soreyo** [comment]
sorry, 203x152 area lol.

**Comment by InfinityGhost** [comment]
> sorry, 203x152 area lol.

Units?
