### ISSUE TITLE
Support Request: Add support for x32 bit systems

### ISSUE THREAD

**Issue by eaull** [OpenTabletDriver/OpenTabletDriver#907]
I use windows x32 bit and play osu and I want to try using this tablet driver but it doesn't support my system.

**Comment by jjhhgg100123** [comment]
OpenTabletDriver doesn't officially support 32 bit operating systems. If you require it, you can build it yourself from the source, shouldn't be too difficult. But support will not be provided for it, as x86 is at this point, ancient, and providing support for it at this point just wouldn't be worth the time it would take.
