### ISSUE TITLE
CTL-4100 Buttons always pressed after receiving positional input

### ISSUE THREAD

**Issue by GopoBoi** [OpenTabletDriver/OpenTabletDriver#909]
## Description

with the tablet buttons bound to anything, simply placing the pen above the tablet will cause the buttons to be pressed until they're actually physically pressed.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Arch Linux (happens on windows too though) |
| Software Version | v0.5.2.3  |
| Tablet           | Wacom CTL-4100 |

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload the json file here. Will double check configuration for anything weird.

**Comment by GopoBoi** [comment]
can't upload json files directly, it's in the zip file
[diagnostics.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6195902/diagnostics.zip)

**Comment by X9VoiD** [comment]
Replace `Configurations\CTL-4100.json` with this [CTL-4100 config](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6196082/CTL-4100.zip) then press `Detect tablet` to test.

**Comment by GopoBoi** [comment]
Can confirm that it fixes it.
