### ISSUE TITLE
Add suport for Huion H640P pls

### ISSUE THREAD

**Issue by GzFabi** [OpenTabletDriver/OpenTabletDriver#911]
## Description

huion H640P is not working
## System Information:

| Name      | Value | 
| Fabian usernam: GzFabi | ? |
| Operating System |
AMD Athon X2, AMD Radeon HD 6670  
| Software Version |
windows 10 64 bit
| Tablet           |
Huion H640P

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload the resulting diagnostics here as zip file.

**Comment by InfinityGhost** [comment]
Nearly 2 weeks without response, assuming resolved.

**Comment by ducanh2002123** [comment]
Status report: I am using a huion H640P, the software can detect it just fine, but the only action that i could do on the tablet is to tap the pen on the tablet and that would simulate a left click, mouse movement doesn't work, custom button mapping doesn't work, basically only 2 things work: 1: Detecting the tablet, and 2: clicking on the tablet, the console doesn't return any error code

Diagnostic file:
[opentabletdriverdiagnostic.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6312143/opentabletdriverdiagnostic.txt)

**Comment by X9VoiD** [comment]
Yoy might want to set an actual tablet area before complaining that the input is not working.

**Comment by ducanh2002123** [comment]
Oh..? On the GUI it said my width is 160 and my height is 100, or X:80 and Y:50.
![Screenshot from 2021-04-15 15-00-22](https://user-images.githubusercontent.com/10848519/114834982-50a0ce00-9dfb-11eb-8963-97c549bd1029.png)

**Comment by GzFabi** [comment]
> Nearly 2 weeks without response, assuming resolved.



> Nearly 2 weeks without response, assuming resolved.

nope

**Comment by Mrcubix** [comment]
> OTD -> Help -> Export Diagnostics, upload the resulting diagnostics here as zip file.
> 
> H640P is already supported, just not tested. If you have problems with detection follow instructions from [FAQ](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Windows-FAQ#my-gaomonhuion-tablet-isnt-detected-but-is-listed-as-supported)
