### ISSUE TITLE
Add support for Huion GC610

### ISSUE THREAD

**Issue by iceCreamMint** [OpenTabletDriver/OpenTabletDriver#916]
i have a sneaking suspicion that this is just the g10t but sold in china
# Tablet Information

| Name            | Value |
| --------------- | ----- |
| Manufacturer    | Huion
| Product Name    | GC610
| Width           | 374 mm(254 working)
| Height          | 177 mm(158.8 working)
| Pressure Levels | 8192 levels
| LPI             | 5080

## Diagnostic Information

[gc610.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6204263/gc610.txt)

**Comment by Mrcubix** [comment]
[GC610.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6204421/GC610.zip)
with htis config, head to tablet > device string reader, there type the following:
-9580
-110
-201
send request and paste the obtained string here

**Comment by iceCreamMint** [comment]
HUION_T166_170329

**Comment by iceCreamMint** [comment]
HUION_T166_170329

**Comment by Mrcubix** [comment]
[GC610.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6206256/GC610.zip)
try this config, it should work now

**Comment by iceCreamMint** [comment]
it works

**Comment by Mrcubix** [comment]
alright, i'll be PRing this config, it should be available in the next releases

**Comment by Mrcubix** [comment]
just to make sure, go to tablet > tablet debugger, move your pen to the bottom right corner and check the max position value

**Comment by iceCreamMint** [comment]
max values are [50800, 31750], but most times it goes to [50790, 31740]
