### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by EikelFlo** [OpenTabletDriver/OpenTabletDriver#928]
# Support Request
My Gaomon s56k is not getting detected.

## What I've already tried
I tried the Linux FAQ Points:

1. ArgumentOutOfRangeException: Value [0-15]
2. The driver fails to open the tablet (DeviceIOException)
3. Failed to initialize virtual tablet/pointer

I can fix either OutOfRange error but as soon as I replug my tablet I get DeviceIOException and the other way around.
I even tried to use it with installing the digimend-dkms driver beforehand. 

Diagnostics:
https://paste.eikelflo.com/dutilufupa.json

**Comment by EikelFlo** [comment]
If there is anything I read wrong my bad

**Comment by Mrcubix** [comment]
lemme make a config for your variation real quick

**Comment by Mrcubix** [comment]
[S56K.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6216451/S56K.zip)
extract this config in Configurations/Gaomon , replacing the old one and you should be good unless you're using latest master, in which case, let me know

**Comment by EikelFlo** [comment]
After crashing the program and checking that there was a small mistake in the json double , It detects it perfectly.
Thanks for the quick help

**Comment by EikelFlo** [comment]
After the detection issue was fixed I didn't test out if it does work, and it does not, when I move my stylus on the tablet my mouse doesn't move at all anything I need to enable?. It does get detected in the tablet debugger.

**Comment by EikelFlo** [comment]
What I already tried is 

- `sudo nano /etc/modprobe.d/blacklist.confecho "blacklist wacom" | sudo tee -a /etc/modprobe.d/blacklist.conf same with gaomon`
-  sudo chmod 0666 /dev/uinput
-  INPUT_UINPUT=y
- Enabling it with xinput --list and then xinput enable
- gsettings reset org.gnome.desktop.peripherals.touchpad send-events

**Comment by Mrcubix** [comment]
let's try some stuff, with the debugger open:
- drag, and tell me the reportID, 
- hover, need it again
- out, YEP, also need that

once you're done with that, try to get max value for position by moving slowly to the bottom right corner, and send the value here too.

**Comment by EikelFlo** [comment]
drag : 96 report rate smth with 400
hover:same
out: id 0 report 205

max Pos 32767 , 32767

**Comment by Mrcubix** [comment]
as for position, are you sure that's the max?

**Comment by EikelFlo** [comment]
![Uploading 2zz6r4.png…]()

**Comment by EikelFlo** [comment]
![2zz6r4](https://user-images.githubusercontent.com/53355483/112753491-05ec1d00-8fd8-11eb-87b5-ff06d5f0bcb2.png)

**Comment by Mrcubix** [comment]
that's weird considering this tablet sensor isn't a square afaik but ok

**Comment by Mrcubix** [comment]
[S56K.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6217351/S56K.zip)
try this config

**Comment by EikelFlo** [comment]
Still wont move anything works fine in the debugger tho, any touch pad // tablet support I could've enabled or didn't // disabled somewhere?

**Comment by Mrcubix** [comment]
[S56K.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6217360/S56K.zip)
going for the pepega clap WR, here is a config where `"StartInclusive": true`

**Comment by EikelFlo** [comment]
works fine now :joy:
