### ISSUE TITLE
Compatabilty on M1 Macbooks? (Big Sur)

### ISSUE THREAD

**Issue by Chanw11** [OpenTabletDriver/OpenTabletDriver#933]
# Support Request
Big Sur/ M1 Macbook doesnt open .app after unziping
Will ask to open from unknown source and will do nothing after

## What I've already tried
Tried versions 0.5.1, 0.5.2, 0.5.2.3
Tried right click open

## Diagnostic Information
none

**Comment by Mrcubix** [comment]
M1 is an ARM architecture CPU, it's completely from x86 or x64, you could try building it for your architecture, but we won't support it

**Comment by Chanw11** [comment]
> M1 is an ARM architecture CPU, it's completely different from x86 or x64, you could try building it for your architecture, but we don't support it yet

Ok I'll go the emulation route and see how that goes. Thanks!
