### ISSUE TITLE
Veikk A15 Pro Bindings don't override default official bindings

### ISSUE THREAD

**Issue by Squaduck** [OpenTabletDriver/OpenTabletDriver#936]
## Description

Bindings don't override default official bindings
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System |Windows 10 Pro (64bit)
| Software Version |v0.5.2.3
| Tablet           |Veikk A15 Pro

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload file here in zip format

**Comment by Squaduck** [comment]
[Diagnostics.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6223692/Diagnostics.zip)

**Comment by X9VoiD** [comment]
The tablet buttons for Veikk tablets are not supported yet. If you want you may send us information about which bytes represent which button through tablet debugger to speed up adding support for it.

**Comment by Squaduck** [comment]
In Tablet Debugger I didn't see any bytes change when any button was pressed

**Comment by X9VoiD** [comment]
Is the "official binding" something configurable on the Veikk's OEM driver?

**Comment by Squaduck** [comment]
Yes, you can change what the buttons do in the OEM driver

**Comment by InfinityGhost** [comment]
Potentially a secondary endpoint for auxiliary input? Haven't looked at the diagnostics yet.

**Comment by InfinityGhost** [comment]
Stale support request, assuming it has been resolved. This can be reopened in the case this was a mistake.

**Comment by Squaduck** [comment]
This has not been resolved

**Comment by InfinityGhost** [comment]
Can discussion be taken into Discord? It would help speed up the process.

**Comment by Squaduck** [comment]
Shure
