### ISSUE TITLE
i3wm / tiling window manager, double cursor problem

### ISSUE THREAD

**Issue by S-Traut** [OpenTabletDriver/OpenTabletDriver#941]
## Description
When I run the app using i3wm it doesn't remove my base mouse cursor, which means the cursor teleports between the 2 positions, and it's not sync because my mouse cursor seems to move freely in my 2 monitors while the tablet cursor stick to the area defined. I'm on a pretty fresh install and never downloaded any tablet driver.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | arch-linux
| Software Version | v0.5.2.3
| Tablet           | wacom CTH-470

**Comment by X9VoiD** [comment]
Read [wiki for instructions](https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position).

**Comment by X9VoiD** [comment]
What have you done specifically?

**Comment by S-Traut** [comment]
Ok nevermind, I though this was linked to IOException error, seems to be fine now.. sorry for bothering ..

**Comment by X9VoiD** [comment]
If you don't have any problems anymore, you may close the issue now.
