### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by pyatnica1** [OpenTabletDriver/OpenTabletDriver#943]
# Support Request
First of all I can't open Plugin Manager and don't know why, google didn't help. Second thing is that everytime when I run driver there is an error "OpenTabletDriver should not be run with administrator privileges" even tho I don't run it as administator. 

## What I've already tried
Few versions of driver. Installer and portable versions.

**Comment by X9VoiD** [comment]
Enable UAC. Plugin manager don't run when OTD is running with elevated/admin permissions.

**Comment by pyatnica1** [comment]
It worked. Thank you very much.
