### ISSUE TITLE
Wacom PTH-651 Cursor stops moving when tip of pen touches surface of tablet 

### ISSUE THREAD

**Issue by ndrp** [OpenTabletDriver/OpenTabletDriver#951]
I would really like to use this driver, but unfortunately this problem makes it impossible to use at the moment.

When I took a look at it in tablet debug mode, it seemed like it was still registering the movement, but the blue dot that should visualize the movement had vanished. The problem occurs when hover distance is 0. It seems like there is something wrong with the reports, as report ID is always 0 when hover distance is 0 (although the report rate is still some 150-200hz).

**Comment by InfinityGhost** [comment]
Export diagnostics from within the UI, it will be very helpful for figuring this issue out. I presume the configuration report ID range needs to be extended to all values.

**Comment by ndrp** [comment]
https://pastebin.com/WDYmR83D

**Comment by pasi123567** [comment]
Is this still a problem? I had a similar issue and it was fixed with the newest driver version.

**Comment by InfinityGhost** [comment]
> Is this still a problem? I had a similar issue and it was fixed with the newest driver version.

I'm pretty sure we did fix this, thanks for the bump. Will reopen this if the issue creator still experiences this on the latest version.
