### ISSUE TITLE
Support Request: DontNet error upon attempt to start v0.5.2.3

### ISSUE THREAD

**Issue by Crystal-Gear** [OpenTabletDriver/OpenTabletDriver#954]
# Support Request
 When attempting to start the driver after the install is complete, an error pops up saying "To run this application, you need to install a newer version of .NET Core. Would you like to download it now?"

![image](https://user-images.githubusercontent.com/81930093/113520309-0bbea100-958a-11eb-82f8-cc6fd46959a5.png)

![image](https://user-images.githubusercontent.com/81930093/113520301-019ca280-958a-11eb-8b8a-16635b4caa47.png)

## What I've already tried
 I have been unable to find anything on any search engines after looking for around 15 minutes

**Comment by X9VoiD** [comment]
Click "Yes", download and install NET 5 x64 runtime.

**Comment by InfinityGhost** [comment]
You must install the .NET 5 x64 Desktop Runtime.
