### ISSUE TITLE
cursor teleporting 

### ISSUE THREAD

**Issue by LuckV2** [OpenTabletDriver/OpenTabletDriver#967]
whenever i move my pen around the upper middle of the tablet (veikk a50) it teleports at the full area and the part area

here is a video to show the issue

https://user-images.githubusercontent.com/81621288/113896102-e9b36180-97c9-11eb-9345-764af9c805fe.mp4

**Comment by LuckV2** [comment]
fixed, uninstalled other drivers

**Comment by thorsten8989** [comment]
> fixed, uninstalled other drivers

Could you tell me what drivers you uninstalled? I am having the same problems.

**Comment by Mrcubix** [comment]
first of all open your own issue, second, any other
