### ISSUE TITLE
Support Request: Can't start the program, it asks me to install .NET (already installed)

### ISSUE THREAD

**Issue by RandomPotato0** [OpenTabletDriver/OpenTabletDriver#969]
# Support Request
I can't start the program after installing it because it asks me to install [.NET](https://dotnet.microsoft.com/download/dotnet/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral) 

## What I've already tried
I've already installed it, its previous and later version but it still asks me to install it even though I already have it (x64)

**Comment by Mrcubix** [comment]
you need .NET 5 x64, not x86

x86 = 32 bits
x64 = 64 bits

**Comment by RandomPotato0** [comment]
> you need .NET 5 x64, not x86
> 
> x86 = 32 bits
> x64 = 64 bits

I know, i've installed 64 bit version, but i also tried 32 bit just in case, still, neither works

**Comment by Kraaaait** [comment]
I had the same issue and fixed it today. Installing dotnet via the install script provided by Microsoft fixed it for me.

Download the script here:
https://dotnet.microsoft.com/download/dotnet/scripts

Open a PowerShell window in the download folder and run this command:
`.\dotnet-install.ps1 --runtime 5.0.202`

**Comment by RandomPotato0** [comment]
@Kraaaait I did as you said but it still asks me to install it

**Comment by InfinityGhost** [comment]
This isn't an issue with OpenTabletDriver, rather with .NET 5. Closing but leaving conversation unlocked.
