### ISSUE TITLE
driver not working properly

### ISSUE THREAD

**Issue by pietarus** [OpenTabletDriver/OpenTabletDriver#977]
## Description

The driver loads the small area above the default area of the tablet, so the cursor keeps switching between the two areas making the driver unusable. 
## System Information:

| Name             | Value |
| -pietarus | ----- |
| Manjaro |
| 0.5.2.3 |
| Tablet wacom cth 480 |

**Comment by LavaDesu** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position

**Comment by X9VoiD** [comment]
Duplicate of #778
