### ISSUE TITLE
After closing the OTD UI , the tablet doesnt respond neither is it a background task anymore

### ISSUE THREAD

**Issue by osufan11** [OpenTabletDriver/OpenTabletDriver#978]
## Description

The tablet doesn't respond neither is it a background task i just closed the UI...
## System Information:

| Name | Value |
| ---------------- | ----- |
| Operating System | Windows 10 |
| Software Version | Latest |
| Tablet           | G640 |

**Comment by AbstractQbit** [comment]
Minimize it instead, it will hide to system tray.

**Comment by osufan11** [comment]
> 
> 
> Minimize it instead, it will hide to system tray.

Oh ok

**Comment by X9VoiD** [comment]
This is intended behaviour, and not an issue.
