### ISSUE TITLE
Can´t add Plugins

### ISSUE THREAD

**Issue by EnricoCMD** [OpenTabletDriver/OpenTabletDriver#979]
When I click on the button to open that nothing happens...a friend has the same issue

**Comment by X9VoiD** [comment]
Are you getting a warning about running as admin?

**Comment by EnricoCMD** [comment]
> 
> 
> Are you getting a warning about running as admin?

yes but i do not run this with admin

**Comment by X9VoiD** [comment]
Duplicate of #943
