### ISSUE TITLE
Hawku smoothing filter plugin huge lag

### ISSUE THREAD

**Issue by Mrturtlenugget** [OpenTabletDriver/OpenTabletDriver#981]
When ever I use the Hawku smoothing filter plugin I get huge lag spikes even with anti chatter like 14-50ms 

I use Gaomon S620

And the latest version of otd

**Comment by X9VoiD** [comment]
What OS? And define "lag spike".

**Comment by Mrturtlenugget** [comment]
Windows 10 and lag spike as in like choppy frames and input lag on osu

**Comment by X9VoiD** [comment]
Are you using a weak CPU?

**Comment by Mrturtlenugget** [comment]
maybe I don't know if I do or not.

**Comment by Mrturtlenugget** [comment]
I have a modern cpu

**Comment by Mrturtlenugget** [comment]
I use ryzen quad core I don't know which model

**Comment by X9VoiD** [comment]
Hawku smoothing and Devocub antichatter is not intended to be used at the same time. The timer API used is managed by Windows, and the filters itself is already optimized to use SIMD. If there's some sort of performance penalty it incurs then it just means your CPU is weak or you have way too many processes or other forms of CPU load in the background. OTD nor TabletDriverFilters have control over this.

**Comment by AbstractQbit** [comment]
Not sure why you'd want to add more smoothing to a tablet that already has some in firmware. Smoothing by it's nature makes the cursor feel more laggy and sluggish.
