### ISSUE TITLE
Add advanced binds / Add F24 key to binds

### ISSUE THREAD

**Issue by markiszka** [OpenTabletDriver/OpenTabletDriver#991]
Like to hawku drivers where you can set hotkeys like Alt+Up or Alt+Down for volume or F24 would be nice because then you can use autohotkey to do more advanced things.

**Comment by InfinityGhost** [comment]
Duplicate of #740

But on the note of autohotkey, a plugin exists to run autohotkey scripts from within OpenTabletDriver if that is what you're looking for.

**Comment by Mrcubix** [comment]
it's called script runner and the only thing you need to use it, is to create a script, insert the path in one of the plugin property fields and then go into the advanced binding menu (the ...) and select script runner as a type and the right slot and you should be good to go
