### ISSUE TITLE
Plugin Manager increasingly takes longer to load on each refresh

### ISSUE THREAD

**Issue by InfinityGhost** [OpenTabletDriver/OpenTabletDriver#992]
## Description

Root cause appears to be as result of the App.Settings property being changed, causing all event hooks to be rehooked, and eventually causes huge slowdowns and/or hangups.

https://github.com/OpenTabletDriver/OpenTabletDriver/blob/a91c751d2ee57a8edf30225d34ab12fd81ba3ad5/OpenTabletDriver.UX/Windows/PluginManagerWindow.cs#L114-L126

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | NixOS Linux
| Software Version | a91c751d2ee57a8edf30225d34ab12fd81ba3ad5

**Comment by gonX** [comment]
#801 (which was superseded by #1059 and #1063 which are merged) would've fixed this. Is this still occuring?

**Comment by gonX** [comment]
I'm assuming this is no longer occuring given the merged PRs. Please reopen if this is still not the case @InfinityGhost
