### ISSUE TITLE
Weird Build Error from Arch AUR

### ISSUE THREAD

**Issue by PrincessAkira** [OpenTabletDriver/OpenTabletDriver#993]
## Description
There is some Strange Build Error i get on Arch Linux which i attached below

## System Information:
Ryzen 7 2700
5.11.14-147-tkg-upds Kernel
Latest Dotnet Runtime via the Yay AUR
I Freshly installed that System 2 Hours ago from Writing this

## External Stuff:
The Error: https://paste.thighs.live/oqofikadop.rb
Screenshot of my Dotnet Version:
![image](https://user-images.githubusercontent.com/45071533/114760322-78daef00-9d5f-11eb-8505-cc6b89696e44.png)

**Comment by peet1993** [comment]
This is not a bug. The reason is that the Symantec Root Certificate got removed recently on Arch, check the pinned comment here: https://aur.archlinux.org/packages/opentabletdriver-git/

**Comment by InfinityGhost** [comment]
Duplicate of #948
