### ISSUE TITLE
Pen buttons not working in Huion H430P

### ISSUE THREAD

**Issue by jupiteria47** [OpenTabletDriver/OpenTabletDriver#995]
## Description

the pen button is not working on this driver but it works on other drivers
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | 0.5.3.1
| Tablet           | Huion H430P

**Comment by X9VoiD** [comment]
OTD -> Help -> Export Diagnostics, upload the file in zipped format.

**Comment by X9VoiD** [comment]
Will close for now until firther information is provided.
