### ISSUE TITLE
Plugins weren't working

### ISSUE THREAD

**Issue by ghsantos9** [OpenTabletDriver/OpenTabletDriver#996]
For some reason plugins were not working giving the error:
[Plugin:Debug]No constructor found for 'TabletDriverFilters.Devocub.AntiChatter'
My guess is that I used plugin manager when it was just released so creating naming issues.

Solved starting a new Local\OpenTabletDriver.

I never really realized that was not working, the error only display when debug is select.

Old settings.json:
[old_settings.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6321695/old_settings.txt)

Windows 10
v0.5.3.1
Wacom CTL-472

**Comment by InfinityGhost** [comment]
Odds are that the plugin was out of date, but since this won't be reproducible since you wiped the old directory I'm closing this under the assumption it was a non-bug.
