### ISSUE TITLE
Not functional UI

### ISSUE THREAD

**Issue by acedia3** [OpenTabletDriver/OpenTabletDriver#999]
First of all, thanks for the driver! Cured my anxiety after using the OEM G640 one :)

The problems I am having:
1) "Show window" does nothing, but "Close" works: having to exit the application entirely to reopen the UI.
2) "Open plugin manager" not working at all

Installed using the guide.

| Operating System | Windows 10
| Software Version | Latest (v 0.5.3.1)
| Tablet           | G640

**Comment by Mrcubix** [comment]
1. can't reproduce
2. enable UAC to the second points from the top at least

**Comment by acedia3** [comment]
Also, after attempting to run the driver as admin it crashes and never launches again unless I reboot

**Comment by acedia3** [comment]
> 1. can't reproduce
> 2. enable UAC to the second points from the top at least

Will test, thanks!

**Comment by acedia3** [comment]
> 1. can't reproduce
> 2. enable UAC to the second points from the top at least

Great, that solved the issue with plugin manager and also with the "show window" button lmao. Thanks a lot

**Comment by acedia3** [comment]
>enable UAC to the second points from the top at least 
solved the issue
